BEGIN TRY
DECLARE @TERMINO DATETIME
DECLARE @INICIO DATETIME
DECLARE @PASOS DATETIME
SET @INICIO=GETDATE()
SET @PASOS=@INICIO
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('CONJUNTO EJECUCION SP','INICIO',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
WAITFOR DELAY '00:00:02'
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SP_BASE_PBI','INICIO',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
WAITFOR DELAY '00:00:02'
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++CARGA MAESTRO PERSONA
DECLARE @FECHA_ULTIMA_CARGA DATE
SET @FECHA_ULTIMA_CARGA =(SELECT MAX(TIMESTAMP) FROM ALMACEN_DE_DATOS.DBO.SURA_MAESTRO_PERSONA_FULL)
DECLARE @ULTIMA_CARGA INT
SET @ULTIMA_CARGA=(((YEAR(@FECHA_ULTIMA_CARGA)*100)+MONTH(@FECHA_ULTIMA_CARGA))*100)+DAY(@FECHA_ULTIMA_CARGA)

CREATE  TABLE #TBACSMAE 
(
NNUMRUT NUMERIC(10),
CINDTIPE CHAR(1),
CAPEPATE CHAR(40),
CAPEMATE CHAR(20),
CNOMPERS CHAR(60),
CCOGICOM CHAR(11),
NFECNACI INT,
CINDSEXO CHAR(1),
NFECUACT CHAR(8)
)

DELETE FROM ALMACEN_DE_DATOS.DBO.SURA_MAESTRO_PERSONA_FULL WHERE TIMESTAMP=@FECHA_ULTIMA_CARGA

DECLARE @CONSULTA AS NVARCHAR(4000)	
SET @CONSULTA = 		
		
'SELECT * FROM OPENQUERY(SOL,''

SELECT
NNUMRUT,
CINDTIPE,
CAPEPATE,
CAPEMATE,
CNOMPERS,
CCOGICOM,
NFECNACI,
CINDSEXO,
NFECUACT
FROM RSASOLDB2.TBACSMAE
WHERE
NNUMRUT>0 AND NFECUACT>=  '+CAST (@ULTIMA_CARGA AS NVARCHAR(8))+'
		  '')'
INSERT INTO #TBACSMAE
EXEC SP_EXECUTESQL @CONSULTA

UPDATE #TBACSMAE
SET NFECNACI=NULL
WHERE NFECNACI<19000000


INSERT INTO ALMACEN_DE_DATOS.DBO.SURA_MAESTRO_PERSONA_FULL
SELECT 
NNUMRUT,	
CASE WHEN CINDTIPE='N' THEN 'NATURAL' ELSE 'JUDICIAL' END,	
UPPER(CAPEPATE),
UPPER(CAPEMATE),
UPPER(CNOMPERS),
CCOGICOM,	
NFECNACI,
CINDSEXO,
NULL,
NULL,
CONVERT(DATE,NFECUACT)
FROM #TBACSMAE
---++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++








DECLARE @PERIODO INT
SELECT @PERIODO= MAX (CIERRE_MES) FROM MESES_CERRADOS




--SELECT * FROM MOVILIDAD_CONTROL_DE_EJECUCION ORDER BY 3 DESC

------------------------------EJECUTIVOS CA PARA BASE DE TRADICIONAL Y MARCAR LOS REPORTES CON CA
TRUNCATE  TABLE TRANSACCIONAL.DBO.BASE_CORREDOR_EJECUTIVO_CA
INSERT INTO TRANSACCIONAL.DBO.BASE_CORREDOR_EJECUTIVO_CA
SELECT * FROM  CANAL_ASESOR.DBO.BASE_CORREDOR_EJECUTIVO_CA --WHERE PERIODO =(SELECT CONVERT(VARCHAR(25),DATEADD(dd,-(DAY(getdate())-1),getdate()),101))

------------------------------CANAL


TRUNCATE TABLE BASE_CANAL_DIARIO
INSERT INTO BASE_CANAL_DIARIO
select UPPER(CANAL)CANAL,UPPER(SUBGERENCIA)SUBGERENCIA,NNURUEJCNEW,UPPER(NOMBREEJECUTIVO)NOMBREEJECUTIVO,PERIODO_CONTABLE 
from SGF1016.SQLMISFACT.dbo.DimCanal_Diario

TRUNCATE TABLE BASE_CANAL_MENSUAL
INSERT INTO BASE_CANAL_MENSUAL
select UPPER(CANAL)CANAL,UPPER(SUBGERENCIA)SUBGERENCIA,NNURUEJCNEW,UPPER(NOMBREEJECUTIVO)NOMBREEJECUTIVO,PERIODO_CONTABLE 
from SGF1016.SQLMISFACT.dbo.DimCanal



--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++7
SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SP_BASE_PBI','1 de 9',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

------------------------------COTIZACIONES

EXEC SP_COTIZACIONES_WEB

------------------------------------------------------------TERMINO DE COTIZACIONES-----------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------

UPDATE BASE_CORREDOR_EJECUTIVO_CA
SET
RUT_INTERMEDIARIO	=UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(RUT_INTERMEDIARIO	, 'Á', 'A'), 'É','E'), 'Í', 'I'), 'Ó', 'O'), 'Ú','U')), 
INTERMEDIARIO		=UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(INTERMEDIARIO		, 'Á', 'A'), 'É','E'), 'Í', 'I'), 'Ó', 'O'), 'Ú','U')), 
EJECUTIVO			=UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(EJECUTIVO			, 'Á', 'A'), 'É','E'), 'Í', 'I'), 'Ó', 'O'), 'Ú','U')), 
LIDER_COMERCIAL		=UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LIDER_COMERCIAL		, 'Á', 'A'), 'É','E'), 'Í', 'I'), 'Ó', 'O'), 'Ú','U')), 
SUCURSAL			=UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SUCURSAL				, 'Á', 'A'), 'É','E'), 'Í', 'I'), 'Ó', 'O'), 'Ú','U')), 
TIPO				=UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TIPO					, 'Á', 'A'), 'É','E'), 'Í', 'I'), 'Ó', 'O'), 'Ú','U')), 
SEGMENTACION		=UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SEGMENTACION			, 'Á', 'A'), 'É','E'), 'Í', 'I'), 'Ó', 'O'), 'Ú','U')), 
ESTADO_ASESOR		=UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ESTADO_ASESOR		, 'Á', 'A'), 'É','E'), 'Í', 'I'), 'Ó', 'O'), 'Ú','U')), 
ZONA				=UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ZONA					, 'Á', 'A'), 'É','E'), 'Í', 'I'), 'Ó', 'O'), 'Ú','U'))



--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SP_BASE_PBI','2 de 9',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()--+++
--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


CREATE  TABLE #ULTIMOS_PERIODOS (PERIODOS DATE )
INSERT INTO #ULTIMOS_PERIODOS
SELECT TOP 1 PERIODO_CONTABLE FROM FactWrittenPremium_Mensual

INSERT INTO #ULTIMOS_PERIODOS
SELECT TOP 1 PERIODO_CONTABLE FROM FactWrittenPremium_DiarioMI



TRUNCATE TABLE BASE_PBI_PREVIO 
INSERT INTO BASE_PBI_PREVIO

SELECT --top 10 
CASE	WHEN AA.CINTIPDO='P' THEN 'POL'
		WHEN AA.CINTIPDO='C' THEN 'CER'
		WHEN AA.CINTIPDO='E' THEN 'END' END																		AS TIPO,
CONVERT(NVARCHAR(50),AA.NNUMDOCU)+'.'+CONVERT(NVARCHAR(50),AA.NNUMENDO)+'.'+CONVERT(NVARCHAR(50),AA.NNUMCERT)+'.'+CONVERT(NVARCHAR(50),AA.NNUMITEM)	AS LLAVE_POLIZA,
''																												AS FILTRO_TIPO_RIESGO,
A.KEIRATOTAL																									AS FILTRO_RIESGO,
''																												AS FILTRO_TIPO_EMISION,
''																												AS FILTRO_TIPO_SOLUCION,
0																												AS CANTIDAD_COTIZACIONES,
AA.NNUMDOCU																										AS POLIZA,
AA.PERIODO_CONTABLE																								AS PERIODO_FECHA,
AA.CCODRAMO																										AS RAMO,
AA.NPLAN																										AS CODIGO_PLAN_COMERCIAL,
AA.NPLANTEC																										AS CODIGO_PLAN_TECNICO,
AA.CLINPROD																										AS LINEA_PRODUCTO,
A.LINEANEGOCIO																									AS LINEA_NEGOCIO,
A.RAMOCONTABLE																									AS RAMO_KEIRA,
AA.NNURUINT																										AS RUT_INTERMEDIARIO,
AA.NNURUEJC																										AS RUT_EJECUTIVO,
AA.NNURUASE																										AS RUT_ASEGURADO,
CASE WHEN AA.CAUSA_CANCELACION IN (select CAUSA_CANCELACION from TRANSACCIONAL.DBO.POLIZAS_VIGENTES_TIPO_ENDOSOS where TIPO_ENDOSO in ('CANCELACION','ANULACION')) THEN 1 ELSE 0 END															AS IN_CANCELACION,
0																												AS IND_ANULACION,		
0																												AS IND_REHABILITACION,
CASE WHEN NEWRENEWAL ='R' THEN 1 ELSE 0 END																		AS IND_RENOVACION,
NFECFIRM																										AS FECHA_EMISION,
NFEINVIG																										AS FECHA_INICIO_VIGENCIA,
NFETEVIG																										AS FECHA_TERMINO_VIGENCIA,
NULL																											AS FEHCA_TERMINO_VIGENCIA_REAL,
SUM(COMISION_02)																								AS COMISION_CLF,
SUM(COMISION_01)																								AS COMISION_CLP,
SUM(PRIMA_02)																									AS PRIMA_ORIGINAL_CLF,
SUM(PRIMA_01)																									AS PRIMA_ORIGINAL_CLP,
''																												AS FILTRO_INTERMEDIARIO,
''																												AS ORDEN_NIVEL,
''																												AS EQUIPO,
''																												AS TIPO_CARTERA,
AA.CCODSUCU																										AS SUCURSAL,
COUNT(DISTINCT AA.NNUMITEM)																						AS CANTIDAD_ITEMS,
NULL																											AS CANTIDAD_POLIZAS,
NULL																											AS CAPACIDAD
from 
FactWrittenPremium_Mensual AA LEFT JOIN [SGF1016].[SQLMISFACT].[dbo].[DimKeira_Class_Ramos] A ON AA.PERIODO_CONTABLE=A.PERIODO_CONTABLE AND AA.RAMOCONTABLE=A.RAMOCONTABLE 
WHERE --CINTIPDO IN ('P','R') AND 
GRSNETCEDID='Gross' AND AA.CCODRAMO	 NOT IN ('W')
GROUP BY 
AA.CINTIPDO	,
CONVERT(NVARCHAR(50),AA.NNUMDOCU)+'.'+CONVERT(NVARCHAR(50),AA.NNUMENDO)+'.'+CONVERT(NVARCHAR(50),AA.NNUMCERT)+'.'+CONVERT(NVARCHAR(50),AA.NNUMITEM),
A.KEIRATOTAL,
AA.NNUMDOCU,
AA.PERIODO_CONTABLE,
AA.CCODRAMO,
AA.NPLAN,
AA.NPLANTEC,
AA.CLINPROD,
A.LINEANEGOCIO,
A.RAMOCONTABLE,
AA.NNURUINT,
AA.NNURUEJC,
AA.NNURUASE,
AA.CAUSA_CANCELACION ,
CASE WHEN NEWRENEWAL ='R' THEN 1 ELSE 0 END,
NFECFIRM,
NFEINVIG,
NFETEVIG,
AA.CCODSUCU	
ORDER BY 2 DESC



INSERT INTO BASE_PBI_PREVIO

SELECT --top 10 
CASE	WHEN AA.CINTIPDO='P' THEN 'POL'
		WHEN AA.CINTIPDO='C' THEN 'CER'
		WHEN AA.CINTIPDO='E' THEN 'END' END																		AS TIPO,
CONVERT(NVARCHAR(50),AA.NNUMDOCU)+'.'+CONVERT(NVARCHAR(50),AA.NNUMENDO)+'.'+CONVERT(NVARCHAR(50),AA.NNUMCERT)+'.'+CONVERT(NVARCHAR(50),AA.NNUMITEM)	AS LLAVE_POLIZA,
''																												AS FILTRO_TIPO_RIESGO,
A.KEIRATOTAL																									AS FILTRO_RIESGO,
''																												AS FILTRO_TIPO_EMISION,
''																												AS FILTRO_TIPO_SOLUCION,
0																												AS CANTIDAD_COTIZACIONES,
AA.NNUMDOCU																										AS POLIZA,
AA.PERIODO_CONTABLE																								AS PERIODO_FECHA,
AA.CCODRAMO																										AS RAMO,
AA.NPLAN																										AS CODIGO_PLAN_COMERCIAL,
AA.NPLANTEC																										AS CODIGO_PLAN_TECNICO,
AA.CLINPROD																										AS LINEA_PRODUCTO,
A.LINEANEGOCIO																									AS LINEA_NEGOCIO,
A.RAMOCONTABLE																									AS RAMO_KEIRA,
AA.NNURUINT																										AS RUT_INTERMEDIARIO,
AA.NNURUEJC																										AS RUT_EJECUTIVO,
AA.NNURUASE																										AS RUT_ASEGURADO,
CASE WHEN AA.CAUSA_CANCELACION IN (select CAUSA_CANCELACION from TRANSACCIONAL.DBO.POLIZAS_VIGENTES_TIPO_ENDOSOS where TIPO_ENDOSO in ('CANCELACION','ANULACION')) THEN 1 ELSE 0 END,
0																												AS IND_ANULACION,		
0																												AS IND_REHABILITACION,
CASE WHEN NEWRENEWAL ='R' THEN 1 ELSE 0 END																		AS IND_RENOVACION,
NFECFIRM																										AS FECHA_EMISION,
NFEINVIG																										AS FECHA_INICIO_VIGENCIA,
NFETEVIG																										AS FECHA_TERMINO_VIGENCIA,
NULL																											AS FEHCA_TERMINO_VIGENCIA_REAL,
SUM(COMISION_02)																								AS COMISION_CLF,
SUM(COMISION_01)																								AS COMISION_CLP,
SUM(PRIMA_02)																									AS PRIMA_ORIGINAL_CLF,
SUM(PRIMA_01)																									AS PRIMA_ORIGINAL_CLP,
''																												AS FILTRO_INTERMEDIARIO,
''																												AS ORDEN_NIVEL,
''																												AS EQUIPO,
''																												AS TIPO_CARTERA,
AA.CCODSUCU																										AS SUCURSAL,
COUNT(DISTINCT AA.NNUMITEM)																						AS CANTIDAD_ITEMS,
NULL																											AS CANTIDAD_POLIZAS,
NULL																											AS CAPACIDAD
from 
FactWrittenPremium_DiarioMI AA LEFT JOIN [SGF1016].[SQLMISFACT].[dbo].[DimKeira_Class_Ramos] A ON AA.PERIODO_CONTABLE=A.PERIODO_CONTABLE AND AA.RAMOCONTABLE=A.RAMOCONTABLE 
WHERE --CINTIPDO IN ('P','R') AND 
GRSNETCEDID='Gross' AND AA.CCODRAMO	 NOT IN ('W')
GROUP BY 
AA.CINTIPDO	,
CONVERT(NVARCHAR(50),AA.NNUMDOCU)+'.'+CONVERT(NVARCHAR(50),AA.NNUMENDO)+'.'+CONVERT(NVARCHAR(50),AA.NNUMCERT)+'.'+CONVERT(NVARCHAR(50),AA.NNUMITEM),
A.KEIRATOTAL,
AA.NNUMDOCU,
AA.PERIODO_CONTABLE,
AA.CCODRAMO,
AA.NPLAN,
AA.NPLANTEC,
AA.CLINPROD,
A.LINEANEGOCIO,
A.RAMOCONTABLE,
AA.NNURUINT,
AA.NNURUEJC,
AA.NNURUASE,
AA.CAUSA_CANCELACION,
CASE WHEN NEWRENEWAL ='R' THEN 1 ELSE 0 END,
NFECFIRM,
NFEINVIG,
NFETEVIG,
AA.CCODSUCU	
ORDER BY 2 DESC



UPDATE BASE_PBI_PREVIO 
SET RAMO_KEIRA=B.REPORTE_SEGUIMIENTO
FROM BASE_PBI_PREVIO  A, SEGUIMIENTO_RAMO_KERIA B
WHERE 
A.RAMO_KEIRA=B.RAMO_CONTABLE 



--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SP_BASE_PBI','3 de 9',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

----------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------TERMINO DE LLENADO BASE_PBI_PREVIO------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------


TRUNCATE TABLE REPORTES.DBO.BASE_PBI

INSERT INTO REPORTES.DBO.BASE_PBI
SELECT 
TIPO,
LLAVE_POLIZA,
FILTRO_TIPO_RIESGO,
NULL FILTRO_RIESGO,
FILTRO_TIPO_EMISION,
FILTRO_SOLUCION,
CANTIDAD_COTIZACIONES,
POLIZA,
PERIODO_FECHA,
NULL RAMO,
CODIGO_PLAN_COMERCIAL,
CODIGO_PLAN_TECNICO,
LINEA_PRODUCTO,
LINEA_NEGOCIO,
NULL	AS RAMO_KEIRA,
RUT_INTERMEDIARIO,
RUT_EJECUTIVO,
RUT_ASEGURADO,
IND_CANCELACION,
IND_ANULACION,		
IND_REHABILITACION,
IND_RENOVACION,
FECHA_EMISION,
INICIO_VIGENCIA,
TERMINO_VIGENCIA,
TERMINO_VIGENCIA_REAL,
SUM(COMISION_CLF) AS COMISION_CLF,
SUM(COMISION_CLP) AS COMISION_CLP,
SUM(PRIMA_ORIGINAL_CLF) AS PRIMA_ORIGINAL_CLF,
SUM(PRIMA_ORIGINAL_CLP) AS PRIMA_ORIGINAL_CLP,
FILTRO_INTERMEDIARIO,
ORDEN_NIVEL,
EQUIPO,
TIPO_CARTERA,
SUCURSAL,
CANTIDAD_ITEMS,
NULL AS RUT_EJECUTIVO_CA,
NULL AS SUCURSAL_CA,
NULL AS LIDER_COMERCIAL_CA,
NULL AS CANAL,
NULL AS NOMBRE_EJECUTIVO,
NULL AS SUBGERENCIA,
NULL AS ORDEN_SOLUCION,
NULL AS SEMANA,
NULL AS CANTIDAD_EQUIPO,
NULL AS TIPO_EQUIPO,
NULL AS ORDEN_TIPO_CARTERA,
NULL AS ORDEN_TIPO,
NULL AS TIPO_ASESOR_CA,
NULL AS SEGMENTACION_CA,
NULL AS ESTADO_ASESOR_CA,
NULL AS LLAVE_CANITDAD,
NULL AS CAPACIDAD,
0	 AS CANTIDAD_POLIZAS,
NULL AS EMPRESA_SURA
FROM BASE_PBI_PREVIO
WHERE  PERIODO_FECHA IN (SELECT * FROM #ULTIMOS_PERIODOS)
GROUP BY TIPO,
LLAVE_POLIZA,
FILTRO_TIPO_RIESGO,
FILTRO_TIPO_EMISION,
FILTRO_SOLUCION,
CANTIDAD_COTIZACIONES,
POLIZA,
PERIODO_FECHA,
CODIGO_PLAN_COMERCIAL,
CODIGO_PLAN_TECNICO,
LINEA_PRODUCTO,
LINEA_NEGOCIO,
RUT_INTERMEDIARIO,
RUT_EJECUTIVO,
RUT_ASEGURADO,
IND_CANCELACION,
IND_ANULACION,		
IND_REHABILITACION,
IND_RENOVACION,
FECHA_EMISION,
INICIO_VIGENCIA,
TERMINO_VIGENCIA,
TERMINO_VIGENCIA_REAL,
FILTRO_INTERMEDIARIO,
ORDEN_NIVEL,
EQUIPO,
TIPO_CARTERA,
SUCURSAL,
CANTIDAD_ITEMS

DELETE FROM REPORTES.DBO.BASE_PBI WHERE LINEA_PRODUCTO='VID' AND TIPO='POL'

SELECT A.POLIZA,B.FEMISIO,A.RUT_ASEGURADO,B.TIPO_RECIBO,SUM(B.PRIMA_NETA_MO) PRIMA_NETA_MO ,SUM(B.PRIMA_AFECTA+B.PRIMA_EXENTA)PRIMA_NETA
INTO #AXIS_PRO_LIBRO_PRODUCCION
FROM AXIS_PRO_INVENTARIO_POLIZAS A LEFT JOIN AXIS_PRO_LIBRO_PRODUCCION B ON
A.POLIZA=B.POLIZA
WHERE YEAR(A.FECHA_GENERACION_POLIZA) >=2017 
--AND A.POLIZA=44695
AND A.RAMO=401 AND A.MODALIDAD=3  AND A.TIPO_SEGURO=1 AND A.PARENTESCO='TITULAR' AND B.TIPO_RECIBO IS NOT NULL 
GROUP BY A.POLIZA,B.FEMISIO,A.RUT_ASEGURADO,B.TIPO_RECIBO
ORDER BY 1 DESC




INSERT INTO REPORTES.DBO.BASE_PBI
SELECT 
'POL' 																							AS TIPO,
A.POLIZA																						AS LLAVE_POLIZA,
'ESTANDAR'																						AS FILTRO_TIPO_RIESGO,
'VIDA'																							AS FILTRO_RIESGO,
'WEB'																							AS FITRO_TIPO_EMISION,
'VIDA CLICK'																					AS FILTRO_SOLUCION,
0																								AS CANTIDAD_COTIZACIONES,
A.POLIZA																						AS POLIZA,
CONVERT(DATE,DATEADD(MM, DATEDIFF(MM,0,B.FEMISIO), 0) )											AS PERDIODO_FECHA,
A.RAMO																							AS RAMO,
1111																							AS PLAN_COMERCIAL,
2222																							AS PLAN_TECNICO,
'VID'																							AS LINEA_PRODUCTO,
'PERSONAL'																						AS LINEA_NEGOCIO,
'VIDA'																							AS RAMO_KEIRA,
A.COD_AGENTE																					AS RUT_INTERMEDIARIO, 
NULL																							AS RUT_EJECUTIVO,
NULL																							AS RUT_ASEGURADO, 
--CASE WHEN A.ESTADO='ANULADA' THEN 1 ELSE 0 END												AS IND_CANCELACION,	
0																								AS IND_CANCELACION,	
0																								AS IND_ANULACION,	 
0																								AS IND_REHABILITACION,	
CASE WHEN B.TIPO_RECIBO='Cartera-Renovación'	THEN 1 ELSE 0 END 								AS IND_RENOVACION,
CONVERT(DATE,B.FEMISIO)																			AS FECHA_EMISION,
CONVERT(DATE,A.FECHA_INICIO_VIGENCIA_POLIZA)													AS INICIO_VIGENCIA,	
CONVERT(DATE,A.FECHA_FIN_VIGENCIA_POLIZA)														AS TERMINO_VIGENCIA,
CONVERT(DATE,A.FECHA_ANULACION_POLIZA)															AS TERMINO_VIGENCIA_REAL,	
0																								AS COMISION_CLF,	
0																								AS COMISION_CLP,	
B.PRIMA_NETA_MO																					AS PRIMA_ORIGINAL_CLF,	
B.PRIMA_NETA																					AS PRIMA_ORIGINAL_CLP,
NULL																							AS FILTRO_INTERMEDIARIO,	
NULL																							AS ORDEN_NIVEL,	
NULL																							AS EQUIPO,	
CASE WHEN B.TIPO_RECIBO='Cartera-Renovación' THEN 'VENTA RENOVACION' ELSE 'VENTA NUEVA'  END	AS TIPO_CARTERA,	
NULL																							AS SUCURSAL,	
1																								AS CANTIDAD_ITEMS,	
NULL																							AS RUT_EJECUTIVO_CA,	
NULL																							AS SUCURSAL_CA,	
NULL																							AS LIDER_COMERCIAL_CA,	
NULL																							AS CANAL,	
NULL																							AS NOMBRE_EJECUTIVO,
NULL																							AS SUBGERENCIA,
1																								AS ORDEN_SOLUCION,
NULL																							AS SEMANA,
NULL																							AS CANTIDAD_EQUIPO,
NULL																							AS TIPO_EQUIPO,
NULL																							AS ORDEN_TIPO_CARTERA,
NULL																							AS ORDEN_TIPO,
NULL																							AS TIPO_ASESOR_CA,
NULL																							AS SEGMENTACION_CA,
NULL																							AS ESTADO_ASESOR_CA,
NULL																							AS LLAVE_CANITDAD,
NULL																							AS CAPACIDAD,
0																								AS CANTIDAD_POLIZAS,
NULL																							AS EMPRERSA_SURA
FROM AXIS_PRO_INVENTARIO_POLIZAS A LEFT JOIN #AXIS_PRO_LIBRO_PRODUCCION B ON
A.POLIZA=B.POLIZA
WHERE YEAR(A.FECHA_GENERACION_POLIZA) >=2017 
AND A.RAMO=401 AND A.MODALIDAD=3  AND A.TIPO_SEGURO=1 AND A.PARENTESCO='TITULAR' AND B.TIPO_RECIBO IS NOT NULL AND A.RUT_ASEGURADO=B.RUT_ASEGURADO
AND CONVERT(DATE,DATEADD(MM, DATEDIFF(MM,0,B.FEMISIO), 0) )	 IN (SELECT * FROM #ULTIMOS_PERIODOS)
ORDER BY B.FEMISIO DESC

SELECT DISTINCT NUMEROPOLIZA					AS POLIZA,
REPLACE(REPLACE(RUTCORREDOR,'.',''),' ','')		AS RUT_CORREDOR,
REPLACE(REPLACE(RUTEJECUTIVO,'.',''),' ','')	AS RUT_EJECUTIVO
--DROP TABLE #CORREDOR_EJECUTIVO_VIDA
INTO #CORREDOR_EJECUTIVO_VIDA
FROM WebVida 
WHERE Numeropoliza IN (SELECT DISTINCT POLIZA FROM AXIS_PRO_INVENTARIO_POLIZAS) ORDER BY 3 DESC


UPDATE #CORREDOR_EJECUTIVO_VIDA
SET 
RUT_CORREDOR=	CASE WHEN RUT_CORREDOR=''	THEN '' ELSE LEFT(RUT_CORREDOR,	LEN(RUT_CORREDOR)	-2)END,
RUT_EJECUTIVO=	CASE WHEN RUT_EJECUTIVO=''	THEN '' ELSE LEFT(RUT_EJECUTIVO,LEN(RUT_EJECUTIVO)	-2)END

UPDATE REPORTES.DBO.BASE_PBI
SET RUT_INTERMEDIARIO=B.RUT_CORREDOR, RUT_EJECUTIVO=B.RUT_EJECUTIVO
FROM REPORTES.DBO.BASE_PBI A,#CORREDOR_EJECUTIVO_VIDA B
WHERE A.POLIZA=B.POLIZA AND A.FILTRO_RIESGO='VIDA'

SELECT DISTINCT RUT_INTERMEDIARIO,RUT_EJECUTIVO,SUCURSAL INTO #SUCURSAL_VIDA FROM BASE_PBI WHERE FILTRO_RIESGO<>'VIDA' AND TIPO_EQUIPO='NO CA'AND SUCURSAL <>'SIN ASIGNAR'

UPDATE REPORTES.DBO.BASE_PBI
SET SUCURSAL=B.SUCURSAL
FROM REPORTES.DBO.BASE_PBI A, #SUCURSAL_VIDA B
WHERE A.RUT_EJECUTIVO=B.RUT_EJECUTIVO AND A.FILTRO_RIESGO='VIDA' AND A.TIPO_EQUIPO='NO CA'



UPDATE CANAL_ASESOR.DBO.TRONCO_COTIZACION
SET RUT_EJECUTIVO =''
WHERE RUT_EJECUTIVO LIKE ('%M%')

UPDATE CANAL_ASESOR.DBO.TRONCO_COTIZACION
SET RUT_EJECUTIVO =''
WHERE RUT_EJECUTIVO LIKE ('%l%')

UPDATE CANAL_ASESOR.DBO.TRONCO_COTIZACION
SET RUT_EJECUTIVO =''
WHERE RUT_EJECUTIVO LIKE ('%BERTA TORR%')

UPDATE CANAL_ASESOR.DBO.TRONCO_COTIZACION
SET RUT_EJECUTIVO =''
WHERE RUT_EJECUTIVO LIKE ('%C arce%')


UPDATE CANAL_ASESOR.DBO.TRONCO_COTIZACION
SET RUT_EJECUTIVO =REPLACE(RUT_EJECUTIVO,'-',''),RUT_ASEGURADO =REPLACE(RUT_ASEGURADO,'-',''),RUT_INTERMEDIARIO=REPLACE(RUT_INTERMEDIARIO,'-','')

DELETE FROM REPORTES.DBO.BASE_PBI WHERE TIPO='COT'

INSERT INTO REPORTES.DBO.BASE_PBI
SELECT
'COT'																					AS TIPO,
0																						AS LLAVE_POLIZA, 	
'ESTANDAR'																				AS FILTRO_TIPO_RIESGO, 	
SOLUCION																				AS RIESGO, 	
'WEB'																					AS TIPO_EMISION, 	
CANAL																					AS SOLUCION, 	
COUNT(*)																				AS CANTIDAD_COTIZACIONES, 	
POLIZA																					AS POLIZA, 	
CONVERT(DATE,DATEADD(MM, DATEDIFF(MM,0,FECHA_COTIZACION), 0) )							AS PERIODO_FECHA, 	
RAMO																					AS RAMO, 	
0																						AS CODIGO_PLAN_COMERCIAL, 
CODIGO_PLAN_TECNICO																		AS CODIGO_PLAN_TECNICO, 	
LINEA_PRODUCTO																			AS LINEA_PRODUCTO, 	
0																						AS LINEA_NEGOCIO, 	
0																						AS RAMO_KEIRA, 	
RUT_INTERMEDIARIO																		AS RUT_INTERMEDIARIO, 	
CASE WHEN ISNUMERIC(SUBSTRING (RUT_EJECUTIVO,1,1))=0 THEN NULL ELSE RUT_EJECUTIVO END	AS RUT_EJECUTIVO, 	
NULL																					AS RUT_ASEGURADO, 	 	
0																						AS IND_CANCELACION, 	
0																						AS IND_ANULACION, 	
0																						AS IND_REHABILITACION, 	
0																						AS IND_RENOVACON, 	
FECHA_COTIZACION																		AS FECHA_EMISON, 	
NULL																					AS INICIO_VIGENCIA, 	
NULL																					AS TERMINO_VIGENCIA, 	
NULL																					AS TERMINO_VIGENCIA_REAL, 	
0																						AS COMISION_CLF, 
0																						AS COMISION_CLP, 	
0																						AS PRIMA_ORIGINAL_CLF,
0																						AS PRIMA_ORIGINAL_CLP,
NULL AS FILTRO_INTERMEDIARIO,
NULL AS ORDEN_NIVEL_ACTIVIDAD,
NULL AS EQUIPO,
NULL AS TIPO_CARTERA,
NULL AS SUCURSAL,
0 AS CANTIDAD_ITEMS,
NULL AS RUT_EJECUTIVO_CA,
NULL AS SUCURSAL_CA,
NULL AS LIDER_COMERCIAL_CA,
NULL AS CANAL,
NULL AS NOMBRE_EJECUTIVO,
NULL AS SUBGERENCIA,
NULL AS ORDEN_SOLUCION,
NULL AS SEMANA,
NULL AS CANTIDAD_EQUIPO,
NULL AS TIPO_EQUIPO,
NULL AS ORDEN_TIPO_CARTERA,
NULL AS ORDEN_TIPO,
NULL AS TIPO_ASESOR_CA,
NULL AS SEGMENTACION_CA,
NULL AS ESTADO_ASESOR_CA,
NULL AS LLAVE_CANITDAD,
NULL AS CAPACIDAD,
0    AS CANTIDAD_POLIZAS,
NULL AS EMPRESA_SURA
FROM 
CANAL_ASESOR.DBO.TRONCO_COTIZACION
WHERE CONVERT(DATE,DATEADD(MM, DATEDIFF(MM,0,FECHA_COTIZACION), 0) )	IN (SELECT * FROM #ULTIMOS_PERIODOS)
--WHERE SOLUCION LIKE ('%VIDA%')
GROUP BY 
SOLUCION, 	
CANAL, 	
POLIZA,
CONVERT(DATE,DATEADD(MM, DATEDIFF(MM,0,FECHA_COTIZACION), 0) ), 	
RAMO, 	
CODIGO_PLAN_TECNICO, 	
LINEA_PRODUCTO, 		
RUT_INTERMEDIARIO, 	
NOMBRE_INTERMEDIARIO,
CASE WHEN ISNUMERIC(SUBSTRING (RUT_EJECUTIVO,1,1))=0 THEN NULL ELSE RUT_EJECUTIVO END,
FECHA_COTIZACION

--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SP_BASE_PBI','4 de 9',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
----------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------TERMINO DE LLENADO BASE_PBI-------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------
TRUNCATE TABLE BASE_CANTIDAD_ASESORES
INSERT INTO BASE_CANTIDAD_ASESORES
SELECT 
UPPER(PERIODO)			AS PERIODO,
UPPER(SUCURSAL)			AS SUCURSAL,
UPPER(SEGMENTACION)		AS SEGMENTACION,
UPPER(TIPO)				AS TIPO,
UPPER(ZONA)				AS ZONA,
UPPER(ESTADO_ASESOR)	AS ESTADO_ASESOR,
CASE WHEN ZONA='FRANQUICIA' THEN 'FRANQUICIA' ELSE 'CA' END EQUIPO, 
UPPER(REPLACE(RTRIM(CONVERT(NVARCHAR(10),PERIODO)+'-'+SUCURSAL+'-'+SEGMENTACION+'-'+TIPO+'-'+ZONA+'-'+ESTADO_ASESOR+'-'+CASE WHEN ZONA='FRANQUICIA' THEN 'FRANQUICIA' ELSE 'CA' END ),' ','')) AS LLAVE_CANTIDAD ,COUNT(*) CANTIDAD_ASESORES
FROM BASE_CORREDOR_EJECUTIVO_CA b
--WHERE PERIODO IN ('2021-03-01') and SEGMENTACIOn= 'FORMACIÓN (CAP)' and ESTADO_ASESOR='activo'
GROUP BY 
PERIODO,SUCURSAL,SEGMENTACION,TIPO,ZONA,ESTADO_ASESOR,CASE WHEN ZONA='FRANQUICIA' THEN 'FRANQUICIA' ELSE 'CA' END ,
UPPER(REPLACE(RTRIM(CONVERT(NVARCHAR(10),PERIODO)+'-'+SUCURSAL+'-'+SEGMENTACION+'-'+TIPO+'-'+ZONA+'-'+ESTADO_ASESOR+'-'+CASE WHEN ZONA='FRANQUICIA' THEN 'FRANQUICIA' ELSE 'CA' END),' ',''))




---------------SUCURSAL, FILTRO_RIESGO,RAMO,RAMO_KEIRA,RUT_EJECUTIVO,SUBGERENCIA
--------------------------------------------------------------------------------


UPDATE REPORTES.DBO.BASE_PBI
SET RAMO_KEIRA=B.REPORTE_SEGUIMIENTO
FROM REPORTES.DBO.BASE_PBI A, SEGUIMIENTO_RAMO_KERIA B
WHERE 
A.RAMO_KEIRA=B.RAMO_CONTABLE 

UPDATE REPORTES.DBO.BASE_PBI
SET SUCURSAL=B.CDESELEM                                          
FROM REPORTES.DBO.BASE_PBI A, [SGF1016].[SQLMISFACT].[dbo].[DimSucursal] B
WHERE A.SUCURSAL=B.CCODSUCU AND A.PERIODO_FECHA IN (SELECT * FROM #ULTIMOS_PERIODOS)

SELECT LLAVE_POLIZA,'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'FILTRO_RIESGO,'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'RAMO_KEIRA,'XX'RAMO,
MAX(ABS(PRIMA_ORIGINAL_CLF)) PRIMA_ORIGINAL_CLF 
INTO #PRIMA_MAYOR
FROM BASE_PBI_PREVIO
GROUP BY LLAVE_POLIZA


UPDATE #PRIMA_MAYOR
SET FILTRO_RIESGO=B.FILTRO_RIESGO,RAMO=B.RAMO,RAMO_KEIRA=B.RAMO_KEIRA
FROM #PRIMA_MAYOR A,BASE_PBI_PREVIO B
WHERE A.LLAVE_POLIZA=B.LLAVE_POLIZA AND A.PRIMA_ORIGINAL_CLF=ABS(B.PRIMA_ORIGINAL_CLF)

UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_RIESGO=B.FILTRO_RIESGO,RAMO=B.RAMO, RAMO_KEIRA=B.RAMO_KEIRA
FROM REPORTES.DBO.BASE_PBI A,#PRIMA_MAYOR B
WHERE
A.LLAVE_POLIZA=B.LLAVE_POLIZA 


SELECT SPERSON,CAGENTE INTO #AGENTES FROM OPENQUERY([IAXIS_PROD],'SELECT * from AGENTES') 
DELETE FROM #AGENTES WHERE CAGENTE NOT IN (SELECT RUT_INTERMEDIARIO FROM REPORTES.DBO.BASE_PBI WHERE FILTRO_SOLUCION='VIDA CLICK' GROUP BY RUT_INTERMEDIARIO)
SELECT * INTO #PER_PERSONAS FROM OPENQUERY([IAXIS_PROD],'SELECT A.* from PER_PERSONAS A, AGENTES B WHERE A.SPERSON=B.SPERSON')


SELECT A.CAGENTE,B.NNUMIDE INTO #RUT_INTERMEDIARIO_VID FROM #AGENTES A,#PER_PERSONAS B
WHERE 
A.SPERSON=B.SPERSON



UPDATE REPORTES.DBO.BASE_PBI
SET RUT_INTERMEDIARIO=B.NNUMIDE
FROM REPORTES.DBO.BASE_PBI A, #RUT_INTERMEDIARIO_VID B
WHERE A.RUT_INTERMEDIARIO=B.CAGENTE


SELECT DISTINCT RUT_INTERMEDIARIO,RUT_EJECUTIVO,PERIODO_FECHA,SUCURSAL,SUBGERENCIA INTO #EJECUTIVO_COT FROM REPORTES.DBO.BASE_PBI WHERE TIPO <>'COT' AND FILTRO_SOLUCION<>'VIDA CLICK'

UPDATE REPORTES.DBO.BASE_PBI
SET RUT_EJECUTIVO=B.RUT_EJECUTIVO, SUCURSAL=B.SUCURSAL,SUBGERENCIA=B.SUBGERENCIA
FROM REPORTES.DBO.BASE_PBI A, #EJECUTIVO_COT B
WHERE A.RUT_INTERMEDIARIO=B.RUT_INTERMEDIARIO AND A.PERIODO_FECHA=B.PERIODO_FECHA  AND  TIPO ='COT'

UPDATE REPORTES.DBO.BASE_PBI
SET RUT_EJECUTIVO=B.RUT_EJECUTIVO, SUCURSAL=B.SUCURSAL,SUBGERENCIA=B.SUBGERENCIA
FROM REPORTES.DBO.BASE_PBI A, #EJECUTIVO_COT B
WHERE A.RUT_INTERMEDIARIO=B.RUT_INTERMEDIARIO AND A.TIPO ='COT' AND A.RUT_EJECUTIVO IS NULL

UPDATE REPORTES.DBO.BASE_PBI
SET RUT_EJECUTIVO=B.RUT_EJECUTIVO, SUCURSAL=B.SUCURSAL,SUBGERENCIA=B.SUBGERENCIA
FROM REPORTES.DBO.BASE_PBI A, #EJECUTIVO_COT B
WHERE A.RUT_INTERMEDIARIO=B.RUT_INTERMEDIARIO AND A.SUCURSAL IS NULL

UPDATE REPORTES.DBO.BASE_PBI
SET RUT_EJECUTIVO=B.RUT_EJECUTIVO, SUCURSAL=B.SUCURSAL
FROM REPORTES.DBO.BASE_PBI A, #EJECUTIVO_COT B
WHERE A.RUT_INTERMEDIARIO=B.RUT_INTERMEDIARIO AND A.PERIODO_FECHA=B.PERIODO_FECHA  AND  FILTRO_SOLUCION='VIDA CLICK'

UPDATE REPORTES.DBO.BASE_PBI
SET RUT_EJECUTIVO=B.RUT_EJECUTIVO, SUCURSAL=B.SUCURSAL
FROM REPORTES.DBO.BASE_PBI A, #EJECUTIVO_COT B
WHERE A.RUT_INTERMEDIARIO=B.RUT_INTERMEDIARIO AND  FILTRO_SOLUCION='VIDA CLICK' AND A.SUCURSAL IS NULL


--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SP_BASE_PBI','5 de 9',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
------------------NOMBRE INTERMEDIARIO
--------------------------------------
--SELECT * FROM BASE_CORREDOR where RUT_INTERMEDIARIO=14241271
--SELECT * FROM #INTERMEDIARIO where RUT=14241271

DELETE FROM BASE_CORREDOR WHERE INTERMEDIARIO='SIN REGISTRO EN SOL'

INSERT INTO BASE_CORREDOR
SELECT *,'SIN REGISTRO EN SOL' FROM (
SELECT DISTINCT RUT_INTERMEDIARIO FROM REPORTES.DBO.BASE_PBI WHERE RUT_INTERMEDIARIO not in  (SELECT RUT_INTERMEDIARIO FROM BASE_CORREDOR ))X

SELECT RUT_INTERMEDIARIO INTO #INTERMEDIARIOS FROM BASE_CORREDOR WHERE INTERMEDIARIO='SIN REGISTRO EN SOL'

SELECT B.RUT,REPLACE(UPPER(B.NOMBRE),'  ','') +' '+ REPLACE(UPPER(APELLIDO_PATERNO),'  ','')CNOCOPER
 INTO #INTERMEDIARIO 
FROM #INTERMEDIARIOS A LEFT JOIN ALMACEN_DE_DATOS.DBO.SURA_MAESTRO_PERSONA_FULL B ON
A.RUT_INTERMEDIARIO=B.RUT 
WHERE B.RUT IS NOT NULL



UPDATE BASE_CORREDOR
SET INTERMEDIARIO=UPPER(B.CNOCOPER)
FROM BASE_CORREDOR A,#INTERMEDIARIO B
WHERE A.RUT_INTERMEDIARIO=B.RUT



---SUCURSAL CANAL ASESOR -----------------------------------
UPDATE REPORTES.DBO.BASE_PBI
SET SUCURSAL_CA='SIN ASIGNAR',ZONA='SIN ASIGNAR',LIDER_COMERCIAL_CA=NULL

UPDATE REPORTES.DBO.BASE_PBI
SET 
RUT_EJECUTIVO_CA	=B.RUT_EJECUTIVO, 
SUCURSAL_CA			=UPPER(B.SUCURSAL),
--SUCURSAL			=REPLACE(B.SUCURSAL,' - CA',''),
LIDER_COMERCIAL_CA	=UPPER(B.LIDER_COMERCIAL),
TIPO_ASESOR_CA		=UPPER(B.TIPO),
SEGMENTACION_CA		=UPPER(B.SEGMENTACION),
ESTADO_ASESOR_CA	=UPPER(B.ESTADO_ASESOR),
CANTIDAD_EQUIPO		=B.CANTIDAD_EQUIPO,
ZONA				=UPPER(B.ZONA)
FROM REPORTES.DBO.BASE_PBI A, BASE_CORREDOR_EJECUTIVO_CA B
WHERE 
A.RUT_INTERMEDIARIO=B.RUT_INTERMEDIARIO AND YEAR(A.PERIODO_FECHA)*100 + MONTH(A.PERIODO_FECHA)=YEAR(B.PERIODO)*100 + MONTH(B.PERIODO)
AND A.RUT_EJECUTIVO=B.RUT_EJECUTIVO
AND B.AREA='EX PYME'

UPDATE REPORTES.DBO.BASE_PBI
SET 
RUT_EJECUTIVO_CA	=B.RUT_EJECUTIVO, 
SUCURSAL_CA			=UPPER(B.SUCURSAL),
--SUCURSAL			=REPLACE(B.SUCURSAL,' - CA',''),
LIDER_COMERCIAL_CA	=UPPER(B.LIDER_COMERCIAL),
TIPO_ASESOR_CA		=UPPER(B.TIPO),
SEGMENTACION_CA		=UPPER(B.SEGMENTACION),
ESTADO_ASESOR_CA	=UPPER(B.ESTADO_ASESOR),
CANTIDAD_EQUIPO		=B.CANTIDAD_EQUIPO,
ZONA				=UPPER(B.ZONA)
FROM REPORTES.DBO.BASE_PBI A, BASE_CORREDOR_EJECUTIVO_CA B
WHERE 
A.RUT_INTERMEDIARIO=B.RUT_INTERMEDIARIO AND YEAR(A.PERIODO_FECHA)*100 + MONTH(A.PERIODO_FECHA)=YEAR(B.PERIODO)*100 + MONTH(B.PERIODO)
AND B.AREA<>'EX PYME'


UPDATE REPORTES.DBO.BASE_PBI
SET RUT_EJECUTIVO=99017000, SUCURSAL='CASA MATRIZ',SUCURSAL_CA='CASA MATRIZ',SUBGERENCIA='CASA MATRIZ'
FROM REPORTES.DBO.BASE_PBI WHERE RUT_INTERMEDIARIO IN(99017000) AND  TIPO ='COT'

UPDATE REPORTES.DBO.BASE_PBI
SET RUT_EJECUTIVO=76263414, SUCURSAL='CASA MATRIZ',SUCURSAL_CA='CASA MATRIZ',SUBGERENCIA='CASA MATRIZ',CANAL='CANAL DIRECTO'
FROM REPORTES.DBO.BASE_PBI WHERE RUT_INTERMEDIARIO IN(76263414) 

UPDATE REPORTES.DBO.BASE_PBI
SET RUT_EJECUTIVO_CA=RUT_EJECUTIVO, SUCURSAL_CA=SUCURSAL
WHERE SUCURSAL_CA='SIN ASIGNAR'

UPDATE REPORTES.DBO.BASE_PBI
SET LIDER_COMERCIAL_CA='NO CANAL ASESOR'
WHERE LIDER_COMERCIAL_CA IS NULL

UPDATE REPORTES.DBO.BASE_PBI
SET SUCURSAL='SIN ASIGNAR'
WHERE SUCURSAL IS NULL

UPDATE REPORTES.DBO.BASE_PBI
SET SUCURSAL_CA='SIN ASIGNAR'
WHERE SUCURSAL_CA IS NULL



-------------------RAMO_KERIRA,LINEA_PRODUCTO,FILTRO_SOLUCION,FILTRO_TIPO_RIESGO,
UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_TIPO_RIESGO='ESTANDAR', FILTRO_SOLUCION='VIDA CLICK'
where FILTRO_RIESGO like ('%VIDA%')

UPDATE REPORTES.DBO.BASE_PBI
SET RAMO_KEIRA=B.RAMO_KEIRA
FROM REPORTES.DBO.BASE_PBI A,(SELECT RAMO_KEIRA ,CODIGO_PLAN_TECNICO 
FROM REPORTES.DBO.BASE_PBI WHERE TIPO<>'COT'
GROUP BY RAMO_KEIRA,CODIGO_PLAN_TECNICO )B
WHERE A.CODIGO_PLAN_TECNICO=B.CODIGO_PLAN_TECNICO AND TIPO='COT'

UPDATE REPORTES.DBO.BASE_PBI
SET LINEA_PRODUCTO=B.LINEA_PRODUCTO
FROM REPORTES.DBO.BASE_PBI A,(SELECT LINEA_PRODUCTO ,CODIGO_PLAN_TECNICO 
FROM REPORTES.DBO.BASE_PBI WHERE TIPO<>'COT'
GROUP BY LINEA_PRODUCTO,CODIGO_PLAN_TECNICO )B
WHERE A.CODIGO_PLAN_TECNICO=B.CODIGO_PLAN_TECNICO AND TIPO='COT'

UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_SOLUCION='OTRO',FILTRO_TIPO_RIESGO='NO ESTANDAR'

UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_SOLUCION=B.SOLUCION, CAPACIDAD=B.CAPACIDAD
FROM REPORTES.DBO.BASE_PBI A, CANAL_ASESOR.DBO.PLAN_TECNICO B
WHERE A.CODIGO_PLAN_TECNICO=B.COD_PLAN_TECNICO




UPDATE REPORTES.DBO.BASE_PBI
SET 
FILTRO_TIPO_RIESGO		='ESTANDAR', 
FILTRO_RIESGO			= B.RIESGO, 
ORDEN_SOLUCION			= B.ORDEN_SOLUCION
FROM REPORTES.DBO.BASE_PBI A, (
SELECT *,
CASE WHEN SOLUCION LIKE ('%AUTO%')				THEN 'MOTOR'			ELSE 
CASE WHEN SOLUCION LIKE ('%CAMIONES CLICK%')	THEN 'CAMIONES'			ELSE
CASE WHEN SOLUCION LIKE ('%CONDOMINIO%')		THEN 'CONDOMINIO'		ELSE
CASE WHEN SOLUCION LIKE ('%HOGAR%')				THEN 'HOGAR'			ELSE
CASE WHEN SOLUCION LIKE ('%PYME%')				THEN 'PYME'				ELSE
CASE WHEN SOLUCION LIKE ('%RC %')				THEN 'RC'				ELSE
CASE WHEN SOLUCION LIKE ('%VIDA%')				THEN 'VIDA'				ELSE
CASE WHEN SOLUCION LIKE ('%CONTENE%')			THEN 'CONTENEDORES'		ELSE
CASE WHEN SOLUCION LIKE ('%VIAJE%')				THEN 'VIAJE'			ELSE'OTRO' END END END END END END END END END  RIESGO
FROM CANAL_ASESOR.DBO.PLAN_TECNICO)B
WHERE 
A.CODIGO_PLAN_TECNICO=B.COD_PLAN_TECNICO 

UPDATE REPORTES.DBO.BASE_PBI
SET CANTIDAD_COTIZACIONES=1 WHERE POLIZA<>0 AND FILTRO_SOLUCION IN ('CAMIONES CLICK','CONTENEDORES CLICK','RC EMPRESAS','RC WEB','VIAJE ESPECIFICO CLICK')
AND TIPO='POL'



--WEB
UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_TIPO_EMISION='WEB'
WHERE POLIZA IN (SELECT DISTINCT POLIZA FROM CANAL_ASESOR.DBO.TRONCO_COTIZACION WHERE POLIZA<>0)
AND FILTRO_TIPO_EMISION=''

--RENOVACIONES WEB

SELECT * INTO #REN_WEB FROM OPENQUERY(SOL,'
SELECT
DISTINCT NNDOCNEW
FROM RSASOLDB2.SUACSRNV
WHERE CUSUARIO=''RENMOTWEB'' AND CAPLICAC=''RENOVACION MOTORS WEB''
		  ')


UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_TIPO_EMISION='WEB'
WHERE POLIZA IN (SELECT NNDOCNEW FROM #REN_WEB )
AND FILTRO_TIPO_EMISION=''

--MASIVO

SELECT * INTO #MASIVO FROM OPENQUERY(SOL,'
SELECT
DISTINCT NNUMDOCU
FROM RSASOLDB2.RDACSDNN
WHERE NNUMDOCU<>0
		  ')

UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_TIPO_EMISION='MASIVO'
WHERE POLIZA IN (SELECT  NNUMDOCU FROM #MASIVO )
AND FILTRO_TIPO_EMISION=''

--MANUAL
UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_TIPO_EMISION='MANUAL'
WHERE FILTRO_TIPO_EMISION=''


DELETE FROM REPORTES.DBO.BASE_PBI WHERE RAMO_KEIRA='0'


--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SP_BASE_PBI','6 de 9',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

------------------------ACTUALIZACION CANAL
--UPDATE BASE_PBI SET CANAL=NULL, NOMBRE_EJECUTIVO =NULL

UPDATE REPORTES.DBO.BASE_PBI
SET CANAL=B.CANAL, NOMBRE_EJECUTIVO=B.NOMBRE_EJECUTIVO,SUBGERENCIA=B.SUBGERENCIA 
FROM REPORTES.DBO.BASE_PBI A, BASE_CANAL_DIARIO B
WHERE A.RUT_EJECUTIVO=B.RUT_EJECUTIVO AND A.PERIODO_FECHA=B.PERIODO_CONTABLE



UPDATE REPORTES.DBO.BASE_PBI
SET CANAL=B.CANAL, NOMBRE_EJECUTIVO=B.NOMBRE_EJECUTIVO,SUBGERENCIA=B.SUBGERENCIA 
FROM REPORTES.DBO.BASE_PBI A, BASE_CANAL_MENSUAL B
WHERE A.RUT_EJECUTIVO=B.RUT_EJECUTIVO AND A.PERIODO_FECHA=B.PERIODO_CONTABLE

UPDATE REPORTES.DBO.BASE_PBI
SET CANAL=B.CANAL,NOMBRE_EJECUTIVO=B.NOMBRE_EJECUTIVO
FROM REPORTES.DBO.BASE_PBI A,
(SELECT RUT_EJECUTIVO,CANAL,NOMBRE_EJECUTIVO FROM REPORTES.DBO.BASE_PBI WHERE RUT_EJECUTIVO IN (SELECT RUT_EJECUTIVO FROM REPORTES.DBO.BASE_PBI WHERE CANAL IS NULL AND TIPO <>'COT' GROUP BY RUT_EJECUTIVO )
GROUP BY RUT_EJECUTIVO,CANAL,NOMBRE_EJECUTIVO HAVING CANAL IS NOT NULL)B
WHERE A.CANAL IS NULL AND A.RUT_EJECUTIVO=B.RUT_EJECUTIVO

UPDATE REPORTES.DBO.BASE_PBI
SET CANAL='UNDEFINED',NOMBRE_EJECUTIVO='SIN ASIGNACION',SUBGERENCIA='SIN ASIGNACIÓN EJECUTIVO'
FROM REPORTES.DBO.BASE_PBI
WHERE CANAL IS NULL




--PARA MARCAR LOS INTERMEDIARIOS REGULARES
SELECT RUT_INTERMEDIARIO,SUM(MARCA_COTIZACION)MARCA_COTIZACION INTO  #INTERMEDIARIO_REGULARES FROM(
select RUT_INTERMEDIARIO,PERIODO_FECHA,1 AS MARCA_COTIZACION from REPORTES.DBO.BASE_PBI WHERE CANTIDAD_COTIZACIONES>0
AND PERIODO_FECHA >=DATEADD(MM,-12,DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE())-1, 0))
GROUP BY RUT_INTERMEDIARIO,PERIODO_FECHA)X
GROUP BY RUT_INTERMEDIARIO
HAVING SUM(MARCA_COTIZACION)>=9

UPDATE REPORTES.DBO.BASE_PBI
SET POLIZA=0 WHERE TIPO='COT'




---ORDERN TIPO
UPDATE REPORTES.DBO.BASE_PBI
SET ORDEN_TIPO=1
WHERE TIPO='POL'

UPDATE REPORTES.DBO.BASE_PBI
SET ORDEN_TIPO=2
WHERE TIPO='CER'

UPDATE REPORTES.DBO.BASE_PBI
SET ORDEN_TIPO=3
WHERE TIPO='END'

UPDATE REPORTES.DBO.BASE_PBI
SET ORDEN_TIPO=4
WHERE TIPO='COT'


--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SP_BASE_PBI','7 de 9',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

---TIPO CARTERA
UPDATE REPORTES.DBO.BASE_PBI
SET TIPO_CARTERA='VENTA NUEVA', ORDEN_TIPO_CARTERA=1
WHERE TIPO IN ('POL','CER') AND IND_ANULACION=0 AND IND_CANCELACION=0 AND IND_RENOVACION=0

UPDATE REPORTES.DBO.BASE_PBI
SET TIPO_CARTERA='VENTA RENOVACION', ORDEN_TIPO_CARTERA=2
WHERE TIPO IN ('POL','CER') AND IND_ANULACION=0 AND IND_CANCELACION=0 AND IND_RENOVACION=1




UPDATE REPORTES.DBO.BASE_PBI
SET TIPO_CARTERA='OTROS ENDOSO', ORDEN_TIPO_CARTERA=4
WHERE TIPO IN ('END')

UPDATE REPORTES.DBO.BASE_PBI
SET TIPO_CARTERA='ENDOSOS DE CANCELACION', ORDEN_TIPO_CARTERA=3
WHERE (IND_ANULACION+IND_CANCELACION)>0 

UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_RIESGO='VEHICULO'
WHERE FILTRO_RIESGO='MOTOR'

UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_RIESGO='OTROS'
WHERE FILTRO_RIESGO='OTRO'


---------ACTUALIZACION PRODUCTO DE VIDA
UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_TIPO_RIESGO='ESTANDAR', FILTRO_SOLUCION='VIDA CLICK',TIPO_CARTERA='VENTA NUEVA', ORDEN_TIPO_CARTERA=1
WHERE LINEA_PRODUCTO='VID' AND TIPO='POL' AND IND_RENOVACION=0

UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_TIPO_RIESGO='ESTANDAR', FILTRO_SOLUCION='VIDA CLICK',TIPO_CARTERA='VENTA RENOVACION', ORDEN_TIPO_CARTERA=2
WHERE LINEA_PRODUCTO='VID' AND TIPO='POL' AND IND_RENOVACION=1

---------SEMANAS
UPDATE REPORTES.DBO.BASE_PBI
SET SEMANA= DATEPART(WEEK,FECHA_EMISION)-1					
---------

--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SP_BASE_PBI','8 de 9',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TRUNCATE TABLE BASE_EQUIPO
INSERT INTO BASE_EQUIPO
select  SUCURSAL,MAX(ZONA) from BASE_CORREDOR_EJECUTIVO_CA 
GROUP BY SUCURSAL
ORDER BY 1 DESC


UPDATE BASE_EQUIPO
SET EQUIPO='CA'
WHERE EQUIPO<>'FRANQUICIAS'

UPDATE BASE_EQUIPO
SET EQUIPO='FRANQUICIA'
WHERE EQUIPO='FRANQUICIAS'


UPDATE REPORTES.DBO.BASE_PBI
SET EQUIPO='NO CA'

UPDATE REPORTES.DBO.BASE_PBI
SET EQUIPO=B.EQUIPO
FROM REPORTES.DBO.BASE_PBI A,BASE_EQUIPO B
WHERE A.SUCURSAL_CA=B.SUCURSAL



---------CANTIDAD_EQUIPO
SELECT PERIODO_FECHA,SUCURSAL_CA,COUNT(DISTINCT RUT_INTERMEDIARIO )CANTIDAD INTO #CANTIDAD_SUCURSAL_NO_CA FROM REPORTES.DBO.BASE_PBI
WHERE EQUIPO<>'CA'
GROUP BY PERIODO_FECHA,SUCURSAL_CA



UPDATE REPORTES.DBO.BASE_PBI
SET CANTIDAD_EQUIPO=B.CANTIDAD
FROM  REPORTES.DBO.BASE_PBI A , #CANTIDAD_SUCURSAL_NO_CA B
WHERE A.SUCURSAL_CA=B.SUCURSAL_CA AND A.PERIODO_FECHA=B.PERIODO_FECHA

----------- TIPO EQUIPO
UPDATE REPORTES.DBO.BASE_PBI
SET TIPO_EQUIPO='NO CA'

UPDATE REPORTES.DBO.BASE_PBI
SET TIPO_EQUIPO='CA'
WHERE EQUIPO IN('CA','FRANQUICIA')



----------- FILTRO INTERMEDIARIO
UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_INTERMEDIARIO =NULL

UPDATE REPORTES.DBO.BASE_PBI
SET FILTRO_INTERMEDIARIO =CONVERT(NVARCHAR(10),A.RUT_INTERMEDIARIO) +' - '+UPPER(B.INTERMEDIARIO)
FROM REPORTES.DBO.BASE_PBI A, BASE_CORREDOR B
WHERE A.RUT_INTERMEDIARIO=B.RUT_INTERMEDIARIO

----------- ZONA

UPDATE REPORTES.DBO.BASE_PBI 
SET ZONA=B.ZONA
FROM REPORTES.DBO.BASE_PBI A, BASE_ZONA B
WHERE
A.SUCURSAL=B.SUCURSAL AND A.ZONA='SIN ASIGNAR'

UPDATE REPORTES.DBO.BASE_PBI
SET LLAVE_CANTIDAD=UPPER(REPLACE(RTRIM(CONVERT(NVARCHAR(10),PERIODO_FECHA)+'-'+SUCURSAL_CA+'-'+SEGMENTACION_CA+'-'+TIPO_ASESOR_CA+'-'+ZONA+'-'+ESTADO_ASESOR_CA+'-'+CASE WHEN ZONA='FRANQUICIA' THEN 'FRANQUICIA' ELSE 'CA' END ),' ',''))
WHERE LIDER_COMERCIAL_CA<>'NO CANAL ASESOR'

UPDATE REPORTES.DBO.BASE_PBI
SET LLAVE_CANTIDAD=UPPER(REPLACE(RTRIM(CONVERT(NVARCHAR(10),PERIODO_FECHA)+'-'+SUCURSAL+'-'+'SIN SEGMENTACION'+'-'+TIPO+'-'+ZONA+'-'+'ACTIVO'+'-'+'NO CA' ),' ',''))
WHERE LIDER_COMERCIAL_CA='NO CANAL ASESOR'

--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SP_BASE_PBI','9 de 9',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


TRUNCATE    TABLE SUCURSALES_CA_ASIGNADOS
INSERT INTO SUCURSALES_CA_ASIGNADOS
SELECT DISTINCT SUCURSAL,CANTIDAD_EQUIPO,PERIODO 
FROM BASE_CORREDOR_EJECUTIVO_CA ORDER BY 1 DESC

UPDATE REPORTES.DBO.BASE_PBI
SET CANAL=
CASE WHEN TIPO_EQUIPO='CA' THEN 'CANAL ASESOR' ELSE 
CASE WHEN RUT_INTERMEDIARIO IN(	99017000,76263414) THEN 'DIRECTO' ELSE 'PYME' END END

INSERT INTO BASE_CANTIDAD_ASESORES
SELECT 
UPPER(PERIODO_FECHA)	AS PERIODO,
UPPER(SUCURSAL)			AS SUCURSAL,
'SIN SEGMENTACION'		AS SEGMENTACION,
UPPER(TIPO)				AS TIPO,
UPPER(ZONA)				AS ZONA,
'ACTIVO'				AS ESTADO_ASESOR,
'NO CA'					AS EQUIPO, 
UPPER(REPLACE(RTRIM(CONVERT(NVARCHAR(10),PERIODO_FECHA)+'-'+SUCURSAL+'-'+'SIN SEGMENTACION'+'-'+TIPO+'-'+ZONA+'-'+'ACTIVO'+'-'+'NO CA' ),' ','')) AS LLAVE_CANTIDAD ,
COUNT(DISTINCT RUT_INTERMEDIARIO) CANTIDAD_ASESORES
FROM REPORTES.DBO.BASE_PBI
WHERE LIDER_COMERCIAL_CA='NO CANAL ASESOR'
GROUP BY 
PERIODO_FECHA,SUCURSAL,TIPO,ZONA,
UPPER(REPLACE(RTRIM(CONVERT(NVARCHAR(10),PERIODO_FECHA)+'-'+SUCURSAL+'-'+'SIN SEGMENTACION'+'-'+TIPO+'-'+ZONA+'-'+'ACTIVO'+'-'+'NO CA'),' ',''))

UPDATE REPORTES.DBO.BASE_PBI
SET CAPACIDAD='NO ESTANDAR'
WHERE CAPACIDAD IS NULL AND TIPO='POL'

DELETE FROM  BASE_PBI WHERE PERIODO_FECHA IN (SELECT * FROM #ULTIMOS_PERIODOS)	
INSERT INTO BASE_PBI
SELECT  *,'' AS CANAL_PYG FROM REPORTES.DBO.BASE_PBI



---------CANTIDAD_POLIZAS
UPDATE BASE_PBI
SET CANTIDAD_POLIZAS=0
WHERE PERIODO_FECHA IN (SELECT * FROM #ULTIMOS_PERIODOS)


SELECT LLAVE_POLIZA,FILTRO_RIESGO,RAMO_KEIRA,(PRIMA_ORIGINAL_CLF)PRIMA_ORIGINAL_CLF INTO #CANTIDAD_POLIZA FROM BASE_PBI WHERE TIPO IN ('POL','CER')
AND PERIODO_FECHA IN (SELECT * FROM #ULTIMOS_PERIODOS)
GROUP BY LLAVE_POLIZA,FILTRO_RIESGO,RAMO_KEIRA,PRIMA_ORIGINAL_CLF
ORDER BY LLAVE_POLIZA

SELECT LLAVE_POLIZA,MAX(PRIMA_ORIGINAL_CLF) PRIMA_MAYOR INTO #CANTIDAD_POLIZA_2 FROM #CANTIDAD_POLIZA
GROUP BY LLAVE_POLIZA
ORDER BY LLAVE_POLIZA


SELECT A.* INTO #CANTIDAD_POLIZA_3 FROM #CANTIDAD_POLIZA A, #CANTIDAD_POLIZA_2 B
WHERE A.LLAVE_POLIZA=B.LLAVE_POLIZA AND A.PRIMA_ORIGINAL_CLF=B.PRIMA_MAYOR

SELECT LLAVE_POLIZA,MIN(RAMO_KEIRA)RAMO_KEIRA INTO #SACA_RAMO_MENOR FROM #CANTIDAD_POLIZA_3 WHERE LLAVE_POLIZA IN (
SELECT LLAVE_POLIZA FROM #CANTIDAD_POLIZA_3
GROUP BY LLAVE_POLIZA
HAVING COUNT(*) >1)
GROUP BY LLAVE_POLIZA

UPDATE #CANTIDAD_POLIZA_3
SET PRIMA_ORIGINAL_CLF=11223344
FROM #CANTIDAD_POLIZA_3 A,#SACA_RAMO_MENOR B
WHERE A.LLAVE_POLIZA=B.LLAVE_POLIZA AND A.RAMO_KEIRA=B.RAMO_KEIRA

DELETE FROM #CANTIDAD_POLIZA_3 WHERE PRIMA_ORIGINAL_CLF=11223344

UPDATE BASE_PBI
SET CANTIDAD_POLIZAS=1
FROM BASE_PBI A,#CANTIDAD_POLIZA_3 B
WHERE 
PERIODO_FECHA IN (SELECT * FROM #ULTIMOS_PERIODOS)
AND RIGHT (A.LLAVE_POLIZA,2)='.1' 
AND A.TIPO IN ('POL','CER') 
AND A.LLAVE_POLIZA=B.LLAVE_POLIZA 
AND A.FILTRO_RIESGO=B.FILTRO_RIESGO 
AND A.RAMO_KEIRA=B.RAMO_KEIRA 
AND A.PRIMA_ORIGINAL_CLF=B.PRIMA_ORIGINAL_CLF

--------------

--- DIFERENCIAR PRODUCTO RMX, ES DESDE EL 01-08-2021 PARA NO MODIFICAR LA HISTORIA 
UPDATE BASE_PBI
SET FILTRO_SOLUCION='RMX',ORDEN_SOLUCION=161
WHERE CODIGO_PLAN_TECNICO IN (7076,7077)
AND PERIODO_FECHA>='2021-08-01'

UPDATE  BASE_PBI
SET CANAL_PYG=B.CANAL
FROM BASE_PBI A, CDG_CANAL_PYG_ENDOSO B
WHERE A.POLIZA=B.NNUMDOCU  AND A.TIPO IN ('POL','END','CER')
AND CANAL_PYG=''



--TRUNCATE TABLE TABLAS_COMPARTIDAS.DBO.BASE_PBI
--INSERT INTO TABLAS_COMPARTIDAS.DBO.BASE_PBI
--SELECT * FROM BASE_PBI




DELETE FROM MESES_CERRADOS WHERE CIERRE_MES IN (SELECT MAX (YEAR(PERIODO_CONTABLE)*100+MONTH(PERIODO_CONTABLE)) FROM FactWrittenPremium_Mensual)
--SELECT * FROM MESES_CERRADOS
INSERT INTO MESES_CERRADOS
SELECT MAX (YEAR(PERIODO_CONTABLE)*100+MONTH(PERIODO_CONTABLE)) CIERRE_MES, GETDATE() TIMESTAMP FROM FactWrittenPremium_Mensual


--select * from BASE_CONTROL_DE_CARGA


TRUNCATE TABLE BASE_CONTROL_DE_CARGA
INSERT INTO BASE_CONTROL_DE_CARGA
SELECT CONVERT(DATE,MAX(NFECFIRM)),'CARGA DIARIA SEGUROS GENERALES' FROM FactWrittenPremium_DiarioMI WHERE CCODRAMO<>'W'
UNION
SELECT CONVERT(DATE,MAX(PERIODO_CONTABLE)),'ULTIMO CIERRE CARGADO SEGUROS GENERALES' FROM FactWrittenPremium_Mensual
UNION
SELECT CONVERT(DATE,MAX(FECHA_GENERACION_POLIZA)),'CARGA DIARIA SEGUROS DE VIDA' FROM AXIS_PRO_INVENTARIO_POLIZAS
UNION
SELECT MAX(TIMESTAMP),'ULTIMA EJECUCION DE EXTRACCION'  FROM MOVILIDAD_CONTROL_DE_EJECUCION WHERE PROCESO='SP_BASE_PBI' AND PASO='FIN'


---MARCA DE EMPRESA_SURA


TRUNCATE TABLE BASE_PBI_EMPRESA_SURA
INSERT INTO BASE_PBI_EMPRESA_SURA
SELECT *  FROM BASE_PBI 


SELECT MIN(FECHA)FECHA,
RUT,ACTIVIDAD,PUBLICO
INTO  #produccion_base_sura_2
FROM ALMACEN_DE_DATOS.DBO.SURA_EMPRESA_SURA
WHERE RUT<>0
GROUP BY RUT,ACTIVIDAD,PUBLICO

UPDATE BASE_PBI_EMPRESA_SURA
SET EMPRESA_SURA='PRODUCCION DE ASEGURADO'
FROM BASE_PBI_EMPRESA_SURA A, #produccion_base_sura_2 B
WHERE  A.RUT_ASEGURADO=B.RUT AND YEAR(A.PERIODO_FECHA)>=2022 

UPDATE BASE_PBI_EMPRESA_SURA
SET EMPRESA_SURA='PRODUCCION DE INTERMEDIARIO'
FROM BASE_PBI_EMPRESA_SURA A, #produccion_base_sura_2 B
WHERE  A.RUT_INTERMEDIARIO=B.RUT AND YEAR(A.PERIODO_FECHA)>=2022 


--UPDATE BASE_PBI_EMPRESA_SURA
--SET EMPRESA_SURA='PRODUCCION DE PROPONENTE'
--FROM BASE_PBI_EMPRESA_SURA A, #produccion_base_sura_2 B
--WHERE  A.P=B.RUT AND YEAR(A.PERIODO_FECHA)>=2022 



TRUNCATE TABLE TABLAS_COMPARTIDAS.DBO.PLAN_TECNICO
INSERT INTO TABLAS_COMPARTIDAS.DBO.PLAN_TECNICO
SELECT * FROM PLAN_TECNICO 

SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SP_BASE_PBI','FIN',@TERMINO,DATEDIFF(MINUTE,@INICIO,@TERMINO)/60,DATEDIFF(MINUTE,@INICIO,@TERMINO)%60)

--UPDATE BASE_PBI
--SET FILTRO_TIPO_RIESGO='',TIPO_CARTERA=''
--WHERE TIPO='CER'

DECLARE @PRIMER_DIA_MES DATE
SET @PRIMER_DIA_MES=CAST(DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE())-0, 0) AS DATE)


EXEC [SP_SEGUIMIENTO]

EXEC TRANSACCIONAL.DBO.SP_TELEMATICA_GESTION

EXEC TRANSACCIONAL.DBO.SP_SINIESTRO_SIN_INSPECCION

EXEC ALMACEN_DE_DATOS.DBO.SP_SURA_ASISTENCIA @PRIMER_DIA_MES

EXEC ALMACEN_DE_DATOS.DBO.SP_SURA_COBERTURAS

EXEC ALMACEN_DE_DATOS.DBO.[01_SP_SURA_CIERRE_MES]

EXEC ALMACEN_DE_DATOS.DBO.[02_SP_SURA_TRANSACCIONAL]

EXEC ALMACEN_DE_DATOS.DBO.[03_SP_SURA_MOVILIDAD_INFO_ADICIONAL]

EXEC ALMACEN_DE_DATOS.DBO.[04_SP_SURA_MOVILIDAD_TRANSACCIONAL]

EXEC ALMACEN_DE_DATOS.DBO.COTIZACIONES_CANALES


EXEC ALMACEN_DE_DATOS.DBO.ALTAS_Y_BAJAS

EXEC ALMACEN_DE_DATOS.DBO.SP_CONTROL_RENOVACIONES
--EXEC ALMACEN_DE_DATOS.DBO.SP_CONTROL_RENOVACIONES_MANUAL_2
EXEC ALMACEN_DE_DATOS.DBO.SP_CONTROL_RENOVACIONES_MANUAL_3

EXEC ALMACEN_DE_DATOS.DBO.RENOVACION_POLIZAS_MENSUALES

--EXEC ALMACEN_DE_DATOS.DBO.MIGRACION_JOOYCAR

END TRY
BEGIN CATCH
INSERT INTO MOVILIDAD_CONTROL_ERROR
  SELECT 
    ERROR_NUMBER()		AS NUMERO_ERROR,
    ERROR_STATE()		AS ESTADO_ERROR,
    ERROR_SEVERITY()	AS SEVERIDAD_ERROR,
    ERROR_PROCEDURE()	AS NOMBRE_PROCEDIMIENTO,
    ERROR_LINE()		AS LINEA_ERROR,
    ERROR_MESSAGE()		AS MENBSAGE_ERROR,
	GETDATE()			AS TIMESTAMP,
	CURRENT_USER		AS USUARIO_EJECUTA
	;
END CATCH;

--EXEC ALMACEN_DE_DATOS.DBO.PYG '202211'

WAITFOR DELAY '00:00:02'
SET @TERMINO= GETDATE()
INSERT INTO MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('CONJUNTO EJECUCION SP','FIN',@TERMINO,DATEDIFF(MINUTE,@INICIO,@TERMINO)/60,DATEDIFF(MINUTE,@INICIO,@TERMINO)%60)