USE [Transaccional]
GO
/****** Object:  StoredProcedure [dbo].[SP_MI_TRANSACCIONAL_MOTOR_00]    Script Date: 14-10-2025 10:22:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- RECORDAR EJECUTAR ANTES [Transaccional].[dbo].[SP_MI_PRE_PROCESO] !!!!!

-- PD: En caso que algun proceso tarde mas de lo normal, puede ser por alguna tabla antigua que este muy fragmentada (Pasa con el tiempo al hacer tantos Truncate e Insert). En ese caso hay 2 opciones:
-- 1. Desfragmentar los indices fragmentados (Se necesitan permisos especificos)
-- 2. Borrar la tabla y volver a crearla (Verificar que se mantengan las mismas columnas con sus nombres y tipo de dato para que no genere algun error)

ALTER  PROCEDURE [dbo].[SP_MI_TRANSACCIONAL_MOTOR_00](
@NANOPROC AS INT,
@NMESPROC AS INT
)
as
DECLARE @CONSULTA_PERSONAL AS NVARCHAR(4000)	
DECLARE @CONSULTA_COMERCIAL	AS NVARCHAR(4000)	
DECLARE @CONSULTA	AS NVARCHAR(4000)		
DECLARE @RAMO AS NVARCHAR(800)				


begin

-- EDITAR Y PONER EL AÑO MES DEL CIERRE!!! EJEMPLO: cuando corro los primeros dias de Agosto 2025 pongo 202507 (Cierre a Julio)
-- exec [SP_MI_TRANSACCIONAL_MOTOR_00] @NANOPROC, @NMESPROC
-- EJEMPLO: exec [SP_MI_TRANSACCIONAL_MOTOR_00] 2025,06

delete from MI_BASE_EMISION WHERE NPECOSUS= (@NANOPROC*100)+@NMESPROC 

TRUNCATE TABLE MI_PERS_MOTOR 
TRUNCATE TABLE MI_COMM_MOTOR 


----------------------------------------------------PERSONAL			
		
-- TABLA PARA MONITOREAR EL AVANCE DEL PROCESO (ABARCA PROCESOS 00, 01, 02 y 04)
TRUNCATE TABLE AUX_MOTOR_00_CHECKPOINTS
-- SELECT * FROM AUX_MOTOR_00_CHECKPOINTS

/****** Checkpoint Inicio ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('PROCESO INICIADO', SYSDATETIME())
/*********************************************************************************/


SET @RAMO = '(''''8102'''',''''8121'''')'	
SET @CONSULTA_PERSONAL = 		
		
'SELECT * FROM OPENQUERY(SOL,''
		SELECT  
		x.LN13,		x.NANOPROC, x.NMESPROC, x.CCODLNRO, x.NNUMDOCU, x.NNUMENDO, x.NNUMITEM, x.NNUMCERT,	x.CCODRAMO, x.CCOMOORI, x.CCUECONT, x.NFEINVIG,	x.NFETEVIG, x.NFECEMIS,	
		x.NNURUASE,	x.NNURUPRO, x.NNURUINT, x.NNURUEJC, x.NNUDOANT, x.CNOMPROP, x.CNOMINT,	x.CNOMEJC,	x.CCODSUCU,	x.SUCURS, x.NPLAN,	x.NPLANTEC,	x.PLAN_TECNICO,	x.CTIPNEGO, 
		x.MONTOUF, 	x.MONTOCLP,	x.DPRINETA,	R.DMOCOINT,	x.NFECNACI,	X.DVALCICO,X.NCODDIRE
		

		FROM (
		SELECT  EMPPER.LN13, PCAPSUVT.NANOPROC, PCAPSUVT.NMESPROC, PCAPSUVT.CCODLNRO, PCAPSUVT.NNUMDOCU, PCAPSUVT.NNUMENDO, PCAPSUVT.NNUMITEM, PCAPSUVT.NNUMCERT,		
		PCAPSUVT.CCODRAMO, PCAPSUVT.CCOMOORI, PCAPSUVT.CCUECONT, SUACSITE.NFEINVIG, SUACSITE.NFETEVIG, SUACSPOL.NFECEMIS,(CASE WHEN SUACSITE.NNURUASE IS NULL THEN 0 ELSE SUACSITE.NNURUASE END) NNURUASE,		
		SUACSPOL.NNURUPRO, SUACSPOL.NNURUINT, SUACSPOL.NNURUEJC, SUACSPOL.NNUDOANT, MAE_1.CNOCOPER AS CNOMPROP, MAE_2.CNOCOPER AS CNOMINT,	MAE_3.CNOCOPER AS CNOMEJC, SUACSPOL.CCODSUCU,		
		TGE_1.CSIGELEM AS SUCURS, SUACSPOL.NPLAN, SUACSITE.NPLANTEC, PDACSPPT.DESCRIP AS PLAN_TECNICO, SUACSPOL.CTIPNEGO, SUM (PCAPSUVT.DVALHABE-PCAPSUVT.DVALDEBE) as MONTOUF, 		 
		SUM ((PCAPSUVT.DVALHABE-PCAPSUVT.DVALDEBE)*VCA.DVALCICO) as MONTOCLP,
		SUACSITE.DPRINETA,SUACSPOL.NPECOSUS,MAE_1.NFECNACI ,VCA.DVALCICO,SUACSPOL.NCODDIRE

		FROM 	
			
		RSASOLDB2.EMPPER EMPPER, RSASOLDB2.PCAPSUVT PCAPSUVT, RSASOLDB2.SUACSITE SUACSITE, RSASOLDB2.SUACSPOL SUACSPOL,	RSASOLDB2.PDACSRCC PDACSRCC,	
		RSASOLDB2.TBACSMAE MAE_1,	RSASOLDB2.TBACSMAE MAE_2,	RSASOLDB2.TBACSMAE MAE_3,	RSASOLDB2.TBACSTGE TGE_1,	
		(SELECT NPLANTEC, MAX(CDESCRIP) AS DESCRIP FROM RSASOLDB2.PDACSPPT GROUP BY NPLANTEC) PDACSPPT,	
		RSASOLDB2.TSACSVCA VCA	
		
		WHERE
				
		PCAPSUVT.CCODRAMO = EMPPER.RAMO AND PCAPSUVT.CCODCOBE = EMPPER.COBER 	
		AND PCAPSUVT.NNUMDOCU = SUACSPOL.NNUMDOCU AND PCAPSUVT.NNUMCERT = SUACSPOL.NNUMCERT 	
		AND PCAPSUVT.NNUMENDO = SUACSPOL.NNUMENDO 	
		AND PCAPSUVT.NNUMDOCU = SUACSITE.NNUMDOCU AND PCAPSUVT.NNUMCERT = SUACSITE.NNUMCERT 	
		AND PCAPSUVT.NNUMENDO = SUACSITE.NNUMENDO AND PCAPSUVT.NNUMITEM = SUACSITE.NNUMITEM 	
		AND PCAPSUVT.CCODCOBE= PDACSRCC.CCODCOBE AND PCAPSUVT.CCODRAMO=PDACSRCC.CCODRAMO 	
		AND PCAPSUVT.nvercobe= PDACSRCC.NVERCOBE	
		AND SUACSPOL.NNURUPRO= MAE_1.NNUMRUT	
		AND SUACSPOL.NNURUINT= MAE_2.NNUMRUT	
		AND SUACSPOL.NNURUEJC= MAE_3.NNUMRUT
		AND SUACSPOL.CCODSUCU= TGE_1.CCODUNIC	
		AND PDACSPPT.NPLANTEC= SUACSITE.NPLANTEC 	
		AND (PCAPSUVT.NANOPROC*100 + PCAPSUVT.NMESPROC) = VCA.NMESACON	
		AND PCAPSUVT.CCOMOORI= VCA.CCOMOORI	
		AND PCAPSUVT.NANOPROC = '+CAST (@NANOPROC AS NVARCHAR(10))+'
		AND PCAPSUVT.NMESPROC = '+CAST (@NMESPROC AS NVARCHAR(10))+'
		AND EMPPER.LN13 IN ' + @RAMO +'
		AND PCAPSUVT.CCUECONT >= ''''800000'''' 	
		AND PCAPSUVT.CCODLNRO IN (''''17391    00'''',''''17393    00'''')	
						
		GROUP BY 		
		EMPPER.LN13, 		
		PCAPSUVT.NANOPROC, 		
		PCAPSUVT.NMESPROC, 		
		PCAPSUVT.CCODLNRO, 		
		PCAPSUVT.NNUMDOCU, 		
		PCAPSUVT.NNUMENDO,		
		PCAPSUVT.NNUMITEM, 		
		PCAPSUVT.NNUMCERT,		
		PCAPSUVT.CCODRAMO,		
		PCAPSUVT.CCOMOORI,
		PCAPSUVT.CCUECONT,		
		SUACSITE.NFEINVIG, 		
		SUACSITE.NFETEVIG, 		
		SUACSPOL.NFECEMIS,
		NNURUASE,		
		SUACSPOL.NNURUPRO,		
		SUACSPOL.NNURUINT,		
		SUACSPOL.NNURUEJC,
		SUACSPOL.NNUDOANT,		
		MAE_1.CNOCOPER,
		MAE_2.CNOCOPER,		
		MAE_3.CNOCOPER,
		SUACSPOL.CCODSUCU,		
		TGE_1.CSIGELEM,
		SUACSPOL.NPLAN,		
		SUACSITE.NPLANTEC,		
		PDACSPPT.DESCRIP,
		SUACSPOL.CTIPNEGO,
		SUACSITE.DPRINETA,
		SUACSPOL.NPECOSUS,
		MAE_1.NFECNACI,
		VCA.DVALCICO,
		SUACSPOL.NCODDIRE ) x

		INNER JOIN 
		
		(select B.NNUMDOCU,B.NNUMENDO,B.NNUMITEM,SUM(B.DMOCOINT) AS DMOCOINT from RSASOLDB2.SUACSCOB b where  B.NNUMCERT=0 and 
		B.NNUMDOCU>0
		group by  B.NNUMDOCU,B.NNUMENDO,B.NNUMITEM)R

		ON
		
		X.NNUMDOCU = R.NNUMDOCU AND
		X.NNUMENDO = R.NNUMENDO AND
		X.NNUMITEM = R.NNUMITEM

		 '')'

INSERT INTO  MI_PERS_MOTOR
EXEC SP_EXECUTESQL @CONSULTA_PERSONAL

/****** Checkpoint 1 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 1', SYSDATETIME())
/****************************************************************************/

--Actualizar con años no bisiestos
update MI_PERS_MOTOR
set NFEINVIG=substring(convert(char(8),NFEINVIG),1,4)+0228
where substring(convert(char(8),NFEINVIG),5,2)=02 and 
substring(convert(char(8),NFEINVIG),7,2)>28 and 
substring(convert(char(8),NFEINVIG),1,4) in (2009,2010,2011,2013,2014,2015,2017,2018,2019,2021,2022,2023,2025)

update MI_PERS_MOTOR
set NFETEVIG=substring(convert(char(8),NFETEVIG),1,4)+0228
where substring(convert(char(8),NFETEVIG),5,2)=02 and 
substring(convert(char(8),NFETEVIG),7,2)>28 and 
substring(convert(char(8),NFETEVIG),1,4) in (2009,2010,2011,2013,2014,2015,2017,2018,2019,2021,2022,2023,2025)

update MI_PERS_MOTOR
set NFECEMIS=substring(convert(char(8),NFECEMIS),1,4)+0228
where substring(convert(char(8),NFECEMIS),5,2)=02 and 
substring(convert(char(8),NFECEMIS),7,2)>28 and 
substring(convert(char(8),NFECEMIS),1,4) in (2009,2010,2011,2013,2014,2015,2017,2018,2019,2021,2022,2023,2025)



update MI_PERS_MOTOR
set NFEINVIG=substring(convert(char(8),NFEINVIG),1,4)+0630
where substring(convert(char(8),NFEINVIG),5,2)=06 and 
substring(convert(char(8),NFEINVIG),7,2)>30

update MI_PERS_MOTOR
set NFETEVIG=substring(convert(char(8),NFETEVIG),1,4)+0630
where substring(convert(char(8),NFETEVIG),5,2)=06 and 
substring(convert(char(8),NFETEVIG),7,2)>30

update MI_PERS_MOTOR
set NFECEMIS=substring(convert(char(8),NFECEMIS),1,4)+0630
where substring(convert(char(8),NFECEMIS),5,2)=06 and 
substring(convert(char(8),NFECEMIS),7,2)>30


update MI_PERS_MOTOR
set NFEINVIG=NFECEMIS
where NFEINVIG<20000000

update MI_PERS_MOTOR
set NFETEVIG=NFEINVIG+10000 
where NFETEVIG<20000000

update MI_PERS_MOTOR
set NFECEMIS=NFEINVIG
where NFECEMIS<20000000


update MI_PERS_MOTOR
set NFEINVIG=NFETEVIG-10000 
where substring(convert(char(8),NFEINVIG),5,2)>12 

update MI_PERS_MOTOR
set NFETEVIG=NFEINVIG+10000 
where substring(convert(char(8),NFETEVIG),5,2)>12 

update MI_PERS_MOTOR
set NFECEMIS=NFEINVIG
where substring(convert(char(8),NFECEMIS),5,2)>12 

/****** Checkpoint 2 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 2', SYSDATETIME())
/****************************************************************************/

----------------------------------------------------COMERCIAL


	

SET @RAMO = '(''''8202'''',''''8221'''')'
SET @CONSULTA_COMERCIAL =
'SELECT * FROM OPENQUERY(SOL,''
		SELECT  
		x.LN24,		x.NANOPROC, x.NMESPROC, x.CCODLNRO, x.NNUMDOCU, x.NNUMENDO, x.NNUMITEM, x.NNUMCERT,	x.CCODRAMO, x.CCOMOORI, x.CCUECONT, x.NFEINVIG,	x.NFETEVIG, x.NFECEMIS,		
		x.NNURUASE,	x.NNURUPRO, x.NNURUINT, x.NNURUEJC, x.NNUDOANT, x.CNOMPROP, x.CNOMINT,	x.CNOMEJC,	x.CCODSUCU,	x.SUCURS,	x.NPLAN,	x.NPLANTEC,	x.PLAN_TECNICO, x.CTIPNEGO, 
		x.MONTOUF,	x.MONTOCLP,	x.DPRINETA,	R.DMOCOINT,	x.NFECNACI,	X.DVALCICO,X.NCODDIRE


		FROM (
		SELECT  EMPPER.LN24, PCAPSUVT.NANOPROC, PCAPSUVT.NMESPROC, PCAPSUVT.CCODLNRO, PCAPSUVT.NNUMDOCU, PCAPSUVT.NNUMENDO, PCAPSUVT.NNUMITEM, PCAPSUVT.NNUMCERT,		
		PCAPSUVT.CCODRAMO, PCAPSUVT.CCOMOORI, PCAPSUVT.CCUECONT, SUACSITE.NFEINVIG, SUACSITE.NFETEVIG, SUACSPOL.NFECEMIS,(CASE WHEN SUACSITE.NNURUASE IS NULL THEN 0 ELSE SUACSITE.NNURUASE END) NNURUASE,		
		SUACSPOL.NNURUPRO, SUACSPOL.NNURUINT, SUACSPOL.NNURUEJC, SUACSPOL.NNUDOANT, MAE_1.CNOCOPER AS CNOMPROP, MAE_2.CNOCOPER AS CNOMINT,	MAE_3.CNOCOPER AS CNOMEJC, SUACSPOL.CCODSUCU,		
		TGE_1.CSIGELEM AS SUCURS, SUACSPOL.NPLAN, SUACSITE.NPLANTEC, PDACSPPT.DESCRIP AS PLAN_TECNICO, SUACSPOL.CTIPNEGO, SUM (PCAPSUVT.DVALHABE-PCAPSUVT.DVALDEBE) as MONTOUF, 		 
		SUM ((PCAPSUVT.DVALHABE-PCAPSUVT.DVALDEBE)*VCA.DVALCICO) as MONTOCLP,
		SUACSITE.DPRINETA,SUACSPOL.NPECOSUS,MAE_1.NFECNACI ,VCA.DVALCICO,SUACSPOL.NCODDIRE

		FROM 	
			
		RSASOLDB2.EMPPER EMPPER, RSASOLDB2.PCAPSUVT PCAPSUVT, RSASOLDB2.SUACSITE SUACSITE, RSASOLDB2.SUACSPOL SUACSPOL,	RSASOLDB2.PDACSRCC PDACSRCC,	
		RSASOLDB2.TBACSMAE MAE_1,	RSASOLDB2.TBACSMAE MAE_2,	RSASOLDB2.TBACSMAE MAE_3,	RSASOLDB2.TBACSTGE TGE_1,	
		(SELECT NPLANTEC, MAX(CDESCRIP) AS DESCRIP FROM RSASOLDB2.PDACSPPT GROUP BY NPLANTEC) PDACSPPT,	
		RSASOLDB2.TSACSVCA VCA	
		
		WHERE
				
		PCAPSUVT.CCODRAMO = EMPPER.RAMO 
		AND PCAPSUVT.CCODCOBE = EMPPER.COBER 	
		AND PCAPSUVT.NNUMDOCU = SUACSPOL.NNUMDOCU 
		AND PCAPSUVT.NNUMCERT = SUACSPOL.NNUMCERT 	
		AND PCAPSUVT.NNUMENDO = SUACSPOL.NNUMENDO 	
		AND PCAPSUVT.NNUMDOCU = SUACSITE.NNUMDOCU AND PCAPSUVT.NNUMCERT = SUACSITE.NNUMCERT 	
		AND PCAPSUVT.NNUMENDO = SUACSITE.NNUMENDO AND PCAPSUVT.NNUMITEM = SUACSITE.NNUMITEM 	
		AND PCAPSUVT.CCODCOBE= PDACSRCC.CCODCOBE AND PCAPSUVT.CCODRAMO=PDACSRCC.CCODRAMO 	
		AND PCAPSUVT.nvercobe= PDACSRCC.NVERCOBE	
		AND SUACSPOL.NNURUPRO= MAE_1.NNUMRUT	
		AND SUACSPOL.NNURUINT= MAE_2.NNUMRUT	
		AND SUACSPOL.NNURUEJC= MAE_3.NNUMRUT	
		AND SUACSPOL.CCODSUCU= TGE_1.CCODUNIC	
		AND PDACSPPT.NPLANTEC= SUACSITE.NPLANTEC 	
		AND (PCAPSUVT.NANOPROC*100 + PCAPSUVT.NMESPROC) = VCA.NMESACON	
		AND PCAPSUVT.CCOMOORI= VCA.CCOMOORI	
		AND PCAPSUVT.NANOPROC = '+CAST (@NANOPROC AS NVARCHAR(10))+'
		AND PCAPSUVT.NMESPROC = '+CAST (@NMESPROC AS NVARCHAR(10))+'
		AND EMPPER.LN24 IN ' + @RAMO +'
		AND PCAPSUVT.CCUECONT >= ''''800000'''' 	
		AND PCAPSUVT.CCODLNRO IN (''''17392    00'''',''''17394    00'''')	
						
		GROUP BY 		
		EMPPER.LN24, 		
		PCAPSUVT.NANOPROC, 		
		PCAPSUVT.NMESPROC, 		
		PCAPSUVT.CCODLNRO, 		
		PCAPSUVT.NNUMDOCU, 		
		PCAPSUVT.NNUMENDO,		
		PCAPSUVT.NNUMITEM, 		
		PCAPSUVT.NNUMCERT,		
		PCAPSUVT.CCODRAMO,		
		PCAPSUVT.CCOMOORI,
		PCAPSUVT.CCUECONT,		
		SUACSITE.NFEINVIG, 		
		SUACSITE.NFETEVIG, 		
		SUACSPOL.NFECEMIS,
		NNURUASE,		
		SUACSPOL.NNURUPRO,		
		SUACSPOL.NNURUINT,		
		SUACSPOL.NNURUEJC,
		SUACSPOL.NNUDOANT,		
		MAE_1.CNOCOPER,
		MAE_2.CNOCOPER,		
		MAE_3.CNOCOPER,
		SUACSPOL.CCODSUCU,		
		TGE_1.CSIGELEM,
		SUACSPOL.NPLAN,		
		SUACSITE.NPLANTEC,		
		PDACSPPT.DESCRIP,
		SUACSPOL.CTIPNEGO,
		SUACSITE.DPRINETA,
		SUACSPOL.NPECOSUS,
		MAE_1.NFECNACI,
		VCA.DVALCICO,
		SUACSPOL.NCODDIRE ) x
		
		INNER JOIN 
		
		(select B.NNUMDOCU,B.NNUMENDO,B.NNUMITEM,SUM(B.DMOCOINT) AS DMOCOINT from RSASOLDB2.SUACSCOB b where  B.NNUMCERT=0 and 
		 B.NNUMDOCU>0
		group by  B.NNUMDOCU,B.NNUMENDO,B.NNUMITEM)R

		ON
		
		X.NNUMDOCU = R.NNUMDOCU AND
		X.NNUMENDO = R.NNUMENDO AND
		X.NNUMITEM = R.NNUMITEM


		 '')'

	INSERT INTO MI_COMM_MOTOR
	EXEC SP_EXECUTESQL @CONSULTA_COMERCIAL


update MI_COMM_MOTOR
set NFEINVIG=substring(convert(char(8),NFEINVIG),1,4)+0228
where substring(convert(char(8),NFEINVIG),5,2)=02 and 
substring(convert(char(8),NFEINVIG),7,2)>28 and 
substring(convert(char(8),NFEINVIG),1,4) in (2009,2010,2011,2013,2014,2015,2017,2018,2019,2021,2022,2023,2025)

update MI_COMM_MOTOR
set NFETEVIG=substring(convert(char(8),NFETEVIG),1,4)+0228
where substring(convert(char(8),NFETEVIG),5,2)=02 and 
substring(convert(char(8),NFETEVIG),7,2)>28 and 
substring(convert(char(8),NFETEVIG),1,4) in (2009,2010,2011,2013,2014,2015,2017,2018,2019,2021,2022,2023,2025)

update MI_COMM_MOTOR
set NFECEMIS=substring(convert(char(8),NFECEMIS),1,4)+0228
where substring(convert(char(8),NFECEMIS),5,2)=02 and 
substring(convert(char(8),NFECEMIS),7,2)>28 and 
substring(convert(char(8),NFECEMIS),1,4) in (2009,2010,2011,2013,2014,2015,2017,2018,2019,2021,2022,2023,2025)

update MI_COMM_MOTOR
set NFEINVIG=substring(convert(char(8),NFEINVIG),1,4)+0630
where substring(convert(char(8),NFEINVIG),5,2)=06 and 
substring(convert(char(8),NFEINVIG),7,2)>30

update MI_COMM_MOTOR
set NFETEVIG=substring(convert(char(8),NFETEVIG),1,4)+0630
where substring(convert(char(8),NFETEVIG),5,2)=06 and 
substring(convert(char(8),NFETEVIG),7,2)>30

update MI_COMM_MOTOR
set NFECEMIS=substring(convert(char(8),NFECEMIS),1,4)+0630
where substring(convert(char(8),NFECEMIS),5,2)=06 and 
substring(convert(char(8),NFECEMIS),7,2)>30


update MI_COMM_MOTOR
set NFEINVIG=NFECEMIS
where NFEINVIG<20000000

update MI_COMM_MOTOR
set NFETEVIG=NFEINVIG+10000 
where NFETEVIG<20000000

update MI_COMM_MOTOR
set NFECEMIS=NFEINVIG
where NFECEMIS<20000000


update MI_COMM_MOTOR
set NFEINVIG=NFETEVIG-10000 
where substring(convert(char(8),NFEINVIG),5,2)>12 

update MI_COMM_MOTOR
set NFETEVIG=NFEINVIG+10000 
where substring(convert(char(8),NFETEVIG),5,2)>12 

update MI_COMM_MOTOR
set NFECEMIS=NFEINVIG
where substring(convert(char(8),NFECEMIS),5,2)>12 

/****** Checkpoint 3 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 3', SYSDATETIME())
/****************************************************************************/

--select * from MI_BASE_EMISION

----INSERTAR REGISTROS DE LINEA DE NEGOCIO PERSONAL
INSERT INTO MI_BASE_EMISION
select NPECOSUS,NNUMDOCU,NNUMENDO,NNUMITEM,NFEINVIG,NFETEVIG,NFECEMIS,CCODSUCU,NPLAN,NPLANTEC,PLAN_TECNICO,
NNURUEJC,NNURUINT,NNURUPRO,NNURUASE,CCOMOORI,IND_REN,
CASE WHEN MAX(GWP_UF) =0 THEN MIN(GWP_UF) ELSE MAX(GWP_UF) END as GWP_UF,
CASE WHEN MAX(COM_UF) =0 THEN MIN(COM_UF) ELSE MAX(COM_UF) END as COM_UF,
CASE WHEN MAX(GWP_UF) =0 THEN MIN(GWP_UF) ELSE MAX(GWP_UF) END * MAX(TIPO_CAMBIO) as GWP_CLP,
CASE WHEN MAX(COM_UF) =0 THEN MIN(COM_UF) ELSE MAX(COM_UF) END * MAX(TIPO_CAMBIO) as COM_CLP,
'',
'',
'',
'Personal' as LINEA_NEGOCIO,''
,'',CNOMINT,NULL,NULL,NFECNACI,
'','','','',NCODDIRE,'','',NULL,'',NULL,NULL,'','','','','','','','',NULL,'','','',CCODRAMO,0,NULL
from (
select (NANOPROC*100)+NMESPROC as NPECOSUS,NNUMDOCU,NNUMENDO,NNUMITEM,
substring(convert(char(8),NFEINVIG),1,4)+'-'+substring(convert(char(8),NFEINVIG),5,2)+'-'+substring(convert(char(8),NFEINVIG),7,2) as NFEINVIG,
case 
when NFETEVIG=0 then 
substring(convert(char(8),NFEINVIG),1,4)+'-'+substring(convert(char(8),NFEINVIG),5,2)+'-'+substring(convert(char(8),NFEINVIG),7,2)
else
substring(convert(char(8),NFETEVIG),1,4)+'-'+substring(convert(char(8),NFETEVIG),5,2)+'-'+substring(convert(char(8),NFETEVIG),7,2) end NFETEVIG,
substring(convert(char(8),NFECEMIS),1,4)+'-'+substring(convert(char(8),NFECEMIS),5,2)+'-'+substring(convert(char(8),NFECEMIS),7,2) as NFECEMIS,

CCODSUCU,NPLAN,NPLANTEC,PLAN_TECNICO,NNURUEJC,NNURUINT,NNURUPRO,NNURUASE,CCOMOORI,CNOMINT,
case 
when NNUDOANT= 0 then 0 else 1 end as IND_REN,
case
when CCUECONT in (811011,811012)	then DPRINETA	else 0 end as GWP_UF,
case
when CCUECONT in (916011)			then DMOCOINT	else 0 end as COM_UF,
case
when CCUECONT in (811011,811012)	then DPRINETA	else 0 end as GWP_CLP,
case
when CCUECONT in (916011)			then DMOCOINT	else 0 end as COM_CLP,NFECNACI,TIPO_CAMBIO,CCODRAMO,NCODDIRE

from MI_PERS_MOTOR --where nnumdocu='5181954' 
)X

group by 
NPECOSUS,NNUMDOCU,NNUMENDO,NNUMITEM,NFEINVIG,NFETEVIG,NFECEMIS,CCODSUCU,NPLAN,NPLANTEC,PLAN_TECNICO,
NNURUEJC,NNURUINT,NNURUPRO,NNURUASE,CCOMOORI,IND_REN,NFECNACI,CNOMINT,NCODDIRE,CCODRAMO






----INSERTAR REGISTROS DE LINEA DE NEGOCIO COMERCIAL
INSERT INTO MI_BASE_EMISION
select NPECOSUS,NNUMDOCU,NNUMENDO,NNUMITEM,NFEINVIG,NFETEVIG,NFECEMIS,CCODSUCU,NPLAN,NPLANTEC,PLAN_TECNICO,
NNURUEJC,NNURUINT,NNURUPRO,NNURUASE,CCOMOORI,IND_REN,
CASE WHEN MAX(GWP_UF) =0 THEN MIN(GWP_UF) ELSE MAX(GWP_UF) END as GWP_UF,
CASE WHEN MAX(COM_UF) =0 THEN MIN(COM_UF) ELSE MAX(COM_UF) END as COM_UF,
CASE WHEN MAX(GWP_UF) =0 THEN MIN(GWP_UF) ELSE MAX(GWP_UF) END * MAX(TIPO_CAMBIO) as GWP_CLP,
CASE WHEN MAX(COM_UF) =0 THEN MIN(COM_UF) ELSE MAX(COM_UF) END * MAX(TIPO_CAMBIO) as COM_CLP,
'',
'',
'',
'Commercial' as LINEA_NEGOCIO,''
,'',CNOMINT,NULL,NULL,NFECNACI,
'','','','',NCODDIRE,'','',NULL,'',NULL,NULL,'','','','','','','','',NULL,'','','',CCODRAMO,0,NULL
from (
select (NANOPROC*100)+NMESPROC as NPECOSUS,NNUMDOCU,NNUMENDO,NNUMITEM,
substring(convert(char(8),NFEINVIG),1,4)+'-'+substring(convert(char(8),NFEINVIG),5,2)+'-'+substring(convert(char(8),NFEINVIG),7,2) as NFEINVIG,
case 
when NFETEVIG=0 then 
substring(convert(char(8),NFEINVIG),1,4)+'-'+substring(convert(char(8),NFEINVIG),5,2)+'-'+substring(convert(char(8),NFEINVIG),7,2)
else
substring(convert(char(8),NFETEVIG),1,4)+'-'+substring(convert(char(8),NFETEVIG),5,2)+'-'+substring(convert(char(8),NFETEVIG),7,2) end NFETEVIG,
substring(convert(char(8),NFECEMIS),1,4)+'-'+substring(convert(char(8),NFECEMIS),5,2)+'-'+substring(convert(char(8),NFECEMIS),7,2) as NFECEMIS,

CCODSUCU,NPLAN,NPLANTEC,PLAN_TECNICO,NNURUEJC,NNURUINT,NNURUPRO,NNURUASE,CCOMOORI,CNOMINT,
case 
when NNUDOANT= 0 then 0 else 1 end as IND_REN,
case
when CCUECONT in (811011,811012)	then DPRINETA	else 0 end as GWP_UF,
case
when CCUECONT in (916011)			then DMOCOINT	else 0 end as COM_UF,
case
when CCUECONT in (811011,811012)	then DPRINETA	else 0 end as GWP_CLP,
case
when CCUECONT in (916011)			then DMOCOINT	else 0 end as COM_CLP,NFECNACI,TIPO_CAMBIO,CCODRAMO,NCODDIRE

from MI_COMM_MOTOR --where nnumdocu='5181954' 
)X

group by 
NPECOSUS,NNUMDOCU,NNUMENDO,NNUMITEM,NFEINVIG,NFETEVIG,NFECEMIS,CCODSUCU,NPLAN,NPLANTEC,PLAN_TECNICO,
NNURUEJC,NNURUINT,NNURUPRO,NNURUASE,CCOMOORI,IND_REN,NFECNACI,CNOMINT,NCODDIRE,CCODRAMO

DECLARE @AÑOMESD INT
SET @AÑOMESD=(@NANOPROC*100 + @NMESPROC) *100 

DELETE  FROM  MI_DATOS_MOTOR_PRE WHERE NFECUACT>@AÑOMESD     
							 
DECLARE @CONSULTA_DATOS_MOTOR AS NVARCHAR(4000)	
SET @CONSULTA_DATOS_MOTOR = 'SELECT * FROM OPENQUERY(SOL,'' 
SELECT B.NNUMDOCU,B.NNUMCERT,B.NNUMENDO,B.NNUMITEM,B.CCOMAVEH,B.NCOMOVEH,B.NCOTIVEC,B.CEXTENSI,B.NCILINDR,
B.NANFAVEH,B.CNUMOVEH,B.CNUCHVEH,B.CNUMPATE,B.CCOLOR,B.CDIGPATE,B.CUSOVEHI,B.nfecuact  
FROM  RSASOLDB2.SUACST05 B 
WHERE  B.NFECUACT >' +CAST (@AÑOMESD AS NVARCHAR(10)) +' 
 '')'

INSERT INTO MI_DATOS_MOTOR_PRE
EXEC SP_EXECUTESQL @CONSULTA_DATOS_MOTOR
										

/****** Checkpoint 4 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 4', SYSDATETIME())
/****************************************************************************/


					  
	
						 
						  
						 

--truncate table MI_DATOS_MOTOR
--INSERT INTO MI_DATOS_MOTOR
drop table if exists MI_DATOS_MOTOR
SELECT A.* into MI_DATOS_MOTOR FROM MI_DATOS_MOTOR_PRE A INNER JOIN (SELECT NNUMDOCU,NNUMITEM,MAX(NNUMENDO)NNUMENDO FROM MI_DATOS_MOTOR_PRE GROUP BY NNUMDOCU,NNUMITEM) B ON
A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM AND A.NNUMENDO=B.NNUMENDO



UPDATE MI_BASE_EMISION
SET 
COD_MARCA_VEH = CCOMAVEH,
COD_MODELO_VEH = NCOMOVEH,
EXTENSION_VEH = CEXTENSI,
CILINDRADA_VEH = NCILINDR,
AÑO_FABR_VEH = NANFAVEH,
NUMMOT_VEH = CNUMOVEH,
NUMCHA_VEH = CNUCHVEH,
PATENTE_VEH = CNUMPATE,
COLOR_VEH = CCOLOR,
DIG_PATENTE_VEH = CDIGPATE,
COD_USO_VEH = CUSOVEHI,
COD_TIPO_VEH = NCOTIVEC
FROM MI_BASE_EMISION A, MI_DATOS_MOTOR B
WHERE 
A.NNUMDOCU = B.NNUMDOCU AND									 
A.NNUMITEM = B.NNUMITEM 


UPDATE MI_BASE_EMISION
SET TIPO_VEH=SUBSTRING (B.TIPO_VEH,1,15)
FROM MI_BASE_EMISION A, PROCESOS.DBO.BASE_TIPO_VEH b
WHERE A.COD_TIPO_VEH = B.COD_TIPO_VEH 
	  

DELETE FROM PROCESOS.DBO.BASE_MARCA_MODELO
DECLARE @QUERY AS NVARCHAR(4000)	
SET @QUERY = 'SELECT * FROM OPENQUERY(SOL,'' SELECT ma.ccomaveh,CAST(mo.ncomoveh AS NUMERIC),ma.cdescort DE1,mo.cdescort DE2 FROM RSASOLDB2.SUACSMOV MO, RSASOLDB2.SUACSMVH MA
where ma.ccomaveh=mo.ccomaveh order by 1, 2 desc '')'
INSERT INTO  PROCESOS.DBO.BASE_MARCA_MODELO

EXEC SP_EXECUTESQL @QUERY

UPDATE MI_BASE_EMISION
SET MARCA_VEH=M.MARCA_VEH,MODELO_VEH=M.MODELO_VEH
FROM MI_BASE_EMISION A, PROCESOS.DBO.BASE_MARCA_MODELO M
WHERE 
A.COD_MARCA_VEH = M.COD_MARCA_VEH AND
A.COD_MODELO_VEH = M.COD_MODELO_VEH 
					

DECLARE @AÑOMES AS char(6)
SET @AÑOMES=(@NANOPROC*100)+@NMESPROC

DELETE FROM PROCESOS.DBO.BASE_FECH_NAC WHERE TIMESTAMP = @AÑOMES


SET @QUERY = 'SELECT * FROM OPENQUERY(SOL,'' 
SELECT NNURUTASE,EDAD,AÑO_CONSULTA,(cast(AÑO_CONSULTA as numeric)- cast(edad as numeric)) *10000+601 AS NFENACIM,' + @AÑOMES+' FROM
(
select 
a.nrutcont AS NNURUTASE,
max(c.edad) AS EDAD,
max(substr(cast (a.nfecact as character(8)),1,4)) AS AÑO_CONSULTA
from leempwebdb.cvacsccc a,leempwebdb.cvacscdt c
where nfecha >=' + @AÑOMES+'01 and 
a.nidcotiz =c.nidcot 
group by  a.nrutcont) x
  '')'

INSERT INTO  PROCESOS.DBO.BASE_FECH_NAC
EXEC SP_EXECUTESQL @QUERY


UPDATE MI_BASE_EMISION
SET NFENACIM=B.NFENACIM
FROM MI_BASE_EMISION A, PROCESOS.DBO.BASE_FECH_NAC B
WHERE 
A.NNURUTASE=B.NNURUTASE AND
A.NPECOSUS= (@NANOPROC*100)+@NMESPROC 



INSERT INTO COMUNA_COMPLETA
SELECT B.*  FROM [MI_BASE_EMISION] A LEFT JOIN [SOL].[S1031EBB].RSASOLDB2.TBACSDIR B
ON CONVERT (INT, A.COMUNA_ASEGURADO)=B.NCODDIRE
WHERE DIRECCION_ASEGURADO='' AND B.NCODDIRE NOT IN (SELECT NCODDIRE FROM COMUNA_COMPLETA)



UPDATE [MI_BASE_EMISION]
SET
DIRECCION_ASEGURADO=B.CDIRECCI,
COMUNA_ASEGURADO=B.CCODCOMU
FROM [MI_BASE_EMISION] A, COMUNA_COMPLETA B
WHERE  DIRECCION_ASEGURADO='' AND
CONVERT (INT, A.COMUNA_ASEGURADO)=CONVERT (INT,B.NCODDIRE)

/****** Checkpoint 5 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 5', SYSDATETIME())
/****************************************************************************/

/*
DELETE FROM PROCESOS.DBO.BASE_DIR_ASEG

SET @QUERY = 'SELECT * FROM OPENQUERY(SOL,'' 
select  
A.NNUMRUT,'''' '''','''' '''',B.CDIRECCI,B.CCODCOMU
from (SELECT NNUMRUT,MAX(ncoddire) AS ncoddire FROM RSASOLDB2.TBACSDPE WHERE CCOTIDIR = ''''1038PST  00'''' GROUP BY  NNUMRUT)  A, RSASOLDB2.TBACSDIR B
where NNUMRUT in(
select
SUACSITE.NNURUASE from RSASOLDB2.PCAPSUVT PCAPSUVT,RSASOLDB2.SUACSITE SUACSITE
where
PCAPSUVT.NANOPROC='+ CAST (@NANOPROC AS NVARCHAR(10)) +'
AND PCAPSUVT.NMESPROC=' +CAST (@NMESPROC AS NVARCHAR(10)) +' 
AND PCAPSUVT.CCODRAMO IN (''''EE'''', ''''ET'''', ''''EL'''', ''''AE'''', ''''EP'''',''''AV'''') 
AND PCAPSUVT.CCUECONT >= 800000
AND PCAPSUVT.CCODLNRO IN (''''17392    00'''',''''17394    00'''',''''17391    00'''',''''17393    00'''')		
AND PCAPSUVT.NNUMDOCU = SUACSITE.NNUMDOCU 
AND PCAPSUVT.NNUMCERT = SUACSITE.NNUMCERT 	
AND PCAPSUVT.NNUMENDO = SUACSITE.NNUMENDO group by SUACSITE.NNURUASE)
AND A.ncoddire=B.ncoddire

  '')'

INSERT INTO  PROCESOS.DBO.BASE_DIR_ASEG
--SELECT  @QUERY
EXEC SP_EXECUTESQL @QUERY

UPDATE [MI_BASE_EMISION]
SET
DIRECCION_ASEGURADO=B.DIRECCION,
COMUNA_ASEGURADO=B.COMUNA,
MAIL_ASEGURADO=B.MAIL,
FONO_ASEGURADO=B.FONO
FROM [MI_BASE_EMISION] A, PROCESOS.DBO.BASE_DIR_ASEG B
WHERE 
A.NNURUTASE=B.NNURUTASE
AND A.NPECOSUS= (@NANOPROC*100)+@NMESPROC 
*/

UPDATE MI_BASE_EMISION
SET
COMUNA_ASEGURADO=COMUNA,PROVINCIA_ASEGURADO=PROVINCIA,REGION_ASEGURADO=REGION
FROM MI_BASE_EMISION A,PROCESOS.DBO.BASE_MAESTRO_COMUNAS_REGIONES_ZONAS B
WHERE A.COMUNA_ASEGURADO COLLATE SQL_Latin1_General_CP1_CI_AS = B.CODIGOS
AND A.NPECOSUS= (@NANOPROC*100)+@NMESPROC 

UPDATE MI_BASE_EMISION
SET
COMUNA_ASEGURADO		= 'IGNORADA',
PROVINCIA_ASEGURADO		= 'IGNORADA',
REGION_ASEGURADO		= 'IGNORADA'
FROM MI_BASE_EMISION
WHERE COMUNA_ASEGURADO IS NULL OR COMUNA_ASEGURADO = ''


UPDATE MI_BASE_EMISION
SET
SUCURSAL=SUBSTRING(CDESELEM,1,30)
FROM MI_BASE_EMISION A,PROCESOS.DBO.BASE_COM_CIU_REG B
WHERE A.NOMSUCU=B.CCODUNIC
AND A.NPECOSUS= (@NANOPROC*100)+@NMESPROC 


UPDATE MI_BASE_EMISION
SET
PLAN_COMERCIAL=B.PLAN_COMERCIAL
FROM MI_BASE_EMISION A,PROCESOS.DBO.BASE_PLANES_COMERCIALES B
WHERE A.NPLAN=B.NPLAN
AND A.NPECOSUS= (@NANOPROC*100)+@NMESPROC 


UPDATE MI_BASE_EMISION
SET
BUSINESS_UNIT= "BUSINESS UNIT",
GRUPO= B.GRUPO,
CHANNEL=B.CHANNEL
FROM MI_BASE_EMISION A,PROCESOS.DBO.BASE_PLANES_TECNICOS B
WHERE 
A.NNURUINT = B.NNUMRUT
AND A.NPLANTEC = B.NPLANTEC
AND A.LINEA_NEGOCIO = B.LINEA_NEGOCIO
AND A.NPECOSUS= (@NANOPROC*100)+@NMESPROC 


		 

				

 
TRUNCATE TABLE MI_PERS_MOTOR 
TRUNCATE TABLE MI_COMM_MOTOR 
TRUNCATE TABLE PROCESOS.DBO.BASE_ASEGURADO

/****** Checkpoint 6 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 6', SYSDATETIME())
/****************************************************************************/

EXEC SP_MI_TRANSACCIONAL_MOTOR_01_V2 @NANOPROC,@NMESPROC

EXEC SP_MI_TRANSACCIONAL_MOTOR_02


--SELECT 'Base Emision Personal',@NANOPROC,@NMESPROC, count(*) FROM MI_BASE_EMISION WHERE LINEA_NEGOCIO='Personal' and NPECOSUS= (@NANOPROC*100)+@NMESPROC 
--union
--SELECT 'Base Emision Comercial',@NANOPROC,@NMESPROC, count(*) FROM MI_BASE_EMISION WHERE LINEA_NEGOCIO='Commercial' and NPECOSUS= (@NANOPROC*100)+@NMESPROC 


/****** Checkpoint PROCESO TERMINADO ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('PROCESO TERMINADO', SYSDATETIME())
/****************************************************************************/

end





