USE [Transaccional]
GO
/****** Object:  StoredProcedure [dbo].[SP_MI_TRANSACCIONAL_MOTOR_01_V2]    Script Date: 14-10-2025 10:22:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER  PROCEDURE [dbo].[SP_MI_TRANSACCIONAL_MOTOR_01_V2](
@NANOPROC AS INT,
@NMESPROC AS INT
)
AS
DECLARE @CONSULTA_COMERCIAL	AS NVARCHAR(4000)	
		
BEGIN

-- exec [SP_MI_TRANSACCIONAL_MOTOR_01_V2] @NANOPROC, @NMESPROC
-- EJEMPLO: exec [SP_MI_TRANSACCIONAL_MOTOR_01_V2] 2025,06

-- TABLA PARA MONITOREAR EL AVANCE DEL PROCESO (ABARCA PROCESOS 00, 01, 02 y 04)
-- SELECT * FROM AUX_MOTOR_00_CHECKPOINTS

------------------------------- TERMINO DE VIGENCIA REAL

/****** Checkpoint Inicio ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('PROCESO 01 INICIADO', SYSDATETIME())
/*********************************************************************************/

TRUNCATE TABLE MI_TER_VIG_REAL
DECLARE @CONSULTA	AS NVARCHAR(4000)		
SET @CONSULTA = 		
		
'SELECT * FROM OPENQUERY(SOL,''
SELECT YY.NNUMDOCU, YY.NNUMENDO,YY.NNUMITEM,0,YY.NFEINVIG,
CASE WHEN YY.CESTPOLI IN (''''1106AN   00'''',''''1106CA   00'''') THEN MIN(RR.NFEINVIG) ELSE 0 END AS NFETEVIG_REAL ,
YY.NFETEVIG,
MIN(YY.NFECEMIS)AS NFECEMIS,
CASE WHEN YY.CESTPOLI IN (''''1106CA   00'''') THEN RR.NFECEMIS ELSE 0 END AS FECHA_CANCELACION ,


YY.CCODRAMO,RR.NNURUINT, YY.CESTPOLI
FROM  
RSASOLDB2.SUACSPOL RR
INNER JOIN
(SELECT X.NNUMDOCU,X.NNUMCERT,MAX(X.NNUMENDO) NNUMENDO,MIN(X.NFECEMIS) NFECEMIS,MIN(Y.NFEINVIG) NFEINVIG,MAX(Y.NFETEVIG)NFETEVIG, X.CCODRAMO,Y.NNUMITEM 
, X.CESTPOLI
		 FROM RSASOLDB2.SUACSPOL X INNER JOIN RSASOLDB2.SUACSITE Y 
			ON 
			X.NNUMDOCU = Y.NNUMDOCU
			AND X.NNUMCERT = Y.NNUMCERT 
			AND X.NNUMENDO = Y.NNUMENDO 
			WHERE 
			CCODESDO =  ''''0240F    00'''' 
			AND X.CCODTNRO <> ''''17374    00'''' 
			AND X.CCODRAMO IN (''''EE'''', ''''ET'''', ''''EL'''', ''''AE'''', ''''EP'''', ''''AV'''', ''''EA'''', ''''EC'''') 
			AND SUBSTR(CHAR(NFECEMIS),1,4)>2015 
			AND X.CESTPOLI IN (''''1106CT   00'''',''''1106VI   00'''',''''1106AN   00'''',''''1106CA   00'''')
			AND X.NNUMCERT =  0
			AND X.NNUMENDO>= 0
			GROUP BY X.NNUMDOCU,X.NNUMCERT,X.CCODRAMO,Y.NNUMITEM,X.CESTPOLI ORDER BY 1 DESC)YY
ON
RR.NNUMDOCU=YY.NNUMDOCU
AND RR.NNUMENDO=YY.NNUMENDO
WHERE 
RR.NNUMENDO>=0
AND RR.NNUMCERT =  0
GROUP BY 
YY.NNUMDOCU, YY.NNUMENDO,YY.NNUMITEM,YY.NFEINVIG,RR.NFECEMIS,YY.NFETEVIG,YY.NFECEMIS,YY.CCODRAMO,RR.NNURUINT,YY.CESTPOLI '')'

INSERT INTO  MI_TER_VIG_REAL
EXEC SP_EXECUTESQL @CONSULTA


/****** Checkpoint 1 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 01-1', SYSDATETIME())
/****************************************************************************/

--------------------------------POLIZAS CON PRORROGA

--ESTA ES LA PARTE MAS PESADA YA QUE TRAE MUCHA INFORMACION DESDE SOL

--30 mins
DECLARE @QUERY_PRO AS NVARCHAR(4000)
DROP TABLE IF EXISTS SUACSPOL_TEMP3
SET @QUERY_PRO = 'SELECT * INTO SUACSPOL_TEMP3 FROM OPENQUERY(SOL,''SELECT NNUMDOCU,NNUMENDO,CCODRAMO,CESTPOLI,CCODMOEN,NPECOSUS,CCODESDO,CCODTNRO,NNUMCERT FROM RSASOLDB2.SUACSPOL WHERE NFECUACT >= 20150101 '')'
EXEC SP_EXECUTESQL @QUERY_PRO

--1h 05 min
--DECLARE @QUERY_PRO AS NVARCHAR(4000)	
DROP TABLE IF EXISTS SUACSITE_TEMP3
SET @QUERY_PRO = 'SELECT * INTO SUACSITE_TEMP3 FROM OPENQUERY(SOL,''SELECT NNUMDOCU,NNUMENDO,NFECUACT,NFEINVIG,NFETEVIG,NNUMITEM FROM RSASOLDB2.SUACSITE WHERE NFECUACT >= 20160101 '')'
EXEC SP_EXECUTESQL @QUERY_PRO


--SELECT * FROM SUACSPOL_TEMP
--SELECT * FROM SUACSITE_TEMP


DROP TABLE IF EXISTS #TEMP
SELECT Y.NNUMDOCU,Y.NNUMENDO,Y.NFECUACT,Y.NFEINVIG,Y.NFETEVIG,Y.NNUMITEM 
INTO #TEMP
FROM (
	SELECT P.NNUMDOCU,P.NNUMITEM 
	FROM SUACSITE_TEMP3 P 
	INNER JOIN (
		SELECT NNUMDOCU,NNUMENDO
		FROM SUACSPOL_TEMP3
		WHERE 
			NPECOSUS>=201501 AND CCODMOEN ='0036I32  00' AND 
			CCODESDO =  '0240F    00' AND 
			CCODTNRO <> '17374    00' AND 
			CCODRAMO IN ('EE', 'ET', 'EL', 'AE', 'EP', 'AV', 'EA', 'EC') AND 
			NNUMCERT =  0 AND NNUMENDO >= 0 AND NNUMDOCU > 0 
		GROUP BY NNUMDOCU,NNUMENDO 
	) R ON
		P.NNUMDOCU=R.NNUMDOCU AND P.NNUMENDO=R.NNUMENDO
	GROUP BY P.NNUMDOCU,P.NNUMITEM
) X 
INNER JOIN SUACSITE_TEMP3 Y ON 
	X.NNUMDOCU = Y.NNUMDOCU
	AND X.NNUMITEM = Y.NNUMITEM 
GROUP BY  Y.NNUMDOCU,Y.NNUMENDO,Y.NFECUACT, Y.NFEINVIG,Y.NFETEVIG,Y.NNUMITEM

--select * from MI_POLIZAS_PRORROGADAS_2
DROP TABLE IF EXISTS MI_POLIZAS_PRORROGADAS_2
SELECT 
	H.NNUMDOCU POLIZA,H.NNUMENDO ENDOSO,H.NFECUACT NFECUACT, H.NFEINVIG NFEINVIG,H.NFETEVIG NFETEVIG,H.NNUMITEM ITEM,
	L.CCODRAMO RAMO,L.CESTPOLI CESTPOLI,L.CCODMOEN CCODMOEN,
	0 PRORROGA
INTO MI_POLIZAS_PRORROGADAS_2
FROM #TEMP H
INNER JOIN SUACSPOL_TEMP3 L ON
	H.NNUMDOCU=L.NNUMDOCU AND 
	H.NNUMENDO=L.NNUMENDO
GROUP BY 
	H.NNUMDOCU,H.NNUMENDO,H.NFECUACT, H.NFEINVIG,H.NFETEVIG,H.NNUMITEM,L.CCODRAMO,L.CESTPOLI,L.CCODMOEN



/****** Checkpoint 2 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 01-2', SYSDATETIME())
/****************************************************************************/

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=0

UPDATE MI_POLIZAS_PRORROGADAS_2
SET NFETEVIG=20141203
WHERE NFETEVIG=20141303

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=1
FROM (SELECT POLIZA, MIN(ENDOSO)AS ENDOSO , ITEM FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN IN ('0036I32  00','0036D62  00')AND CESTPOLI IS NOT NULL AND PRORROGA=0 GROUP BY POLIZA,ITEM ) A, MI_POLIZAS_PRORROGADAS_2 B
WHERE A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM AND A.ENDOSO=B.ENDOSO AND B.PRORROGA=0 AND CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=2
FROM (SELECT POLIZA, MIN(ENDOSO)AS ENDOSO , ITEM FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND PRORROGA=0 GROUP BY POLIZA,ITEM ) A, MI_POLIZAS_PRORROGADAS_2 B
WHERE A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM AND A.ENDOSO=B.ENDOSO AND B.PRORROGA=0 AND CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=3
FROM (SELECT POLIZA, MIN(ENDOSO)AS ENDOSO , ITEM FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND PRORROGA=0 GROUP BY POLIZA,ITEM ) A, MI_POLIZAS_PRORROGADAS_2 B
WHERE A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM AND A.ENDOSO=B.ENDOSO AND B.PRORROGA=0 AND CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=4
FROM (SELECT POLIZA, MIN(ENDOSO)AS ENDOSO , ITEM FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND PRORROGA=0 GROUP BY POLIZA,ITEM ) A, MI_POLIZAS_PRORROGADAS_2 B
WHERE A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM AND A.ENDOSO=B.ENDOSO AND B.PRORROGA=0 AND CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=5
FROM (SELECT POLIZA, MIN(ENDOSO)AS ENDOSO , ITEM FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND PRORROGA=0 GROUP BY POLIZA,ITEM ) A, MI_POLIZAS_PRORROGADAS_2 B
WHERE A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM AND A.ENDOSO=B.ENDOSO AND B.PRORROGA=0 AND CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=6
FROM (SELECT POLIZA, MIN(ENDOSO)AS ENDOSO , ITEM FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND PRORROGA=0 GROUP BY POLIZA,ITEM ) A, MI_POLIZAS_PRORROGADAS_2 B
WHERE A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM AND A.ENDOSO=B.ENDOSO AND B.PRORROGA=0 AND CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=7
FROM (SELECT POLIZA, MIN(ENDOSO)AS ENDOSO , ITEM FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND PRORROGA=0 GROUP BY POLIZA,ITEM ) A, MI_POLIZAS_PRORROGADAS_2 B
WHERE A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM AND A.ENDOSO=B.ENDOSO AND B.PRORROGA=0 AND CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=8
FROM (SELECT POLIZA, MIN(ENDOSO)AS ENDOSO , ITEM FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND PRORROGA=0 GROUP BY POLIZA,ITEM ) A, MI_POLIZAS_PRORROGADAS_2 B
WHERE A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM AND A.ENDOSO=B.ENDOSO AND B.PRORROGA=0 AND CCODMOEN IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL

/****** Checkpoint 3 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 01-3', SYSDATETIME())
/****************************************************************************/

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=1
FROM MI_POLIZAS_PRORROGADAS_2 X,
(SELECT B.* FROM MI_POLIZAS_PRORROGADAS_2  A, (SELECT * FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN NOT IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND CCODMOEN IS NOT NULL)B
WHERE A.PRORROGA=1 AND A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM  AND B.NFECUACT>A.NFECUACT )Z 
WHERE 
X.POLIZA=Z.POLIZA AND X.ENDOSO=Z.ENDOSO

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=2
FROM MI_POLIZAS_PRORROGADAS_2 X,
(SELECT B.* FROM MI_POLIZAS_PRORROGADAS_2  A, (SELECT * FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN NOT IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND CCODMOEN IS NOT NULL)B
WHERE A.PRORROGA=2 AND A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM  AND B.NFECUACT>A.NFECUACT )Z 
WHERE 
X.POLIZA=Z.POLIZA AND X.ENDOSO=Z.ENDOSO

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=3
FROM MI_POLIZAS_PRORROGADAS_2 X,
(SELECT B.* FROM MI_POLIZAS_PRORROGADAS_2  A, (SELECT * FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN NOT IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND CCODMOEN IS NOT NULL)B
WHERE A.PRORROGA=3 AND A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM  AND B.NFECUACT>A.NFECUACT )Z 
WHERE 
X.POLIZA=Z.POLIZA AND X.ENDOSO=Z.ENDOSO

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=4
FROM MI_POLIZAS_PRORROGADAS_2 X,
(SELECT B.* FROM MI_POLIZAS_PRORROGADAS_2  A, (SELECT * FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN NOT IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND CCODMOEN IS NOT NULL)B
WHERE A.PRORROGA=4 AND A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM  AND B.NFECUACT>A.NFECUACT )Z 
WHERE 
X.POLIZA=Z.POLIZA AND X.ENDOSO=Z.ENDOSO

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=5
FROM MI_POLIZAS_PRORROGADAS_2 X,
(SELECT B.* FROM MI_POLIZAS_PRORROGADAS_2  A, (SELECT * FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN NOT IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND CCODMOEN IS NOT NULL)B
WHERE A.PRORROGA=5 AND A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM  AND B.NFECUACT>A.NFECUACT )Z 
WHERE 
X.POLIZA=Z.POLIZA AND X.ENDOSO=Z.ENDOSO

UPDATE MI_POLIZAS_PRORROGADAS_2
SET PRORROGA=6
FROM MI_POLIZAS_PRORROGADAS_2 X,
(SELECT B.* FROM MI_POLIZAS_PRORROGADAS_2  A, (SELECT * FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN NOT IN ('0036I32  00','0036D62  00') AND CESTPOLI IS NOT NULL AND CCODMOEN IS NOT NULL)B
WHERE A.PRORROGA=6 AND A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM  AND B.NFECUACT>A.NFECUACT )Z 
WHERE 
X.POLIZA=Z.POLIZA AND X.ENDOSO=Z.ENDOSO

/****** Checkpoint 4 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 01-4', SYSDATETIME())
/****************************************************************************/

UPDATE MI_POLIZAS_PRORROGADAS_2
SET NFEINVIG=B.NFEINVIG
FROM MI_POLIZAS_PRORROGADAS_2 A,
(SELECT * FROM MI_POLIZAS_PRORROGADAS_2 WHERE CCODMOEN NOT IN
('0036D01  00','0036D02  00','0036D10  00','0036I03  00','0036I35  00','0036D61  00'))B
WHERE A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM AND A.PRORROGA=B.PRORROGA AND A.CCODMOEN  IN
('0036D01  00','0036D02  00','0036D10  00','0036I03  00','0036I35  00','0036D61  00')


UPDATE MI_BASE_EMISION
SET PRORROGA=0

UPDATE MI_BASE_EMISION
SET  
NFECEMIS=SUBSTRING(CONVERT(CHAR(8),B.NFECUACT),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFECUACT),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFECUACT),7,2),
NFEINVIG=SUBSTRING(CONVERT(CHAR(8),B.NFEINVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFEINVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFEINVIG),7,2),
NFETEVIG=SUBSTRING(CONVERT(CHAR(8),B.NFETEVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFETEVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFETEVIG),7,2),
PRORROGA=B.PRORROGA
FROM MI_BASE_EMISION A, (SELECT * FROM MI_POLIZAS_PRORROGADAS_2 WHERE PRORROGA>0)B
WHERE A.NNUMDOCU=B.POLIZA AND A.NNUMENDO=B.ENDOSO AND A.NNUMITEM=B.ITEM


UPDATE MI_BASE_EMISION
SET  
NFECEMIS=SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),7,2),
NFEINVIG=SUBSTRING(CONVERT(CHAR(8),Z.NFEINVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFEINVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFEINVIG),7,2),
NFETEVIG=SUBSTRING(CONVERT(CHAR(8),Z.NFETEVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFETEVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFETEVIG),7,2),
FECTEVIG_REAL=SUBSTRING(CONVERT(CHAR(8),Z.NFEINVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFEINVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFEINVIG),7,2),
FECHA_CANCELACION=SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),7,2)
FROM MI_BASE_EMISION X, (SELECT A.* FROM MI_POLIZAS_PRORROGADAS_2 A,
(SELECT POLIZA, MAX(ENDOSO) ENDOSO,ITEM FROM MI_POLIZAS_PRORROGADAS_2 WHERE PRORROGA>0 GROUP BY POLIZA,ITEM)B
WHERE A.POLIZA =B.POLIZA AND A.ENDOSO=B.ENDOSO AND  A.ITEM=B.ITEM
AND CCODMOEN IN ('0036D01  00','0036D02  00','0036D10  00','0036I03  00','0036I35  00','0036D61  00'))Z
WHERE X.NNUMDOCU=Z.POLIZA  AND X.NNUMITEM=Z.ITEM AND X.PRORROGA=Z.PRORROGA


UPDATE MI_BASE_EMISION
SET  
NFECEMIS=SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),7,2),
NFEINVIG=SUBSTRING(CONVERT(CHAR(8),Z.NFEINVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFEINVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFEINVIG),7,2),
NFETEVIG=SUBSTRING(CONVERT(CHAR(8),Z.NFETEVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFETEVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFETEVIG),7,2),
FECTEVIG_REAL=SUBSTRING(CONVERT(CHAR(8),Z.NFETEVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFETEVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFETEVIG),7,2),
FECHA_CANCELACION=SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),Z.NFECUACT),7,2)
FROM MI_BASE_EMISION X, (SELECT A.* FROM MI_POLIZAS_PRORROGADAS_2 A,
(SELECT POLIZA, MAX(ENDOSO) ENDOSO,ITEM FROM MI_POLIZAS_PRORROGADAS_2 WHERE PRORROGA>0 GROUP BY POLIZA,ITEM)B
WHERE A.POLIZA =B.POLIZA AND A.ENDOSO=B.ENDOSO AND  A.ITEM=B.ITEM
AND CCODMOEN NOT IN ('0036D01  00','0036D02  00','0036D10  00','0036I03  00','0036I35  00','0036D61  00'))Z
WHERE X.NNUMDOCU=Z.POLIZA  AND X.NNUMITEM=Z.ITEM AND X.PRORROGA=Z.PRORROGA



UPDATE MI_TER_VIG_REAL
SET FECINVIG=SUBSTRING(CONVERT(CHAR(8),FECINVIG),1,4)+0228
WHERE SUBSTRING(CONVERT(CHAR(8),FECINVIG),5,2)=02 AND 
SUBSTRING(CONVERT(CHAR(8),FECINVIG),7,2)>28 AND 
SUBSTRING(CONVERT(CHAR(8),FECINVIG),1,4) IN (2009,2010,2011,2013,2014,2015,2017,2018,2019,2021,2022,2023,2025)


UPDATE MI_TER_VIG_REAL
SET FECINVIG=SUBSTRING(CONVERT(CHAR(8),FECINVIG),1,4)+0630
WHERE SUBSTRING(CONVERT(CHAR(8),FECINVIG),5,2)=06 AND 
SUBSTRING(CONVERT(CHAR(8),FECINVIG),7,2)>30

UPDATE MI_TER_VIG_REAL
SET FECINVIG=FECINVIG-100
WHERE SUBSTRING(CONVERT(CHAR(8),FECINVIG),5,2)>12


UPDATE MI_TER_VIG_REAL
SET FECTEVIG=SUBSTRING(CONVERT(CHAR(8),FECTEVIG),1,4)+0228
WHERE SUBSTRING(CONVERT(CHAR(8),FECTEVIG),5,2)=02 AND 
SUBSTRING(CONVERT(CHAR(8),FECTEVIG),7,2)>28 AND 
SUBSTRING(CONVERT(CHAR(8),FECTEVIG),1,4) IN (2009,2010,2011,2013,2014,2015,2017,2018,2019,2021,2022,2023,2025)


UPDATE MI_TER_VIG_REAL
SET FECTEVIG=SUBSTRING(CONVERT(CHAR(8),FECTEVIG),1,4)+0630
WHERE SUBSTRING(CONVERT(CHAR(8),FECTEVIG),5,2)=06 AND 
SUBSTRING(CONVERT(CHAR(8),FECTEVIG),7,2)>30

UPDATE MI_TER_VIG_REAL
SET FECTEVIG=FECTEVIG-100
WHERE SUBSTRING(CONVERT(CHAR(8),FECTEVIG),5,2)>12

UPDATE MI_TER_VIG_REAL
SET FECTEVIG_REAL=SUBSTRING(CONVERT(CHAR(8),FECTEVIG_REAL),1,4)+0228
WHERE SUBSTRING(CONVERT(CHAR(8),FECTEVIG_REAL),5,2)=02 AND 
SUBSTRING(CONVERT(CHAR(8),FECTEVIG_REAL),7,2)>28 AND 
SUBSTRING(CONVERT(CHAR(8),FECTEVIG_REAL),1,4) IN (2009,2010,2011,2013,2014,2015,2017,2018,2019,2021,2022,2023,2025)
AND FECTEVIG_REAL BETWEEN 19000101 AND 21000000

UPDATE MI_TER_VIG_REAL
SET FECTEVIG_REAL=SUBSTRING(CONVERT(CHAR(8),FECTEVIG_REAL),1,4)+0630
WHERE SUBSTRING(CONVERT(CHAR(8),FECTEVIG_REAL),5,2)=06 AND 
SUBSTRING(CONVERT(CHAR(8),FECTEVIG_REAL),7,2)>30
AND FECTEVIG_REAL BETWEEN 19000101 AND 21000000

UPDATE MI_TER_VIG_REAL
SET FECTEVIG_REAL=FECTEVIG_REAL-100
WHERE SUBSTRING(CONVERT(CHAR(8),FECTEVIG),5,2)>12
AND FECTEVIG_REAL BETWEEN 19000101 AND 21000000

UPDATE MI_BASE_EMISION
SET FECTEVIG_REAL='01/01/1900',
FECHA_CANCELACION='01/01/1900'


UPDATE MI_BASE_EMISION
SET RAMO=B.RAMO
FROM MI_BASE_EMISION A, MI_TER_VIG_REAL B
WHERE A.NNUMDOCU=B.NNUMDOCU 
AND A.RAMO=''


UPDATE MI_BASE_EMISION
SET FECTEVIG_REAL=SUBSTRING(CONVERT(CHAR(8),B.FECTEVIG_REAL),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECTEVIG_REAL),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECTEVIG_REAL),7,2),
RAMO=B.RAMO,
FECHA_CANCELACION=SUBSTRING(CONVERT(CHAR(8),B.FECEMIS),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECEMIS),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECEMIS),7,2)
FROM MI_BASE_EMISION A, MI_TER_VIG_REAL B
WHERE A.NNUMDOCU=B.NNUMDOCU  AND A.NNUMITEM=B.NNUMITEM AND B.FECTEVIG_REAL<>0
AND B.FECTEVIG_REAL BETWEEN 19000101 AND 21000000 AND A.PRORROGA=0



UPDATE MI_BASE_EMISION
SET FECTEVIG_REAL='01/01/1900',
RAMO=B.RAMO,
FECHA_CANCELACION='01/01/1900'
FROM MI_BASE_EMISION A, MI_TER_VIG_REAL B
WHERE A.NNUMDOCU=B.NNUMDOCU  AND A.NNUMITEM=B.NNUMITEM AND B.FECTEVIG_REAL=0 AND A.PRORROGA=0



SELECT A.* INTO #MI_FECHAS_PRORROGA_0 FROM MI_POLIZAS_PRORROGADAS_2 A , (SELECT POLIZA,MAX(ENDOSO)ENDOSO,ITEM FROM MI_POLIZAS_PRORROGADAS_2 WHERE PRORROGA=0 GROUP BY POLIZA,ITEM ) B WHERE  
A.POLIZA=B.POLIZA AND A.ENDOSO=B.ENDOSO AND A.ITEM=B.ITEM AND  A.PRORROGA=0 



UPDATE MI_BASE_EMISION
SET NFETEVIG=SUBSTRING(CONVERT(CHAR(8),B.FECTEVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECTEVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECTEVIG),7,2) 
FROM MI_BASE_EMISION A, MI_TER_VIG_REAL B
WHERE A.NNUMDOCU=B.NNUMDOCU  AND A.NNUMITEM=B.NNUMITEM
AND B.FECTEVIG BETWEEN 19000101 AND 21000000 AND A.PRORROGA=0

UPDATE MI_BASE_EMISION
SET NFEINVIG=SUBSTRING(CONVERT(CHAR(8),B.FECINVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECINVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECINVIG),7,2) 
FROM MI_BASE_EMISION A, MI_TER_VIG_REAL B
WHERE A.NNUMDOCU=B.NNUMDOCU  AND A.NNUMITEM=B.NNUMITEM
AND B.FECINVIG BETWEEN 19000101 AND 21000000  AND A.PRORROGA=0

UPDATE MI_BASE_EMISION
SET NFECEMIS=SUBSTRING(CONVERT(CHAR(8),B.FECEMIS),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECEMIS),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECEMIS),7,2) 
FROM MI_BASE_EMISION A, MI_TER_VIG_REAL B
WHERE A.NNUMDOCU=B.NNUMDOCU  AND A.NNUMITEM=B.NNUMITEM
AND B.FECEMIS BETWEEN 19000101 AND 21000000 AND A.PRORROGA=0

UPDATE MI_BASE_EMISION
SET NFETEVIG=SUBSTRING(CONVERT(CHAR(8),B.NFETEVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFETEVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFETEVIG),7,2) 

FROM MI_BASE_EMISION A, #MI_FECHAS_PRORROGA_0 B
WHERE A.NNUMDOCU=B.POLIZA  AND A.NNUMITEM=B.ITEM
AND B.NFECUACT BETWEEN 19000101 AND 21000000 AND A.PRORROGA=0



UPDATE MI_BASE_EMISION
SET FECTEVIG_REAL=NFETEVIG,FECHA_CANCELACION=NFETEVIG
WHERE FECTEVIG_REAL='1900-01-01' 




SELECT NNURUINT,NOMBRE_CORREDOR INTO #CORREDOR FROM  MI_BASE_EMISION WHERE PRORROGA=0 GROUP BY NNURUINT,NOMBRE_CORREDOR

UPDATE MI_BASE_EMISION
SET NNURUINT=B.NNURUINT
FROM MI_BASE_EMISION A, MI_TER_VIG_REAL B
WHERE 
A.NNUMDOCU=B.NNUMDOCU 
AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=0

UPDATE MI_BASE_EMISION
SET NOMBRE_CORREDOR=B.NOMBRE_CORREDOR
FROM MI_BASE_EMISION A, #CORREDOR B
WHERE A.NNURUINT=B.NNURUINT

/****** Checkpoint 5 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 01-5', SYSDATETIME())
/****************************************************************************/

CREATE TABLE #POL_CANCELADA_MASIVA
(
NFECUACT INT,
LLAVE NUMERIC,
NNUMDOCU INT,
NNUMITEM INT,
NFEINVIG INT,
NFETEVIG INT,
ESTADO CHAR(2)
)



DECLARE @CONSULTA2	AS NVARCHAR(4000)		
SET @CONSULTA2 = 		
		
'SELECT * FROM OPENQUERY(SOL,''
SELECT NFECUACT,NNUMENDO AS LLAVE ,NNUMDOCU,NNUMITEM,NFEINVIG,NFETEVIG,CINDBAJA  FROM RSASOLDB2.SUACSITE WHERE NNUMDOCU>0  AND NFETEVIG> 20150101 
AND DPRINETA<0 
 '')'

 --SELECT * FROM MI_TER_VIG_REAL WHERE NNUMDOCU=6393878 AND NNUMITEM=1

INSERT INTO  #POL_CANCELADA_MASIVA
EXEC SP_EXECUTESQL @CONSULTA2

/*TRUNCATE TABLE  MI_POL_CANCELADA_MASIVA
INSERT INTO MI_POL_CANCELADA_MASIVA
SELECT X.NNUMDOCU,X.NNUMITEM,Y.NFEINVIG,Y.NFETEVIG,Y.NFECUACT,Y.ESTADO   FROM 
(SELECT MAX(LLAVE)LLAVE,NNUMDOCU,NNUMITEM FROM #POL_CANCELADA_MASIVA
GROUP BY NNUMDOCU,NNUMITEM  
) X INNER JOIN #POL_CANCELADA_MASIVA Y ON
X.NNUMDOCU=Y.NNUMDOCU AND X.NNUMITEM=Y.NNUMITEM AND X.LLAVE=Y.LLAVE  
*/

DROP TABLE IF EXISTS MI_POL_CANCELADA_MASIVA
SELECT X.NNUMDOCU,X.NNUMITEM,Y.NFEINVIG,Y.NFETEVIG,Y.NFECUACT AS FECHA_CANCELACION,Y.ESTADO 
INTO MI_POL_CANCELADA_MASIVA
FROM 
(SELECT MAX(LLAVE)LLAVE,NNUMDOCU,NNUMITEM FROM #POL_CANCELADA_MASIVA
GROUP BY NNUMDOCU,NNUMITEM  
) X INNER JOIN #POL_CANCELADA_MASIVA Y ON
X.NNUMDOCU=Y.NNUMDOCU AND X.NNUMITEM=Y.NNUMITEM AND X.LLAVE=Y.LLAVE  
 



 --SELECT * FROM MI_POL_CANCELADA_MASIVA

 UPDATE MI_BASE_EMISION
SET FECTEVIG_REAL=SUBSTRING(CONVERT(CHAR(8),B.NFEINVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFEINVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFEINVIG),7,2),
FECHA_CANCELACION=SUBSTRING(CONVERT(CHAR(8),B.FECHA_CANCELACION),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECHA_CANCELACION),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.FECHA_CANCELACION),7,2) 
FROM MI_BASE_EMISION A, MI_POL_CANCELADA_MASIVA B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM =B.NNUMITEM AND B.ESTADO='B' AND A.PRORROGA=0

SELECT NNUMDOCU,MAX(NNUMENDO)NNUMENDO,NNUMITEM,PRORROGA INTO   #MAX_ENDOSO FROM MI_BASE_EMISION GROUP BY NNUMDOCU ,NNUMITEM,PRORROGA

SELECT A.* INTO   #INFO_ACTUAL FROM MI_BASE_EMISION A, #MAX_ENDOSO B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMENDO=B.NNUMENDO AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA

UPDATE MI_BASE_EMISION
SET NOMSUCU=B.NOMSUCU,NNURUEJC=B.NNURUEJC,NNURUINT=B.NNURUINT,NNURUPRO=B.NNURUPRO,NNURUTASE=B.NNURUTASE,SUCURSAL=B.SUCURSAL,NOMBRE_CORREDOR=B.NOMBRE_CORREDOR,DIRECCION_ASEGURADO=B.DIRECCION_ASEGURADO,COMUNA_ASEGURADO=B.COMUNA_ASEGURADO,
PROVINCIA_ASEGURADO=B.PROVINCIA_ASEGURADO,COD_MARCA_VEH=B.COD_MARCA_VEH,COD_MODELO_VEH=B.COD_MODELO_VEH,EXTENSION_VEH=B.EXTENSION_VEH,CILINDRADA_VEH=B.CILINDRADA_VEH,AÑO_FABR_VEH=B.AÑO_FABR_VEH,NUMMOT_VEH=B.NUMMOT_VEH,NUMCHA_VEH=B.NUMCHA_VEH,
PATENTE_VEH=B.PATENTE_VEH,COLOR_VEH=B.COLOR_VEH,DIG_PATENTE_VEH=B.DIG_PATENTE_VEH,COD_USO_VEH=B.COD_USO_VEH,MARCA_VEH=B.MARCA_VEH,MODELO_VEH=B.MODELO_VEH,COD_TIPO_VEH=B.COD_TIPO_VEH,TIPO_VEH=B.TIPO_VEH,REGION_ASEGURADO=B.REGION_ASEGURADO,
LINEA_NEGOCIO=B.LINEA_NEGOCIO,BUSINESS_UNIT=B.BUSINESS_UNIT,GRUPO=B.GRUPO,CHANNEL=B.CHANNEL,RAMO=B.RAMO,CCOMOORI=B.CCOMOORI
FROM MI_BASE_EMISION A,#INFO_ACTUAL B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA


UPDATE MI_BASE_EMISION
SET RAMO=B.RAMO
FROM MI_BASE_EMISION A, MI_TER_VIG_REAL B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM AND A.RAMO=''


UPDATE MI_BASE_EMISION
SET RAMO=B.RAMO
FROM MI_BASE_EMISION A, MI_POLIZAS_PRORROGADAS_2 B
WHERE A.NNUMDOCU=B.POLIZA AND A.NNUMITEM=B.ITEM AND A.RAMO=''


---FECHA INICIO VIGENCIA DE POLIZAS RIPLEY BIANUALES

SELECT POLIZA,ITEM,PRORROGA,MIN(ENDOSO)ENDOSO,MIN(NFEINVIG)NFEINVIG INTO #RIPLEY FROM MI_POLIZAS_PRORROGADAS_2 WHERE 
POLIZA IN (SELECT NNUMDOCU FROM  MI_BASE_EMISION WHERE PLAN_TECNICO LIKE ('%RIPLEY 2X2 4.0%') GROUP BY NNUMDOCU)
GROUP BY POLIZA,ITEM,PRORROGA

UPDATE #RIPLEY
SET NFEINVIG=B.NFEINVIG
FROM #RIPLEY A, MI_POLIZAS_PRORROGADAS_2 B
WHERE A.POLIZA=B.POLIZA AND A.ITEM=B.ITEM AND A.ENDOSO=B.ENDOSO AND A.PRORROGA=B.PRORROGA

UPDATE MI_BASE_EMISION
SET NFEINVIG= SUBSTRING(CONVERT(CHAR(8),B.NFEINVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFEINVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),B.NFEINVIG),7,2)
FROM MI_BASE_EMISION A, #RIPLEY B
WHERE A.NNUMDOCU=B.POLIZA AND A.NNUMITEM=B.ITEM  AND A.PRORROGA=B.PRORROGA



/****** Checkpoint 6 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 01-6', SYSDATETIME())
/****************************************************************************/

/*TRUNCATE TABLE MI_BASE_EMISION_FUSION
INSERT INTO MI_BASE_EMISION_FUSION
SELECT
NPECOSUS,B.NNUMDOCU,B.NNUMENDO,B.NNUMITEM,NFEINVIG,NFETEVIG,NFECEMIS,NOMSUCU,NPLAN,NPLANTEC,PLAN_TECNICO,NNURUEJC,NNURUINT,NNURUPRO,NNURUTASE,CCOMOORI,	
IND_REN,B.GWP_UF,B.COM_UF,B.GWP_CLP,B.COM_CLP,BUSINESS_UNIT,GRUPO,CHANNEL,LINEA_NEGOCIO,PLAN_COMERCIAL,SUCURSAL,NOMBRE_CORREDOR,	
MON_COMI,POR_COMI,NFENACIM,NOMBRE_ASEGURADO,MAIL_ASEGURADO,FONO_ASEGURADO,DIRECCION_ASEGURADO,COMUNA_ASEGURADO,PROVINCIA_ASEGURADO,COD_MARCA_VEH,COD_MODELO_VEH,EXTENSION_VEH,	
CILINDRADA_VEH,AÑO_FABR_VEH,NUMMOT_VEH,NUMCHA_VEH,PATENTE_VEH,COLOR_VEH,DIG_PATENTE_VEH,COD_USO_VEH,MARCA_VEH,MODELO_VEH,COD_TIPO_VEH,TIPO_VEH,REGION_ASEGURADO,FECTEVIG_REAL,RAMO,B.PRORROGA,B.FECHA_CANCELACION
FROM MI_BASE_EMISION A INNER JOIN
(SELECT NNUMDOCU,MAX(NNUMENDO)NNUMENDO,NNUMITEM,PRORROGA,SUM(GWP_UF)GWP_UF,SUM(COM_UF)COM_UF,SUM(GWP_CLP)GWP_CLP,SUM(COM_CLP)COM_CLP ,MAX(FECHA_CANCELACION) FECHA_CANCELACION FROM MI_BASE_EMISION GROUP BY NNUMDOCU,NNUMITEM,PRORROGA)B
ON A.NNUMDOCU=B.NNUMDOCU AND A.NNUMENDO=B.NNUMENDO AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA
*/

DROP TABLE IF EXISTS MI_BASE_EMISION_FUSION
SELECT
NPECOSUS,B.NNUMDOCU,B.NNUMENDO,B.NNUMITEM,NFEINVIG,NFETEVIG,NFECEMIS,NOMSUCU,NPLAN,NPLANTEC,PLAN_TECNICO,NNURUEJC,NNURUINT,NNURUPRO,NNURUTASE,CCOMOORI,	
IND_REN,B.GWP_UF,B.COM_UF,B.GWP_CLP,B.COM_CLP,BUSINESS_UNIT,GRUPO,CHANNEL,LINEA_NEGOCIO,PLAN_COMERCIAL,SUCURSAL,NOMBRE_CORREDOR,	
MON_COMI,POR_COMI,NFENACIM,NOMBRE_ASEGURADO,MAIL_ASEGURADO,FONO_ASEGURADO,DIRECCION_ASEGURADO,COMUNA_ASEGURADO,PROVINCIA_ASEGURADO,COD_MARCA_VEH,COD_MODELO_VEH,EXTENSION_VEH,	
CILINDRADA_VEH,AÑO_FABR_VEH,NUMMOT_VEH,NUMCHA_VEH,PATENTE_VEH,COLOR_VEH,DIG_PATENTE_VEH,COD_USO_VEH,MARCA_VEH,MODELO_VEH,COD_TIPO_VEH,TIPO_VEH,REGION_ASEGURADO,FECTEVIG_REAL,RAMO,B.PRORROGA,B.FECHA_CANCELACION
INTO MI_BASE_EMISION_FUSION
FROM MI_BASE_EMISION A INNER JOIN
(SELECT NNUMDOCU,MAX(NNUMENDO)NNUMENDO,NNUMITEM,PRORROGA,SUM(GWP_UF)GWP_UF,SUM(COM_UF)COM_UF,SUM(GWP_CLP)GWP_CLP,SUM(COM_CLP)COM_CLP ,MAX(FECHA_CANCELACION) FECHA_CANCELACION FROM MI_BASE_EMISION GROUP BY NNUMDOCU,NNUMITEM,PRORROGA)B
ON A.NNUMDOCU=B.NNUMDOCU AND A.NNUMENDO=B.NNUMENDO AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA







--WHERE A.NPLANTEC NOT IN (SELECT NPLANTEC FROM  MI_BASE_EMISION WHERE PLAN_TECNICO LIKE ('%RIPLEY 2X2 4.0%'))


--SELECT NNUMDOCU,MAX(NNUMENDO)NNUMENDO,NNUMITEM,PRORROGA,SUM(GWP_UF)GWP_UF,SUM(COM_UF)COM_UF,SUM(GWP_CLP)GWP_CLP,SUM(COM_CLP)COM_CLP ,
--MAX(FECHA_CANCELACION) FECHA_CANCELACION INTO #BASE_RIPLEY FROM MI_BASE_EMISION 
--WHERE NPLANTEC IN (SELECT NPLANTEC FROM  MI_BASE_EMISION WHERE PLAN_TECNICO LIKE ('%RIPLEY 2X2 4.0%')
--GROUP BY NPLANTEC)
--GROUP BY NNUMDOCU,NNUMITEM,PRORROGA

--SELECT A.NNUMDOCU,MAX(A.NNUMENDO)NNUMENDO,A.NNUMITEM,A.PRORROGA INTO #BASE_RIPLEY_2  
--FROM 
--MI_BASE_EMISION A LEFT JOIN
--(SELECT NNUMDOCU,NNUMITEM,ULTIMO_NNUMENDO,ULTIMO_CDESELEM FROM RAIZ_ENDOSO_FUSION WHERE NNUMDOCU IN
--(SELECT NNUMDOCU FROM  MI_BASE_EMISION WHERE PLAN_TECNICO LIKE ('%RIPLEY 2X2 4.0%'))AND ULTIMO_CDESELEM='DEVOLUCION DE PRIMA')B
--ON A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM AND A.NNUMENDO=B.ULTIMO_NNUMENDO
--WHERE NPLANTEC IN (SELECT NPLANTEC FROM  MI_BASE_EMISION WHERE PLAN_TECNICO LIKE ('%RIPLEY 2X2 4.0%') GROUP BY NPLANTEC)
--AND B.ULTIMO_CDESELEM IS NULL
--GROUP BY  A.NNUMDOCU,A.NNUMITEM,A.PRORROGA

--UPDATE #BASE_RIPLEY
--SET NNUMENDO= B.NNUMENDO
--FROM #BASE_RIPLEY A, #BASE_RIPLEY_2 B
--WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA

--INSERT INTO MI_BASE_EMISION_FUSION
--SELECT
--NPECOSUS,B.NNUMDOCU,B.NNUMENDO,B.NNUMITEM,NFEINVIG,NFETEVIG,NFECEMIS,NOMSUCU,NPLAN,NPLANTEC,PLAN_TECNICO,NNURUEJC,NNURUINT,NNURUPRO,NNURUTASE,CCOMOORI,	
--IND_REN,B.GWP_UF,B.COM_UF,B.GWP_CLP,B.COM_CLP,BUSINESS_UNIT,GRUPO,CHANNEL,LINEA_NEGOCIO,PLAN_COMERCIAL,SUCURSAL,NOMBRE_CORREDOR,	
--MON_COMI,POR_COMI,NFENACIM,NOMBRE_ASEGURADO,MAIL_ASEGURADO,FONO_ASEGURADO,DIRECCION_ASEGURADO,COMUNA_ASEGURADO,PROVINCIA_ASEGURADO,COD_MARCA_VEH,COD_MODELO_VEH,EXTENSION_VEH,	
--CILINDRADA_VEH,AÑO_FABR_VEH,NUMMOT_VEH,NUMCHA_VEH,PATENTE_VEH,COLOR_VEH,DIG_PATENTE_VEH,COD_USO_VEH,MARCA_VEH,MODELO_VEH,COD_TIPO_VEH,TIPO_VEH,REGION_ASEGURADO,FECTEVIG_REAL,RAMO,B.PRORROGA,B.FECHA_CANCELACION
--FROM MI_BASE_EMISION A INNER JOIN
--#BASE_RIPLEY B
--ON A.NNUMDOCU=B.NNUMDOCU AND A.NNUMENDO=B.NNUMENDO AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA



UPDATE MI_BASE_EMISION_FUSION
SET FECHA_CANCELACION=NFEINVIG
WHERE FECHA_CANCELACION IS NULL


UPDATE MI_BASE_EMISION_FUSION
SET NNURUPRO= NULL


UPDATE MI_BASE_EMISION_FUSION
SET NNURUPRO=B.NNURUASE
FROM MI_BASE_EMISION_FUSION A, (SELECT * FROM PROCESOS.DBO.BASE_ASEGURADO WHERE ORIGEN='ITE_POL'AND NNURUASE>0) B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM  AND NNURUPRO IS NULL

UPDATE MI_BASE_EMISION_FUSION
SET NNURUPRO=B.NNURUASE
FROM MI_BASE_EMISION_FUSION A, (SELECT * FROM PROCESOS.DBO.BASE_ASEGURADO WHERE ORIGEN='RPO' AND NNURUASE>0) B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM  AND NNURUPRO IS NULL

UPDATE MI_BASE_EMISION_FUSION
SET NNURUPRO=B.NNURUASE
FROM MI_BASE_EMISION_FUSION A, (SELECT * FROM PROCESOS.DBO.BASE_ASEGURADO WHERE ORIGEN='ITE_POL'AND NNURUASE>0) B
WHERE A.NNUMDOCU=B.NNUMDOCU   AND NNURUPRO IS NULL

UPDATE MI_BASE_EMISION_FUSION
SET NNURUPRO=B.NNURUASE
FROM MI_BASE_EMISION_FUSION A, (SELECT * FROM PROCESOS.DBO.BASE_ASEGURADO WHERE ORIGEN='RPO'AND NNURUASE>0) B
WHERE A.NNUMDOCU=B.NNUMDOCU   AND NNURUPRO IS NULL


UPDATE MI_BASE_EMISION_FUSION
SET NNURUPRO=NNURUTASE
WHERE NNURUPRO IS NULL AND NNURUTASE>0


UPDATE MI_BASE_EMISION_FUSION
SET NNURUPRO=B.NNURUPRO
FROM MI_BASE_EMISION_FUSION A, MI_BASE_EMISION B
WHERE A.NNUMDOCU=B.NNUMDOCU   AND A.NNURUPRO IS NULL  AND B.NNURUPRO>0


/****** Checkpoint 7 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 01-7', SYSDATETIME())
/****************************************************************************/

----------------------------------------------------SERIE DIARIA UF
CREATE TABLE #MI_SERIE_DIARIA_UF(
	FEC INT NULL,
	FECHA CHAR(10) NULL,
	UF [NUMERIC](16, 5) NULL
) ON [PRIMARY]

INSERT INTO #MI_SERIE_DIARIA_UF
SELECT CAST(NMESACON AS CHARACTER(6)) + RIGHT('0' + REPLACE(CAST(NDIACONV AS CHARACTER(2)),' ',''),2),
RIGHT('0' + REPLACE(CAST(NDIACONV AS CHARACTER(2)),' ',''),2) + '-' + SUBSTRING(CAST(NMESACON AS CHARACTER(6)),5,2) + '-' + SUBSTRING(CAST(NMESACON AS CHARACTER(6)),1,4),
DMONCONM
FROM SOL.[S1031EBB].RSASOLDB2.TSACSDVC WHERE CCOMOORI IN ('0052UF   00') AND CCODMONE IN ('0052$    00') AND DMONCONM>0 ORDER BY 1 ASC


-----------------------------------------------------SERIE DIARIA DOLAR
CREATE TABLE #MI_SERIE_DIARIA_DOLAR(
	FEC INT NULL,
	FECHA CHAR(10) NULL,
	DOLAR [NUMERIC](16, 5) NULL
) ON [PRIMARY]

INSERT INTO #MI_SERIE_DIARIA_DOLAR
SELECT CAST(NMESACON AS CHARACTER(6)) + RIGHT('0' + REPLACE(CAST(NDIACONV AS CHARACTER(2)),' ',''),2),
RIGHT('0' + REPLACE(CAST(NDIACONV AS CHARACTER(2)),' ',''),2) + '-' + SUBSTRING(CAST(NMESACON AS CHARACTER(6)),5,2) + '-' + SUBSTRING(CAST(NMESACON AS CHARACTER(6)),1,4),
DMONCONM
FROM SOL.[S1031EBB].RSASOLDB2.TSACSDVC WHERE CCOMOORI IN ('0052US$  00') AND CCODMONE IN ('0052$    00') AND DMONCONM>0 ORDER BY 1 ASC


-----------------------------------------------------SERIE DIARIA EURO
CREATE TABLE #MI_SERIE_DIARIA_EURO(
	FEC INT NULL,
	FECHA CHAR(10) NULL,
	EURO [NUMERIC](16, 5) NULL
) ON [PRIMARY]

INSERT INTO #MI_SERIE_DIARIA_EURO
SELECT CAST(NMESACON AS CHARACTER(6)) + RIGHT('0' + REPLACE(CAST(NDIACONV AS CHARACTER(2)),' ',''),2),
RIGHT('0' + REPLACE(CAST(NDIACONV AS CHARACTER(2)),' ',''),2) + '-' + SUBSTRING(CAST(NMESACON AS CHARACTER(6)),5,2) + '-' + SUBSTRING(CAST(NMESACON AS CHARACTER(6)),1,4),
DMONCONM
FROM SOL.[S1031EBB].RSASOLDB2.TSACSDVC WHERE CCOMOORI IN ('0052EUR  00') AND CCODMONE IN ('0052$    00') AND DMONCONM>0 ORDER BY 1 ASC


----

TRUNCATE TABLE PROCESOS.DBO.BASE_SERIE_DIARIA_MONEDA
INSERT INTO PROCESOS.DBO.BASE_SERIE_DIARIA_MONEDA
SELECT FEC,CONVERT(DATE,FECHA,105),SUM(UF)UF,SUM(DOLAR)DOLAR, SUM(EURO)EURO
FROM (
SELECT *,0 AS DOLAR, 0 AS EURO FROM #MI_SERIE_DIARIA_UF WHERE FEC >20020000
UNION 
SELECT FEC,FECHA,0,DOLAR,0 FROM #MI_SERIE_DIARIA_DOLAR WHERE FEC >20020000
UNION 
SELECT FEC,FECHA,0,0,EURO FROM #MI_SERIE_DIARIA_EURO WHERE FEC >20020000
)  X
WHERE CONVERT(DATE,FECHA,105)<GETDATE()
GROUP BY FEC,CONVERT(DATE,FECHA,105) 
ORDER BY 1 DESC

/****** Checkpoint 8 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 01-8', SYSDATETIME())
/****************************************************************************/

--SELECT * FROM MI_SERIE_DIARIA_DOLAR ORDER BY 1 DESC

----- CALCULO VALOR MONEDA DOLAR

SELECT NNUMDOCU,NNUMITEM,NFECEMIS,PRORROGA,SUM(GWP_CLP)GWP_CLP, SUM(COM_CLP)COM_CLP,SUM(COM_CLP)UF,SUM(COM_CLP)PRIMA_UF, SUM(COM_CLP)COM_UF 
INTO  #VALORPESO FROM [MI_BASE_EMISION]
WHERE  CCOMOORI IN ('0052DOB  00','0052UDP  00','0052US$  00','0052USA  00')
GROUP BY NNUMDOCU,NNUMITEM,PRORROGA,NFECEMIS
HAVING SUM(GWP_CLP)>0

UPDATE #VALORPESO
SET UF=0,PRIMA_UF=0,COM_UF=0

UPDATE #VALORPESO
SET UF=B.UF,PRIMA_UF=GWP_CLP/B.UF,COM_UF=COM_CLP/B.UF
FROM #VALORPESO A, PROCESOS.DBO.BASE_SERIE_DIARIA_MONEDA B
WHERE A.NFECEMIS=B.FECHA

UPDATE #VALORPESO
SET COM_UF=COM_UF*-1
WHERE COM_UF<0

UPDATE MI_BASE_EMISION_FUSION
SET GWP_UF=B.PRIMA_UF , GWP_CLP=B.GWP_CLP,COM_UF=B.COM_UF,COM_CLP=B.COM_CLP
FROM MI_BASE_EMISION_FUSION A, #VALORPESO B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA


UPDATE MI_BASE_EMISION_FUSION
SET COM_UF=ROUND((COM_UF/GWP_UF)*-100,2) WHERE GWP_UF NOT IN (0)

UPDATE MI_BASE_EMISION_FUSION
SET COM_UF=COM_UF*-1 WHERE COM_UF<0


DROP TABLE IF EXISTS SUACSPOL_TEMP3
DROP TABLE IF EXISTS SUACSITE_TEMP3


/****** Checkpoint PROCESO TERMINADO ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('PROCESO 01 TERMINADO', SYSDATETIME())
/****************************************************************************/

END




