USE [Transaccional]
GO
/****** Object:  StoredProcedure [dbo].[SP_MI_TRANSACCIONAL_MOTOR_02]    Script Date: 14-10-2025 10:23:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER  PROCEDURE [dbo].[SP_MI_TRANSACCIONAL_MOTOR_02]
AS
DECLARE @CONSULTA_COMERCIAL	AS NVARCHAR(4000)	
		
BEGIN

-- ESTE PROCESO NO TIENE PARAMETROS, SIMPLEMENTE SE EJECUTA TAL CUAL LA LINEA SIGUIENTE
-- exec [SP_MI_TRANSACCIONAL_MOTOR_02]

/****** Checkpoint Inicio ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('PROCESO 02 INICIADO', SYSDATETIME())
/*********************************************************************************/

TRUNCATE TABLE PROCESOS.DBO.BASE_PLANES_TECNICOS
INSERT INTO PROCESOS.DBO.BASE_PLANES_TECNICOS
SELECT NPLANTEC,NPLANTEC,NNURUINT,PLAN_TECNICO,LINEA_NEGOCIO,' ' TIPO_PLAN, 0 AS DEDUCIBLE,'','','','',0,0,'',0,0,0,0,0,0 
FROM MI_BASE_EMISION_FUSION 
GROUP BY NPLANTEC,NPLANTEC,NNURUINT,PLAN_TECNICO,LINEA_NEGOCIO


UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS
SET TIPO_PLAN=RTRIM(B.TIPO_PLAN),DEDUCIBLE=B.DEDUCIBLE
FROM PROCESOS.DBO.BASE_PLANES_TECNICOS A, PROCESOS.DBO.BASE_INFO_PLANES B
WHERE A.NPLANTEC=B.NPLANTEC


UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS
SET DP=B.DP, PT=B.PT, ROBO=B.ROBO, RC=B.RC, RCA=B.RCA, RCE=B.RCE
FROM PROCESOS.DBO.BASE_PLANES_TECNICOS A, PROCESOS.DBO.BASE_INFO_COBERTURA B
WHERE A.TIPO_PLAN=B.TIPO_PLAN



UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS
SET [BUSINESS UNIT]=RTRIM(B.[BUSINESS_UNIT]),CHANNEL=RTRIM(B.[CHANNEL]), GRUPO=RTRIM(B.[GRUPO])
FROM PROCESOS.DBO.BASE_PLANES_TECNICOS A, PROCESOS.DBO.BASE_INFO_CANAL B
WHERE A.LINEA_NEGOCIO=B.LINEA_NEGOCIO AND A.NNUMRUT=B.NNUMRUT


UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS
SET CHANNEL=RTRIM(B.CHANNEL)
FROM PROCESOS.DBO.BASE_PLANES_TECNICOS A, PROCESOS.DBO.BASE_INFO_AJUSTES_PRODUCTO B
WHERE A.NPLANTEC=B.NPLANTEC 


UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS
SET CORREDOR_AGRUP=RTRIM(B.CORREDOR_AGRUP), F5=B.F5, R7=B.R7, CHANNEL1=RTRIM(B.CHANNEL1)
FROM PROCESOS.DBO.BASE_PLANES_TECNICOS A, PROCESOS.DBO.BASE_INFO_CORREDOR_AGRUPADO B
WHERE A.CHANNEL=B.CHANNEL AND A.LINEA_NEGOCIO=B.LINEA_NEGOCIO




--AJUSTA DERCO
UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS 
SET [BUSINESS UNIT] = 'NEGOCIOS MASIVOS Y CLIENTES',GRUPO = 'DERCO', CORREDOR_AGRUP = CASE WHEN  TIPO_PLAN IN('RCA','RCE')THEN 'RCA / RCE'ELSE 'DERCO' END
WHERE CHANNEL='DERCO'

--AJUSTA BICE
UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS 
SET [BUSINESS UNIT] = 'NEGOCIOS MASIVOS Y CLIENTES',GRUPO = 'BICE', CHANNEL ='BICE', CORREDOR_AGRUP = CASE WHEN  TIPO_PLAN IN('RCA','RCE')THEN 'RCA / RCE'ELSE 'BICE' END
WHERE NNUMRUT=78996780 AND LINEA_NEGOCIO='PERSONAL'

--AJUSTA FORUM PERSONAL
UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS 
SET [BUSINESS UNIT] = 'NEGOCIOS MASIVOS Y CLIENTES',GRUPO = 'FORUM', CORREDOR_AGRUP = CASE WHEN  TIPO_PLAN IN('RCA','RCE')THEN 'RCA / RCE'ELSE 'FORUM' END
WHERE CHANNEL='FORUM' AND LINEA_NEGOCIO='PERSONAL'

--AJUSTA FORUM COMMERCIAL
UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS 
SET [BUSINESS UNIT] = 'NEGOCIOS MASIVOS Y CLIENTES',GRUPO = 'FORUM', CORREDOR_AGRUP = CASE WHEN  TIPO_PLAN IN('RCA','RCE')THEN 'RCA / RCE'ELSE 'AFFINITY OTROS' END
WHERE CHANNEL='FORUM' AND LINEA_NEGOCIO='COMMERCIAL'


--AJUSTA ANS
UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS 
SET [BUSINESS UNIT] = 'NEGOCIOS EMPRESAS Y PERSONAS',GRUPO = 'CORREDORES REGIONES', CORREDOR_AGRUP = CASE WHEN  TIPO_PLAN IN('RCA','RCE')THEN 'RCA / RCE'ELSE 'ANS' END
WHERE CHANNEL='ANS'

--AJUSTA COMPARA ONLINE
UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS 
SET [BUSINESS UNIT] = 'NEGOCIOS MASIVOS Y CLIENTES',GRUPO = 'COMPARA ON LINE', CORREDOR_AGRUP = CASE WHEN  TIPO_PLAN IN('RCA','RCE')THEN 'RCA / RCE'ELSE 'COMPARA ON LINE' END
WHERE CHANNEL='COMPARA ON LINE'AND LINEA_NEGOCIO='PERSONAL'

--AJUSTA DIRECTO
UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS 
SET [BUSINESS UNIT] = 'NEGOCIOS DIRECTOS',GRUPO = 'DIRECTO'
WHERE CHANNEL='DIRECTO'



UPDATE MI_BASE_EMISION_FUSION
SET
BUSINESS_UNIT= RTRIM("BUSINESS UNIT"),
GRUPO= RTRIM(B.GRUPO),
CHANNEL=RTRIM(B.CHANNEL)
FROM MI_BASE_EMISION_FUSION A,PROCESOS.DBO.BASE_PLANES_TECNICOS B
WHERE 
A.NNURUINT = B.NNUMRUT
AND A.NPLANTEC = B.NPLANTEC
AND A.LINEA_NEGOCIO = B.LINEA_NEGOCIO

-- GENERA CLAVE PARA LOS PLANES TECNICOS
UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS
SET CLAVE = REPLACE(CONVERT(CHAR(10),NNUMRUT)+'-'+CONVERT(CHAR(5),RTRIM(NPLANTEC)) +'-'+LINEA_NEGOCIO,' ','')


----------------------------------------------------------------------------------------------------

-- ACTUALIZO TIPO PLANES TÉCNICOS QUE NO ESTAN EN LA BASE

UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS
SET
TIPO_PLAN= B.TIPO_PLAN
FROM PROCESOS.DBO.BASE_PLANES_TECNICOS A 
INNER JOIN (SELECT CODIGO_PLAN_TECNICO, MAX(TIPO_PLAN) TIPO_PLAN FROM REPORTES.DBO.SURA_MOVILIDAD_TRANSACCIONAL GROUP BY CODIGO_PLAN_TECNICO) B
ON A.NPLANTEC = B.CODIGO_PLAN_TECNICO
WHERE A.TIPO_PLAN ='' OR A.TIPO_PLAN IS NULL OR A.TIPO_PLAN LIKE 'NO INDE%'

UPDATE PROCESOS.DBO.BASE_PLANES_TECNICOS
SET
TIPO_PLAN = 'PT + RC'
WHERE (TIPO_PLAN ='' OR TIPO_PLAN IS NULL OR TIPO_PLAN LIKE 'NO INDE%') AND (PLAN_TECNICO LIKE '%TRANS%' OR PLAN_TECNICO LIKE '%BUSES%' OR PLAN_TECNICO LIKE '%METBUS%')

/*
--SIN TIPO PLAN TECNICO
SELECT NPLANTEC,PLAN_TECNICO,TIPO_PLAN,DEDUCIBLE
FROM PROCESOS.DBO.BASE_PLANES_TECNICOS
GROUP BY NPLANTEC,PLAN_TECNICO,TIPO_PLAN,DEDUCIBLE
HAVING TIPO_PLAN ='' OR TIPO_PLAN IS NULL
-- CONFIRMAR SIN TIPO PLAN TECNICO
SELECT TIPO_PLAN FROM PROCESOS.DBO.BASE_PLANES_TECNICOS GROUP BY TIPO_PLAN
---="INSERT INTO PROCESOS.DBO.BASE_INFO_PLANES VALUES ("&A1772&",'"&B1772&"','"&C1772&"',"&D1772&")"



--SIN CANAL
SELECT NNUMRUT,LINEA_NEGOCIO
FROM PROCESOS.DBO.BASE_PLANES_TECNICOS
GROUP BY NNUMRUT,LINEA_NEGOCIO, [BUSINESS UNIT]
HAVING [BUSINESS UNIT]='' OR [BUSINESS UNIT] IS NULL

--CONFIRMAR SIN CANAL
SELECT [BUSINESS UNIT] FROM PROCESOS.DBO.BASE_PLANES_TECNICOS GROUP BY [BUSINESS UNIT]

---SELECT * FROM [MI_BASE_EMISION] WHERE NNURUINT IN(SELECT NNUMRUT FROM PROCESOS.DBO.BASE_PLANES_TECNICOS GROUP BY NNUMRUT,LINEA_NEGOCIO, [BUSINESS UNIT] HAVING [BUSINESS UNIT]='' OR [BUSINESS UNIT] IS NULL)
---EXCEL       ="INSERT INTO PROCESOS.DBO.BASE_INFO_CANAL VALUES ("&A3447&",'"&B3447&"','"&C3447&"','"&D3447&"','"&E3447&"')"
--- RUTA  Q:\PRI_CONFIDENCIAL\MI\A00. FUENTES DE INFORMACION\2016.02



--SIN CORREDOR AGRUPADO
SELECT CHANNEL,CORREDOR_AGRUP
FROM PROCESOS.DBO.BASE_PLANES_TECNICOS
GROUP BY CHANNEL,CORREDOR_AGRUP
HAVING CORREDOR_AGRUP='' OR CORREDOR_AGRUP IS NULL
*/
/****** Checkpoint PROCESO TERMINADO ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('PROCESO 02 TERMINADO', SYSDATETIME())
/****************************************************************************/

END




