USE [Transaccional]
GO
/****** Object:  StoredProcedure [dbo].[SP_MI_SOAP_TABLERO_V3]    Script Date: 14-10-2025 10:30:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO





ALTER  PROCEDURE [dbo].[SP_MI_SOAP_TABLERO_V3](
@DESDE_EXPUESTOS AS DATE,
@HASTA_EXPUESTOS AS DATE,
@DESDE_SINIESTROS AS DATE,
@HASTA_SINIESTROS AS DATE)
AS
DECLARE @CONSULTA_COMERCIAL	AS NVARCHAR(4000)	

---EXEC [SP_MI_SOAP_TABLERO_V3] '2022-01-31','2025-03-31','2022-01-31','2025-03-31'


BEGIN


DECLARE @TERMINO DATETIME
DECLARE @INICIO DATETIME
DECLARE @PASOS DATETIME
SET @INICIO=GETDATE()
SET @PASOS=@INICIO
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SET @TERMINO= GETDATE()
INSERT INTO CANAL_ASESOR.DBO.MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SOAP','INICIO',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()

-- CREA BASE DE EXPUESTOS

/*
DECLARE 
	@HASTA_EXPUESTOS DATE = '2023-07-31',
	@DESDE_EXPUESTOS DATE = '2018-01-31',
	@HASTA_SINIESTROS DATE = '2023-07-31',
	@DESDE_SINIESTROS DATE = '2018-01-31'
*/

DECLARE	@POLIZA	 NUMERIC(8)
SET @POLIZA=(SELECT MAX(POLIZA) from MI_BASE_CONVENIO_SOAP)
		 
DECLARE @CONSULTA AS NVARCHAR(4000)	
SET @CONSULTA = 'SELECT * FROM OPENQUERY(SOL,'' 
SELECT 
A.NNUCESOA	AS POLIZA, 
B.CDESCORT	AS CONVENIO,
A.CINFOPAG	AS FORMA_PAGO,
''''WEB''''	AS TIPO_VENTA 
FROM  
RSASOLDB2.SOACSPOL A LEFT JOIN 
RSASOLDB2.SOACSCAM B ON A.NCODCAMP=B.NCODCAMP
WHERE NNUCESOA>'  +CAST (@POLIZA AS NVARCHAR(10))  +' 
 '')'

INSERT INTO MI_BASE_CONVENIO_SOAP
EXEC SP_EXECUTESQL @CONSULTA


UPDATE MI_BASE_CONVENIO_SOAP
SET CONVENIO = b.Convenio
FROM  MI_BASE_CONVENIO_SOAP A, Convenios_SOAP B
WHERE A.POLIZA=B.NumeroPoliza


CREATE      TABLE #SOAP_EXPUESTOS_1(
POLIZA		CHAR(20) NULL,
MARCA		CHAR(60) NULL,	
MODELO		CHAR(70) NULL,
TIPO 		CHAR(80) NULL,	
SUCURSAL	CHAR(50) NULL,
NFECEMIS	CHAR(50) NULL,
NFEINVIG	CHAR(10) NULL,
NFETEVIG	CHAR(10) NULL,
NNURUPRO	CHAR(10) NULL,
AÑO_FAB		CHAR(10) NULL,
NUM_MOTOR	CHAR(70) NULL,
PATENTE		CHAR(10) NULL,
DV_PATENTE	CHAR(2) NULL,
PRIMA		FLOAT NULL,
NNURUEJC	CHAR(12) NULL,
NNURUINT	CHAR(12) NULL)


INSERT INTO  #SOAP_EXPUESTOS_1
SELECT * FROM OPENQUERY(SOL,' 
SELECT 
A.NNUCESOA POLIZA,
C.CDESCORT AS MARCA,
D.CDESCORT AS MODELO,
E.CDESCORT TIPO,
F.CSIGELEM SUCURSAL,
A.NFECEMIS,
A.NFEINVIG,
A.NFETEVIG,
A.NNURUPRO,
A.NANFAVEH AÑO_FAB,
A.CNUMOVEH NUM_MOTOR,
A.CNUMPATE PATENTE,
A.CDIGPATE DV_PATENTE,
A.DVALPRIM PRIMA,
A.NNURUEJC,
B.NNURUINT
FROM RSASOLDB2.SOACSPOL A
LEFT JOIN RSASOLDB2.SOACSVTA B ON A.NNUREVTA	=B.NNUREVTA
LEFT JOIN RSASOLDB2.SOACSMVH C ON A.CCOMAVEH	=C.CCOMAVEH
LEFT JOIN RSASOLDB2.SOACSMOV D ON A.CCOMAVEH	=D.CCOMAVEH AND A.NCOMOVEH=D.NCOMOVEH AND A.NCOTIVEC=D.NCOTIVEC
LEFT JOIN RSASOLDB2.SOACSTVS E ON A.NCOTIVEC	=E.NCOTIVEC
LEFT JOIN RSASOLDB2.TBACSTGE F ON B.CCODSUCU	=F.CCODUNIC
WHERE A.NFETEVIG>20190000
')



SET @TERMINO= GETDATE()
INSERT INTO CANAL_ASESOR.DBO.MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SOAP','1 DE 5',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()

SELECT A.POLIZA, A.MARCA, A.MODELO, A.TIPO, A.SUCURSAL,
SUBSTRING(CONVERT(CHAR(8),A.NFECEMIS),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),A.NFECEMIS),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),A.NFECEMIS),7,2) NFECEMIS,
SUBSTRING(CONVERT(CHAR(8),A.NFEINVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),A.NFEINVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),A.NFEINVIG),7,2) NFEINVIG,
SUBSTRING(CONVERT(CHAR(8),A.NFETEVIG),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),A.NFETEVIG),5,2)+'-'+SUBSTRING(CONVERT(CHAR(8),A.NFETEVIG),7,2) NFETEVIG,
A.NNURUPRO,
CASE 
	WHEN A.NNURUPRO > 21000000 THEN NULL 
	ELSE (ROUND(CONVERT(INT,(SUBSTRING(A.NFEINVIG,1,4))) - (1930.3 + (3.46 * CONVERT(INT,A.NNURUPRO) / 1000000)), 0)) 
END AS EDAD, 
A.AÑO_FAB, A.NUM_MOTOR, A.PATENTE, A.DV_PATENTE, A.PRIMA, C.FORMA_PAGO, A.NNURUEJC, A.NNURUINT, C.TIPO_VENTA, B.COMUNA_1 AS COMUNA,
YEAR(DATEADD(YEAR,-1,A.NFETEVIG))		AS AÑO_CAMPAÑA,
MONTH(DATEADD(MONTH,0,A.NFETEVIG))		AS MES_CAMPAÑA,
C.CONVENIO
INTO #SOAP_EXPUESTOS_2
FROM #SOAP_EXPUESTOS_1 AS A
LEFT JOIN  BASE_CONTACTABILIDAD_SINACOFI AS B
ON A.NNURUPRO = B.RUT
LEFT JOIN MI_BASE_CONVENIO_SOAP AS C
ON A.POLIZA COLLATE Modern_Spanish_CI_AS = C.POLIZA

drop table #SOAP_EXPUESTOS_1
/*
DECLARE 
	@HASTA_EXPUESTOS DATE = '2023-07-31',
	@DESDE_EXPUESTOS DATE = '2018-01-31'
*/

SELECT A.*,B.PER_ANT,B.PER, 
CASE WHEN NFEINVIG	>	B.PER_ANT	AND NFEINVIG	<=	B.PER		THEN 1 ELSE 0		END			AS INICIA,
CASE WHEN NFETEVIG	<=	B.PER		AND NFETEVIG	>	B.PER_ANT	THEN 1 ELSE 0		END			AS TERMINA,
CASE WHEN NFETEVIG	>	B.PER		AND NFEINVIG	<=	B.PER_ANT	THEN 1 ELSE 0		END			AS VIGENTE,
ROUND(CONVERT( FLOAT, DATEDIFF(DAY,CASE WHEN NFEINVIG>B.PER_ANT THEN DATEADD(DAY,-1,NFEINVIG) ELSE B.PER_ANT	END,
CASE WHEN NFETEVIG<B.PER THEN NFETEVIG ELSE B.PER END ))/CASE WHEN DATEDIFF (DAY,DATEADD(DAY,-1,NFEINVIG),NFETEVIG)=0 THEN 1 ELSE DATEDIFF (DAY,DATEADD(DAY,-1,NFEINVIG),NFETEVIG) END,5)	AS POR_DEV,
ROUND(CONVERT( FLOAT, DATEDIFF(DAY,CASE WHEN NFEINVIG>B.PER_ANT THEN DATEADD(DAY,-1,NFEINVIG) ELSE B.PER_ANT	END,
CASE WHEN NFETEVIG<B.PER THEN NFETEVIG ELSE B.PER END ))/365.25,5)																															AS EXP_AÑO
INTO #SOAP_EXPUESTOS_3
FROM #SOAP_EXPUESTOS_2 A, (SELECT * FROM MI_PERIODO WHERE PER > @DESDE_EXPUESTOS AND PER <= @HASTA_EXPUESTOS ) B

drop table #SOAP_EXPUESTOS_2

SELECT *
INTO #SOAP_EXPUESTOS_4
FROM #SOAP_EXPUESTOS_3
WHERE INICIA + TERMINA + VIGENTE > 0 AND EXP_AÑO > 0

drop table #SOAP_EXPUESTOS_3

drop table if exists SOAP_EXPUESTOS_FINAL
SELECT
A.PER,
A.TIPO,
A.COMUNA,
A.POLIZA,
A.SUCURSAL,
A.EDAD,
SUM(A.PRIMA * A.POR_DEV)	AS PRIMA_GANADA,
SUM(A.PRIMA * INICIA)		AS PRIMA_SUSCRITA,
A.FORMA_PAGO,
SUM(A.EXP_AÑO)				AS EXPUESTOS,
SUM(INICIA+VIGENTE)			AS VIGENTES,
SUM(INICIA)					AS INICIAN,
B.BUSINESS_UNIT				AS UNIDAD_NEGOCIO,
B.GRUPO						AS GRUPO,
B.CHANNEL					AS CANAL,
B.NOMBRE_CORREDOR			AS CORREDOR,
A.TIPO_VENTA,
A.AÑO_CAMPAÑA,
A.MES_CAMPAÑA,
A.CONVENIO,
A.NNURUPRO
INTO SOAP_EXPUESTOS_FINAL
FROM #SOAP_EXPUESTOS_4 A 
LEFT JOIN (
	SELECT NNURUINT, BUSINESS_UNIT, GRUPO, CANAL AS CHANNEL, NOMBRE_CORREDOR
	FROM PROCESOS.DBO.BASE_SOAP_INTERMEDIARIO 
	GROUP BY NNURUINT, BUSINESS_UNIT, GRUPO, CANAL, NOMBRE_CORREDOR) B 
ON A.NNURUINT=B.NNURUINT
GROUP BY 
A.PER, A.TIPO, A.COMUNA, A.POLIZA, A.SUCURSAL, A.EDAD, A.FORMA_PAGO, B.BUSINESS_UNIT, B.GRUPO, B.CHANNEL, B.NOMBRE_CORREDOR, A.TIPO_VENTA, A.AÑO_CAMPAÑA, 
A.MES_CAMPAÑA, A.CONVENIO,A.NNURUPRO

drop table #SOAP_EXPUESTOS_4

SET @TERMINO= GETDATE()
INSERT INTO CANAL_ASESOR.DBO.MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SOAP','2 DE 5',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()

-- CREA BASE DE SINIESTROS

--OBTENER REGISTROS DEL ARCHIVO DE PAGO (ACTUARIAL) 

/*
DECLARE 
	@HASTA_SINIESTROS DATE = '2023-07-31',
	@DESDE_SINIESTROS DATE = '2018-01-31'
*/

select 
SINIESTRO, 
EXPEDIENTE																							AS CORRELATIVO_STRO, 
NUM_POLIZA																							AS POLIZA, 
CONVERT (DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU)))												AS F_OCU, 
CASE WHEN LTRIM(RTRIM(TIPO_STRO_LOCAL)) IS NULL THEN 'NA' ELSE LTRIM(RTRIM(TIPO_STRO_LOCAL)) END	AS TIPO_SINIESTRO,
SUM(MONTO_NET_CLP)																					AS PAGOS,
SUM(MONTO_NET_UF)																					AS PAGOS_UF,
SUM(0)																								AS RESERVAS,
SUM(0)																								AS RESERVAS_UF
INTO #SOAP_PAGOS_RESERVAS
FROM [SGF1034].[ACTUARIAL].DBO.PAGOS_RVAS 
WHERE 
	RAMO_RESERVA LIKE ('%SOAP%') AND CONCEPTO='LIQ'
	AND CONVERT (DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU))) BETWEEN @DESDE_SINIESTROS AND @HASTA_SINIESTROS
	AND CIERRE <=SUBSTRING(REPLACE(CONVERT(CHAR(10),@HASTA_SINIESTROS),'-',''),1,6)
GROUP BY 
SINIESTRO,EXPEDIENTE,NUM_POLIZA,
CONVERT (DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU))),	 
LTRIM(RTRIM(TIPO_STRO_LOCAL)) 
ORDER BY CONVERT (DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU))) DESC

--OBTENER REGISTROS DEL ARCHIVO DE RESERVA (ACTUARIAL) 

INSERT INTO #SOAP_PAGOS_RESERVAS
select 
SINIESTRO, 
EXPEDIENTE																							AS CORRELATIVO_STRO, 
NUM_POLIZA																							AS POLIZA, 
CONVERT (DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU)))												AS F_OCU, 
CASE WHEN LTRIM(RTRIM(TIPO_STRO_LOCAL)) IS NULL THEN 'NA' ELSE LTRIM(RTRIM(TIPO_STRO_LOCAL)) END	AS TIPO_SINIESTRO,
SUM(0)																								AS PAGOS,
SUM(0)																								AS PAGOS_UF,
SUM(MONTO_NET_CLP)																					AS RESERVAS,
SUM(MONTO_NET_UF)																					AS RESERVAS_UF
FROM [SGF1034].[ACTUARIAL].DBO.PAGOS_RVAS 
WHERE 
	RAMO_RESERVA LIKE ('%SOAP%') AND CONCEPTO='RVA'
	AND CONVERT (DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_PR))) = @HASTA_SINIESTROS
GROUP BY 
SINIESTRO,EXPEDIENTE,NUM_POLIZA,
CONVERT (DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU))),	 
LTRIM(RTRIM(TIPO_STRO_LOCAL))


SET @TERMINO= GETDATE()
INSERT INTO CANAL_ASESOR.DBO.MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SOAP','3 DE 5',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()

drop table if exists SOAP_PAGOS_RESERVAS_FINAL

/*
DECLARE 
	@HASTA_SINIESTROS DATE = '2023-07-31',
	@DESDE_SINIESTROS DATE = '2018-01-31'
*/

SELECT 
X.PAGOS			AS PAGOS,
X.PAGOS_UF		AS PAGOS_UF,
X.RESERVAS		AS RESERVAS,
X.RESERVAS_UF	AS RESERVAS_UF,
X.SINIESTRO,
X.POLIZA,
X.TIPO_SINIESTRO,
X.CORRELATIVO_STRO,
1 AS CANTIDAD,
CASE WHEN X.SUMA_EVENTO >= 250 THEN 'EVENTO MAYOR' ELSE 'EVENTO MENOR' END AS TIPO_EVENTO,
X.PER
INTO SOAP_PAGOS_RESERVAS_FINAL
FROM (
	SELECT B.PER, A.SINIESTRO, A.POLIZA, A.TIPO_SINIESTRO,A.CORRELATIVO_STRO, SUM(A.PAGOS) PAGOS, SUM(A.PAGOS_UF) PAGOS_UF,
	SUM(A.RESERVAS) RESERVAS, SUM(A.RESERVAS_UF) RESERVAS_UF, SUM(A.PAGOS_UF + A.RESERVAS_UF) SUMA_EVENTO
	FROM #SOAP_PAGOS_RESERVAS A, (SELECT * FROM MI_PERIODO WHERE PER > @DESDE_SINIESTROS AND PER <= @HASTA_SINIESTROS) B
	WHERE A.F_OCU > B.PER_ANT AND A.F_OCU <= B.PER
	GROUP BY B.PER,B.PER_ANT,A.SINIESTRO,A.CORRELATIVO_STRO, A.POLIZA,A.TIPO_SINIESTRO
) X, SOAP_EXPUESTOS_FINAL C
WHERE C.PER = X.PER
AND C.POLIZA = X.POLIZA


-------------TIPO VEHICULO SOAP-------------
drop table if exists #SOAP_TIPVEH

SELECT DISTINCT POLIZA, max(B.TIPO_VEH) as TIPO_VEH
INTO #SOAP_TIPVEH
FROM SGF1034.ACTUARIAL.DBO.SOAP_BASE A
LEFT JOIN SGF1034.ACTUARIAL.DBO.AGRUP_VEHICULOS B
ON A.COD_VEHICULO=B.COD_VEH
group by POLIZA

select A.*,B.TIPO_VEH
into #SOAP_EXPUESTOS_FINAL
from SOAP_EXPUESTOS_FINAL A
left join #SOAP_TIPVEH B on
A.poliza = B.poliza


update #SOAP_EXPUESTOS_FINAL
set
	TIPO_VEH  = b.TIPO_VEHICULO
from #SOAP_EXPUESTOS_FINAL A
left join (SELECT DISTINCT POLIZA, TIPO_VEHICULO FROM [Transaccional].[dbo].[soap_ventas_taxi_minibus]) B on
A.poliza = B.poliza
WHERE B.poliza IS NOT NULL

drop table #SOAP_TIPVEH


ALTER TABLE #SOAP_EXPUESTOS_FINAL
ADD TIPO_VEH_NUEVO NVARCHAR(80) NULL

UPDATE #SOAP_EXPUESTOS_FINAL
SET
TIPO_VEH_NUEVO = B.DESCRIPCION
FROM #SOAP_EXPUESTOS_FINAL A
LEFT JOIN TRANSACCIONAL.DBO.SOAP_TIPO_VEHICULO B ON 
A.POLIZA = B.NNUMDOCU

---------------------------------------------



SET @TERMINO= GETDATE()
INSERT INTO CANAL_ASESOR.DBO.MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SOAP','4 DE 5',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()

-- CREA BASE DE TABLERO

drop table if exists #SOAP_TABLERO

SELECT
A.PER,
CASE WHEN A.COMUNA					IS NULL THEN 'NA'			ELSE A.COMUNA				END  AS COMUNA,
CASE WHEN A.TIPO_VEH				IS NULL THEN 'NA'			ELSE A.TIPO_VEH				END  AS TIPO,
CASE WHEN A.TIPO					IS NULL THEN 'NA'			ELSE A.TIPO					END  AS TIPO_SOL,
CASE WHEN A.TIPO_VEH_NUEVO			IS NULL THEN 'NA'			ELSE A.TIPO_VEH_NUEVO		END  AS TIPO_VEH_NUEVO,
CASE WHEN A.SUCURSAL				IS NULL THEN 'NA'			ELSE A.SUCURSAL				END  AS SUCURSAL,
CASE WHEN A.UNIDAD_NEGOCIO			IS NULL THEN 'NA'			ELSE A.UNIDAD_NEGOCIO		END  AS UNIDAD_NEGOCIO,
CASE WHEN A.GRUPO					IS NULL THEN 'NA'			ELSE A.GRUPO				END  AS GRUPO,
CASE WHEN A.CANAL					IS NULL THEN 'NA'			ELSE A.CANAL				END  AS CANAL,
CASE WHEN A.CORREDOR				IS NULL THEN 'NA'			ELSE A.CORREDOR				END  AS CORREDOR,
A.AÑO_CAMPAÑA								 											         AS AÑO_CAMPAÑA	,
A.MES_CAMPAÑA																					 AS MES_CAMPAÑA	,
CASE WHEN A.CONVENIO				IS NULL THEN 'SIN CONVENIO'	ELSE A.CONVENIO				END  AS CONVENIO,
RANGO_EDAD = CASE
	WHEN A.EDAD IS NULL THEN NULL
	WHEN A.EDAD BETWEEN 0 AND 17 THEN 'MENOR'
	WHEN A.EDAD BETWEEN 18 AND 25 THEN '<26'
	WHEN A.EDAD BETWEEN 36 AND 45 THEN '<46' 
	WHEN A.EDAD BETWEEN 46 AND 55 THEN '<56' 
	WHEN A.EDAD BETWEEN 56 AND 65 THEN '<66' 
	WHEN A.EDAD BETWEEN 66 AND 75 THEN '<76'
	ELSE '>=76' END,
CASE WHEN A.TIPO_VENTA				IS NULL THEN 'NA'			ELSE A.TIPO_VENTA			END  AS TIPO_VENTA,
CASE WHEN A.FORMA_PAGO				IS NULL THEN 'NA'			ELSE A.FORMA_PAGO			END  AS FORMA_PAGO,
SUM(CASE WHEN A.PRIMA_GANADA		IS NULL THEN 0				ELSE A.PRIMA_GANADA			END) AS PRIMA_GANADA, 
SUM(CASE WHEN A.PRIMA_SUSCRITA		IS NULL THEN 0				ELSE A.PRIMA_SUSCRITA		END) AS PRIMA_SUSCRITA, 
SUM(CASE WHEN A.EXPUESTOS			IS NULL THEN 0				ELSE A.EXPUESTOS			END) AS EXPUESTOS, 
SUM(CASE WHEN A.VIGENTES			IS NULL THEN 0				ELSE A.VIGENTES				END) AS VIGENTES,
SUM(CASE WHEN A.INICIAN				IS NULL THEN 0				ELSE A.INICIAN				END) AS INICIAN,
SUM(CASE WHEN B.PAGOS				IS NULL THEN 0				ELSE B.PAGOS				END) AS PAGOS, 
SUM(CASE WHEN B.RESERVAS			IS NULL THEN 0				ELSE B.RESERVAS				END) AS RESERVAS, 
SUM(CASE WHEN B.CANTIDAD			IS NULL THEN 0				ELSE B.CANTIDAD				END) AS CANTIDAD,
CASE WHEN B.TIPO_SINIESTRO			IS NULL THEN 'NA'			ELSE B.TIPO_SINIESTRO		END	 AS TIPO_SINIESTRO,
CASE WHEN B.TIPO_EVENTO				IS NULL THEN 'NA'			ELSE B.TIPO_EVENTO			END	 AS TIPO_EVENTO
INTO #SOAP_TABLERO
FROM #SOAP_EXPUESTOS_FINAL AS A FULL OUTER JOIN SOAP_PAGOS_RESERVAS_FINAL AS B
ON A.PER = B.PER AND A.POLIZA=B.POLIZA
GROUP BY A.PER,
A.COMUNA,
A.TIPO_VEH,
A.TIPO,
A.TIPO_VEH_NUEVO,
A.SUCURSAL,
A.UNIDAD_NEGOCIO,
A.GRUPO,
A.CANAL,
A.CORREDOR,
A.AÑO_CAMPAÑA,
A.MES_CAMPAÑA,
A.CONVENIO,
A.EDAD,
A.TIPO_VENTA,
A.FORMA_PAGO,
B.TIPO_SINIESTRO,
B.TIPO_EVENTO

DROP TABLE IF EXISTS SOAP_TABLERO_BKP
SELECT * INTO SOAP_TABLERO_BKP FROM #SOAP_TABLERO

drop table if exists #SOAP_EXPUESTOS_FINAL

--select count(*) from #SOAP_TABLERO

SET @TERMINO= GETDATE()
INSERT INTO CANAL_ASESOR.DBO.MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SOAP','5 DE 5',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()

/*
DECLARE 
	@HASTA_EXPUESTOS DATE = '2023-07-31',
	@DESDE_EXPUESTOS DATE = '2018-01-31'
*/

SELECT * INTO #QMAX FROM PROCESOS.DBO.BASE_PERIODOS_TRIMESTRALES_QUARTER WHERE @HASTA_EXPUESTOS BETWEEN FECHA_DESDE AND FECHA_HASTA

---select * from #QMAX

DROP TABLE IF EXISTS MI_SOAP_TABLERO_SALIDA
--TRUNCATE TABLE	MI_SOAP_TABLERO_SALIDA
--INSERT INTO		MI_SOAP_TABLERO_SALIDA
SELECT  
B.QUARTER				AS TRIM,
A.COMUNA,
A.TIPO,
A.TIPO_SOL,
A.TIPO_VEH_NUEVO,
A.SUCURSAL,
A.UNIDAD_NEGOCIO,
A.GRUPO,
A.CANAL,
A.CORREDOR,
A.AÑO_CAMPAÑA,
A.MES_CAMPAÑA,
A.RANGO_EDAD,
A.CONVENIO,
A.TIPO_VENTA,
A.FORMA_PAGO,
SUM(A.PRIMA_GANADA)			AS PRIMA_GANADA, 
SUM(A.PRIMA_SUSCRITA)		AS PRIMA_SUSCRITA,
SUM(A.EXPUESTOS)			AS EXPUESTOS,
SUM(A.VIGENTES) 			AS VIGENTES,
SUM(A.INICIAN)	 			AS INICIAN,
SUM(A.PAGOS)				AS PAGOS, 
SUM(A.RESERVAS)				AS RESERVAS, 
SUM(A.CANTIDAD)				AS CANTIDAD,
A.TIPO_SINIESTRO,
A.TIPO_EVENTO
INTO MI_SOAP_TABLERO_SALIDA
FROM #SOAP_TABLERO AS A 
RIGHT JOIN (SELECT TOP 12 Y.FECHA_DESDE, Y.FECHA_HASTA, Y.QUARTER FROM PROCESOS.DBO.BASE_PERIODOS_TRIMESTRALES_QUARTER AS Y, #QMAX AS X WHERE Y.FECHA_HASTA <= X.FECHA_HASTA ORDER BY 1 DESC) B  
ON A.PER BETWEEN B.FECHA_DESDE AND B.FECHA_HASTA
GROUP BY
B.QUARTER,
A.COMUNA,
A.TIPO,
A.TIPO_SOL,
A.TIPO_VEH_NUEVO,
A.SUCURSAL,
A.UNIDAD_NEGOCIO,
A.GRUPO,
A.CANAL,
A.CORREDOR,
A.AÑO_CAMPAÑA,
A.MES_CAMPAÑA,
A.CONVENIO,
A.RANGO_EDAD,
A.TIPO_VENTA,
A.FORMA_PAGO,
A.TIPO_SINIESTRO,
A.TIPO_EVENTO

/*
TRUNCATE TABLE	REPORTES.DBO.MI_SOAP_TABLERO_SALIDA
INSERT INTO		REPORTES.DBO.MI_SOAP_TABLERO_SALIDA
SELECT * FROM	MI_SOAP_TABLERO_SALIDA*/
DROP TABLE IF EXISTS REPORTES.DBO.MI_SOAP_TABLERO_SALIDA
SELECT * INTO REPORTES.DBO.MI_SOAP_TABLERO_SALIDA FROM MI_SOAP_TABLERO_SALIDA


SET @TERMINO= GETDATE()
INSERT INTO CANAL_ASESOR.DBO.MOVILIDAD_CONTROL_DE_EJECUCION VALUES ('SOAP','FIN',@TERMINO,DATEDIFF(MINUTE,@PASOS,@TERMINO)/60,DATEDIFF(MINUTE,@PASOS,@TERMINO)%60)
SET @PASOS= GETDATE()


END

--Validacion
/*
select 
	[TRIM], 
	sum(pagos) as pagos, 
	sum(reservas) AS reservas,
	sum(cantidad) AS cantidad, 
	sum(pagos + reservas) AS M_SINIESTROS
from REPORTES.DBO.MI_SOAP_TABLERO_SALIDA
group by [trim]
order by [trim] desc
*/




