USE [Transaccional]
GO
/****** Object:  StoredProcedure [dbo].[SP_MI_TRANSACCIONAL_MOTOR_03]    Script Date: 14-10-2025 10:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

----- exec [dbo].[SP_MI_TRANSACCIONAL_MOTOR_03]

ALTER  PROCEDURE [dbo].[SP_MI_TRANSACCIONAL_MOTOR_03]
AS
DECLARE @CONSULTA_COMERCIAL	AS NVARCHAR(4000)	
		
BEGIN

TRUNCATE TABLE MI_PRODUCCION_PER_COM

INSERT INTO MI_PRODUCCION_PER_COM
SELECT NNUMDOCU, NNUMITEM, NNURUPRO , '' AS CESTPOLI, '0' AS NNUDOANT, RAMO, '0' AS CNOMPRO, NFEINVIG, FECTEVIG_REAL,FECHA_CANCELACION, NFETEVIG, SUM(GWP_UF) AS GWP_UF1, ROUND(SUM(COM_UF),2) AS COM_UF1, NPLAN, PLAN_TECNICO AS NOM_PLANCOMERC, NFECEMIS AS NFECEMIS2, '' AS CCODIUSU, 
'' AS NRELDOCU, '' AS CCODMOEN, '' AS CDESELEM, NNURUINT AS NNUMRUT, NOMBRE_CORREDOR AS CNOCOPER, '0' AS L_NEGOCIO, LINEA_NEGOCIO, '' AS CCODLNRO, '' AS CDESELEM01, MARCA_VEH AS CCOMAVEH, MODELO_VEH AS NCOMOVEH, '' AS NCOTIVEC,
 MODELO_VEH AS CDESCORT, AÑO_FABR_VEH AS NANFAVEH, COD_USO_VEH AS CUSOVEHI, '' AS CDESELEM02, SUCURSAL AS CCODSUCU, NPLANTEC, PLAN_TECNICO AS CDESCRIP, '' AS CEXTENSI, PATENTE_VEH AS CNUMPATE, MIN(NPECOSUS) AS NPECOSU,
COMUNA_ASEGURADO AS COMUNA, PROVINCIA_ASEGURADO AS PROVINCIA, NNURUEJC, '' AS CNOCOPER02, '' AS CCODMONE, SUM(GWP_UF) AS DPRINEUF, '0' AS IND_CANCELACION, '0' AS IND_UNICO, IND_REN AS IND_RENOVACION, 
SUM(GWP_UF) AS PRIMA_EMITIDA, '0' AS PRIMA_PERIODO, '0' AS PRIMA_DIARIA, NFETEVIG AS FECFINVIG
, (YEAR([NFECEMIS])*100+MONTH([NFECEMIS])) AS FEMISAUX, REPLACE(CONVERT(CHAR(8),NNURUINT) + '-' + CONVERT(CHAR(4),NPLANTEC) + '-' + LINEA_NEGOCIO,' ','') AS COD_PLAN_TEC, 'USO NO PERSONAL' AS USO,SUM(GWP_CLP),SUM(COM_CLP),PRORROGA
FROM MI_BASE_EMISION_FUSION
GROUP BY NNUMDOCU, NNUMITEM, NNURUTASE,NNURUPRO, RAMO,  NFEINVIG, FECTEVIG_REAL,FECHA_CANCELACION, NFETEVIG, NPLAN, PLAN_TECNICO, NFECEMIS, 
NNURUINT, NOMBRE_CORREDOR, LINEA_NEGOCIO, MARCA_VEH, MODELO_VEH, AÑO_FABR_VEH, COD_USO_VEH, SUCURSAL, NPLANTEC, PLAN_TECNICO,PATENTE_VEH, COMUNA_ASEGURADO, PROVINCIA_ASEGURADO,NNURUEJC, IND_REN, 
NFETEVIG, (YEAR([NFECEMIS])*100+MONTH([NFECEMIS])), REPLACE(CONVERT(CHAR(8),NNURUINT) + '-' + CONVERT(CHAR(4),NPLANTEC) + '-' + LINEA_NEGOCIO,' ',''),PRORROGA

--IDENTIFICAR REGISTROS USO PERSONAL
UPDATE MI_PRODUCCION_PER_COM
SET USO='USO PERSONAL'
WHERE 
(LINEA_NEGOCIO='PERSONAL') OR (NNURUPRO<50000000 AND RAMO IN ('EE') AND LINEA_NEGOCIO='COMMERCIAL')


--PRODUCCION CON PLAN TECNICO
SELECT A.*,RTRIM(B.GRUPO)GRUPO,RTRIM(B.[BUSINESS UNIT])[BUSINESS UNIT],RTRIM(B.CHANNEL)CHANNEL,RTRIM(B.CORREDOR_AGRUP) CORREDOR_AGRUP
INTO      #PCCION_PLAN_TEC 
FROM MI_PRODUCCION_PER_COM A LEFT JOIN PROCESOS.DBO.BASE_PLANES_TECNICOS B ON A.COD_PLAN_TEC=B.CLAVE
WHERE A.LINEA_NEGOCIO='PERSONAL'

--ASIGNA TRAMO SISGEN
SELECT A.*, tramosis=0, tramo=0     --,CASE WHEN B.TRAMO IS NULL THEN 0 ELSE B.TRAMO END AS TRAMOSIS,CASE WHEN B.TRAMO IS NULL THEN 0 ELSE B.TRAMO END AS TRAMO
INTO #PRECARGA_PRODUCCION 
FROM #PCCION_PLAN_TEC A -- LEFT JOIN PROCESOS.DBO.BASE_AUX_SISGEN B ON A.FEMISAUX=B.MES_VIGENCIA AND A.NNURUPRO=B.NRUT 


--PRODUCCION CON PLAN TECNICO COMMERCIAL
SELECT A.*,RTRIM(B.GRUPO)GRUPO,RTRIM(B.[BUSINESS UNIT])[BUSINESS UNIT],RTRIM(B.CHANNEL)CHANNEL,RTRIM(B.CORREDOR_AGRUP) CORREDOR_AGRUP
INTO   #PCCION_PLAN_TEC_COMM 
FROM MI_PRODUCCION_PER_COM A LEFT JOIN PROCESOS.DBO.BASE_PLANES_TECNICOS B ON A.COD_PLAN_TEC=B.CLAVE
WHERE A.LINEA_NEGOCIO='COMMERCIAL'


--ANEXAR DATA COMMERCIAL A PRODUCCION
INSERT INTO #PRECARGA_PRODUCCION
SELECT *,'','' FROM #PCCION_PLAN_TEC_COMM 


TRUNCATE TABLE MI_PASO_PRODUCCION
INSERT INTO MI_PASO_PRODUCCION
SELECT
NNUMDOCU,NNUMITEM,NNURUPRO,CESTPOLI,NNUDOANT,RAMO,CNOMPRO,NFEINVIG,FECTEVIG_REAL,FECHA_CANCELACION,NFETEVIG,GWP_UF1,COM_UF1,NPLAN,NOM_PLANCOMERC,NFECEMIS2,CCODIUSU,NRELDOCU,CCODMOEN,
CDESELEM,NNUMRUT,CNOCOPER,L_NEGOCIO,LINEA_NEGOCIO,CCODLNRO,CDESELEM01,CCOMAVEH,NCOMOVEH,NCOTIVEC,CDESCORT,NANFAVEH,CUSOVEHI,CDESELEM02,CCODSUCU,NPLANTEC,CDESCRIP,CEXTENSI,CNUMPATE,NPECOSU,COMUNA,PROVINCIA,
NNURUEJC,CNOCOPER02,CCODMONE,DPRINEUF,'          'AS TIPO_PLAN,'   'DEDUCIBLE,0 AS IND_CANCELACION,IND_UNICO,IND_RENOVACION,PRIMA_EMITIDA,PRIMA_PERIODO,PRIMA_DIARIA,FECFINVIG,TRAMO,TRAMOSIS,CHANNEL,CORREDOR_AGRUP,GRUPO,"BUSINESS UNIT",USO,PRORROGA
FROM #PRECARGA_PRODUCCION

UPDATE MI_PASO_PRODUCCION
SET FECHA_CANCELACION=FECTEVIG_REAL
WHERE FECTEVIG_REAL>FECHA_CANCELACION

UPDATE MI_PASO_PRODUCCION
SET FECHA_CANCELACION=FECTEVIG_REAL
WHERE FECHA_CANCELACION IS NULL

SELECT NPLANTEC,DEDUCIBLE,RTRIM(TIPO_PLAN)TIPO_PLAN 
INTO  #PLANESTECNICOS 
FROM PROCESOS.DBO.BASE_PLANES_TECNICOS GROUP BY NPLANTEC,DEDUCIBLE,TIPO_PLAN ORDER BY 1 DESC

UPDATE MI_PASO_PRODUCCION
SET DEDUCIBLE=B.DEDUCIBLE,
TIPO_PLAN =B.TIPO_PLAN
FROM MI_PASO_PRODUCCION A, #PLANESTECNICOS B
WHERE A.NPLANTEC=B.NPLANTEC


-------------PRORROGA POR ITEM DIFERENTES
SELECT REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') AS LLAVE,
COUNT(*) AS CANTIDAD 
INTO #PRORROGA_POR_ITEM
FROM MI_PASO_PRODUCCION A 
WHERE PRORROGA=0 AND LINEA_NEGOCIO='PERSONAL' AND NFEINVIG >'2012-12-31' AND GWP_UF1<>0 AND DATEDIFF(DAY,NFEINVIG,FECTEVIG_REAL)>0
GROUP BY 
REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') HAVING 
COUNT(*)>1 AND REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')IS NOT NULL ORDER BY 2 DESC

/*
--OPTIMIZACION (PENDIENTE VALIDAR)
declare @prorroga int = 1

WHILE @prorroga <= 8
BEGIN
	UPDATE MI_PASO_PRODUCCION
		SET PRORROGA=@prorroga
	FROM MI_PASO_PRODUCCION R,
	(
		SELECT REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') AS LLAVE,MIN(FECFINVIG) FECFINVIG
		FROM MI_PASO_PRODUCCION A,#PRORROGA_POR_ITEM B
		WHERE REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=B.LLAVE 
		AND A.PRORROGA =@prorroga-1
		GROUP BY REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')
	) X
	WHERE REPLACE(CONVERT(CHAR(9),R.NNURUPRO)+CONVERT(CHAR(7),R.NNUMDOCU)+R.CCOMAVEH+CONVERT(CHAR(7),R.NCOMOVEH)+CONVERT(CHAR(4),R.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=X.LLAVE 
	AND R.PRORROGA=0 AND DATEDIFF(DAY,R.NFEINVIG,X.FECFINVIG) IN (1,0,-1)

	set @prorroga = @prorroga+1
END*/

UPDATE MI_PASO_PRODUCCION
SET PRORROGA=1
FROM MI_PASO_PRODUCCION R,
(SELECT REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') AS LLAVE,MIN(FECFINVIG)FECFINVIG
FROM MI_PASO_PRODUCCION A,#PRORROGA_POR_ITEM B
WHERE REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=B.LLAVE 
AND A.PRORROGA =0
GROUP BY REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ',''))X
WHERE REPLACE(CONVERT(CHAR(9),R.NNURUPRO)+CONVERT(CHAR(7),R.NNUMDOCU)+R.CCOMAVEH+CONVERT(CHAR(7),R.NCOMOVEH)+CONVERT(CHAR(4),R.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=X.LLAVE 
AND R.PRORROGA=0 AND DATEDIFF(DAY,R.NFEINVIG,X.FECFINVIG) IN (1,0,-1)




UPDATE MI_PASO_PRODUCCION
SET PRORROGA=2
FROM MI_PASO_PRODUCCION R,
(SELECT REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') AS LLAVE,MIN(FECFINVIG)FECFINVIG
FROM MI_PASO_PRODUCCION A,#PRORROGA_POR_ITEM B
WHERE REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=B.LLAVE 
AND A.PRORROGA =1
GROUP BY REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ',''))X
WHERE REPLACE(CONVERT(CHAR(9),R.NNURUPRO)+CONVERT(CHAR(7),R.NNUMDOCU)+R.CCOMAVEH+CONVERT(CHAR(7),R.NCOMOVEH)+CONVERT(CHAR(4),R.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=X.LLAVE 
AND R.PRORROGA=0 AND DATEDIFF(DAY,R.NFEINVIG,X.FECFINVIG) IN (1,0,-1)


UPDATE MI_PASO_PRODUCCION
SET PRORROGA=3
FROM MI_PASO_PRODUCCION R,
(SELECT REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') AS LLAVE,MIN(FECFINVIG)FECFINVIG
FROM MI_PASO_PRODUCCION A,#PRORROGA_POR_ITEM B
WHERE REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=B.LLAVE 
AND A.PRORROGA=2
GROUP BY REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ',''))X
WHERE REPLACE(CONVERT(CHAR(9),R.NNURUPRO)+CONVERT(CHAR(7),R.NNUMDOCU)+R.CCOMAVEH+CONVERT(CHAR(7),R.NCOMOVEH)+CONVERT(CHAR(4),R.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=X.LLAVE 
AND R.PRORROGA=0 AND DATEDIFF(DAY,R.NFEINVIG,X.FECFINVIG) IN (1,0,-1)


UPDATE MI_PASO_PRODUCCION
SET PRORROGA=4
FROM MI_PASO_PRODUCCION R,
(SELECT REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') AS LLAVE,MIN(FECFINVIG)FECFINVIG
FROM MI_PASO_PRODUCCION A,#PRORROGA_POR_ITEM B
WHERE REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=B.LLAVE 
AND A.PRORROGA=3
GROUP BY REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ',''))X
WHERE REPLACE(CONVERT(CHAR(9),R.NNURUPRO)+CONVERT(CHAR(7),R.NNUMDOCU)+R.CCOMAVEH+CONVERT(CHAR(7),R.NCOMOVEH)+CONVERT(CHAR(4),R.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=X.LLAVE 
AND R.PRORROGA=0 AND DATEDIFF(DAY,R.NFEINVIG,X.FECFINVIG) IN (1,0,-1)


UPDATE MI_PASO_PRODUCCION
SET PRORROGA=5
FROM MI_PASO_PRODUCCION R,
(SELECT REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') AS LLAVE,MIN(FECFINVIG)FECFINVIG
FROM MI_PASO_PRODUCCION A,#PRORROGA_POR_ITEM B
WHERE REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=B.LLAVE 
AND A.PRORROGA=4
GROUP BY REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ',''))X
WHERE REPLACE(CONVERT(CHAR(9),R.NNURUPRO)+CONVERT(CHAR(7),R.NNUMDOCU)+R.CCOMAVEH+CONVERT(CHAR(7),R.NCOMOVEH)+CONVERT(CHAR(4),R.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=X.LLAVE 
AND R.PRORROGA=0 AND DATEDIFF(DAY,R.NFEINVIG,X.FECFINVIG) IN (1,0,-1)

UPDATE MI_PASO_PRODUCCION
SET PRORROGA=6
FROM MI_PASO_PRODUCCION R,
(SELECT REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') AS LLAVE,MIN(FECFINVIG)FECFINVIG
FROM MI_PASO_PRODUCCION A,#PRORROGA_POR_ITEM B
WHERE REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=B.LLAVE 
AND A.PRORROGA=5
GROUP BY REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ',''))X
WHERE REPLACE(CONVERT(CHAR(9),R.NNURUPRO)+CONVERT(CHAR(7),R.NNUMDOCU)+R.CCOMAVEH+CONVERT(CHAR(7),R.NCOMOVEH)+CONVERT(CHAR(4),R.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=X.LLAVE 
AND R.PRORROGA=0 AND DATEDIFF(DAY,R.NFEINVIG,X.FECFINVIG) IN (1,0,-1)

UPDATE MI_PASO_PRODUCCION
SET PRORROGA=7
FROM MI_PASO_PRODUCCION R,
(SELECT REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') AS LLAVE,MIN(FECFINVIG)FECFINVIG
FROM MI_PASO_PRODUCCION A,#PRORROGA_POR_ITEM B
WHERE REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=B.LLAVE 
AND A.PRORROGA=6
GROUP BY REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ',''))X
WHERE REPLACE(CONVERT(CHAR(9),R.NNURUPRO)+CONVERT(CHAR(7),R.NNUMDOCU)+R.CCOMAVEH+CONVERT(CHAR(7),R.NCOMOVEH)+CONVERT(CHAR(4),R.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=X.LLAVE 
AND R.PRORROGA=0 AND DATEDIFF(DAY,R.NFEINVIG,X.FECFINVIG) IN (1,0,-1)


UPDATE MI_PASO_PRODUCCION
SET PRORROGA=8
FROM MI_PASO_PRODUCCION R,
(SELECT REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') AS LLAVE,MIN(FECFINVIG)FECFINVIG
FROM MI_PASO_PRODUCCION A,#PRORROGA_POR_ITEM B
WHERE REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=B.LLAVE 
AND A.PRORROGA=7
GROUP BY REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+CONVERT(CHAR(7),A.NNUMDOCU)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),A.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ',''))X
WHERE REPLACE(CONVERT(CHAR(9),R.NNURUPRO)+CONVERT(CHAR(7),R.NNUMDOCU)+R.CCOMAVEH+CONVERT(CHAR(7),R.NCOMOVEH)+CONVERT(CHAR(4),R.NANFAVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')=X.LLAVE 
AND R.PRORROGA=0 AND DATEDIFF(DAY,R.NFEINVIG,X.FECFINVIG) IN (1,0,-1)

------------------------------------------------------------------------------------------------


END

