USE [Transaccional]
GO
/****** Object:  StoredProcedure [dbo].[SP_MI_TRANSACCIONAL_MOTOR_04]    Script Date: 14-10-2025 10:24:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- PROCESO QUE GENERA MI_PRIMA_EMITIDA_ACCESS

ALTER  PROCEDURE [dbo].[SP_MI_TRANSACCIONAL_MOTOR_04]
AS
DECLARE @CONSULTA_COMERCIAL       AS NVARCHAR(4000)   
              
BEGIN

-- exec [SP_MI_TRANSACCIONAL_MOTOR_04]

-- TABLA PARA MONITOREAR EL AVANCE DEL PROCESO (ABARCA PROCESOS 00, 01, 02 y 04)
-- SELECT * FROM AUX_MOTOR_00_CHECKPOINTS

--DATOS CLIENTE 

TRUNCATE TABLE MI_RATING_FACTORS_NEW
TRUNCATE TABLE MI_PRIMA_EMITIDA_PERSONAL
TRUNCATE TABLE MI_PRIMA_EMITIDA_COMME_NEW
TRUNCATE TABLE PROCESOS.DBO.BASE_LIVIANO
TRUNCATE TABLE PROCESOS.DBO.BASE_PESADO
TRUNCATE TABLE MI_PRIMA_EMITIDA_COMMERCIAL_NEW
TRUNCATE TABLE MI_PRIMA_EMITIDA
TRUNCATE TABLE MI_PRIMA_EMITIDA_ACCESS

/****** Checkpoint Inicio ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('PROCESO 04 INICIADO', SYSDATETIME())
/*********************************************************************************/

TRUNCATE TABLE MI_POLIZA_ANTERIOR
DECLARE @CONSULTA_P_ANT    AS NVARCHAR(4000)           
SET @CONSULTA_P_ANT =             
              
'SELECT * FROM OPENQUERY(SOL,''
SELECT NNUMDOCU,NNUDOANT FROM  RSASOLDB2.SUACSPOL WHERE CCODTNRO <> ''''17374    00'''' 
AND CCODRAMO IN (''''EE'''', ''''ET'''', ''''EL'''', ''''AE'''', ''''EP'''', ''''AV'''', ''''EA'''', ''''EC'''') 
AND SUBSTR(CHAR(NFECEMIS),1,4)>2015 '')'
INSERT INTO  MI_POLIZA_ANTERIOR
EXEC SP_EXECUTESQL @CONSULTA_P_ANT

DELETE FROM MI_POLIZA_ANTERIOR WHERE NNUMDOCU<0
DELETE FROM MI_POLIZA_ANTERIOR WHERE NNUDOANT=0

SELECT DISTINCT * INTO #PASO FROM MI_POLIZA_ANTERIOR 

TRUNCATE TABLE MI_POLIZA_ANTERIOR
INSERT INTO MI_POLIZA_ANTERIOR
SELECT * FROM #PASO

UPDATE MI_PASO_PRODUCCION
SET NNUDOANT=B.NNUDOANT
FROM MI_PASO_PRODUCCION A, MI_POLIZA_ANTERIOR B
WHERE A.NNUMDOCU=B.NNUMDOCU


/****** Checkpoint 1 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 04-1', SYSDATETIME())
/****************************************************************************/


SELECT REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') AS LLAVE,
COUNT(*) AS CANTIDAD ,NFETEVIG,CNUMPATE
INTO #LLAVE_RENOVACION
FROM MI_PASO_PRODUCCION A 
WHERE NFEINVIG >'2015-12-31' AND GWP_UF1<>0 AND DATEDIFF(DAY,NFEINVIG,FECTEVIG_REAL)>0
GROUP BY 
REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),NPLANTEC),' ',''),NFETEVIG,CNUMPATE HAVING 
REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),NPLANTEC),' ','')IS NOT NULL ORDER BY 2 DESC

UPDATE MI_PASO_PRODUCCION
SET IND_RENOVACION=1
FROM MI_PASO_PRODUCCION A, #LLAVE_RENOVACION B
WHERE  A.NFEINVIG >'2015-12-31' AND A.GWP_UF1<>0 AND DATEDIFF(DAY,A.NFEINVIG,A.FECTEVIG_REAL)>0 AND LINEA_NEGOCIO='PERSONAL' AND 
REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+A.CCOMAVEH+CONVERT(CHAR(7),A.NCOMOVEH)+CONVERT(CHAR(4),NPLANTEC),' ','') =B.LLAVE AND
DATEDIFF(DAY,A.NFEINVIG,B.NFETEVIG ) <= ABS(3) AND IND_RENOVACION = 0



--MARCA RENOVACION PARA SANTANDER 

SELECT CNUMPATE,NNURUPRO,COUNT(*)CANTIDAD INTO #SANTANDER_PASO FROM MI_PASO_PRODUCCION WHERE CHANNEL LIKE ('%SANTANDER%') GROUP BY CNUMPATE,NNURUPRO
HAVING COUNT(*)>1

UPDATE MI_PASO_PRODUCCION
SET IND_RENOVACION=1
FROM MI_PASO_PRODUCCION A, #SANTANDER_PASO B
WHERE A.CNUMPATE=B.CNUMPATE AND A.NNURUPRO=B.NNURUPRO AND A.CHANNEL LIKE('%SANTANDER%')


/*



------ INDICADOR DE RENOVACION POLIZAS MASIVAS



----MARCO LAS POLIZAS MASIVA CON INDICADOR DE RENOVACION EN 2
UPDATE MI_PASO_PRODUCCION
SET IND_RENOVACION=2
FROM MI_PASO_PRODUCCION A,(SELECT NNUMDOCU,COUNT(*)CANTIDAD FROM MI_PASO_PRODUCCION GROUP BY NNUMDOCU HAVING COUNT(*)>2 ) B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.PRORROGA=0


UPDATE MI_PASO_PRODUCCION                 
SET IND_RENOVACION=1
FROM MI_PASO_PRODUCCION A , (SELECT NNUMDOCU,REPLACE(CONVERT(CHAR(9),NNURUPRO)+CCOMAVEH+NCOMOVEH+CONVERT(CHAR(4),NANFAVEH),' ','')LLAVE FROM MI_PASO_PRODUCCION 
WHERE IND_RENOVACION=2
GROUP BY NNUMDOCU,REPLACE(CONVERT(CHAR(9),NNURUPRO)+CCOMAVEH+NCOMOVEH+CONVERT(CHAR(4),NANFAVEH),' ','') ) B
WHERE A.IND_RENOVACION=2 AND A.PRORROGA=0 AND A.NNUDOANT=B.NNUMDOCU AND REPLACE(CONVERT(CHAR(9),A.NNURUPRO)+A.CCOMAVEH+A.NCOMOVEH+CONVERT(CHAR(4),A.NANFAVEH),' ','')=B.LLAVE

UPDATE MI_PASO_PRODUCCION
SET IND_RENOVACION=0
WHERE IND_RENOVACION=2


---INDICADOR REN ES 1 CUANDO PRORROGA ES MAYO A 0


*/



UPDATE MI_PASO_PRODUCCION
SET IND_RENOVACION=1
WHERE PRORROGA>0

UPDATE MI_PASO_PRODUCCION
SET IND_RENOVACION=1
WHERE NNUDOANT>0 AND LINEA_NEGOCIO='COMMERCIAL'

UPDATE MI_PASO_PRODUCCION -- POLIZAS NUEVAS MOK
SET IND_RENOVACION='0'
WHERE 
NNUMDOCU IN (4417862,
4417856       ,
4417861       ,
4417869       ,
4471870       ,
4417827       ,
4417874       ,
4417866       ,
4830562       ,
4830557       ,
4830550       ,
4830548       ,
4829639       ,
4830643       ,
4830638       ,
4830644       ,
4830642)





UPDATE MI_PASO_PRODUCCION
SET 
	DEDUCIBLE=REPLACE(DEDUCIBLE,',','.'),
	IND_CANCELACION=0

UPDATE MI_PASO_PRODUCCION
SET DEDUCIBLE='0'
WHERE DEDUCIBLE='N/A'


UPDATE MI_PASO_PRODUCCION
SET FECTEVIG_REAL=B.PERIODO
FROM MI_PASO_PRODUCCION A ,MI_UPDATE_FECHA_SIN_POL B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA AND B.TERMINO=1

UPDATE MI_PASO_PRODUCCION
SET NFEINVIG=B.PERIODO
FROM MI_PASO_PRODUCCION A ,MI_UPDATE_FECHA_SIN_POL B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA AND B.INICIO=1



--INDICADOR DE CANCELACION POLIZAS UN ITEM
UPDATE MI_PASO_PRODUCCION
SET IND_CANCELACION=1
FROM MI_PASO_PRODUCCION A, MI_TER_VIG_REAL B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM =B.NNUMITEM AND B.ESTADO IN ('1106AN   00','1106CA   00')
AND B.FECEMIS BETWEEN CONVERT(INT,CONVERT(CHAR(4),YEAR(A.NFEINVIG)) + RIGHT('00'+REPLACE(CONVERT(CHAR(2),MONTH(A.NFEINVIG)),' ',''),2) + RIGHT('00'+REPLACE(CONVERT(CHAR(2),DAY(A.NFEINVIG)),' ',''),2)) 
AND  CONVERT(INT,CONVERT(CHAR(4),YEAR(A.NFETEVIG)) + RIGHT('00'+REPLACE(CONVERT(CHAR(2),MONTH(A.NFETEVIG)),' ',''),2) + RIGHT('00'+REPLACE(CONVERT(CHAR(2),DAY(A.NFETEVIG)),' ',''),2))


UPDATE MI_PASO_PRODUCCION 
SET IND_CANCELACION=1
FROM MI_PASO_PRODUCCION A, MI_POLIZAS_PRORROGADAS_2 B
WHERE A.NNUMDOCU=B.POLIZA AND A.NNUMITEM=B.ITEM AND A.PRORROGA=B.PRORROGA AND  B.CCODMOEN  IN ('0036D01  00','0036D02  00','0036D10  00','0036I03  00','0036I35  00','0036D61  00')



--INDICADOR DE CANCELACION POLIZAS CAON MAS DE UN ITEM
UPDATE MI_PASO_PRODUCCION
SET IND_CANCELACION=1
FROM MI_PASO_PRODUCCION A, (SELECT * FROM MI_POL_CANCELADA_MASIVA WHERE NNUMDOCU NOT IN (SELECT NNUMDOCU FROM  MI_PASO_PRODUCCION WHERE IND_CANCELACION=1 GROUP BY NNUMDOCU HAVING SUM(PRORROGA)>0 ) ) B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM =B.NNUMITEM AND B.ESTADO='B' 
AND B.NFEINVIG BETWEEN CONVERT(INT,CONVERT(CHAR(4),YEAR(A.NFEINVIG)) + RIGHT('00'+REPLACE(CONVERT(CHAR(2),MONTH(A.NFEINVIG)),' ',''),2) + RIGHT('00'+REPLACE(CONVERT(CHAR(2),DAY(A.NFEINVIG)),' ',''),2)) 
AND  CONVERT(INT,CONVERT(CHAR(4),YEAR(A.NFETEVIG)) + RIGHT('00'+REPLACE(CONVERT(CHAR(2),MONTH(A.NFETEVIG)),' ',''),2) + RIGHT('00'+REPLACE(CONVERT(CHAR(2),DAY(A.NFETEVIG)),' ',''),2))


--INDICADOR DE CANCELACION POR FECHA REAL
UPDATE MI_PASO_PRODUCCION
SET  IND_CANCELACION =1
FROM MI_PASO_PRODUCCION
WHERE FECTEVIG_REAL < NFETEVIG AND 
IND_CANCELACION=0


UPDATE MI_PASO_PRODUCCION 
SET GWP_UF1=0 , PRIMA_EMITIDA=0
WHERE  
	(GWP_UF1 <0 AND GWP_UF1> -0.09) OR
	(GWP_UF1 <0 AND IND_CANCELACION=1) OR
	(GWP_UF1 <0 AND NFEINVIG <='2010-12-31')


--SELECT IND_CANCELACION,* FROM MI_PASO_PRODUCCION WHERE GWP_UF1<0 AND NFEINVIG >'31-12-2011'ORDER BY NFEINVIG DESC

/****** Checkpoint 2 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 04-2', SYSDATETIME())
/****************************************************************************/


TRUNCATE TABLE MI_RATING_FACTORS_NEW
INSERT INTO   MI_RATING_FACTORS_NEW
SELECT *,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL  FROM MI_PASO_PRODUCCION WHERE LINEA_NEGOCIO='PERSONAL'

--INSERTAR BANCO CHILE PYME
INSERT INTO   MI_RATING_FACTORS_NEW
SELECT *,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL  FROM MI_PASO_PRODUCCION WHERE NPLANTEC IN (4315,
4316,4317,4318,4319,4320,4321,4322,4323,4324,4429,4430,4431,4432,4433,4450,4451,4452,4453,4454,4870,4873,4874,4875,5183,5184,5185,5186,5187) AND LINEA_NEGOCIO='COMMERCIAL'



-- Linea agregada para redefinir el Corredor Agrupado del segmento Banco Chile PYME. (06-06-2019 @Nicolas Mazzocchi)
UPDATE MI_RATING_FACTORS_NEW
SET CORREDOR_AGRUP = 'BANCO CHILE PYME' WHERE CHANNEL = 'BANCO CHILE' AND LINEA_NEGOCIO = 'Commercial'

/****** Checkpoint 3 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 04-3', SYSDATETIME())
/****************************************************************************/
------------------------------------------------------------------------------------------------------------------------------------------------------

--SELECT NNUMRUT,CNOCOPER,NFECNACI,CINDSEXO INTO #CLIENTE FROM  [SOL].[S1031EBB].RSASOLDB2.TBACSMAE WHERE NFECNACI IS NOT NULL 
--SELECT * FROM CLIENTE_TEMP
DROP TABLE IF EXISTS CLIENTE_TEMP
SELECT * INTO CLIENTE_TEMP FROM OPENQUERY(SOL, 'SELECT NNUMRUT,CNOCOPER,NFECNACI,CINDSEXO FROM RSASOLDB2.TBACSMAE WHERE NFECNACI IS NOT NULL ')


DELETE FROM CLIENTE_TEMP WHERE NFECNACI=0

DELETE FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(10),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(10),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(10),NFECNACI),7,2) IN (
'1919-00-00','1197-04-16','1899-12-30','1900-00-00','1899-12-31','1900-01-00','1195-06-05','1793-06-17','1920-62-3 ','1891-06-26','1040-02-19','1198-01-01','1196-11-20','1498-06-25',
'1904-00-00','1410-19-94','1929-07-54','1190-01-01','1821-01-4 ','1910-41-5 ','1932-09-00','1067-03-27','1190-03-23','1891-03-16','1900-01-0 ','1909-98-28','1959-11-0 ','1953-09-0 ','1961-97-04',
'1960-31-3 ','1964-11-0 ','1963-08-0 ','1984-12-0 ','1979-08-0 ','1982-07-0 ','1980-07-0 ','1999-99-99','1997-41-3 ','2910-16-96','1969-12-0 ','9731-12-0 ','3106-19-90','9810-22-6 ','7612-04-  ')

DELETE FROM CLIENTE_TEMP WHERE CONVERT(INT,SUBSTRING(CONVERT(CHAR(10),NFECNACI),1,4))>=2000
DELETE FROM CLIENTE_TEMP WHERE CONVERT(INT,SUBSTRING(CONVERT(CHAR(10),NFECNACI),1,4))<=1910
DELETE FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(10),NFECNACI),7,2) IN ('1','2','6')

UPDATE CLIENTE_TEMP
SET CINDSEXO='' WHERE CINDSEXO  NOT IN ('M','F')

/****** Checkpoint 4 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 04-4', SYSDATETIME())
/****************************************************************************/

--BORRAR LOS NNUMRUT QUE NO SIRVAN PARA NO TENER QUE APLICAR LA CONDICION A CONTINUACION
DELETE FROM CLIENTE_TEMP WHERE NNUMRUT IN (SELECT RUT_CLIENTE FROM PROCESOS.DBO.BASE_AUX_CLIENTE)


INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (1) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=31
--FROM CLIENTE_TEMP WHERE NNUMRUT NOT IN (SELECT RUT_CLIENTE FROM PROCESOS.DBO.BASE_AUX_CLIENTE) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (1)  AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=31
--CONDICION PREVIA

INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (2) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=29

INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (3) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=31

INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (4) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=30

INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (5) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=31

INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (6) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=30

INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (7) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=31

INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (8) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=31

INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (9) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=30

INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (10) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=31

INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (11) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=30

INSERT INTO PROCESOS.DBO.BASE_AUX_CLIENTE
SELECT NNUMRUT,CNOCOPER,CONVERT(DATE,SUBSTRING(CONVERT(CHAR(8),NFECNACI),1,4)+'-'+SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2)+'-'+ SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)),CINDSEXO,NULL 
FROM CLIENTE_TEMP WHERE SUBSTRING(CONVERT(CHAR(8),NFECNACI),5,2) IN (12) AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)>=1 AND SUBSTRING(CONVERT(CHAR(8),NFECNACI),7,2)<=31

DROP TABLE CLIENTE_TEMP


/****** Checkpoint 5 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 04-5', SYSDATETIME())
/****************************************************************************/

UPDATE MI_RATING_FACTORS_NEW
SET FNAC=B.FEC_NACIMENTO, SEXO=B.SEXO
FROM MI_RATING_FACTORS_NEW A, PROCESOS.DBO.BASE_AUX_CLIENTE B
WHERE 
A.NNURUPRO=B.RUT_CLIENTE

UPDATE MI_RATING_FACTORS_NEW
SET FNAC =  '1900-01-01'
FROM MI_RATING_FACTORS_NEW
WHERE 
FNAC IS NULL



UPDATE MI_RATING_FACTORS_NEW
SET SEXO =  'UNKNOWN'
FROM MI_RATING_FACTORS_NEW
WHERE 
SEXO NOT IN ('M','F') OR SEXO IS NULL

UPDATE MI_RATING_FACTORS_NEW
SET ANTVEH =  CASE WHEN (CONVERT(INT,YEAR(NFEINVIG))-NANFAVEH) <0 THEN '0' ELSE 
                                   CASE WHEN (CONVERT(INT,YEAR(NFEINVIG))-NANFAVEH)>53 THEN 'UNKNOWN' ELSE 
                                          CONVERT(VARCHAR(6),(CONVERT(INT,YEAR(NFEINVIG))-NANFAVEH)) 
                                   END 
                            END 

UPDATE MI_RATING_FACTORS_NEW
SET 
TOP100_2019=SUBSTRING(B.TOP_100_PERSONAL,1,30), 
TIPO_VEHICULO=SUBSTRING(B.TIPO_PERSONAL,1,30),
SUMA_ASEGURADA=SUBSTRING(B.SA,1,30), 
NEW_SA=SUBSTRING(B.RANGO,1,30)
FROM MI_RATING_FACTORS_NEW A, PROCESOS.DBO.BASE_AUXILIAR_MARCA_MODELO B
WHERE 
REPLACE(A.CCOMAVEH,' ','')=REPLACE(CONVERT(CHAR(40),B.CCOMAVEH),' ','') AND REPLACE(A.CDESCORT,' ','')=REPLACE(CONVERT(CHAR(40),B.CDESCORT),' ','')


UPDATE PROCESOS.DBO.BASE_AUXILIAR_MARCA_MODELO
SET RANGO=REPLACE(SUBSTRING(RANGO,1,30), ',','.')


UPDATE MI_RATING_FACTORS_NEW
SET TIPO_VEHICULO=B.TIPO_VEH_RVM 
FROM MI_RATING_FACTORS_NEW A, MI_BASE_TIPO_VEH_RVM_MP B
WHERE A.CCOMAVEH=B.CCOMAVEH AND A.CDESCORT=B.CDESCORT
AND A.TIPO_VEHICULO IS NULL


UPDATE MI_RATING_FACTORS_NEW
SET TOP100_2019 =  'NO INFORMADO'
FROM MI_RATING_FACTORS_NEW
WHERE 
TOP100_2019 IS NULL

UPDATE MI_RATING_FACTORS_NEW
SET TIPO_VEHICULO =  'UNKNOWN'
FROM MI_RATING_FACTORS_NEW
WHERE 
TIPO_VEHICULO IS NULL

UPDATE MI_RATING_FACTORS_NEW
SET SUMA_ASEGURADA =  'UNKNOWN'
FROM MI_RATING_FACTORS_NEW
WHERE 
SUMA_ASEGURADA IS NULL

UPDATE MI_RATING_FACTORS_NEW
SET NEW_SA =  'UNKNOWN'
FROM MI_RATING_FACTORS_NEW
WHERE 
NEW_SA IS NULL

UPDATE MI_RATING_FACTORS_NEW
SET DPRINETAP=GWP_UF1*B.UF,TCAMBIO=B.UF
FROM MI_RATING_FACTORS_NEW A, PROCESOS.DBO.BASE_SERIE_DIARIA_MONEDA B
WHERE 
A.NFECEMIS2=B.FECHA

/*
UPDATE MI_RATING_FACTORS_NEW
SET ZONA=B.GEO_PRICING_PERS
FROM MI_RATING_FACTORS_NEW A, (SELECT COMUNA,GEO_PRICING_PERS FROM PROCESOS.DBO.BASE_MAESTRO_COMUNAS_REGIONES_ZONAS
GROUP BY COMUNA,GEO_PRICING_PERS) B
WHERE 
 A.COMUNA COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS =B.COMUNA
*/


UPDATE MI_RATING_FACTORS_NEW
SET F_CI= CONVERT(DATE,DATEADD(MS,-3,DATEADD(MM,0,DATEADD(MM,DATEDIFF(MM,0,CONVERT(DATETIME,NFECEMIS2))+1,0))))


UPDATE MI_RATING_FACTORS_NEW
SET FNAC=B.FNAC
FROM MI_RATING_FACTORS_NEW A, PROCESOS.DBO.BASE_FNAC_APROX B
WHERE (FLOOR(A.NNURUPRO/1000000))*1000000=B.RANGO AND A.NNURUPRO<=26000000 AND A.FNAC='1900-01-01'



UPDATE MI_RATING_FACTORS_NEW
SET EDAD=CASE WHEN FNAC='1900-01-01' THEN NULL ELSE  
                     CASE WHEN DATEDIFF(YEAR,FNAC,NFECEMIS2) > 89 THEN 89 ELSE
                            CASE WHEN  DATEDIFF(YEAR,FNAC,NFECEMIS2) <18 THEN 18 ELSE
                                   DATEDIFF(YEAR,FNAC,NFECEMIS2) 
                            END
                     END
              END



UPDATE MI_RATING_FACTORS_NEW
SET EDAD='UNKNOWN' 
WHERE 
EDAD='999' OR EDAD IS NULL OR EDAD ='0'

UPDATE MI_RATING_FACTORS_NEW
SET SISNUM= B.NUM_SINI, SISUF=MTO_SINI
FROM MI_RATING_FACTORS_NEW A, PROCESOS.DBO.BASE_AUX_SISGEN_COD B
WHERE 
A.TRAMOSIS=B.TRAMOSIS

UPDATE PROCESOS.DBO.BASE_AUX_SISGEN_COD
SET MTO_SINI=REPLACE(MTO_SINI, ',','.')



UPDATE MI_RATING_FACTORS_NEW
SET SISNUM=3,SISUF='>= 100'
WHERE SISNUM IS NULL


UPDATE MI_RATING_FACTORS_NEW
SET DEDUCIBLE='0'
WHERE 
DEDUCIBLE ='N/A'

UPDATE MI_RATING_FACTORS_NEW
SET DEDUCIBLE='UNKNOWN'
WHERE 
DEDUCIBLE IS NULL



UPDATE MI_RATING_FACTORS_NEW
SET ANTVEH='UNKNOWN'
WHERE 
ANTVEH IS NULL

UPDATE MI_RATING_FACTORS_NEW
SET TOP100_2019='NO INFORMADO'
WHERE 
TOP100_2019 IS NULL OR TOP100_2019='0' OR TOP100_2019=''

UPDATE MI_RATING_FACTORS_NEW
SET IND_RENOVACION='0'
WHERE 
IND_RENOVACION IS NULL



UPDATE MI_RATING_FACTORS_NEW
SET SISUF='>= 100'
WHERE 
SISUF IS NULL OR SISUF ='0' OR SISUF=''

UPDATE MI_RATING_FACTORS_NEW
SET SUMA_ASEGURADA='UNKNOWN'
WHERE 
SUMA_ASEGURADA IS NULL OR SISUF ='0' OR SISUF=''

UPDATE MI_RATING_FACTORS_NEW
SET TIPO_VEHICULO='UNKNOWN'
WHERE 
TIPO_VEHICULO IS NULL OR SISUF ='0' OR SISUF=''

/*

UPDATE MI_RATING_FACTORS_NEW
SET ZONA= NULL 'UNKNOWN'
WHERE 
ZONA IS NULL OR SISUF ='0' OR SISUF=''
*/

UPDATE MI_RATING_FACTORS_NEW
SET ZONA=B.ZONA, REGIONES_URBES = B.REGIONES_URBES
FROM MI_RATING_FACTORS_NEW A , RM_LP_ZONAS B
WHERE A.COMUNA =B.COMUNA AND A.PROVINCIA=B.PROVINCIA

UPDATE MI_RATING_FACTORS_NEW
SET CHANNEL_TO_EMB=B.CHANNEL_TO_EMBLEM
FROM MI_RATING_FACTORS_NEW A , RM_LP_CHANNEL B
WHERE A.CHANNEL =B.CHANNEL AND A.BUSINESS_UNIT=B.BU


UPDATE MI_RATING_FACTORS_NEW
SET TOP100_2019=B.TOP100_2019
FROM MI_RATING_FACTORS_NEW A , RM_LP_TOP100_2019 B
WHERE A.CCOMAVEH =B.CCOMAVEH AND A.CDESCORT=B.CDESCORT




--SIN TOP100_2019 
--SELECT CCOMAVEH,CDESCORT,TOP100_2019
--FROM MI_RATING_FACTORS_NEW
--GROUP BY CCOMAVEH,CDESCORT,TOP100_2019
--HAVING TOP100_2019='NO INFORMADO'

/****** Checkpoint 6 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 04-6', SYSDATETIME())
/****************************************************************************/                 

----PERSITENCIA

SELECT 
YEAR(A.NFEINVIG) AS YR,
A.NNUMDOCU AS DOC_1, 
A.NNUMITEM AS ITEM_1, 
A.PRORROGA AS PRO_1, 
B.NNUMDOCU AS DOC_2, 
B.NNUMITEM AS ITEM_2, 
B.PRORROGA AS PRO_2
INTO #TMP_RENOV_BASE
FROM SGF1025.TRANSACCIONAL.DBO.MI_RATING_FACTORS_NEW AS A
JOIN SGF1025.TRANSACCIONAL.DBO.MI_RATING_FACTORS_NEW AS B ON A.NFEINVIG = B.FECTEVIG_REAL AND A.NNURUPRO = B.NNURUPRO AND A.CCOMAVEH = B.CCOMAVEH 
--AND A.CDESCORT = B.CDESCORT 
AND A.CNUMPATE= B.CNUMPATE
WHERE  CONVERT(NVARCHAR(10),A.NNUMDOCU)+'-'+CONVERT(NVARCHAR(10),A.NNUMITEM)+'-'+CONVERT(NVARCHAR(5),A.PRORROGA) <>CONVERT(NVARCHAR(10),B.NNUMDOCU)+'-'+CONVERT(NVARCHAR(10),B.NNUMITEM)+'-'+CONVERT(NVARCHAR(5),B.PRORROGA)
AND (A.NFEINVIG<>A.FECTEVIG_REAL OR B.NFEINVIG<>B.FECTEVIG_REAL)
ORDER BY DOC_1, ITEM_1,PRO_1

SELECT DISTINCT B.NNUMDOCU, NNUMITEM, PRORROGA, A.DOC_2, A.ITEM_2, A.PRO_2
INTO #TMP_RENOV1
FROM #TMP_RENOV_BASE AS A
JOIN SGF1025.TRANSACCIONAL.DBO.MI_RATING_FACTORS_NEW AS B ON A.DOC_1 = B.NNUMDOCU AND A.ITEM_1 = B.NNUMITEM AND A.PRO_1 = B.PRORROGA;

SELECT DISTINCT A.NNUMDOCU, A.NNUMITEM, A.PRORROGA, A.DOC_2, A.ITEM_2, A.PRO_2, B.DOC_2 AS DOC_3, B.ITEM_2 AS ITEM_3, B.PRO_2 AS PRO_3
INTO #TMP_RENOV2
FROM #TMP_RENOV1 AS A
LEFT JOIN #TMP_RENOV_BASE AS B ON A.DOC_2 = B.DOC_1 AND A.ITEM_2 = B.ITEM_1  AND A.PRO_2 = B.PRO_1;

SELECT DISTINCT A.NNUMDOCU, A.NNUMITEM, A.PRORROGA, A.DOC_2, A.ITEM_2, A.PRO_2, A.DOC_3, A.ITEM_3, A.PRO_3, B.DOC_2 AS DOC_4, B.ITEM_2 AS ITEM_4, B.PRO_2 AS PRO_4
INTO #TMP_RENOV3
FROM #TMP_RENOV2 AS A
LEFT JOIN #TMP_RENOV_BASE AS B ON A.DOC_3 = B.DOC_1 AND A.ITEM_3 = B.ITEM_1  AND A.PRO_3 = B.PRO_1;

SELECT DISTINCT A.NNUMDOCU, A.NNUMITEM, A.PRORROGA, A.DOC_2, A.ITEM_2, A.PRO_2, A.DOC_3, A.ITEM_3, A.PRO_3, A.DOC_4, A.ITEM_4, A.PRO_4, B.DOC_2 AS DOC_5, B.ITEM_2 AS ITEM_5, B.PRO_2 AS PRO_5
INTO #TMP_RENOV4
FROM #TMP_RENOV3 AS A
LEFT JOIN #TMP_RENOV_BASE AS B ON A.DOC_4 = B.DOC_1 AND A.ITEM_4 = B.ITEM_1  AND A.PRO_4 = B.PRO_1;

SELECT DISTINCT A.NNUMDOCU, A.NNUMITEM, A.PRORROGA, A.DOC_2, A.ITEM_2, A.PRO_2, A.DOC_3, A.ITEM_3, A.PRO_3, A.DOC_4, A.ITEM_4, A.PRO_4,  A.DOC_5, A.ITEM_5, A.PRO_5, B.DOC_2 AS DOC_6, B.ITEM_2 AS ITEM_6, B.PRO_2 AS PRO_6
INTO #TMP_RENOV5
FROM #TMP_RENOV4 AS A
LEFT JOIN #TMP_RENOV_BASE AS B ON A.DOC_5 = B.DOC_1 AND A.ITEM_5 = B.ITEM_1  AND A.PRO_5 = B.PRO_1;

SELECT DISTINCT A.NNUMDOCU, A.NNUMITEM, A.PRORROGA, A.DOC_2, A.ITEM_2, A.PRO_2, A.DOC_3, A.ITEM_3, A.PRO_3, A.DOC_4, A.ITEM_4, A.PRO_4,  A.DOC_5, A.ITEM_5, A.PRO_5, A.DOC_6, A.ITEM_6, A.PRO_6, B.DOC_2 AS DOC_7, B.ITEM_2 AS ITEM_7, B.PRO_2 AS PRO_7
INTO #TMP_RENOV6
FROM #TMP_RENOV5 AS A
LEFT JOIN #TMP_RENOV_BASE AS B ON A.DOC_6 = B.DOC_1 AND A.ITEM_6 = B.ITEM_1  AND A.PRO_6 = B.PRO_1;

SELECT DISTINCT A.NNUMDOCU, A.NNUMITEM, A.PRORROGA, A.DOC_2, A.ITEM_2, A.PRO_2, A.DOC_3, A.ITEM_3, A.PRO_3, A.DOC_4, A.ITEM_4, A.PRO_4,  A.DOC_5, A.ITEM_5, A.PRO_5, A.DOC_6, A.ITEM_6, A.PRO_6, A.DOC_7, A.ITEM_7, A.PRO_7,B.DOC_2 AS DOC_8, B.ITEM_2 AS ITEM_8, B.PRO_2 AS PRO_8
INTO #TMP_RENOV7
FROM #TMP_RENOV6 AS A
LEFT JOIN #TMP_RENOV_BASE AS B ON A.DOC_7 = B.DOC_1 AND A.ITEM_7 = B.ITEM_1 AND A.PRO_7 = B.PRO_1

SELECT A.NNUMDOCU, A.NNUMITEM, A.PRORROGA, B.NFEINVIG AS FECINVIG_FIRST,
MAX(CASE      WHEN I.NFEINVIG IS NOT NULL THEN I.NFEINVIG
                     WHEN H.NFEINVIG IS NOT NULL THEN H.NFEINVIG
                     WHEN G.NFEINVIG IS NOT NULL THEN G.NFEINVIG
                     WHEN F.NFEINVIG IS NOT NULL THEN F.NFEINVIG
                     WHEN E.NFEINVIG IS NOT NULL THEN E.NFEINVIG
                     WHEN D.NFEINVIG IS NOT NULL THEN D.NFEINVIG
                     WHEN C.NFEINVIG IS NOT NULL THEN C.NFEINVIG
                     ELSE B.NFEINVIG END) AS FECINVIG_LAST,
ROUND (CAST(DATEDIFF(DAY,MIN(
       CASE   WHEN I.NFEINVIG IS NOT NULL THEN I.NFEINVIG
                     WHEN H.NFEINVIG IS NOT NULL THEN H.NFEINVIG
                     WHEN G.NFEINVIG IS NOT NULL THEN G.NFEINVIG
                     WHEN F.NFEINVIG IS NOT NULL THEN F.NFEINVIG
                     WHEN E.NFEINVIG IS NOT NULL THEN E.NFEINVIG
                     WHEN D.NFEINVIG IS NOT NULL THEN D.NFEINVIG
                     WHEN C.NFEINVIG IS NOT NULL THEN C.NFEINVIG
                     ELSE B.NFEINVIG END), MAX(B.NFEINVIG)) AS FLOAT)/365.25,2) AS PERSISTENCY_2
INTO #TMP_RENOV_FINAL
FROM #TMP_RENOV7 AS A
LEFT JOIN SGF1025.TRANSACCIONAL.DBO.MI_RATING_FACTORS_NEW AS B ON A.NNUMDOCU = B.NNUMDOCU AND A.NNUMITEM = B.NNUMITEM AND A.PRORROGA = B.PRORROGA
LEFT JOIN SGF1025.TRANSACCIONAL.DBO.MI_RATING_FACTORS_NEW AS C ON A.DOC_2 = C.NNUMDOCU AND A.ITEM_2 = C.NNUMITEM AND A.PRO_2 = C.PRORROGA
LEFT JOIN SGF1025.TRANSACCIONAL.DBO.MI_RATING_FACTORS_NEW AS D ON A.DOC_3 = D.NNUMDOCU AND A.ITEM_3 = D.NNUMITEM AND A.PRO_3 = D.PRORROGA
LEFT JOIN SGF1025.TRANSACCIONAL.DBO.MI_RATING_FACTORS_NEW AS E ON A.DOC_4 = E.NNUMDOCU AND A.ITEM_4 = E.NNUMITEM AND A.PRO_4 = E.PRORROGA
LEFT JOIN SGF1025.TRANSACCIONAL.DBO.MI_RATING_FACTORS_NEW AS F ON A.DOC_5 = F.NNUMDOCU AND A.ITEM_5 = F.NNUMITEM AND A.PRO_5 = F.PRORROGA
LEFT JOIN SGF1025.TRANSACCIONAL.DBO.MI_RATING_FACTORS_NEW AS G ON A.DOC_6 = G.NNUMDOCU AND A.ITEM_6 = G.NNUMITEM AND A.PRO_6 = G.PRORROGA
LEFT JOIN SGF1025.TRANSACCIONAL.DBO.MI_RATING_FACTORS_NEW AS H ON A.DOC_7 = H.NNUMDOCU AND A.ITEM_7 = H.NNUMITEM AND A.PRO_7 = H.PRORROGA
LEFT JOIN SGF1025.TRANSACCIONAL.DBO.MI_RATING_FACTORS_NEW AS I ON A.DOC_8 = I.NNUMDOCU AND A.ITEM_8 = I.NNUMITEM AND A.PRO_8 = I.PRORROGA
GROUP BY A.NNUMDOCU, A.NNUMITEM, A.PRORROGA, B.NFEINVIG;

---------------------------------------------------------------


select NNUMDOCU, NNUMITEM, PRORROGA, FLOOR(PERSISTENCY_2) AS PERSISTENCIA
INTO #TMP_PERSISTENCIA_FINAL
from #TMP_RENOV_FINAL

UPDATE #TMP_PERSISTENCIA_FINAL
SET PERSISTENCIA = 0
FROM #TMP_PERSISTENCIA_FINAL
WHERE PERSISTENCIA < 0


UPDATE MI_RATING_FACTORS_NEW
SET PERSISTENCIA=B.PERSISTENCIA
FROM MI_RATING_FACTORS_NEW A, #TMP_PERSISTENCIA_FINAL B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA

UPDATE MI_RATING_FACTORS_NEW
SET PERSISTENCIA=0
WHERE PERSISTENCIA IS NULL


-- Antiguedad RUT-CHANNEL:   (11/02/2021) @Nicolás Mazzocchi

DROP TABLE IF EXISTS #AUX_ANTIG_CL_1
SELECT NNURUPRO, CHANNEL, MIN(NFECEMIS2) AS MIN_INI_VIG
INTO #AUX_ANTIG_CL_1
FROM MI_RATING_FACTORS_NEW
GROUP BY NNURUPRO, CHANNEL

DROP TABLE IF EXISTS #AUX_ANTIG_CL_2
SELECT DISTINCT A.NNURUPRO, A.CHANNEL, A.NFECEMIS2, FLOOR((DATEDIFF(DAY, B.MIN_INI_VIG, NFECEMIS2)+60)/365.25) AS ANTIG_CL_RUT_CHANNEL 
INTO #AUX_ANTIG_CL_2
FROM MI_RATING_FACTORS_NEW A
LEFT JOIN #AUX_ANTIG_CL_1 B ON A.NNURUPRO = B.NNURUPRO AND A.CHANNEL = B.CHANNEL






UPDATE MI_RATING_FACTORS_NEW SET 
ANTIG_CL_RUT_CHANNEL = B.ANTIG_CL_RUT_CHANNEL
FROM MI_RATING_FACTORS_NEW A 
LEFT JOIN #AUX_ANTIG_CL_2 B ON A.NNURUPRO = B.NNURUPRO AND A.CHANNEL = B.CHANNEL AND A.NFECEMIS2 = B.NFECEMIS2


/****** Checkpoint 7 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 04-7', SYSDATETIME())
/****************************************************************************/

/************************************************************************************/
/************************************************************************************/
/************************************************************************************/

-- Planes x km:

DROP TABLE IF EXISTS #AUX_PLANES_X_KM
SELECT NPLANTEC, CDESCRIP
INTO #AUX_PLANES_X_KM
FROM MI_PASO_PRODUCCION
WHERE CDESCRIP LIKE '% KM%' OR CDESCRIP LIKE '%XKM%' OR CDESCRIP LIKE '%KILO%'
GROUP BY NPLANTEC, CDESCRIP
ORDER BY NPLANTEC, CDESCRIP


UPDATE MI_RATING_FACTORS_NEW
SET TIPO_X_KM = 'POLIZA TRADICIONAL'


UPDATE MI_RATING_FACTORS_NEW
SET TIPO_X_KM = 'POLIZA X KM'
FROM MI_RATING_FACTORS_NEW A LEFT JOIN #AUX_PLANES_X_KM B ON A.NPLANTEC = B.NPLANTEC
WHERE B.NPLANTEC IS NOT NULL

/************************************************************************************/
/************************************************************************************/
/************************************************************************************/







--SELECT * FROM MI_RATING_FACTORS_NEW

-- Campos de Sisgen por tipo de siniestro:




UPDATE MI_RATING_FACTORS_NEW
SET SiniG1G2_0_36=B.SiniG1G2_0_36
,SiniRC_0_36=B.SiniRC_0_36
,SiniTot_0_36=B.SiniTot_0_36

FROM MI_RATING_FACTORS_NEW A,SISGEN_ALG_WR_UP_FINAL B
WHERE (YEAR(A.NFECEMIS2)*100)+MONTH(A.NFECEMIS2)=B.YYYYMM AND A.NNURUPRO =B.RUT_Numeric




UPDATE MI_RATING_FACTORS_NEW
SET SiniG1G2_0_36='N'
WHERE SiniG1G2_0_36 IS NULL

UPDATE MI_RATING_FACTORS_NEW
SET SiniTot_0_36='N'
WHERE SiniTot_0_36 IS NULL

UPDATE MI_RATING_FACTORS_NEW
SET SiniRC_0_36='N'
WHERE SiniRC_0_36 IS NULL

DROP TABLE IF EXISTS #MI_PRIMA_EMITIDA_PERSONAL
SELECT CALCULO.*,

(FREC_DP			  *      SEV_DP)              *      TCAMBIO       AS PRDP,
 FREC_DP              *      SEV_DP								       AS PRDPUF,
(FREC_PT			  *      SEV_PT)              *      TCAMBIO       AS PRPT,
 FREC_PT              *      SEV_PT									   AS PRPTUF,
(FREC_RC			  *      SEV_RC)              *      TCAMBIO       AS PRRC,
 FREC_RC              *      SEV_RC									   AS PRRCUF,
(FREC_ROBO			  *      SEV_ROBO)			  *      TCAMBIO       AS PRROBO,
 FREC_ROBO			  *      SEV_ROBO								   AS PRROBOUF

INTO #MI_PRIMA_EMITIDA_PERSONAL

FROM (SELECT RF.*,
(BASE.DP_FREC		* A.DP_FREC          * B.DP_FREC          * C.DP_FREC            * D.DP_FREC          * E.DP_FREC          * F.DP_FREC            * G.DP_FREC        * G2.DP_FREC      * H.DP_FREC          * I.DP_FREC            * J.DP_FREC          * K.DP_FREC         * L.DP_FREC   * N.DP_FREC    )    *(DATEDIFF (DAY,DATEADD(DAY,-1,RF.NFEINVIG) ,RF.FECTEVIG_REAL)/365.25) AS FREC_DP,
 BASE.DP_SEV		* A.DP_SEV           * B.DP_SEV           * C.DP_SEV             * D.DP_SEV           * E.DP_SEV           * F.DP_SEV             * G.DP_SEV         * G2.DP_SEV       * H.DP_SEV           * I.DP_SEV             * J.DP_SEV           * K.DP_SEV          * L.DP_SEV	  * N.DP_SEV				   														         AS SEV_DP,
(BASE.PT_FREC		* A.PT_FREC          * B.PT_FREC          * C.PT_FREC            * D.PT_FREC          * E.PT_FREC          * F.PT_FREC            * G.PT_FREC        * G2.PT_FREC      * H.PT_FREC          * I.PT_FREC            * J.PT_FREC          * K.PT_FREC         * L.PT_FREC   * N.PT_FREC    )    *(DATEDIFF (DAY,DATEADD(DAY,-1,RF.NFEINVIG) ,RF.FECTEVIG_REAL)/365.25) AS FREC_PT,
 BASE.PT_SEV		* A.PT_SEV           * B.PT_SEV           * C.PT_SEV             * D.PT_SEV           * E.PT_SEV           * F.PT_SEV             * G.PT_SEV         * G2.PT_SEV       * H.PT_SEV           * I.PT_SEV             * J.PT_SEV           * K.PT_SEV          * L.PT_SEV	  * N.PT_SEV																		         AS SEV_PT,
(BASE.RC_FREC		* A.RC_FREC          * B.RC_FREC          * C.RC_FREC            * D.RC_FREC          * E.RC_FREC          * F.RC_FREC            * G.RC_FREC        * G2.RC_FREC      * H.RC_FREC          * I.RC_FREC            * J.RC_FREC          * K.RC_FREC         * L.RC_FREC   * N.RC_FREC    )    *(DATEDIFF (DAY,DATEADD(DAY,-1,RF.NFEINVIG) ,RF.FECTEVIG_REAL)/365.25) AS FREC_RC,
 BASE.RC_SEV        * A.RC_SEV           * B.RC_SEV           * C.RC_SEV             * D.RC_SEV           * E.RC_SEV           * F.RC_SEV             * G.RC_SEV         * G2.RC_SEV       * H.RC_SEV           * I.RC_SEV             * J.RC_SEV           * K.RC_SEV		    * L.RC_SEV	  * N.RC_SEV	  																	         AS SEV_RC,
(BASE.ROBO_FREC     * A.ROBO_FREC		 * B.ROBO_FREC		  * C.ROBO_FREC			 * D.ROBO_FREC		  * E.ROBO_FREC		   * F.ROBO_FREC		  * G.ROBO_FREC		 * G2.ROBO_FREC	   * H.ROBO_FREC		* I.ROBO_FREC		   * J.ROBO_FREC		* K.ROBO_FREC		* L.ROBO_FREC * N.ROBO_FREC   )    *(DATEDIFF (DAY,DATEADD(DAY,-1,RF.NFEINVIG) ,RF.FECTEVIG_REAL)/365.25) AS FREC_ROBO,
 BASE.ROBO_SEV		* A.ROBO_SEV		 * B.ROBO_SEV		  * C.ROBO_SEV			 * D.ROBO_SEV		  * E.ROBO_SEV		   * F.ROBO_SEV			  * G.ROBO_SEV		 * G2.ROBO_SEV	   * H.ROBO_SEV		    * I.ROBO_SEV		   * J.ROBO_SEV			* K.ROBO_SEV	    * L.ROBO_SEV  * N.ROBO_SEV																	             AS SEV_ROBO
 
 
FROM

MI_RATING_FACTORS_NEW                                                 RF
LEFT JOIN RM_LP_RF_BASE_RATES                                 BASE			 ON RF.F_CI                  = BASE.F_CI
LEFT JOIN RM_LP_RF_EDAD                                       A              ON RF.EDAD                  = A.EDAD
LEFT JOIN RM_LP_RF_ANTIG_CL_RUT_CHANNEL                       B              ON RF.ANTIG_CL_RUT_CHANNEL  = B.ANTIG_CL_RUT_CHANNEL
LEFT JOIN RM_LP_RF_ZONAS                                      C              ON RF.COMUNA		         = C.COMUNA
LEFT JOIN RM_LP_RF_CHANNEL                                    D              ON RF.CHANNEL_TO_EMB        = D.CHANNEL_TO_EMB
LEFT JOIN RM_LP_RF_DEDUCIBLES                                 E              ON RF.DEDUCIBLE             = E.DEDUCIBLE
LEFT JOIN RM_LP_RF_ANTVEH                                     F              ON RF.ANTVEH                = F.ANTVEH
LEFT JOIN RM_LP_RF_TOP100_2019                                G              ON RF.TOP100_2019           = G.TOP100_2019
LEFT JOIN RM_LP_RF_TIPO										  G2			 ON RF.TIPO_VEHICULO         = G2.TIPO
LEFT JOIN RM_LP_RF_NEW_SA                                     H              ON RF.NEW_SA                = H.NEW_SA
LEFT JOIN RM_LP_RF_SiniG1G2_0_36						      I              ON RF.SiniG1G2_0_36         = I.SiniG1G2_0_36
LEFT JOIN RM_LP_RF_SiniTot_0_36                               J              ON RF.SiniTot_0_36          = J.SiniTot_0_36
LEFT JOIN RM_LP_RF_SiniRC_0_36                                K              ON RF.SiniRC_0_36           = K.SiniRC_0_36
LEFT JOIN RM_LP_RF_FLAG_TIPPLAN							      L		         ON RF.TIPO_PLAN             = L.TIPPLAN
LEFT JOIN RM_LP_RF_TIPO_X_KM                                  N              ON RF.TIPO_X_KM             = N.TIPO_X_KM 

) CALCULO

TRUNCATE      TABLE  MI_PRIMA_EMITIDA_PERSONAL
INSERT        INTO   MI_PRIMA_EMITIDA_PERSONAL
SELECT 
NNUMDOCU, NNUMITEM, NNUMRUT, CNOCOPER, CHANNEL, CORREDOR_AGRUP, GRUPO, BUSINESS_UNIT, NPLAN, NPLANTEC, TIPO_PLAN, DEDUCIBLE, NFEINVIG, NFETEVIG, FECTEVIG_REAL,FECHA_CANCELACION, NFECEMIS2, NNURUPRO, NNURUEJC,  CNOMPRO, FNAC, SEXO, EDAD, 
SISNUM, SISUF, RAMO, LINEA_NEGOCIO, CCOMAVEH, CDESCORT, NANFAVEH, ANTVEH, TOP100_2019, TIPO_VEHICULO, SUMA_ASEGURADA, NEW_SA, CNUMPATE, CCODSUCU, COMUNA, PROVINCIA, ZONA, IND_CANCELACION, 
IND_UNICO, IND_RENOVACION, GWP_UF1 AS PRIMANETA, DPRINETAP, COM_UF1, PRDP, 
FREC_DP, PRPT, FREC_PT, PRRC, FREC_RC, PRROBO, FREC_ROBO, 
([PRDP]+[PRPT]+[PRRC]+[PRROBO]) AS PRRIESGO, 
FREC_DP+FREC_PT+FREC_RC+FREC_ROBO AS FRECTOT, 
USO,PRORROGA, NPECOSU, NNUDOANT, CDESCRIP, PRDPUF, PRPTUF, PRRCUF, PRROBOUF, 
([PRDPUF]+[PRPTUF]+[PRRCUF]+[PRROBOUF]) AS PRRIESGOUF
FROM #MI_PRIMA_EMITIDA_PERSONAL



-------------------------  CONTROL: VERIFICO QUE TODAS LAS POLIZAS TRAEN PRIMA DE RIESGO. sI NO TRAE FALLA ALGUN JOIN -----------------------------------------------------------------------------

/*
SELECT CALCULO.*,

(FREC_DP			  *      SEV_DP)              *      TCAMBIO       AS PRDP,
 FREC_DP              *      SEV_DP								       AS PRDPUF,
(FREC_PT			  *      SEV_PT)              *      TCAMBIO       AS PRPT,
 FREC_PT              *      SEV_PT									   AS PRPTUF,
(FREC_RC			  *      SEV_RC)              *      TCAMBIO       AS PRRC,
 FREC_RC              *      SEV_RC									   AS PRRCUF,
(FREC_ROBO			  *      SEV_ROBO)			  *      TCAMBIO       AS PRROBO,
 FREC_ROBO			  *      SEV_ROBO								   AS PRROBOUF,
  ((FREC_DP              *      SEV_DP) + (FREC_PT              *      SEV_PT) +	(FREC_RC              *      SEV_RC) + ( FREC_ROBO			  *      SEV_ROBO)) as Priesgo

FROM (SELECT RF.*,
(BASE.DP_FREC		* A.DP_FREC          * B.DP_FREC          * C.DP_FREC            * D.DP_FREC          * E.DP_FREC          * F.DP_FREC            * G.DP_FREC        * G2.DP_FREC      * H.DP_FREC          * I.DP_FREC            * J.DP_FREC          * K.DP_FREC         * L.DP_FREC   * N.DP_FREC    )    *(DATEDIFF (DAY,DATEADD(DAY,-1,RF.NFEINVIG) ,RF.FECTEVIG_REAL)/365.25) AS FREC_DP,
 BASE.DP_SEV		* A.DP_SEV           * B.DP_SEV           * C.DP_SEV             * D.DP_SEV           * E.DP_SEV           * F.DP_SEV             * G.DP_SEV         * G2.DP_SEV       * H.DP_SEV           * I.DP_SEV             * J.DP_SEV           * K.DP_SEV          * L.DP_SEV	  * N.DP_SEV				   														         AS SEV_DP,
(BASE.PT_FREC		* A.PT_FREC          * B.PT_FREC          * C.PT_FREC            * D.PT_FREC          * E.PT_FREC          * F.PT_FREC            * G.PT_FREC        * G2.PT_FREC      * H.PT_FREC          * I.PT_FREC            * J.PT_FREC          * K.PT_FREC         * L.PT_FREC   * N.PT_FREC    )    *(DATEDIFF (DAY,DATEADD(DAY,-1,RF.NFEINVIG) ,RF.FECTEVIG_REAL)/365.25) AS FREC_PT,
 BASE.PT_SEV		* A.PT_SEV           * B.PT_SEV           * C.PT_SEV             * D.PT_SEV           * E.PT_SEV           * F.PT_SEV             * G.PT_SEV         * G2.PT_SEV       * H.PT_SEV           * I.PT_SEV             * J.PT_SEV           * K.PT_SEV          * L.PT_SEV	  * N.PT_SEV																		         AS SEV_PT,
(BASE.RC_FREC		* A.RC_FREC          * B.RC_FREC          * C.RC_FREC            * D.RC_FREC          * E.RC_FREC          * F.RC_FREC            * G.RC_FREC        * G2.RC_FREC      * H.RC_FREC          * I.RC_FREC            * J.RC_FREC          * K.RC_FREC         * L.RC_FREC   * N.RC_FREC    )    *(DATEDIFF (DAY,DATEADD(DAY,-1,RF.NFEINVIG) ,RF.FECTEVIG_REAL)/365.25) AS FREC_RC,
 BASE.RC_SEV        * A.RC_SEV           * B.RC_SEV           * C.RC_SEV             * D.RC_SEV           * E.RC_SEV           * F.RC_SEV             * G.RC_SEV         * G2.RC_SEV       * H.RC_SEV           * I.RC_SEV             * J.RC_SEV           * K.RC_SEV		    * L.RC_SEV	  * N.RC_SEV	  																	         AS SEV_RC,
(BASE.ROBO_FREC     * A.ROBO_FREC		 * B.ROBO_FREC		  * C.ROBO_FREC			 * D.ROBO_FREC		  * E.ROBO_FREC		   * F.ROBO_FREC		  * G.ROBO_FREC		 * G2.ROBO_FREC	   * H.ROBO_FREC		* I.ROBO_FREC		   * J.ROBO_FREC		* K.ROBO_FREC		* L.ROBO_FREC * N.ROBO_FREC   )    *(DATEDIFF (DAY,DATEADD(DAY,-1,RF.NFEINVIG) ,RF.FECTEVIG_REAL)/365.25) AS FREC_ROBO,
 BASE.ROBO_SEV		* A.ROBO_SEV		 * B.ROBO_SEV		  * C.ROBO_SEV			 * D.ROBO_SEV		  * E.ROBO_SEV		   * F.ROBO_SEV			  * G.ROBO_SEV		 * G2.ROBO_SEV	   * H.ROBO_SEV		    * I.ROBO_SEV		   * J.ROBO_SEV			* K.ROBO_SEV	    * L.ROBO_SEV  * N.ROBO_SEV																	             AS SEV_ROBO,
 
BASE.DP_FREC BASE_DP_FREC, 	A.DP_FREC A_DP_FREC, 	B.DP_FREC B_DP_FREC, 	C.DP_FREC C_DP_FREC, 	D.DP_FREC D_DP_FREC, 	E.DP_FREC E_DP_FREC, 	F.DP_FREC F_DP_FREC, 	G.DP_FREC G_DP_FREC, 	G2.DP_FREC G2_DP_FREC, 	H.DP_FREC H_DP_FREC, 	I.DP_FREC I_DP_FREC, 	J.DP_FREC J_DP_FREC, 	K.DP_FREC K_DP_FREC, 	L.DP_FREC L_DP_FREC, 	N.DP_FREC N_DP_FREC, 
BASE.DP_SEV BASE_DP_SEV,  	A.DP_SEV A_DP_SEV,  	B.DP_SEV B_DP_SEV,  	C.DP_SEV C_DP_SEV,  	D.DP_SEV D_DP_SEV,  	E.DP_SEV E_DP_SEV,  	F.DP_SEV F_DP_SEV,  	G.DP_SEV G_DP_SEV,  	G2.DP_SEV G2_DP_SEV,  	H.DP_SEV H_DP_SEV,  	I.DP_SEV I_DP_SEV,  	J.DP_SEV J_DP_SEV,  	K.DP_SEV K_DP_SEV,  	L.DP_SEV L_DP_SEV,  	N.DP_SEV N_DP_SEV,  
BASE.PT_FREC BASE_PT_FREC,  	A.PT_FREC A_PT_FREC,  	B.PT_FREC B_PT_FREC,  	C.PT_FREC C_PT_FREC,  	D.PT_FREC D_PT_FREC,  	E.PT_FREC E_PT_FREC,  	F.PT_FREC F_PT_FREC,  	G.PT_FREC G_PT_FREC,  	G2.PT_FREC G2_PT_FREC,  	H.PT_FREC H_PT_FREC,  	I.PT_FREC I_PT_FREC,  	J.PT_FREC J_PT_FREC,  	K.PT_FREC K_PT_FREC,  	L.PT_FREC L_PT_FREC,  	N.PT_FREC N_PT_FREC,  
BASE.PT_SEV BASE_PT_SEV,  	A.PT_SEV A_PT_SEV,  	B.PT_SEV B_PT_SEV,  	C.PT_SEV C_PT_SEV,  	D.PT_SEV D_PT_SEV,  	E.PT_SEV E_PT_SEV,  	F.PT_SEV F_PT_SEV,  	G.PT_SEV G_PT_SEV,  	G2.PT_SEV G2_PT_SEV,  	H.PT_SEV H_PT_SEV,  	I.PT_SEV I_PT_SEV,  	J.PT_SEV J_PT_SEV,  	K.PT_SEV K_PT_SEV,  	L.PT_SEV L_PT_SEV,  	N.PT_SEV N_PT_SEV,  
BASE.RC_FREC BASE_RC_FREC,  	A.RC_FREC A_RC_FREC,  	B.RC_FREC B_RC_FREC,  	C.RC_FREC C_RC_FREC,  	D.RC_FREC D_RC_FREC,  	E.RC_FREC E_RC_FREC,  	F.RC_FREC F_RC_FREC,  	G.RC_FREC G_RC_FREC,  	G2.RC_FREC G2_RC_FREC,  	H.RC_FREC H_RC_FREC,  	I.RC_FREC I_RC_FREC,  	J.RC_FREC J_RC_FREC,  	K.RC_FREC K_RC_FREC,  	L.RC_FREC L_RC_FREC,  	N.RC_FREC N_RC_FREC,  
BASE.RC_SEV BASE_RC_SEV,  	A.RC_SEV A_RC_SEV,  	B.RC_SEV B_RC_SEV,  	C.RC_SEV C_RC_SEV,  	D.RC_SEV D_RC_SEV,  	E.RC_SEV E_RC_SEV,  	F.RC_SEV F_RC_SEV,  	G.RC_SEV G_RC_SEV,  	G2.RC_SEV G2_RC_SEV,  	H.RC_SEV H_RC_SEV,  	I.RC_SEV I_RC_SEV,  	J.RC_SEV J_RC_SEV,  	K.RC_SEV K_RC_SEV,  	L.RC_SEV L_RC_SEV,  	N.RC_SEV N_RC_SEV,  
BASE.ROBO_FREC BASE_ROBO_FREC,  	A.ROBO_FREC A_ROBO_FREC,  	B.ROBO_FREC B_ROBO_FREC,  	C.ROBO_FREC C_ROBO_FREC,  	D.ROBO_FREC D_ROBO_FREC,  	E.ROBO_FREC E_ROBO_FREC,  	F.ROBO_FREC F_ROBO_FREC,  	G.ROBO_FREC G_ROBO_FREC,  	G2.ROBO_FREC G2_ROBO_FREC,  	H.ROBO_FREC H_ROBO_FREC,  	I.ROBO_FREC I_ROBO_FREC,  	J.ROBO_FREC J_ROBO_FREC,  	K.ROBO_FREC K_ROBO_FREC,  	L.ROBO_FREC L_ROBO_FREC,  	N.ROBO_FREC N_ROBO_FREC,  
BASE.ROBO_SEV BASE_ROBO_SEV,  	A.ROBO_SEV A_ROBO_SEV,  	B.ROBO_SEV B_ROBO_SEV,  	C.ROBO_SEV C_ROBO_SEV,  	D.ROBO_SEV D_ROBO_SEV,  	E.ROBO_SEV E_ROBO_SEV,  	F.ROBO_SEV F_ROBO_SEV,  	G.ROBO_SEV G_ROBO_SEV,  	G2.ROBO_SEV G2_ROBO_SEV,  	H.ROBO_SEV H_ROBO_SEV,  	I.ROBO_SEV I_ROBO_SEV,  	J.ROBO_SEV J_ROBO_SEV,  	K.ROBO_SEV K_ROBO_SEV,  	L.ROBO_SEV L_ROBO_SEV,  	N.ROBO_SEV N_ROBO_SEV



FROM

MI_RATING_FACTORS_NEW                                                 RF
LEFT JOIN RM_LP_RF_BASE_RATES                                 BASE			 ON RF.F_CI                  = BASE.F_CI
LEFT JOIN RM_LP_RF_EDAD                                       A              ON RF.EDAD                  = A.EDAD
LEFT JOIN RM_LP_RF_ANTIG_CL_RUT_CHANNEL                       B              ON RF.ANTIG_CL_RUT_CHANNEL  = B.ANTIG_CL_RUT_CHANNEL
LEFT JOIN RM_LP_RF_ZONAS                                      C              ON RF.COMUNA		         = C.COMUNA
LEFT JOIN RM_LP_RF_CHANNEL                                    D              ON RF.CHANNEL_TO_EMB        = D.CHANNEL_TO_EMB
LEFT JOIN RM_LP_RF_DEDUCIBLES                                 E              ON RF.DEDUCIBLE             = E.DEDUCIBLE
LEFT JOIN RM_LP_RF_ANTVEH                                     F              ON RF.ANTVEH                = F.ANTVEH
LEFT JOIN RM_LP_RF_TOP100_2019                                G              ON RF.TOP100_2019           = G.TOP100_2019
LEFT JOIN RM_LP_RF_TIPO										  G2			 ON RF.TIPO_VEHICULO         = G2.TIPO
LEFT JOIN RM_LP_RF_NEW_SA                                     H              ON RF.NEW_SA                = H.NEW_SA
LEFT JOIN RM_LP_RF_SiniG1G2_0_36						      I              ON RF.SiniG1G2_0_36         = I.SiniG1G2_0_36
LEFT JOIN RM_LP_RF_SiniTot_0_36                               J              ON RF.SiniTot_0_36          = J.SiniTot_0_36
LEFT JOIN RM_LP_RF_SiniRC_0_36                                K              ON RF.SiniRC_0_36           = K.SiniRC_0_36
LEFT JOIN RM_LP_RF_FLAG_TIPPLAN							      L		         ON RF.TIPO_PLAN             = L.TIPPLAN
LEFT JOIN RM_LP_RF_TIPO_X_KM                                  N              ON RF.TIPO_X_KM             = N.TIPO_X_KM 

where RF.TIPO_PLAN <> 'RCA'

) CALCULO

where  ((FREC_DP              *      SEV_DP) + (FREC_PT              *      SEV_PT) +	(FREC_RC              *      SEV_RC) + ( FREC_ROBO			  *      SEV_ROBO)) is null
 AND FECTEVIG_REAL >='2022-02-28'

*/



--2 PRIMA EMITIDA COMMERCIAL -A



SELECT NNUMDOCU,NNURUPRO,PRORROGA, 
COUNT(*) AS CANTIDAD 
INTO #CANTIDAD_ITEMS_POR_POLIZA
FROM MI_PASO_PRODUCCION 
WHERE LINEA_NEGOCIO='COMMERCIAL' 
GROUP BY NNUMDOCU,NNURUPRO,PRORROGA

SELECT A.NNUMDOCU, 
A.NNURUPRO, 
A.PRORROGA,
A.CANTIDAD, 
CASE WHEN A.CANTIDAD >2000 THEN '2001 - +' ELSE B.TAMAÑO_AGRUPADO END AS TAMAÑO_AGRUPADO
INTO #TAMAÑO_FLOTAS_AGRUPADO
FROM #CANTIDAD_ITEMS_POR_POLIZA A 
LEFT JOIN PROCESOS.DBO.BASE_AUXILIAR_TAMAÑO_AGRUPADO B 
ON A.CANTIDAD = B.TAMAÑO ORDER BY 3 DESC;

--SELECT * FROM PROCESOS.DBO.BASE_AUXILIAR_TAMAÑO_AGRUPADO

SELECT A.NNUMDOCU, A.NNUMITEM,A.PRORROGA, A.NNURUPRO, A.NNUDOANT, 
A.RAMO, A.NFEINVIG, A.NFETEVIG, A.FECTEVIG_REAL,FECHA_CANCELACION, 
A.NFECEMIS2, A.GWP_UF1, A.COM_UF1, A.NPLAN, A.NNUMRUT, A.NNURUEJC,
A.CNOCOPER, A.CNOMPRO, A.L_NEGOCIO, A.LINEA_NEGOCIO, A.CCOMAVEH,
A.CDESCORT, A.NANFAVEH, A.CCODSUCU, A.NPLANTEC, A.CNUMPATE, 
A.NPECOSU, A.COMUNA, A.PROVINCIA, A.CCODMONE, A.IND_CANCELACION, 
A.IND_UNICO, A.IND_RENOVACION, A.USO, A.CHANNEL, A.CORREDOR_AGRUP, 
A.GRUPO, A.BUSINESS_UNIT, A.TIPO_PLAN, 
CASE WHEN A.DEDUCIBLE IS NULL THEN '0' ELSE A.DEDUCIBLE END AS DEDUCIBLE,
B.NOM_SUCURSAL AS NOMSUCU, 
D.RUBRO AS ACTIVIDAD, 
C.FLOTA, 
A.CDESCRIP
INTO #ACTIVIDAD_SUCURSAL_FLOTA
FROM (((SELECT * FROM MI_PASO_PRODUCCION WHERE LINEA_NEGOCIO='COMMERCIAL') A  
LEFT JOIN PROCESOS.DBO.BASE_AUXILIAR_SUCURSAL B ON A.CCODSUCU = B.SUCURSAL) 
LEFT JOIN PROCESOS.DBO.BASE_FLOTA C ON A.NNURUPRO = C.NNURUPRO) 
LEFT JOIN PROCESOS.DBO.BASE_AUXILIAR_ACTIVIDADES D ON A.NNURUPRO = D.NNUMRUT;


--AA02 AGREGAR INFORMACION
TRUNCATE      TABLE MI_PRIMA_EMITIDA_COMME_NEW
INSERT        INTO  MI_PRIMA_EMITIDA_COMME_NEW
SELECT 
A.NNUMDOCU, A.NNUMITEM, A.PRORROGA, A.NNUMRUT, A.CNOCOPER, A.NPLAN, A.NPLANTEC, A.TIPO_PLAN AS TIPPLAN, A.DEDUCIBLE,
-----CASE WHEN A.TIPO_PLAN = 'FULL' THEN 'FULL ' +  F.DEDUCTIBLE ELSE A.TIPO_PLAN END AS PLAN_DEDUCTIBLE,
A.NFEINVIG, A.NFETEVIG, A.FECTEVIG_REAL, A.FECHA_CANCELACION, A.NFECEMIS2, A.NNURUPRO AS RUTASE, A.NNURUEJC, A.CNOMPRO, A.RAMO, A.LINEA_NEGOCIO, A.CCOMAVEH, A.CDESCORT, A.NANFAVEH, 
CASE WHEN CONVERT(INT,YEAR(A.NFEINVIG))-CONVERT(INT,A.NANFAVEH)<0 THEN '0' ELSE 
       CASE WHEN CONVERT(INT,YEAR(A.NFEINVIG))-CONVERT(INT,A.NANFAVEH)>53 THEN 'UNKNOWN' ELSE  
              CONVERT(CHAR(15),CONVERT(INT,YEAR(A.NFEINVIG))-CONVERT(INT,A.NANFAVEH))
       END
END AS ANTVEH,
---CASE WHEN CONVERT(INT,YEAR(A.NFEINVIG))-CONVERT(INT,A.NANFAVEH)<0 THEN 0 ELSE 
       ---CASE WHEN CONVERT(INT,YEAR(A.NFEINVIG))-CONVERT(INT,A.NANFAVEH)>20 THEN '9999' ELSE  
              --CONVERT(CHAR(15),CONVERT(INT,YEAR(A.NFEINVIG))-CONVERT(INT,A.NANFAVEH))
       --END
--END AS VEH_AGE,
CASE WHEN C.TOP_100_COMMERCIAL IS NULL THEN 'NO INFORMADO' ELSE C.TOP_100_COMMERCIAL END AS TOP100,
CASE WHEN C.TOP_25_COMMERCIAL IS NULL THEN 'NO INFORMADO' ELSE C.TOP_25_COMMERCIAL END AS TOP25,
CASE WHEN C.TIPO_COMMERCIAL IS NULL THEN 'UNKNOWN' ELSE C.TIPO_COMMERCIAL END AS TIPO_VEHICULO,
CASE WHEN C.SA IS NULL THEN 'UNKNOWN' ELSE C.SA END AS SUMA_ASEGURADA, 
A.CNUMPATE, A.CCODSUCU, A.NOMSUCU, A.COMUNA, A.PROVINCIA, A.IND_CANCELACION, A.IND_UNICO, A.IND_RENOVACION, A.GWP_UF1, 
CASE WHEN D.UF IS NULL THEN D1.UF ELSE D.UF END * A.GWP_UF1 AS DPRINETAP, 
A.COM_UF1, B.TAMAÑO_AGRUPADO, 
CASE WHEN A.ACTIVIDAD IS NULL THEN 'UNKNOWN' ELSE A.ACTIVIDAD END AS ACTIVIDAD,
CASE WHEN D.UF IS NULL THEN D1.UF ELSE D.UF END AS TCAMBIO, 
CASE WHEN E.GEO_PRICING_COMM IS NULL THEN 'UNKNOWN' ELSE E.GEO_PRICING_COMM END AS ZONA,
CASE WHEN E.REGION IS NULL THEN 'UNKNOWN' ELSE E.REGION END AS REGION, 
A.CHANNEL, A.CORREDOR_AGRUP, A.USO, A.GRUPO, A.NNUDOANT, A.NPECOSU, 
'FLOTA SIN ASIGNAR' AS FLOTA,
A.BUSINESS_UNIT, A.CDESCRIP, 
CONVERT(DATE,DATEADD(MS,-3,DATEADD(MM,0,DATEADD(MM,DATEDIFF(MM,0,CONVERT(DATETIME,NFECEMIS2))+1,0)))) AS F_CI 
FROM (((((#ACTIVIDAD_SUCURSAL_FLOTA A 
LEFT JOIN #TAMAÑO_FLOTAS_AGRUPADO B ON (A.NNURUPRO = B.NNURUPRO) AND (A.NNUMDOCU = B.NNUMDOCU) AND A.PRORROGA=B.PRORROGA) 
LEFT JOIN PROCESOS.DBO.BASE_AUXILIAR_MARCA_MODELO_NEW C ON (A.CDESCORT = CONVERT(CHAR(40),C.CDESCORT)) AND (A.CCOMAVEH = CONVERT(CHAR(40),C.CCOMAVEH))) 
LEFT JOIN PROCESOS.DBO.BASE_SERIE_DIARIA_MONEDA D ON A.NFECEMIS2  = D.FECHA) 
LEFT JOIN PROCESOS.DBO.BASE_SERIE_DIARIA_MONEDA D1 ON A.NFEINVIG = D1.FECHA) 
LEFT JOIN (SELECT COMUNA, REGION, GEO_PRICING_COMM FROM PROCESOS.DBO.BASE_MAESTRO_COMUNAS_REGIONES_ZONAS GROUP BY COMUNA, REGION, GEO_PRICING_COMM) AS E
                     ON (A.COMUNA COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = CONVERT(CHAR(40),E.COMUNA))) 

----LEFT JOIN PROCESOS.DBO.BASE_AUXILIAR_DEDUCTIBLE F ON A.DEDUCIBLE = F.DEDUCIBLE



UPDATE MI_PRIMA_EMITIDA_COMME_NEW SET DEDUCIBLE = '0'
WHERE DEDUCIBLE IS NULL

UPDATE MI_PRIMA_EMITIDA_COMME_NEW SET ANTVEH = 'UNKNOWN'
WHERE ANTVEH IS NULL

UPDATE MI_PRIMA_EMITIDA_COMME_NEW SET TOP100 = 'NO INFORMADO'
WHERE TOP100 IS NULL

UPDATE MI_PRIMA_EMITIDA_COMME_NEW SET TIPO_VEHICULO = 'UNKNOWN'
WHERE TIPO_VEHICULO IS NULL

UPDATE MI_PRIMA_EMITIDA_COMME_NEW SET ZONA = 'UNKNOWN'
WHERE ZONA IS NULL

UPDATE MI_PRIMA_EMITIDA_COMME_NEW SET ACTIVIDAD = 'UNKNOWN'
WHERE ACTIVIDAD IS NULL 


--2 PRIMA EMITIDA COMMERCIAL -B

--TRUNCATE TABLE PROCESOS.DBO.BASE_LIVIANO_NEW
--INSERT INTO PROCESOS.DBO.BASE_LIVIANO_NEW


--SELECT A.NNUMDOCU, A.NNUMITEM, A.PRORROGA, A.NNUMRUT,CNOCOPER, A.NPLAN, A.NPLANTEC,TIPPLAN, DEDUCIBLE,NFEINVIG, NFETEVIG, FECTEVIG_REAL, FECHA_CANCELACION,NFECEMIS2, RUTASE, NNURUEJC, CNOMPRO, RAMO, LINEA_NEGOCIO, A.CCOMAVEH, A.CDESCORT, NANFAVEH, ANTVEH, B.TOP_100_COMMERCIAL AS TOP100, A.TOP25, TIPO_VEHICULO, SUMA_ASEGURADA, CNUMPATE, CCODSUCU, NOMSUCU, COMUNA, PROVINCIA, IND_CANCELACION, IND_UNICO, IND_RENOVACION, GWP_UF1, DPRINETAP,COM_UF1, TAMAÑO_AGRUPADO, ACTIVIDAD, TCAMBIO, ZONA, REGION, CHANNEL, CORREDOR_AGRUP, USO, GRUPO, NNUDOANT, NPECOSU, FLOTA, BUSINESS_UNIT, CDESCRIP, F_CI , C.IND_SPLIT  
--FROM (PROCESOS.DBO.BASE_LIVIANO A
--LEFT JOIN RM_TOP_100_COMMERCIAL_LIVIANO B ON (A.CDESCORT = CONVERT(CHAR(40),B.CDESCORT)) AND (A.CCOMAVEH = CONVERT(CHAR(40),B.CCOMAVEH)) 
--LEFT JOIN RM_FLOTAS_IND_SPLIT C ON A.CCOMAVEH=C.CCOMAVEH AND A.CDESCORT=C.CDESCORT)
--WHERE C.IND_SPLIT='LIVIANO'


--TRUNCATE TABLE PROCESOS.DBO.BASE_PESADO_NEW
--INSERT INTO PROCESOS.DBO.BASE_PESADO_NEW

--SELECT A.NNUMDOCU, A.NNUMITEM, A.PRORROGA, A.NNUMRUT,CNOCOPER, A.NPLAN, A.NPLANTEC,TIPPLAN, DEDUCIBLE,NFEINVIG, NFETEVIG, FECTEVIG_REAL, FECHA_CANCELACION,NFECEMIS2, RUTASE, NNURUEJC, CNOMPRO, RAMO, LINEA_NEGOCIO, A.CCOMAVEH, A.CDESCORT, NANFAVEH, ANTVEH, B.TOP_100_COMMERCIAL AS TOP100, C.TOP_25_Commercial AS TOP25, TIPO_VEHICULO, SUMA_ASEGURADA, CNUMPATE, CCODSUCU, NOMSUCU, COMUNA, PROVINCIA, IND_CANCELACION, IND_UNICO, IND_RENOVACION, GWP_UF1, DPRINETAP,COM_UF1, TAMAÑO_AGRUPADO, ACTIVIDAD, TCAMBIO, ZONA, REGION, CHANNEL, CORREDOR_AGRUP, USO, GRUPO, NNUDOANT, NPECOSU, FLOTA, BUSINESS_UNIT, CDESCRIP, F_CI, D.IND_SPLIT   
--FROM (PROCESOS.DBO.BASE_PESADO A 
--LEFT JOIN RM_TOP_100_COMMERCIAL_LIVIANO B ON (A.CDESCORT = CONVERT(CHAR(40),B.CDESCORT)) AND (A.CCOMAVEH = CONVERT(CHAR(40),B.CCOMAVEH))
--LEFT JOIN RM_TOP_25_COMMERCIAL_PESADOS C ON (A.CDESCORT = CONVERT(CHAR(40),C.CDESCORT)) AND (A.CCOMAVEH = CONVERT(CHAR(40),C.CCOMAVEH))
--LEFT JOIN RM_FLOTAS_IND_SPLIT D ON A.CCOMAVEH=D.CCOMAVEH AND D.CDESCORT=C.CDESCORT)
--WHERE D.IND_SPLIT='PESADO'




--------------------------------------------------------------------


-- Tabla temporal para asignar segmento por patente:
DROP TABLE IF EXISTS #SEGMENTO_POR_PATENTE
SELECT A.PPU, A.TIPO_VEH, A.MARCA, A.MODELO, B.SEGMENTO
INTO #SEGMENTO_POR_PATENTE
FROM BASE_VEHICULOS_RC_2021 A
LEFT JOIN MC_RM_VEH_SEGMENTACION B ON A.TIPO_VEH = B.TIPO_VEHICULO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS 


DROP TABLE IF EXISTS PROCESOS.DBO.BASE_LIVIANO
SELECT A.[NNUMDOCU]
      ,A.[NNUMITEM]
      ,A.[PRORROGA]
      ,A.[NNUMRUT]
      ,A.[CNOCOPER]
      ,A.[NPLAN]
      ,A.[NPLANTEC]
      ,A.[TIPPLAN]
      ,A.[DEDUCIBLE]
	  ,NULL AS [PLAN_DEDUCTIBLE]
      ,A.[NFEINVIG]
      ,A.[NFETEVIG]
      ,A.[FECTEVIG_REAL]
      ,A.[FECHA_CANCELACION]
      ,A.[NFECEMIS2]
      ,A.[RUTASE]
      ,A.[NNURUEJC]
      ,A.[CNOMPRO]
      ,A.[RAMO]
      ,A.[LINEA_NEGOCIO]
      ,A.[CCOMAVEH]
      ,A.[CDESCORT]
      ,A.[NANFAVEH]
      ,A.[ANTVEH]
	  ,NULL AS [VEH_AGE]
      ,A.[TOP100]
      ,A.[TOP25]
      ,A.[TIPO_VEHICULO]
      ,A.[SUMA_ASEGURADA]
      ,A.[CNUMPATE]
      ,A.[CCODSUCU]
      ,A.[NOMSUCU]
      ,A.[COMUNA]
      ,A.[PROVINCIA]
      ,A.[IND_CANCELACION]
      ,A.[IND_UNICO]
      ,A.[IND_RENOVACION]
      ,A.[GWP_UF1]
      ,A.[DPRINETAP]
      ,A.[COM_UF1]
      ,A.[TAMAÑO_AGRUPADO]
      ,A.[ACTIVIDAD]
      ,A.[TCAMBIO]
      ,A.[ZONA]
      ,A.[REGION]
      ,A.[CHANNEL]
      ,A.[CORREDOR_AGRUP]
      ,A.[USO]
      ,A.[GRUPO]
      ,A.[NNUDOANT]
      ,A.[NPECOSU]
      ,A.[FLOTA]
      ,A.[BUSINESS_UNIT]
      ,A.[CDESCRIP]
      ,A.[F_CI]
, CASE WHEN C.VALUE_AGE IS NULL THEN 'UNKNOWN' ELSE C.VALUE_AGE END AS VALUE_AGE1
,E.[TIPO_VEH] COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS AS TIPO_VEH_RVM
,CASE WHEN F.SEGMENTO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS IS NULL THEN B.LIV_PES ELSE F.SEGMENTO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS END AS SEGMENTO  

INTO PROCESOS.DBO.BASE_LIVIANO

FROM (MI_PRIMA_EMITIDA_COMME_NEW A 
LEFT JOIN PROCESOS.DBO.BASE_AUXILIAR_LIVIANOS_PESADOS B ON SUBSTRING(A.TIPO_VEHICULO,1,40) = B.TIPO_COMMERCIAL) 
LEFT JOIN PROCESOS.DBO.BASE_AUXILIAR_VALUE C ON (A.ANTVEH = C.AGE1) AND (A.CDESCORT = C.CDESCORT) AND (A.CCOMAVEH = C.CCOMAVEH)
LEFT JOIN RM_FLOTAS_IND_SPLIT D ON A.CCOMAVEH=D.CCOMAVEH AND A.CDESCORT=D.CDESCORT
LEFT JOIN BASE_VEHICULOS_RC_2021 E ON A.CNUMPATE = E.PPU COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS
LEFT JOIN #SEGMENTO_POR_PATENTE F ON A.CNUMPATE = F.PPU COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS 
WHERE (CASE WHEN F.SEGMENTO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS IS NOT NULL THEN F.SEGMENTO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS ELSE B.LIV_PES END) IN ('LIVIANOS', 'OTROS');

/****** Checkpoint 8 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 04-8', SYSDATETIME())
/****************************************************************************/

DROP TABLE IF EXISTS PROCESOS.DBO.BASE_PESADO
SELECT A.[NNUMDOCU]
      ,A.[NNUMITEM]
      ,A.[PRORROGA]
      ,A.[NNUMRUT]
      ,A.[CNOCOPER]
      ,A.[NPLAN]
      ,A.[NPLANTEC]
      ,A.[TIPPLAN]
      ,A.[DEDUCIBLE]
	  ,NULL AS [PLAN_DEDUCTIBLE]
      ,A.[NFEINVIG]
      ,A.[NFETEVIG]
      ,A.[FECTEVIG_REAL]
      ,A.[FECHA_CANCELACION]
      ,A.[NFECEMIS2]
      ,A.[RUTASE]
      ,A.[NNURUEJC]
      ,A.[CNOMPRO]
      ,A.[RAMO]
      ,A.[LINEA_NEGOCIO]
      ,A.[CCOMAVEH]
      ,A.[CDESCORT]
      ,A.[NANFAVEH]
      ,A.[ANTVEH]
	  ,NULL AS [VEH_AGE]
      ,A.[TOP100]
      ,A.[TOP25]
      ,A.[TIPO_VEHICULO]
      ,A.[SUMA_ASEGURADA]
      ,A.[CNUMPATE]
      ,A.[CCODSUCU]
      ,A.[NOMSUCU]
      ,A.[COMUNA]
      ,A.[PROVINCIA]
      ,A.[IND_CANCELACION]
      ,A.[IND_UNICO]
      ,A.[IND_RENOVACION]
      ,A.[GWP_UF1]
      ,A.[DPRINETAP]
      ,A.[COM_UF1]
      ,A.[TAMAÑO_AGRUPADO]
      ,A.[ACTIVIDAD]
      ,A.[TCAMBIO]
      ,A.[ZONA]
      ,A.[REGION]
      ,A.[CHANNEL]
      ,A.[CORREDOR_AGRUP]
      ,A.[USO]
      ,A.[GRUPO]
      ,A.[NNUDOANT]
      ,A.[NPECOSU]
      ,A.[FLOTA]
      ,A.[BUSINESS_UNIT]
      ,A.[CDESCRIP]
      ,A.[F_CI] 
      , CASE WHEN C.VALUE_AGE IS NULL THEN 'UNKNOWN' ELSE C.VALUE_AGE END AS VALUE_AGE1
	  ,E.[TIPO_VEH] COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS AS TIPO_VEH_RVM
	  ,CASE WHEN F.SEGMENTO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS IS NULL THEN B.LIV_PES ELSE F.SEGMENTO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS END AS SEGMENTO  

INTO PROCESOS.DBO.BASE_PESADO

FROM (MI_PRIMA_EMITIDA_COMME_NEW A
LEFT JOIN PROCESOS.DBO.BASE_AUXILIAR_LIVIANOS_PESADOS B ON SUBSTRING(A.TIPO_VEHICULO,1,40) = B.TIPO_COMMERCIAL) 
LEFT JOIN PROCESOS.DBO.BASE_AUXILIAR_VALUE C ON (A.ANTVEH = C.AGE1) AND (A.CDESCORT = C.CDESCORT) AND (A.CCOMAVEH = C.CCOMAVEH)
LEFT JOIN RM_FLOTAS_IND_SPLIT D ON A.CCOMAVEH=D.CCOMAVEH AND A.CDESCORT=D.CDESCORT
LEFT JOIN BASE_VEHICULOS_RC_2021 E ON A.CNUMPATE = E.PPU COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS
LEFT JOIN #SEGMENTO_POR_PATENTE F ON A.CNUMPATE = F.PPU COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS 
WHERE  (CASE WHEN F.SEGMENTO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS IS NOT NULL THEN F.SEGMENTO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS ELSE B.LIV_PES END) in ('PESADOS','BUSES','ESPECIAL');



--------------------------------------------------------------------------
------------------------------------------------------------------------------







UPDATE PROCESOS.DBO.BASE_PESADO
SET COMUNA ='UNKNOWN'
WHERE COMUNA ='IGNORADA'


--2 PRIMA EMITIDA COMMERCIAL -C 

--PESADO


SELECT CALCULO.*,
(FREC_DP      *      SEV_DP)              *      TCAMBIO       AS PRDP,
FREC_DP       *      SEV_DP									   AS PRDPUF,
(FREC_PT      *      SEV_PT)              *      TCAMBIO       AS PRPT,
FREC_PT       *      SEV_PT								       AS PRPTUF,
(FREC_RC      *      SEV_RC)              *      TCAMBIO       AS PRRC,
FREC_RC       *      SEV_RC							           AS PRRCUF,
(FREC_ROBO    *      SEV_ROBO)		      *      TCAMBIO       AS PRROBO,
FREC_ROBO     *      SEV_ROBO				                   AS PRROBOUF
INTO  #MI_PRIMA_EMITIDA_COMMERCIAL_PESADO
FROM (SELECT A.*, J.PLAN_TECNICO,
(BASE.DP_FREC		 * C.DP_FREC          * D.DP_FREC            * E.DP_FREC          * F.DP_FREC          * G.DP_FREC            * H.DP_FREC		* I.DP_FREC)       *(DATEDIFF (DAY,DATEADD(DAY,-1,A.NFEINVIG) ,A.FECTEVIG_REAL)/365.25)  AS FREC_DP,
BASE.DP_SEV          * C.DP_SEV			  * D.DP_SEV             * E.DP_SEV           * F.DP_SEV           * G.DP_SEV             * H.DP_SEV        * I.DP_SEV 																				    AS SEV_DP,
(BASE.PT_FREC		 * C.PT_FREC		  * D.PT_FREC            * E.PT_FREC          * F.PT_FREC          * G.PT_FREC            * H.PT_FREC       * I.PT_FREC)       *(DATEDIFF (DAY,DATEADD(DAY,-1,A.NFEINVIG) ,A.FECTEVIG_REAL)/365.25)  AS FREC_PT,
BASE.PT_SEV          * C.PT_SEV			  * D.PT_SEV             * E.PT_SEV           * F.PT_SEV           * G.PT_SEV             * H.PT_SEV        * I.PT_SEV  																				AS SEV_PT,
(BASE.RC_FREC		 * C.RC_FREC		  * D.RC_FREC	         * E.RC_FREC          * F.RC_FREC          * G.RC_FREC            * H.RC_FREC       * I.RC_FREC)       *(DATEDIFF (DAY,DATEADD(DAY,-1,A.NFEINVIG) ,A.FECTEVIG_REAL)/365.25)  AS FREC_RC,
BASE.RC_SEV          * C.RC_SEV			  * D.RC_SEV	         * E.RC_SEV           * F.RC_SEV           * G.RC_SEV             * H.RC_SEV        * I.RC_SEV 																				AS SEV_RC,
(BASE.ROBO_FREC      * C.ROBO_FREC		  * D.ROBO_FREC			 * E.ROBO_FREC		  * F.ROBO_FREC		   * G.ROBO_FREC		  * H.ROBO_FREC		* I.ROBO_FREC)		*(DATEDIFF (DAY,DATEADD(DAY,-1,A.NFEINVIG) ,A.FECTEVIG_REAL)/365.25)  AS FREC_ROBO,
BASE.ROBO_SEV		 * C.ROBO_SEV		  * D.ROBO_SEV			 * E.ROBO_SEV		  * F.ROBO_SEV		   * G.ROBO_SEV			  * H.ROBO_SEV		* I.ROBO_SEV																					AS SEV_ROBO

FROM PROCESOS.DBO.BASE_PESADO                          A 

LEFT JOIN RM_LC_RF_BASE_RATES_PES                      BASE          ON A.F_CI                      =BASE.F_CI
LEFT JOIN RM_LC_RF_DEDUCIBLE_PES                       C             ON A.DEDUCIBLE                 =C.DEDUCIBLE
LEFT JOIN RM_LC_RF_ANTVEH_PES                          D             ON A.ANTVEH                    =D.ANTVEH
LEFT JOIN RM_LC_RF_TAMAÑO_PES                          E             ON A.TAMAÑO_AGRUPADO			=E.TAMAÑO
LEFT JOIN RM_LC_RF_ACTIVIDAD_PES                       F             ON A.ACTIVIDAD                 =F.ACTIVIDAD
LEFT JOIN RM_LC_RF_COMUNA_PES                          G             ON A.COMUNA                    =G.COMUNA
LEFT JOIN RM_LC_RF_MARCA_MODELO_PES                    H             ON A.CCOMAVEH					=H.CCOMAVEH AND A.CDESCORT= H.CDESCORT 
LEFT JOIN RM_LC_RF_FLAG_TIPPLAN                        I             ON A.TIPPLAN					=I.TIPLAN 
LEFT JOIN  PROCESOS.DBO.BASE_PLANES_TECNICOS		   J             ON A.NPLANTEC					=J.NPLANTEC and a.NNUMRUT = J.NNUMRUT AND A.LINEA_NEGOCIO = J.LINEA_NEGOCIO

) CALCULO


UPDATE #MI_PRIMA_EMITIDA_COMMERCIAL_PESADO

SET FREC_DP = 0 ,
SEV_DP = 0 ,
FREC_PT = 0 ,
SEV_PT = 0 ,
FREC_RC = 0 ,
SEV_RC = 0 ,
FREC_ROBO = 0 ,
SEV_ROBO = 0 ,
 PRDP = 0 ,
 PRDPUF = 0 ,
 PRPT = 0 ,
 PRPTUF = 0 ,
 PRRC = 0 ,
 PRRCUF = 0 ,
 PRROBO = 0 ,
 PRROBOUF = 0 

WHERE 

SUBSTRING(SEGMENTO,1,40) IN ('BUSES','ESPECIAL')
OR
(TIPPLAN IN ('RCE','RCA','RCE + RCA') ) or (PLAN_TECNICO LIKE ('%UBER%') OR PLAN_TECNICO LIKE ('%TSTGO%') OR PLAN_TECNICO LIKE ('%HERTZ%'))
---- Planes Técnicos Uber Blanket
OR (NPLANTEC IN (5253,5335,5337,5828, 6159,6273,6794,6244, 6245, 6247, 6686, 6692))
----- Planes Técnicos Sol de Reñaca
OR (NPLANTEC IN (5839, 5840))
----- Planes Técnicos Central Placeres
OR (NPLANTEC IN (5845, 5852, 5853, 5854))
----- RUT Hertz
OR (RUTASE IN (53547100, 83547100, 93510300, 96510300, 96556350, 77289570))
----- RUT Transantiago
OR (RUTASE IN (99557450, 99557440, 76071048, 99546310, 76044148, 76204717, 99577050, 99559010, 99554700) )

ALTER TABLE #MI_PRIMA_EMITIDA_COMMERCIAL_PESADO
DROP COLUMN PLAN_TECNICO;

TRUNCATE      TABLE  MI_PRIMA_EMITIDA_COMMERCIAL_PES
INSERT        INTO   MI_PRIMA_EMITIDA_COMMERCIAL_PES

SELECT 
NNUMDOCU, NNUMITEM, PRORROGA, NNUMRUT, CNOCOPER, CHANNEL, CORREDOR_AGRUP, GRUPO, BUSINESS_UNIT, NPLAN, NPLANTEC, TIPPLAN, DEDUCIBLE, NFEINVIG, NFETEVIG, FECTEVIG_REAL,
FECHA_CANCELACION, NFECEMIS2, RUTASE, NNURUEJC, CNOMPRO, RAMO, LINEA_NEGOCIO, CCOMAVEH, CDESCORT,NANFAVEH, ANTVEH, TOP100, TOP25, TIPO_VEHICULO, SUMA_ASEGURADA, 
CNUMPATE, CCODSUCU, NOMSUCU, COMUNA, PROVINCIA, ZONA, REGION, IND_CANCELACION, IND_UNICO, IND_RENOVACION, GWP_UF1, DPRINETAP, COM_UF1, F_CI, USO, NNUDOANT, NPECOSU,
TAMAÑO_AGRUPADO AS TAMAÑO, FLOTA, CDESCRIP, ACTIVIDAD, TCAMBIO, TIPO_VEHICULO AS TIPO_VEH_RVM, SEGMENTO,
PRDP, FREC_DP, PRPT, FREC_PT, PRRC, FREC_RC, PRROBO, FREC_ROBO, 
([PRDP]+[PRPT]+[PRRC]+[PRROBO]) AS PRRIESGO, 
FREC_DP+FREC_PT+FREC_RC+FREC_ROBO AS FRECTOT, 
 PRDPUF, PRPTUF, PRRCUF, PRROBOUF, 
([PRDPUF]+[PRPTUF]+[PRRCUF]+[PRROBOUF]) AS PRRIESGOUF
FROM #MI_PRIMA_EMITIDA_COMMERCIAL_PESADO


	 ----


UPDATE MI_PRIMA_EMITIDA_COMMERCIAL_PES
SET 
PRRIESGO=[PRDP]+[PRPT]+[PRRC]+[PRROBO], 
PRRIESGOUF=[PRDPUF]+[PRPTUF]+[PRRCUF]+[PRROBOUF] 



---------------------


UPDATE PROCESOS.DBO.BASE_LIVIANO
SET COMUNA ='UNKNOWN'
WHERE COMUNA ='IGNORADA'


--LIVIANO



SELECT CALCULO.*,
(FREC_DP      *      SEV_DP)              *      TCAMBIO       AS PRDP,
FREC_DP       *      SEV_DP								       AS PRDPUF,
(FREC_PT      *      SEV_PT)              *      TCAMBIO       AS PRPT,
FREC_PT       *      SEV_PT								       AS PRPTUF,
(FREC_RC      *      SEV_RC)              *      TCAMBIO       AS PRRC,
FREC_RC       *      SEV_RC								       AS PRRCUF,
(FREC_ROBO    *      SEV_ROBO)			  *      TCAMBIO       AS PRROBO,
FREC_ROBO     *      SEV_ROBO							       AS PRROBOUF

INTO  #MI_PRIMA_EMITIDA_COMMERCIAL_LIVIANO

FROM (SELECT A.*,J.PLAN_TECNICO,
(BASE.DP_FREC		 * C.DP_FREC          * D.DP_FREC          * E.DP_FREC            * F.DP_FREC          * G.DP_FREC          * H.DP_FREC            * I.DP_FREC   )       *(DATEDIFF (DAY,DATEADD(DAY,-1,A.NFEINVIG) ,A.FECTEVIG_REAL)/365.25)  AS FREC_DP,
BASE.DP_SEV          * C.DP_SEV           * D.DP_SEV           * E.DP_SEV             * F.DP_SEV           * G.DP_SEV           * H.DP_SEV             * I.DP_SEV  																					AS SEV_DP,
(BASE.PT_FREC		 * C.PT_FREC          * D.PT_FREC          * E.PT_FREC            * F.PT_FREC          * G.PT_FREC          * H.PT_FREC            * I.PT_FREC   )       *(DATEDIFF (DAY,DATEADD(DAY,-1,A.NFEINVIG) ,A.FECTEVIG_REAL)/365.25)  AS FREC_PT,
BASE.PT_SEV          * C.PT_SEV           * D.PT_SEV           * E.PT_SEV             * F.PT_SEV           * G.PT_SEV           * H.PT_SEV             * I.PT_SEV 																					AS SEV_PT,
(BASE.RC_FREC		 * C.RC_FREC          * D.RC_FREC          * E.RC_FREC            * F.RC_FREC          * G.RC_FREC          * H.RC_FREC            * I.RC_FREC   )       *(DATEDIFF (DAY,DATEADD(DAY,-1,A.NFEINVIG) ,A.FECTEVIG_REAL)/365.25)  AS FREC_RC,
BASE.RC_SEV          * C.RC_SEV           * D.RC_SEV           * E.RC_SEV             * F.RC_SEV           * G.RC_SEV           * H.RC_SEV             * I.RC_SEV 																					AS SEV_RC,
(BASE.ROBO_FREC      * C.ROBO_FREC		  * D.ROBO_FREC		   * E.ROBO_FREC		  * F.ROBO_FREC		   * G.ROBO_FREC		* H.ROBO_FREC		   * I.ROBO_FREC )	      *(DATEDIFF (DAY,DATEADD(DAY,-1,A.NFEINVIG) ,A.FECTEVIG_REAL)/365.25)  AS FREC_ROBO,
BASE.ROBO_SEV		 * C.ROBO_SEV		  * D.ROBO_SEV		   * E.ROBO_SEV			  * F.ROBO_SEV		   * G.ROBO_SEV			* H.ROBO_SEV		   * I.ROBO_SEV																					AS SEV_ROBO

FROM PROCESOS.DBO.BASE_LIVIANO                 A 

LEFT JOIN RM_LC_RF_BASE_RATES_LIV              BASE	   ON A.F_CI            = BASE.F_CI
LEFT JOIN RM_LC_RF_DEDUCIBLE_LIV               C       ON A.DEDUCIBLE       = C.DEDUCIBLE
LEFT JOIN RM_LC_RF_ANTVEH_LIV                  D       ON A.ANTVEH          = D.ANTVEH
LEFT JOIN RM_LC_RF_TAMAÑO_LIV                  E       ON A.TAMAÑO_AGRUPADO = E.TAMAÑO
LEFT JOIN RM_LC_RF_ACTIVIDAD_LIV               F       ON A.ACTIVIDAD       = F.ACTIVIDAD
LEFT JOIN RM_LC_RF_COMUNA_LIV                  G       ON A.COMUNA          = G.COMUNA
LEFT JOIN RM_LC_RF_MARCA_MODELO_LIV            H       ON A.CCOMAVEH        = H.CCOMAVEH AND A.CDESCORT= H.CDESCORT 
LEFT JOIN RM_LC_RF_FLAG_TIPPLAN                I       ON A.TIPPLAN         = I.TIPLAN 
LEFT JOIN PROCESOS.DBO.BASE_PLANES_TECNICOS    J	   ON A.NPLANTEC        = J.NPLANTEC and a.NNUMRUT = J.NNUMRUT AND A.LINEA_NEGOCIO = J.LINEA_NEGOCIO
) CALCULO

UPDATE #MI_PRIMA_EMITIDA_COMMERCIAL_LIVIANO

SET FREC_DP = 0 ,
SEV_DP = 0 ,
FREC_PT = 0 ,
SEV_PT = 0 ,
FREC_RC = 0 ,
SEV_RC = 0 ,
FREC_ROBO = 0 ,
SEV_ROBO = 0 ,
 PRDP = 0 ,
 PRDPUF = 0 ,
 PRPT = 0 ,
 PRPTUF = 0 ,
 PRRC = 0 ,
 PRRCUF = 0 ,
 PRROBO = 0 ,
 PRROBOUF = 0 

WHERE 

SUBSTRING(SEGMENTO,1,40) = 'OTROS'
OR
(TIPPLAN IN ('RCE','RCA','RCE + RCA') ) or (PLAN_TECNICO LIKE ('%UBER%') OR PLAN_TECNICO LIKE ('%TSTGO%') OR PLAN_TECNICO LIKE ('%HERTZ%'))
---- Planes Técnicos Uber Blanket
OR (NPLANTEC IN (5253,5335,5337,5828, 6159,6273,6794,6244, 6245, 6247, 6686, 6692))
----- Planes Técnicos Sol de Reñaca
OR (NPLANTEC IN (5839, 5840))
----- Planes Técnicos Central Placeres
OR (NPLANTEC IN (5845, 5852, 5853, 5854))
----- RUT Hertz
OR (RUTASE IN (53547100, 83547100, 93510300, 96510300, 96556350, 77289570))
----- RUT Transantiago
OR (RUTASE IN (99557450, 99557440, 76071048, 99546310, 76044148, 76204717, 99577050, 99559010, 99554700) )



ALTER TABLE #MI_PRIMA_EMITIDA_COMMERCIAL_LIVIANO
DROP COLUMN PLAN_TECNICO;


TRUNCATE      TABLE  MI_PRIMA_EMITIDA_COMMERCIAL_LIV
INSERT        INTO   MI_PRIMA_EMITIDA_COMMERCIAL_LIV

SELECT 
NNUMDOCU, NNUMITEM, PRORROGA, NNUMRUT, CNOCOPER, CHANNEL, CORREDOR_AGRUP, GRUPO, BUSINESS_UNIT, NPLAN, NPLANTEC, TIPPLAN, DEDUCIBLE, NFEINVIG, NFETEVIG, FECTEVIG_REAL,
FECHA_CANCELACION, NFECEMIS2, RUTASE, NNURUEJC, CNOMPRO, RAMO, LINEA_NEGOCIO, CCOMAVEH, CDESCORT,NANFAVEH, ANTVEH, TOP100, TOP25, TIPO_VEHICULO, SUMA_ASEGURADA, 
CNUMPATE, CCODSUCU, NOMSUCU, COMUNA, PROVINCIA, ZONA, REGION, IND_CANCELACION, IND_UNICO, IND_RENOVACION, GWP_UF1, DPRINETAP, COM_UF1, F_CI, USO, NNUDOANT, NPECOSU,
TAMAÑO_AGRUPADO AS TAMAÑO, FLOTA, CDESCRIP, ACTIVIDAD, TCAMBIO, TIPO_VEHICULO AS TIPO_VEH_RVM, SEGMENTO,
PRDP, FREC_DP, PRPT, FREC_PT, PRRC, FREC_RC, PRROBO, FREC_ROBO, 
([PRDP]+[PRPT]+[PRRC]+[PRROBO]) AS PRRIESGO, 
FREC_DP+FREC_PT+FREC_RC+FREC_ROBO AS FRECTOT, 
 PRDPUF, PRPTUF, PRRCUF, PRROBOUF, 
([PRDPUF]+[PRPTUF]+[PRRCUF]+[PRROBOUF]) AS PRRIESGOUF
FROM #MI_PRIMA_EMITIDA_COMMERCIAL_LIVIANO


UPDATE MI_PRIMA_EMITIDA_COMMERCIAL_LIV
SET PRRC = CASE WHEN R.RESP_CIVIL_DAÑO_EMERGENTE > 5000 THEN (R.FL+(R.FLS-R.FL)*((R.RESP_CIVIL_DAÑO_EMERGENTE-R.LIMITE_RC_INI)/CASE WHEN (- R.LIMITE_RC_INI) = 0 THEN 1 ELSE (R.LIMITE_RC_TER - R.LIMITE_RC_INI) END))
ELSE (R.FL+(R.FLS-R.FL)*((R.RESP_CIVIL_DAÑO_EMERGENTE-R.LIMITE_RC_INI)/CASE WHEN (R.LIMITE_RC_TER - R.LIMITE_RC_INI) = 0 THEN 1 ELSE (R.LIMITE_RC_TER - R.LIMITE_RC_INI) END)) END * PRRC,
PRRCUF= CASE WHEN R.RESP_CIVIL_DAÑO_EMERGENTE > 5000 THEN (R.FL+(R.FLS-R.FL)*((R.RESP_CIVIL_DAÑO_EMERGENTE-R.LIMITE_RC_INI)/CASE WHEN (- R.LIMITE_RC_INI) = 0 THEN 1 ELSE (R.LIMITE_RC_TER - R.LIMITE_RC_INI) END))
ELSE (R.FL+(R.FLS-R.FL)*((R.RESP_CIVIL_DAÑO_EMERGENTE-R.LIMITE_RC_INI)/CASE WHEN (R.LIMITE_RC_TER - R.LIMITE_RC_INI) = 0 THEN 1 ELSE (R.LIMITE_RC_TER - R.LIMITE_RC_INI) END)) END * PRRCUF
FROM
MI_PRIMA_EMITIDA_COMMERCIAL_LIV Q,
(SELECT * FROM (SELECT X.NNUMDOCU,X.NNUMITEM,CASE WHEN Z.RESP_CIVIL_DAÑO_EMERGENTE IS NULL THEN 0 ELSE Z.RESP_CIVIL_DAÑO_EMERGENTE END RESP_CIVIL_DAÑO_EMERGENTE 
 FROM MI_PRIMA_EMITIDA_COMMERCIAL_LIV X LEFT JOIN PROCESOS.DBO.BASE_RC_LIMITE_COB Z ON X.NNUMDOCU=Z.NNUMDOCU AND X.NNUMITEM=Z.NNUMITEM) A, 
 PROCESOS.DBO.BASE_FACTORES_LIMITE_RC B WHERE
A.RESP_CIVIL_DAÑO_EMERGENTE  BETWEEN B.LIMITE_RC_INI AND B.LIMITE_RC_TER)R
WHERE Q.NNUMDOCU=R.NNUMDOCU AND Q.NNUMITEM=R.NNUMITEM


UPDATE MI_PRIMA_EMITIDA_COMMERCIAL_LIV
SET 
PRRIESGO=[PRDP]+[PRPT]+[PRRC]+[PRROBO], 
PRRIESGOUF=[PRDPUF]+[PRPTUF]+[PRRCUF]+[PRROBOUF] 


TRUNCATE TABLE MI_PRIMA_EMITIDA_COMMERCIAL_NEW

INSERT INTO  MI_PRIMA_EMITIDA_COMMERCIAL_NEW
select * from MI_PRIMA_EMITIDA_COMMERCIAL_LIV


INSERT INTO  MI_PRIMA_EMITIDA_COMMERCIAL_NEW
select * from MI_PRIMA_EMITIDA_COMMERCIAL_PES



UPDATE MI_PRIMA_EMITIDA_COMMERCIAL_NEW
SET PRRC = CASE WHEN R.RESP_CIVIL_DAÑO_EMERGENTE > 5000 THEN (R.FP+(R.FPS-R.FP)*((R.RESP_CIVIL_DAÑO_EMERGENTE-R.LIMITE_RC_INI)/CASE WHEN (- R.LIMITE_RC_INI) = 0 THEN 1 ELSE (R.LIMITE_RC_TER - R.LIMITE_RC_INI) END))
ELSE (R.FP+(R.FPS-R.FP)*((R.RESP_CIVIL_DAÑO_EMERGENTE-R.LIMITE_RC_INI)/CASE WHEN (R.LIMITE_RC_TER - R.LIMITE_RC_INI) = 0 THEN 1 ELSE (R.LIMITE_RC_TER - R.LIMITE_RC_INI) END)) END * PRRC,
PRRCUF = CASE WHEN R.RESP_CIVIL_DAÑO_EMERGENTE > 5000 THEN (R.FP+(R.FPS-R.FP)*((R.RESP_CIVIL_DAÑO_EMERGENTE-R.LIMITE_RC_INI)/CASE WHEN (- R.LIMITE_RC_INI) = 0 THEN 1 ELSE (R.LIMITE_RC_TER - R.LIMITE_RC_INI) END))
ELSE (R.FP+(R.FPS-R.FP)*((R.RESP_CIVIL_DAÑO_EMERGENTE-R.LIMITE_RC_INI)/CASE WHEN (R.LIMITE_RC_TER - R.LIMITE_RC_INI) = 0 THEN 1 ELSE (R.LIMITE_RC_TER - R.LIMITE_RC_INI) END)) END * PRRCUF
FROM
MI_PRIMA_EMITIDA_COMMERCIAL_NEW Q,
(SELECT * FROM (SELECT X.NNUMDOCU,X.NNUMITEM,CASE WHEN Z.RESP_CIVIL_DAÑO_EMERGENTE IS NULL THEN 0 ELSE Z.RESP_CIVIL_DAÑO_EMERGENTE END RESP_CIVIL_DAÑO_EMERGENTE 
 FROM MI_PRIMA_EMITIDA_COMMERCIAL_NEW X LEFT JOIN PROCESOS.DBO.BASE_RC_LIMITE_COB Z ON X.NNUMDOCU=Z.NNUMDOCU AND X.NNUMITEM=Z.NNUMITEM) A, 
 PROCESOS.DBO.BASE_FACTORES_LIMITE_RC B WHERE
A.RESP_CIVIL_DAÑO_EMERGENTE  BETWEEN B.LIMITE_RC_INI AND B.LIMITE_RC_TER)R
WHERE Q.NNUMDOCU=R.NNUMDOCU AND Q.NNUMITEM=R.NNUMITEM


UPDATE MI_PRIMA_EMITIDA_COMMERCIAL_NEW
SET 
PRRIESGO=[PRDP]+[PRPT]+[PRRC]+[PRROBO], 
PRRIESGOUF=[PRDPUF]+[PRPTUF]+[PRRCUF]+[PRROBOUF] 


/****** Checkpoint 9 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 04-9', SYSDATETIME())
/****************************************************************************/

--PERSONAL
TRUNCATE TABLE MI_PRIMA_EMITIDA
INSERT INTO  MI_PRIMA_EMITIDA
SELECT NNUMDOCU, NNUMITEM,PRORROGA, NNUMRUT, CNOCOPER,CHANNEL,CORREDOR_AGRUP, GRUPO, BUSINESS_UNIT, NPLAN, NPLANTEC, TIPO_PLAN, DEDUCIBLE, NFEINVIG, NFETEVIG, FECTEVIG_REAL,FECHA_CANCELACION, NFECEMIS2, 
NNURUPRO, NNURUEJC, CNOMPRO, FNAC, A.SEXO, EDAD, SISNUM , SISUF , RAMO, LINEA_NEGOCIO, CCOMAVEH, CDESCORT, NANFAVEH, ANTVEH, TOP100, A.tipo_vehiculo, SUMA_ASEGURADA, 
NEW_SA , CNUMPATE, CCODSUCU, CCODSUCU AS SUCURSAL, A.COMUNA, A.PROVINCIA, B.REGION, B.MACRO_ZONAS, B.ZONAS_GEOGRAFICAS, B.REGIONES_URBES, ZONA, IND_CANCELACION, IND_UNICO, IND_RENOVACION, PRIMANETA, DPRINETAP, COM_UF1, 
PRDP, PRDPUF,
FRECDP, PRPT, PRPTUF,
FRECPT, PRRC, PRRCUF,
FRECRC, PRROBO, PRROBOUF,
FRECROBO, PRRIESGO, PRRIESGOUF,
FRECTOT, USO, NNUDOANT, NPECOSU, 
'NO APLICA'AS FLOTA,
'NO APLICA'AS TAMAÑO,
'NO APLICA'AS ACTIVIDAD_GRUPO, CDESCRIP
,C.[TIPO_VEH] COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS AS TIPO_VEH_RVM
,D.SEGMENTO 

FROM MI_PRIMA_EMITIDA_PERSONAL AS A
LEFT JOIN (SELECT COMUNA,PROVINCIA,REGION,MACRO_ZONAS,ZONAS_GEOGRAFICAS,REGIONES_URBES FROM PROCESOS.DBO.BASE_MAESTRO_COMUNAS_REGIONES_ZONAS
GROUP BY COMUNA,PROVINCIA,REGION,MACRO_ZONAS,ZONAS_GEOGRAFICAS,REGIONES_URBES) AS B
ON A.COMUNA COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = B.COMUNA 
LEFT JOIN BASE_VEHICULOS_RC_2021 C ON A.CNUMPATE = C.PPU COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS
LEFT JOIN #SEGMENTO_POR_PATENTE D ON A.CNUMPATE = D.PPU COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS 


--COMMERCIAL --- SIN BANCO DE CHILE PYME
INSERT INTO  MI_PRIMA_EMITIDA
SELECT NNUMDOCU, NNUMITEM,PRORROGA, NNUMRUT, CNOCOPER,CHANNEL,CORREDOR_AGRUP, GRUPO, BUSINESS_UNIT, NPLAN, NPLANTEC, TIPPLAN, DEDUCIBLE, NFEINVIG, NFETEVIG, FECTEVIG_REAL,FECHA_CANCELACION, NFECEMIS2, 
RUTASE, NNURUEJC, CNOMPRO, 
NULL FNAC, 'NO APLICA' AS SEXO, 'NO APLICA' AS EDAD, NULL , 'NO APLICA' AS SISUF , RAMO, LINEA_NEGOCIO, CCOMAVEH, CDESCORT, NANFAVEH, ANTVEH, TOP100, TIPO_VEHICULO, SUMA_ASEGURADA, 
'NO APLICA' NEW_SA , CNUMPATE, CCODSUCU, CCODSUCU , A.COMUNA, A.PROVINCIA, B.REGION, B.MACRO_ZONAS, B.ZONAS_GEOGRAFICAS, B.REGIONES_URBES, ZONA, IND_CANCELACION, IND_UNICO, IND_RENOVACION, GWP_UF1, DPRINETAP, COM_UF1, 
PRDP, PRDPUF,
FREC_DP AS FRECDP, PRPT, PRPTUF,
FREC_PT AS FRECPT, PRRC, PRRCUF,
FREC_RC AS FRECRC, PRROBO, PRROBOUF,
FREC_ROBO AS FRECROBO, PRRIESGO, PRRIESGOUF,
FRECTOT, USO, NNUDOANT, NPECOSU, 
FLOTA,
TAMAÑO,
ACTIVIDAD, CDESCRIP, TIPO_VEH_RVM, SEGMENTO
FROM MI_PRIMA_EMITIDA_COMMERCIAL_NEW AS A
LEFT JOIN (SELECT COMUNA,PROVINCIA,REGION,MACRO_ZONAS,ZONAS_GEOGRAFICAS,REGIONES_URBES FROM PROCESOS.DBO.BASE_MAESTRO_COMUNAS_REGIONES_ZONAS
GROUP BY COMUNA,PROVINCIA,REGION,MACRO_ZONAS,ZONAS_GEOGRAFICAS,REGIONES_URBES) AS B
ON A.COMUNA COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = B.COMUNA
WHERE NPLANTEC NOT IN (4315,
4316,4317,4318,4319,4320,4321,4322,4323,4324,4429,4430,4431,4432,4433,4450,4451,4452,4453,4454,4870,4873,4874,4875,5183,5184,5185,5186,5187)


CREATE   TABLE #POL_CANCELADA_INDIVIDUAL
(NNUMDOCU INT,
NNUMITEM INT,
ESTADO VARCHAR(15)
)

DECLARE @CONSULTA3  AS NVARCHAR(4000)           
SET @CONSULTA3 =            
              
'SELECT * FROM OPENQUERY(SOL,''
SELECT X.NNUMDOCU,Y.NNUMITEM,X.CESTPOLI 
               FROM RSASOLDB2.SUACSPOL X INNER JOIN RSASOLDB2.SUACSITE Y 
                     ON 
                     X.NNUMDOCU = Y.NNUMDOCU
                     AND X.NNUMCERT = Y.NNUMCERT 
                     AND X.NNUMENDO = Y.NNUMENDO 
                     WHERE 
                     CCODESDO =  ''''0240F    00'''' 
                     AND X.CCODTNRO <> ''''17374    00'''' 
                     AND X.CCODRAMO IN (''''EE'''', ''''ET'''', ''''EL'''', ''''AE'''', ''''EP'''', ''''AV'''', ''''EA'''') 
                     AND SUBSTR(CHAR(NFECEMIS),1,4)>2009 
                     AND X.CESTPOLI IN (''''1106AN   00'''',''''1106CA   00'''')
                     AND X.NNUMCERT =  0
                     AND X.NNUMENDO>= 0
                     GROUP BY X.NNUMDOCU,Y.NNUMITEM,X.CESTPOLI '')'

INSERT INTO  #POL_CANCELADA_INDIVIDUAL
EXEC SP_EXECUTESQL @CONSULTA3


UPDATE #POL_CANCELADA_INDIVIDUAL
SET NNUMDOCU=NNUMDOCU*-1
WHERE NNUMDOCU<0

UPDATE MI_POL_CANCELADA_MASIVA
SET NNUMDOCU=NNUMDOCU*-1
WHERE NNUMDOCU<0

DELETE FROM #POL_CANCELADA_INDIVIDUAL WHERE NNUMDOCU IN (SELECT NNUMDOCU FROM MI_POL_CANCELADA_MASIVA  GROUP BY NNUMDOCU )

INSERT INTO #POL_CANCELADA_INDIVIDUAL
SELECT NNUMDOCU,NNUMITEM,'MASIVA_CAN' FROM MI_POL_CANCELADA_MASIVA
WHERE ESTADO='B'  
GROUP BY NNUMDOCU,NNUMITEM 

UPDATE MI_PRIMA_EMITIDA
SET  IND_CANCELACION =1
FROM MI_PRIMA_EMITIDA A, #POL_CANCELADA_INDIVIDUAL B
WHERE 
A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM =B.NNUMITEM AND A.PRORROGA=0
--------------------------------------------------------------------------------------------

TRUNCATE TABLE  MI_PRIMA_EMITIDA_ACCESS
INSERT INTO  MI_PRIMA_EMITIDA_ACCESS
SELECT 
NNUMDOCU,NNUMITEM,PRORROGA,NNUMRUT,CORREDOR,CHANNEL,CORREDOR_AGRUP,GRUPO,BU,NPLAN,NPLANTEC,TIPPLAN,DEDUCIBLE,FECINVIG,FECTEVIG,FECTEVIG_REAL,
FECHA_CANCELACION,FECEMIS,NNURUPRO,NNURUEJC,CNOMPRO,FNAC,SEXO,EDAD,SISNUM,SISUF,CCODRAMO,LINEA_NEGOCIO,CCOMAVEH,CDESCORT,NULL AS GAMA,NANFAVEH,ANTVEH,TOP100,TIPO,
SUMA_ASEG,NEW_SA,CNUMPATE,CCODSUCU,NOMSUCU,COMUNA, PROVINCIA, REGION, MACRO_ZONAS, ZONAS_GEOGRAFICAS, REGIONES_URBES,ZONA,IND_CANCELACION,IND_UNICO,IND_RENOVACION,DPRINETA,DPRINETAP,DPORCOMI,PRDP,PRDPUF,
FRECDP,PRPT,PRPTUF,FRECPT,PRRC,PRRCUF,FRECRC,PRROBO,PRROBOUF,FRECROBO,PRRIESGO,PRRIESGOUF,FRECTOT,USO,NNUDOANT,NPECOSUS,FLOTA,
TAMAÑO,ACTIVIDAD_AGRUP,CDESCRIP,0,0,0,0,0,0,TIPO_VEH_RVM,SEGMENTO FROM MI_PRIMA_EMITIDA 
--------------------------------------------------------------------------------------------


------------------------ACTUALIZACIÓN DE ENDOSOS DE CANCELACIÓN POR PERDIDA TOTAL 
UPDATE MI_PRIMA_EMITIDA_ACCESS
SET 
FECHA_CANCELACION		=B.NFECEMIS, 
FECTEVIG_REAL			=B.NFEINVIG, 
IND_CANCELACION			=1
FROM MI_PRIMA_EMITIDA_ACCESS A, ALMACEN_DE_DATOS.DBO.SURA_CANCELACION_PERDIDA_TOTAL B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM

------------------------


UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET FECTEVIG_REAL=B.PERIODO,MARCA_FECHA_SIN=1
FROM  MI_PRIMA_EMITIDA_ACCESS A ,MI_UPDATE_FECHA_SIN_POL B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA AND B.TERMINO=1

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET FECINVIG=B.PERIODO,MARCA_FECHA_SIN=2
FROM  MI_PRIMA_EMITIDA_ACCESS A ,MI_UPDATE_FECHA_SIN_POL B
WHERE A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM AND A.PRORROGA=B.PRORROGA AND B.INICIO=1

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET IND_CANCELACION=1
FROM (
SELECT NNUMDOCU,NNUMITEM FROM MI_TER_VIG_REAL WHERE 
NNUMDOCU NOT IN (SELECT NNUMDOCU FROM MI_TER_VIG_REAL WHERE NNUMITEM>1 AND NNUMDOCU>0 GROUP BY NNUMDOCU) 
AND FECTEVIG_REAL>0 AND NNUMDOCU>0 AND  FECTEVIG >20100000  GROUP BY NNUMDOCU,NNUMITEM) A INNER JOIN  MI_PRIMA_EMITIDA_ACCESS B
ON A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM
WHERE  B.PRORROGA=0 



UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET VIGENCIA_TEORICA = DATEDIFF (DAY,DATEADD(DAY,0,FECINVIG),FECTEVIG)
FROM  MI_PRIMA_EMITIDA_ACCESS

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET VIGENCIA_CONTABLE = DATEDIFF (DAY,DATEADD(DAY,0,FECINVIG),FECTEVIG_REAL)
FROM  MI_PRIMA_EMITIDA_ACCESS

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET VIGENCIA_EXP_AÑO = DATEDIFF (DAY,DATEADD(DAY,0,FECINVIG),FECHA_CANCELACION)
FROM  MI_PRIMA_EMITIDA_ACCESS

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET EXP_AÑO = VIGENCIA_EXP_AÑO / 365.25
FROM  MI_PRIMA_EMITIDA_ACCESS

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET GAMA = B.GAMA
FROM  MI_PRIMA_EMITIDA_ACCESS AS A
LEFT JOIN MI_GAMA_VEHICULOS AS B
ON A.CCOMAVEH COLLATE MODERN_SPANISH_CI_AS = B.MARCA
AND A.CDESCORT COLLATE MODERN_SPANISH_CI_AS = B.MODELO


CREATE TABLE #MI_CONTRATANTE
(NNUMDOCU INT,
NNURUPRO INT)


DECLARE @CONSULTA_CONTRATANTE     AS NVARCHAR(4000)   
SET @CONSULTA_CONTRATANTE =                     
'SELECT * FROM OPENQUERY(SOL,''
SELECT NNUMDOCU,NNURUPRO FROM RSASOLDB2.SUACSPOL WHERE CCODRAMO IN (''''EE'''', ''''ET'''', ''''EL'''', ''''AE'''', ''''EP'''', ''''AV'''', ''''EA'''', ''''EC'''') AND  NFECEMIS>20080000 AND NNUMDOCU>0 
GROUP BY NNUMDOCU,NNURUPRO

'')'
INSERT INTO #MI_CONTRATANTE
EXEC SP_EXECUTESQL @CONSULTA_CONTRATANTE

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET CONTRATANTE=B.NNURUPRO
FROM  MI_PRIMA_EMITIDA_ACCESS A, #MI_CONTRATANTE B
WHERE A.NNUMDOCU=B.NNUMDOCU
/*
UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET NNURUPRO=B.NNURUPRO
FROM  MI_PRIMA_EMITIDA_ACCESS A, #MI_CONTRATANTE B
WHERE A.NNUMDOCU=B.NNUMDOCU
*/

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET FLOTA= 'SIN ASIGNAR'

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET FLOTA=B.FLOTA
FROM  MI_PRIMA_EMITIDA_ACCESS A , PROCESOS.DBO.BASE_FLOTA_SEGMENTO B
WHERE A.NPLANTEC=B.NPLANTEC

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET FLOTA=B.FLOTA
FROM  MI_PRIMA_EMITIDA_ACCESS A, PROCESOS.DBO.BASE_FLOTA B
WHERE A.CONTRATANTE=B.NNURUPRO

UPDATE   MI_PRIMA_EMITIDA_ACCESS
SET CHANNEL='UBER' , GRUPO='UBER',BU='NEGOCIOS MASIVOS Y CLIENTES'
WHERE NPLANTEC IN (5335,5337)

--INCORPORA FLOTAS FALTANTES
UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET FLOTA='TSTGO - BUSES VULE'
WHERE NNUMDOCU IN (3738683,3752538,3947090)

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET FLOTA='TSTGO - LAS ARAUCARIAS'
WHERE NNUMDOCU IN (3812334)

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET FLOTA='TRANSPORTE SOL DE REÑACA'
WHERE NNUMDOCU IN (5724833)

UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET FLOTA='TRANSPORTE CENTRAL PLACERES'
WHERE NNUMDOCU IN (5731021,5732543,5732550,5732598,5734810,5753014)


---INCORPORA TOP100 NO INFORMADO EN COMMERCIAL (@VAGUILAR 12-03-21)
UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET TOP100= TOP100_2019
FROM  MI_PRIMA_EMITIDA_ACCESS A,RM_LP_TOP100_2019 B
WHERE A.CCOMAVEH=B.CCOMAVEH AND A.CDESCORT=B.CDESCORT AND LINEA_NEGOCIO='COMMERCIAL' AND TOP100='NO INFORMADO'


UPDATE  MI_PRIMA_EMITIDA_ACCESS
SET BU='CANAL ASESOR', CHANNEL='CANAL ASESOR'
FROM  MI_PRIMA_EMITIDA_ACCESS A,BASE_CORREDOR_EJECUTIVO_CA2 B
WHERE A.NNUMRUT=B.RUT_INTERMEDIARIO 
AND YEAR(A.FECEMIS)*100+MONTH(A.FECEMIS)=YEAR(B.PERIODO)*100+MONTH(B.PERIODO)

/****** Checkpoint 10 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 04-10', SYSDATETIME())
/****************************************************************************/

--Agregado 31-07-2024
-----------------------------------------------------------------------------------------------------------------------------------------
															--NUEVAS CORRECCIONES:
-----------------------------------------------------------------------------------------------------------------------------------------
--RCI
UPDATE MI_PRIMA_EMITIDA_ACCESS
SET
TIPPLAN = 'RCI'
where NPLANTEC in (4958,6034,3708,3706,4731,3709,1067,3710,3712,6042,6042,3711)

--RCI+ROBO
UPDATE MI_PRIMA_EMITIDA_ACCESS
SET
TIPPLAN = 'RCI+ROBO'
where NPLANTEC IN (6041,4730,4756)

-----------------------------------------------------------------------------------------------------------------------------------------
--ACTUALIZACION DE TIPPLAN CRUZANDO CON LA TABLA DE CARLOS VICENCIO
update MI_PRIMA_EMITIDA_ACCESS
set
	TIPPLAN = CASE WHEN B.TIPO_PLAN IS NULL OR B.TIPO_PLAN = '' THEN A.TIPPLAN ELSE B.TIPO_PLAN END
from MI_PRIMA_EMITIDA_ACCESS A
left join (select CODIGO_PLAN_TECNICO, PLAN_TECNICO, TIPO_PLAN from reportes.dbo.PLANES_TECNICOS_MOVILIDAD) B ON
A.NPLANTEC = B.CODIGO_PLAN_TECNICO
where 
	A.tipplan <> b.tipo_plan
	and A.tipplan not in ('RCI', 'RCI+ROBO')
	and B.TIPO_PLAN <> 'NO INDENT'
	and B.PLAN_TECNICO like '%MARCA%'
	and B.TIPO_PLAN <> 'RCA'

-----------------------------------------------------------------------------------------------------------------------------------------
--PARCHE CASOS AL AIRE
--RCI
update MI_PRIMA_EMITIDA_ACCESS
set
	TIPPLAN = 'RCI'
from MI_PRIMA_EMITIDA_ACCESS A
left join (select CODIGO_PLAN_TECNICO, PLAN_TECNICO, TIPO_PLAN from reportes.dbo.PLANES_TECNICOS_MOVILIDAD) B ON
A.NPLANTEC = B.CODIGO_PLAN_TECNICO
where 
	a.NPLANTEC = 1636

--RCI+ROBO
update MI_PRIMA_EMITIDA_ACCESS
set
	TIPPLAN = 'RCI+ROBO'
from MI_PRIMA_EMITIDA_ACCESS A
left join (select CODIGO_PLAN_TECNICO, PLAN_TECNICO, TIPO_PLAN from reportes.dbo.PLANES_TECNICOS_MOVILIDAD) B ON
A.NPLANTEC = B.CODIGO_PLAN_TECNICO
where 
	a.NPLANTEC = 6366

-----------------------------------------------------------------------------------------------------------------------------------------
--Correccion para Planes tecnicos con palabra 'Marca' y TIPPLAN 'RCA'
update MI_PRIMA_EMITIDA_ACCESS
set
	TIPPLAN = 'FULL'
from MI_PRIMA_EMITIDA_ACCESS A
left join (select CODIGO_PLAN_TECNICO, PLAN_TECNICO, TIPO_PLAN from reportes.dbo.PLANES_TECNICOS_MOVILIDAD) B ON
A.NPLANTEC = B.CODIGO_PLAN_TECNICO
where 
	b.PLAN_TECNICO like '%MARCA%'
	and tipplan = 'RCA'

-----------------------------------------------------------------------------------------------------------------------------------------
--CORRECCION CASOS ESPECIFICOS
update MI_PRIMA_EMITIDA_ACCESS
set
	TIPPLAN = replace(B.TIPO_PLAN,' ','')
from MI_PRIMA_EMITIDA_ACCESS A
left join (select CODIGO_PLAN_TECNICO, PLAN_TECNICO, TIPO_PLAN from reportes.dbo.PLANES_TECNICOS_MOVILIDAD) B ON
A.NPLANTEC = B.CODIGO_PLAN_TECNICO
where 
	a.tipplan <> b.tipo_plan
	and a.tipplan not in ('RCI', 'RCI+ROBO')
	and b.TIPO_PLAN <> 'NO INDENT'
	and not (b.PLAN_TECNICO like '%MARCA%' and b.TIPO_PLAN = 'RCA')
	and replace(replace(B.PLAN_TECNICO, 'PT RC', 'PT+RC'),'PT + RC','PT+RC') not like '%' + replace(A.TIPPLAN,' ','') + '%'
	and B.PLAN_TECNICO NOT LIKE '%FORCENTER%'
	and NPLANTEC not in (6839,6803)

-----------------------------------------------------------------------------------------------------------------------------------------
--RCA sueltos
update MI_PRIMA_EMITIDA_ACCESS
set
	TIPPLAN = 'RCI'
from MI_PRIMA_EMITIDA_ACCESS A
left join (select CODIGO_PLAN_TECNICO, PLAN_TECNICO, TIPO_PLAN from reportes.dbo.PLANES_TECNICOS_MOVILIDAD) B ON
A.NPLANTEC = B.CODIGO_PLAN_TECNICO
where 
	A.tipplan = 'RCA'
	and (B.PLAN_TECNICO like 'RCA%' or B.PLAN_TECNICO like 'RC%ARG%')
	and B.PLAN_TECNICO not like '%+%ROBO%'
	and B.PLAN_TECNICO not like '%NORCAVAL%'

update MI_PRIMA_EMITIDA_ACCESS
set 
	TIPPLAN = 'RCI'
where 
	TIPPLAN = 'RCA'

-----------------------------------------------------------------------------------------------------------------------------------------
--Correccion RCA NORCAVAL
update MI_PRIMA_EMITIDA_ACCESS
set
	TIPPLAN = 'FULL'
from MI_PRIMA_EMITIDA_ACCESS A
left join (select CODIGO_PLAN_TECNICO, PLAN_TECNICO, TIPO_PLAN from reportes.dbo.PLANES_TECNICOS_MOVILIDAD) B ON
A.NPLANTEC = B.CODIGO_PLAN_TECNICO
where 
	A.tipplan = 'RCI'
	and B.PLAN_TECNICO like '%NORCAVAL%'
	and NPLANTEC = 8331

-----------------------------------------------------------------------------------------------------------------------------------------
--Correccion PT + RC
update MI_PRIMA_EMITIDA_ACCESS
set
	TIPPLAN = 'PT + RC'
where 
	TIPPLAN = 'PT+RC'

-----------------------------------------------------------------------------------------------------------------------------------------
/*
--Correccion vacios (REVISAR SI ES POSIBLE NULL)
update #MI_PRIMA_EMITIDA_ACCESS
set
	TIPPLAN = NULL
where 
	TIPPLAN = ''
*/

-----------------------------------------------------------------------------------------------------------------------------------------
--Correccion Norcaval RCI
update MI_PRIMA_EMITIDA_ACCESS
set
	TIPPLAN = 'FULL'
where
	TIPPLAN = 'RCI' and
	CDESCRIP like '%NORCAVAL%'
-----------------------------------------------------------------------------------------------------------------------------------------
--AGREGAR FLOTAS
UPDATE MI_PRIMA_EMITIDA_ACCESS
SET
FLOTA = CASE 
	WHEN CONTRATANTE=77532011 THEN 'TSTGO - STU' 
	WHEN CONTRATANTE=77532114 THEN 'TSTGO - BUSES ALFA' 
	WHEN CONTRATANTE=77532117 THEN 'TSTGO - BUSES OMEGA' 
	WHEN CONTRATANTE=77532096 THEN 'TSTGO - RBU SANTIAGO'
	WHEN CONTRATANTE=99557440 THEN 'TSTGO - METBUS'
	WHEN CONTRATANTE=76071048 THEN 'TSTGO - BUSES VULE'
	WHEN CONTRATANTE=99577050 THEN 'TSTGO - RED BUS'
	ELSE FLOTA
END
WHERE CONTRATANTE IN (77532011, 77532114, 77532117, 77532096, 99557440, 76071048, 99577050)
-----------------------------------------------------------------------------------------------------------------------------------------
--FIN NUEVAS CORRECCIONES

/****** Checkpoint 11 ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('CHECKPOINT 04-11', SYSDATETIME())
/****************************************************************************/


--TRUNCATE TABLE TABLAS_COMPARTIDAS.DBO.MI_PRIMA_EMITIDA_ACCESS
--INSERT INTO TABLAS_COMPARTIDAS.DBO.MI_PRIMA_EMITIDA_ACCESS
--SELECT * FROM  MI_PRIMA_EMITIDA_ACCESS

TRUNCATE TABLE REPORTES.DBO.MI_PRIMA_EMITIDA_ACCESS
INSERT INTO REPORTES.DBO.MI_PRIMA_EMITIDA_ACCESS
SELECT * FROM  MI_PRIMA_EMITIDA_ACCESS


/****** Checkpoint PROCESO TERMINADO ********************************************************/
INSERT INTO AUX_MOTOR_00_CHECKPOINTS VALUES('PROCESO 04 TERMINADO', SYSDATETIME())
/****************************************************************************/


END



/*-------------------------  CONTROL PRIMAS-----------------------------------------------------

SELECT year(fecemiS)*100+month(fecemiS),SUM(DPRINETA) AS PRIMA_EMI
from [SGF1025].transaccional.dbo.MI_PRIMA_EMITIDA_ACCESS
where year(fecemiS)*100+month(fecemis) between 201901 and 202208 and linea_negocio like 'PER%'
AND NPLANTEC NOT IN (5709,5710,5711,5712,5951,5952,
5953,5954,5955,5956,5957,5958,5959,5960,5961,5962,5963,5964,5965,5966,5967,5968,
5969,5970,5971,5972,5973,5974,5975,5976,5977,5978,5979,5980,5981,5982,5983,5984,
5985,5986,6145,6146,6147,6148,6149,6150,6151,6152,6153,6154,6155,6156,6465,6479,
6480,6481,6677,6678,6679,6680,6681,6682,6957,6958,6959,6960,6991,6992,6993,6994,
7009,7010,7011,7012,7013,7014,7015,7016,7017,7018,7019,7020,7080,7081,7082,7083)
GROUP BY year(fecemis)*100+month(fecemis)
ORDER BY year(fecemis)*100+month(fecemis) */


/*-------------------------  GENERACIÓN BASE CLIENTES-----------------------------------------------------


USE Transaccional
select count(*)
from Base_resumen_clientes
--391.054

drop table  Base_resumen_clientes

drop table #Base_resumen_clientes_1
select distinct 
 BAS.nnuruase, BP.COMUNA, BP.PROVINCIA, BP.REGION, BP.Latitud_Destino, BP.Longitud_Destino,  BFT.GSE,BFT.edad, BFT.SEXO,CONVERT(DATE,DATEADD(MS,-3,DATEADD(MM,0,DATEADD(MM,DATEDIFF(MM,0,CONVERT(DATETIME,bas.fecha_obs))+1,0)))) AS PER_OBS
into #Base_resumen_clientes_1
from sgv1864.AnalyticsDM.dbo.base_asegurados_sura BAS

left join sgv1864.AnalyticsAbastecimiento.dbo.Base_Personas BP on BP.RUT=BAS.nnuruase
left join sgv1864.AnalyticsAbastecimiento.dbo.segmentacion_multi BFT on BAS.nnuruase=BFT.Rut
where  bas.capacidad='Movilidad' AND bas.fecha_obs >= '2019-01-01'


DROP TABLE #Base_resumen_clientes_2
SELECT nnuruase, MAX(PER_OBS) AS PER_OBS 
INTO #Base_resumen_clientes_2
FROM #Base_resumen_clientes_1
GROUP BY nnuruase 
-- (391054 rows affected)

DROP TABLE transaccional.dbo.Base_resumen_clientes
SELECT A.nnuruase, A.PER_OBS, BP.COMUNA, BP.PROVINCIA, BP.REGION, BP.Latitud_Destino, BP.Longitud_Destino,  BP.GSE, BP.edad, BP.SEXO
INTO transaccional.dbo.Base_resumen_clientes
FROM #Base_resumen_clientes_2 A
LEFT JOIN #Base_resumen_clientes_1 BP
ON A.nnuruase=BP.NNURUASE AND A.PER_OBS = BP.PER_OBS 
-- (391054 rows affected)


update transaccional.dbo.Base_resumen_clientes
set region = b.region,
	comuna = b.comuna
from  transaccional.dbo.Base_resumen_clientes a left join sgv1864.AnalyticsAbastecimiento.dbo.dim_contactos_unico_cliente b
on a.nnuruase = b.rut
where b.region is not null or b.region <>'Unknown'




*/