USE [Transaccional]
GO
/****** Object:  StoredProcedure [dbo].[SP_MI_TRANSACCIONAL_MOTOR_05_V2 (SINIESTROS)]    Script Date: 14-10-2025 10:26:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- PROCESO QUE GENERA LA TABLA DE SINIESTROS MI_A3_COMPLETO_FINAL

-- ANTES DE EJECUTAR VERIFICAR QUE LA BASE DE RESERVAS TENGA INFORMACIÓN DEL NUEVO TRIMESTRE!!!!!!!!!
-- SELECT MAX(QUARTER_OCU) FROM sgf1034.actuarial.dbo.INCURRIDOS_POWERBI_06


ALTER  PROCEDURE [dbo].[SP_MI_TRANSACCIONAL_MOTOR_05_V2 (SINIESTROS)](
@HASTA AS DATE
)
as

-- exec [SP_MI_TRANSACCIONAL_MOTOR_05_V2 (SINIESTROS)] @HASTA
-- EJEMPLO: exec [SP_MI_TRANSACCIONAL_MOTOR_05_V2 (SINIESTROS)] '2025-07-31'
		
begin
-- DECLARE @HASTA DATE SET @HASTA='2023-07-31'
DECLARE @DESDE DATE
DECLARE @FECHA_UX DATE
DECLARE @LDF INT
DECLARE @LDF_DATA INT

-- NUEVO PROCESO QUE GENERA LA TABLA DE LOS LDF DE MANERA AUTOMÁTICA
DECLARE @ULTIMO_LDF_PROCESADO DATE
DECLARE @LDF_POR_PROCESAR DATE
SET @ULTIMO_LDF_PROCESADO=(SELECT MAX(MES) FROM PROCESOS.DBO.BASE_LDF_COMPLETO_V2)
SET @LDF_POR_PROCESAR=(SELECT MAX(DATEFROMPARTS(LEFT(QUARTER_OCU, 4),CASE RIGHT(QUARTER_OCU, 2) WHEN 'Q1' THEN 3 WHEN 'Q2' THEN 6 WHEN 'Q3' THEN 9 WHEN 'Q4' THEN 12 END, CASE RIGHT(QUARTER_OCU, 2) WHEN 'Q1' THEN 31 WHEN 'Q2' THEN 30 WHEN 'Q3' THEN 30 WHEN 'Q4' THEN 31 END )) AS MES FROM sgf1034.actuarial.dbo.INCURRIDOS_POWERBI_06)

IF @ULTIMO_LDF_PROCESADO<@LDF_POR_PROCESAR
BEGIN
-----------------------------------------------------------------------------------
		drop table if exists #AUX_LDF
		select 
			'PANEL RESERVAS' AS CODIGO
		    ,DATEFROMPARTS(
		        LEFT(QUARTER_OCU, 4), -- Año
		        CASE RIGHT(QUARTER_OCU, 2) -- Trimestre
		            WHEN 'Q1' THEN 3
		            WHEN 'Q2' THEN 6
		            WHEN 'Q3' THEN 9
		            WHEN 'Q4' THEN 12
		        END,
		        CASE RIGHT(QUARTER_OCU, 2)
		            WHEN 'Q1' THEN 31
		            WHEN 'Q2' THEN 30
		            WHEN 'Q3' THEN 30
		            WHEN 'Q4' THEN 31
		        END
		    ) AS MES
			,RAMO_IBNR_IFRS COLLATE SQL_Latin1_General_CP1_CI_AS AS RAMO_RESERVA
		
		--ATRITIONAL
			,cast(SUM(ATT_DIAG_INC_NET + IBNR_NETO) * 1000 AS numeric(20,6)) ATT_ULTIMATE_$
			,cast(SUM(ATT_DIAG_INC_NET) * 1000 AS numeric(20,6)) ATT_INCURRIDO_$	
			,cast(COALESCE(SUM(ATT_DIAG_INC_NET + IBNR_NETO)/NULLIF(SUM(ATT_DIAG_INC_NET),0),1) AS numeric(20,6)) ATT_LDF_$	
			,cast(SUM(ATT_DIAG_CASOS_INC + IBNR_CASOS) * 1000 AS numeric(20,6)) ATT_ULTIMATE_#
			,cast(SUM(ATT_DIAG_CASOS_INC) * 1000 AS numeric(20,6)) ATT_INCURRIDO_#	
			,cast(COALESCE(SUM(ATT_DIAG_CASOS_INC + IBNR_CASOS)/NULLIF(SUM(ATT_DIAG_CASOS_INC),0),1)  AS numeric(20,6)) ATT_LDF_#
		
		--LARGE LOSSES
			,cast(SUM(LL_DIAG_INC_NET) * 1000 AS numeric(20,6)) LL_ULTIMATE_$
			,cast(SUM(LL_DIAG_INC_NET) * 1000 AS numeric(20,6)) LL_INCURRIDO_$	
			,cast(COALESCE(SUM(LL_DIAG_INC_NET)/NULLIF(SUM(LL_DIAG_INC_NET),0),1) AS numeric(20,6)) LL_LDF_$		
			,cast(SUM(LL_DIAG_CASOS_INC) * 1000 AS numeric(20,6)) LL_ULTIMATE_#
			,cast(SUM(LL_DIAG_CASOS_INC) * 1000 AS numeric(20,6)) LL_INCURRIDO_#
			,cast(COALESCE(SUM(LL_DIAG_CASOS_INC)/NULLIF(SUM(LL_DIAG_CASOS_INC),0),1) AS numeric(20,6)) LL_LDF_#
			
		--WEATHER
			,CAST(SUM(WL_DIAG_INC_NET) * 1000 AS numeric(20,6)) WL_ULTIMATE_$
			,CAST(SUM(WL_DIAG_INC_NET) * 1000 AS numeric(20,6))WL_INCURRIDO_$	
			,CAST(COALESCE(SUM(WL_DIAG_INC_NET)/NULLIF(SUM(WL_DIAG_INC_NET),0),1) AS numeric(20,6)) WL_LDF_$	
			,CAST(SUM(WL_DIAG_CASOS_INC) * 1000 AS numeric(20,6)) WL_ULTIMATE_#
			,CAST(SUM(WL_DIAG_CASOS_INC) * 1000 AS numeric(20,6)) WL_INCURRIDO_#
			,CAST(COALESCE(SUM(WL_DIAG_CASOS_INC)/NULLIF(SUM(WL_DIAG_CASOS_INC),0),1) AS numeric(20,6)) WL_LDF_#
		into #AUX_LDF
		from sgf1034.actuarial.dbo.INCURRIDOS_POWERBI_06 
		where NETO_BRUTO = 'NETO' AND 	BOTON_CM = 'SIN CM' AND (RAMO_IBNR_IFRS LIKE 'MP%' OR RAMO_IBNR_IFRS LIKE 'MC%')
		GROUP BY QUARTER_OCU, RAMO_IBNR_IFRS
		ORDER BY 4,3
		
		-- COMO LA BASE DE RESERVAS SÓLO TIENE INFO DESDE CIERTA FECHA EN ADELANTE, REUTILIZO LA INFO YA QUE LOS LDF MAS ANTIGUOS NO DEBEN VARIAR CASI NADA
		DECLARE @FechaMinima DATE;
		SELECT @FechaMinima = MIN(mes) FROM #AUX_LDF;
		DELETE FROM PROCESOS.DBO.BASE_LDF_COMPLETO_V2 WHERE mes >= @FechaMinima
		INSERT INTO PROCESOS.DBO.BASE_LDF_COMPLETO_V2 
		SELECT * FROM  #AUX_LDF
------------------------------------------------------------------------------------------------------------------------------
END

TRUNCATE TABLE	MI_PAGOS_RESERVAS_2
INSERT INTO		MI_PAGOS_RESERVAS_2
--SELECT CONCEPTO,CIA,SINIESTRO,EXPEDIENTE,NUM_POLIZA,NUM_ENDOSO,NUM_ITEM,NUM_CERTIFICADO,RUT_INTERM,COD_RAMO,COD_COBE,COD_LN,LINEA_NEGOCIO,RAMO_KEIRA,SUBRAMO_KEIRA,RAMO_RESERVA,RAMO_IBNR_IFRS,RAMO_IBNR_LOCAL,CIERRE,FECHA_PR,FECHA_OCU,FECHA_DENU,FECHA_APER,FECHA_CIERR,NUM_PAGO,COD_PAGO,DESC_PAGO,MONEDA,CORREDOR,TIPO_STRO_1,TIPO_STRO_2,WEATHER_LOCAL,WEATHER_IFRS,TIPO_STRO_LOCAL,TIPO_STRO_IFRS,DESC_COBE,NCORASVS,NUM_RAMO,RAMO_LOCAL,MATERIA,MATERIA_AGRUP,BU,PARTNER_SUCURSAL,PARTNER_AGRUP,COD_EVENTO,DESC_EVENTO,COD_CAUSA,DESC_CAUSA,RUT_PROPONENTE,PLAN_TECNICO,COBER_AGRUP,COD_VEHICULO,TIPO_VEHICULO,VEH_AGRUP,COD_CAMPAÑA,TIPO_CAMPAÑA,CAUSA_AGRUP,TC_MO,TC_UF,MONTO_BRU_MO,MONTO_CED_MO,MONTO_NET_MO,MONTO_BRU_CLP,MONTO_CED_CLP,MONTO_NET_CLP,MONTO_BRU_UF,MONTO_CED_UF,MONTO_NET_UF,COMUNA,DESC_PAGO_AGRUP 
--FROM [SGF1034].[ACTUARIAL].DBO.PAGOS_RVAS
select * FROM openquery(sgf1034, 'select CONCEPTO,CIA,SINIESTRO,EXPEDIENTE,NUM_POLIZA,NUM_ENDOSO,NUM_ITEM,NUM_CERTIFICADO,RUT_INTERM,COD_RAMO,COD_COBE,COD_LN,LINEA_NEGOCIO,RAMO_KEIRA,SUBRAMO_KEIRA,RAMO_RESERVA,RAMO_IBNR_IFRS,RAMO_IBNR_LOCAL,CIERRE,FECHA_PR,FECHA_OCU,FECHA_DENU,FECHA_APER,FECHA_CIERR,NUM_PAGO,COD_PAGO,DESC_PAGO,MONEDA,CORREDOR,TIPO_STRO_1,TIPO_STRO_2,WEATHER_LOCAL,WEATHER_IFRS,TIPO_STRO_LOCAL,TIPO_STRO_IFRS,DESC_COBE,NCORASVS,NUM_RAMO,RAMO_LOCAL,MATERIA,MATERIA_AGRUP,BU,PARTNER_SUCURSAL,PARTNER_AGRUP,COD_EVENTO,DESC_EVENTO,COD_CAUSA,DESC_CAUSA,RUT_PROPONENTE,PLAN_TECNICO,COBER_AGRUP,COD_VEHICULO,TIPO_VEHICULO,VEH_AGRUP,COD_CAMPAÑA,TIPO_CAMPAÑA,CAUSA_AGRUP,TC_MO,TC_UF,MONTO_BRU_MO,MONTO_CED_MO,MONTO_NET_MO,MONTO_BRU_CLP,MONTO_CED_CLP,MONTO_NET_CLP,MONTO_BRU_UF,MONTO_CED_UF,MONTO_NET_UF,COMUNA,DESC_PAGO_AGRUP from actuarial.dbo.pagos_rvas')
--MI_PAGOS_RESERVAS

SET @DESDE='2010-12-31'
SET @LDF=(SELECT LDF FROM PROCESOS.DBO.BASE_LDF_MES WHERE MES=MONTH(@HASTA))
SET @FECHA_UX=convert(DATE,dateadd(ms,-3,DATEADD(mm, DATEDIFF(m,0,convert(DATETIME, DATEADD(month, (@LDF*-1), @HASTA), 112)  )+1, 0)),101)
SET @LDF_DATA =(SELECT COUNT(*) FROM PROCESOS.DBO.BASE_LDF_COMPLETO_V2 WHERE MES=DATEADD (DAY,-1,(dateadd( month,1,CONVERT(DATE,CONVERT(CHAR(4),YEAR(@FECHA_UX))+'-'+ CONVERT(CHAR(2),CASE WHEN MONTH(@FECHA_UX)<4 THEN 3 ELSE CASE WHEN MONTH(@FECHA_UX)<7 THEN 6 ELSE CASE WHEN MONTH(@FECHA_UX)<10 THEN 9 ELSE 12 END END END)+'-01')))))

IF @LDF=0 AND @LDF_DATA=0
BEGIN
SET @LDF=3
END


IF @LDF IN (1,2) AND @LDF_DATA=0
	BEGIN
		SELECT 'FALTA LDF DEL PERIODO'
	END
ELSE
	BEGIN


	
		TRUNCATE TABLE MI_SINIESTROS_PAGOS_RESERVAS_B_NEW
		INSERT INTO		MI_SINIESTROS_PAGOS_RESERVAS_B_NEW

		SELECT SINIESTRO,EXPEDIENTE,NUM_POLIZA,NUM_ITEM,COD_RAMO,COD_COBE,DESC_COBE,RAMO_KEIRA,SUBRAMO_KEIRA,RAMO_IBNR_IFRS,RAMO_RESERVA,RAMO_LOCAL,
		CONVERT (DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU)))				AS F_OCU,
		CONVERT(DATE,DATEADD(MS,-3,DATEADD(MM, DATEDIFF(M,0,
		CONVERT(DATETIME, DATEADD(MONTH, (@LDF*-1), CONVERT (
		DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU)))), 112)  )+1, 0)),101) AS F_OCU_AUX,
		TIPO_STRO_LOCAL														AS TIPO_SINIESTRO,
		CASE WHEN  WEATHER_LOCAL='NO'	THEN 0				ELSE 1		END AS WEATHER_LOCAL,
		CASE WHEN  CONCEPTO='LIQ'		THEN MONTO_NET_CLP	ELSE 0		END AS PAGO_GROSS_P,
		CASE WHEN  CONCEPTO='LIQ'		THEN 0				ELSE 0		END AS PAGO_TREATY_P,
		CASE WHEN  CONCEPTO='LIQ'		THEN MONTO_CED_CLP	ELSE 0		END AS PAGO_EXTERNAL_P,
		0																	AS OCR_GROSS_P,
		0																	AS OCR_TREATY_P,
		0																	AS OCR_EXTERNAL_P,
		MONTO_NET_CLP														AS INC_GROSS_P,
		0																	AS INC_TREATY_P,
		MONTO_CED_CLP														AS INC_EXTERNAL_P,
		CASE WHEN  CONCEPTO='LIQ'		THEN MONTO_NET_UF	ELSE 0		END AS PAGO_GROSS,
		CASE WHEN  CONCEPTO='LIQ'		THEN 0				ELSE 0		END AS PAGO_TREATY,
		CASE WHEN  CONCEPTO='LIQ'		THEN MONTO_CED_UF	ELSE 0		END AS PAGO_EXTERNAL,
		0																	AS OCR_GROSS,
		0																	AS OCR_TREATY,
		0																	AS OCR_EXTERNAL,
		MONTO_NET_UF														AS INC_GROSS,
		0																	AS INC_TREATY,
		MONTO_CED_UF														AS INC_EXTERNAL,
		LINEA_NEGOCIO														AS LINEA_NEGOCIO, 
		CASE WHEN  CONCEPTO='RVA'		THEN 'RESERVA'		ELSE 'PAGO' END AS TIPO,
		''																	AS CANTIDAD
		FROM MI_PAGOS_RESERVAS_2 WHERE RAMO_KEIRA='MOTOR'
		AND CONVERT (DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU))) BETWEEN @DESDE AND @HASTA 
		AND CONCEPTO='LIQ'

		INSERT INTO		MI_SINIESTROS_PAGOS_RESERVAS_B_NEW
		SELECT SINIESTRO,EXPEDIENTE,NUM_POLIZA,NUM_ITEM,COD_RAMO,COD_COBE,DESC_COBE,RAMO_KEIRA,SUBRAMO_KEIRA,RAMO_IBNR_IFRS,RAMO_RESERVA,RAMO_LOCAL,
		CONVERT (DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU)))				AS F_OCU,
		CONVERT(DATE,DATEADD(MS,-3,DATEADD(MM, DATEDIFF(M,0,
		CONVERT(DATETIME, DATEADD(MONTH, (@LDF*-1), CONVERT (
		DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU)))), 112)  )+1, 0)),101) AS F_OCU_AUX,
		TIPO_STRO_LOCAL														AS TIPO_SINIESTRO,
		CASE WHEN  WEATHER_LOCAL='NO'	THEN 0				ELSE 1		END AS WEATHER_LOCAL,
		0 AS PAGO_GROSS_P,
		0 AS PAGO_TREATY_P,
		0 AS PAGO_EXTERNAL_P,
		CASE WHEN  CONCEPTO='RVA'		THEN MONTO_NET_CLP	ELSE 0		END AS OCR_GROSS_P,
		CASE WHEN  CONCEPTO='RVA'		THEN 0				ELSE 0		END AS OCR_TREATY_P,
		CASE WHEN  CONCEPTO='RVA'		THEN MONTO_CED_CLP	ELSE 0		END AS OCR_EXTERNAL_P,
		MONTO_NET_CLP														AS INC_GROSS_P,
		0																	AS INC_TREATY_P,
		MONTO_CED_CLP														AS INC_EXTERNAL_P,
		0																	AS PAGO_GROSS,
		0																	AS PAGO_TREATY,
		0																	AS PAGO_EXTERNAL,
		CASE WHEN  CONCEPTO='RVA'		THEN MONTO_NET_UF	ELSE 0		END AS OCR_GROSS,
		CASE WHEN  CONCEPTO='RVA'		THEN 0				ELSE 0		END AS OCR_TREATY,
		CASE WHEN  CONCEPTO='RVA'		THEN MONTO_CED_UF	ELSE 0		END AS OCR_EXTERNAL,
		MONTO_NET_UF														AS INC_GROSS,
		0																	AS INC_TREATY,
		MONTO_CED_UF														AS INC_EXTERNAL,
		LINEA_NEGOCIO														AS LINEA_NEGOCIO, 
		CASE WHEN  CONCEPTO='RVA'		THEN 'RESERVA'		ELSE 'PAGO' END AS TIPO,
		''																	AS CANTIDAD
		FROM MI_PAGOS_RESERVAS_2 WHERE RAMO_KEIRA='MOTOR'
		AND CONVERT (DATE,CONVERT(CHAR(8),CONVERT(INT,FECHA_OCU))) BETWEEN @DESDE AND @HASTA 
		AND CIERRE =YEAR(@HASTA)*100+MONTH(@HASTA)
		AND CONCEPTO='RVA'





		
		--SELECT * FROM MI_SINIESTROS_PAGOS_RESERVAS_B_NEW
		--------------------------------------------------------------------------------------------------MI_A3_COMPLETO 
		--DECLARE @HASTA DATE SET @HASTA='2018-08-31'
		TRUNCATE TABLE MI_A3_COMPLETO
		INSERT INTO MI_A3_COMPLETO
		SELECT X.*,CASE WHEN X.RAMO_RESERVA LIKE ('%TPL%') THEN 'RC' ELSE B.COBERTURA  END FROM (
		SELECT 
		EOMONTH(F_OCU_AUX,CASE WHEN MONTH(F_OCU_AUX) IN (1,4,7,10) THEN 2 ELSE CASE WHEN MONTH(F_OCU_AUX) IN (2,5,8,11) THEN 1 ELSE 0 END END) AS MES,
		EOMONTH(F_OCU_AUX,CASE WHEN MONTH(F_OCU_AUX) IN (1,4,7,10) THEN -1 ELSE CASE WHEN MONTH(F_OCU_AUX) IN (2,5,8,11) THEN -2 ELSE -3 END END) AS MES_ANT,
		NNUMSINI,NNUCOSIN,NNUMDOCU,NNUMITEM,LINEA_NEGOCIO,CCODCOBE,DESC_COBE,RAMO_KEIRA,SUBRAMO_KEIRA,RAMO_RESERVA,RAMO_LOCAL,F_OCU,
		CASE WHEN EOMONTH(F_OCU,CASE WHEN MONTH(F_OCU) IN (1,4,7,10) THEN 2 ELSE CASE WHEN MONTH(F_OCU) IN (2,5,8,11) THEN 1 ELSE 0 END END ) > @HASTA
		--CASE WHEN EOMONTH(F_OCU,CASE WHEN MONTH(F_OCU) IN (1,4,7,10) THEN 2 ELSE CASE WHEN MONTH(F_OCU) IN (2,5,8,11) THEN 1 ELSE 0 END END ) > DATEADD(MONTH, -1, @HASTA) 

			THEN EOMONTH(F_OCU,CASE WHEN MONTH(F_OCU) IN (1,4,7,10) THEN -1 ELSE CASE WHEN MONTH(F_OCU) IN (2,5,8,11) THEN -2 ELSE 0 END END ) 
			ELSE EOMONTH(F_OCU,CASE WHEN MONTH(F_OCU) IN (1,4,7,10) THEN 2 ELSE CASE WHEN MONTH(F_OCU) IN (2,5,8,11) THEN 1 ELSE 0 END END ) END AS F_OCU_LDF,
		TIPO_SINIESTRO,IND_WEATHER,
		SUM(PAGO_GROSS_P)		AS PAGO_GROSS_P,
		SUM(PAGO_TREATY_P)		AS PAGO_TREATY_P,
		SUM(PAGO_EXTERNAL_P)	AS PAGO_EXTERNAL_P,
		SUM(OCR_GROSS_P)		AS OCR_GROSS_P,
		SUM(OCR_TREATY_P)		AS OCR_TREATY_P,
		SUM(OCR_EXTERNAL_P)		AS OCR_EXTERNAL_P,
		SUM(INC_GROSS_P)		AS INC_GROSS_P,
		SUM(INC_TREATY_P)		AS INC_TREATY_P,
		SUM(INC_EXTERNAL_P)		AS INC_EXTERNAL_P,
		SUM(PAGO_GROSS)			AS PAGO_GROSS,
		SUM(PAGO_TREATY)		AS PAGO_TREATY,
		SUM(PAGO_EXTERNAL)		AS PAGO_EXTERNAL,
		SUM(OCR_GROSS)			AS OCR_GROSS,
		SUM(OCR_TREATY)			AS OCR_TREATY,
		SUM(OCR_EXTERNAL)		AS OCR_EXTERNAL,
		SUM(INC_GROSS)			AS INC_GROSS,
		SUM(INC_TREATY)			AS INC_TREATY,
		SUM(INC_EXTERNAL)		AS INC_EXTERNAL,
		1						AS CANTIDAD 
		FROM MI_SINIESTROS_PAGOS_RESERVAS_B_NEW
		GROUP BY
		EOMONTH(F_OCU_AUX,CASE WHEN MONTH(F_OCU_AUX) IN (1,4,7,10) THEN 2 ELSE CASE WHEN MONTH(F_OCU_AUX) IN (2,5,8,11) THEN 1 ELSE 0 END END) ,
		EOMONTH(F_OCU_AUX,CASE WHEN MONTH(F_OCU_AUX) IN (1,4,7,10) THEN -1 ELSE CASE WHEN MONTH(F_OCU_AUX) IN (2,5,8,11) THEN -2 ELSE -3 END END),
		EOMONTH(F_OCU,CASE WHEN MONTH(F_OCU) IN (1,4,7,10) THEN 2 ELSE CASE WHEN MONTH(F_OCU) IN (2,5,8,11) THEN 1 ELSE 0 END END ),
		NNUMSINI,NNUCOSIN,NNUMDOCU,NNUMITEM,LINEA_NEGOCIO,CCODCOBE,DESC_COBE,RAMO_KEIRA,SUBRAMO_KEIRA,RAMO_RESERVA,RAMO_LOCAL,F_OCU,TIPO_SINIESTRO,IND_WEATHER,F_OCU_AUX)X
		LEFT JOIN MI_COBERTURA_IBNR B ON
		X.NNUMSINI =B.NNUMSINI AND X.NNUCOSIN=B.NNUCOSIN LEFT JOIN MI_MARCA_SIN_HOGAR C ON 
		X.NNUMSINI =C.NNUMSINI AND X.NNUCOSIN=C.CORRSINI 



		TRUNCATE TABLE MI_A3_COMPLETO_FINAL
		INSERT INTO MI_A3_COMPLETO_FINAL
		SELECT 
		CONVERT(DATE,DATEADD(MS,-3,DATEADD(MM, DATEDIFF(M,0,CONVERT(DATETIME, DATEADD(MONTH, (0), F_OCU), 112)  )+1, 0)),101) AS PER,
		NNUMSINI,NNUCOSIN,NNUMDOCU,NNUMITEM,NULL AS NNUMCERT,LINEA_NEGOCIO,CCODCOBE,DESC_COBE,A.COBERTURA_IBNR AS RAMO_RESERVA,RAMO_LOCAL,F_OCU,A.TIPO_SINIESTRO,
		INC_GROSS_P,
		INC_TREATY_P,
		INC_EXTERNAL_P,
		PAGO_GROSS_P,
		PAGO_TREATY_P,
		PAGO_EXTERNAL_P,
		OCR_GROSS_P,
		OCR_TREATY_P,
		OCR_EXTERNAL_P,
		INC_GROSS,
		INC_TREATY,
		INC_EXTERNAL,
		PAGO_GROSS,
		PAGO_TREATY,
		PAGO_EXTERNAL,
		OCR_GROSS,
		OCR_TREATY,
		OCR_EXTERNAL,
		(INC_GROSS_P)		*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	END	 				AS IBNR_GROSS_P,
		(INC_TREATY_P)		*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	END					AS IBNR_TREATY_P,
		(INC_EXTERNAL_P)	*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	END					AS IBNR_EXTERNAL_P,
		(INC_GROSS)			*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	END					AS IBNR_GROSS,
		(INC_TREATY)		*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	END					AS IBNR_TREATY,
		(INC_EXTERNAL)		*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)-1	END					AS IBNR_EXTERNAL,
		(INC_GROSS_P)		*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)		IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)		END					AS ULT_GROSS_P,
		(INC_TREATY_P)		*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)		IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)		END					AS ULT_TREATY_P,
		(INC_EXTERNAL_P)	*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)		IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)		END					AS ULT_EXTERNAL_P,
		(INC_GROSS)			*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)		IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END) 	END					AS ULT_GROSS,
		(INC_TREATY)		*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)		IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)		END					AS ULT_TREATY,
		(INC_EXTERNAL)		*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)		IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_$ END END END)		END					AS ULT_EXTERNAL,
		CANTIDAD			*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_# END END END)-1	IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_# END END END)-1	END					AS IBNR_CANTIDAD,
		CANTIDAD			*	CASE WHEN  (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_# END END END)		IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='ATTRITIONAL' THEN B.ATT_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='LARGE' THEN B.LL_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='WEATHER' THEN B.WE_LDF_# END END END)		END					AS ULT_CANTIDAD,
		CANTIDAD																										AS CANTIDAD,
		IND_WEATHER																										AS IND_WEATHER,
		COBERTURA																										AS COBERTURA,
		CASE WHEN  (CASE WHEN TIPO_SINIESTRO='Attritional' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='Large Loss' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='Weather' THEN B.WE_LDF_$ END END END)	IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='Attritional' THEN B.ATT_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='Large Loss' THEN B.LL_LDF_$ ELSE CASE WHEN TIPO_SINIESTRO='Weather' THEN B.WE_LDF_$ END END END) END	AS FACTOR_LDF_$,
		CASE WHEN  (CASE WHEN TIPO_SINIESTRO='Attritional' THEN B.ATT_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='Large Loss' THEN B.LL_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='Weather' THEN B.WE_LDF_# END END END)	IS NULL THEN 0 
									  ELSE (CASE WHEN TIPO_SINIESTRO='Attritional' THEN B.ATT_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='Large Loss' THEN B.LL_LDF_# ELSE CASE WHEN TIPO_SINIESTRO='Weather' THEN B.WE_LDF_# END END END) END	AS FACTOR_LDF_#,
		0 RECUPERO
		FROM MI_A3_COMPLETO A LEFT JOIN PROCESOS.DBO.BASE_LDF_COMPLETO_V2 B
		ON 
		A.F_OCU_LDF  =B.MES AND A.COBERTURA_IBNR COLLATE SQL_Latin1_General_CP1_CI_AS=B.RAMO_RESERVA

		

		UPDATE MI_A3_COMPLETO_FINAL
		SET NNUMCERT = B.NNUMCERT
		FROM MI_A3_COMPLETO_FINAL AS A, (SELECT NNUMCERT,NNUMSINI,NNUCOSIN FROM SOL.[S1031EBB].RSASOLDB2.SNACSCOR GROUP BY NNUMCERT,NNUMSINI,NNUCOSIN) AS B
		WHERE A.NNUMSINI = B.NNUMSINI
		AND A.NNUCOSIN = B.NNUCOSIN

		---SELECT * FROM MI_A3_COMPLETO_FINAL
		UPDATE MI_A3_COMPLETO_FINAL
		SET COBERTURA='ASISTENCIA'
		WHERE RAMO_RESERVA LIKE ('%ASIST%')

		UPDATE MI_A3_COMPLETO_FINAL
		SET COBERTURA='RC'
		WHERE RAMO_RESERVA LIKE ('%DMA%') or RAMO_RESERVA LIKE ('%MC_RC_CORNER%')

		UPDATE MI_A3_COMPLETO_FINAL
		SET COBERTURA='RC'
		WHERE RAMO_RESERVA LIKE ('%DPE%')

		UPDATE MI_A3_COMPLETO_FINAL
		SET COBERTURA='ROBO'
		WHERE RAMO_RESERVA LIKE ('%ROBO%')

		UPDATE MI_A3_COMPLETO_FINAL
		SET COBERTURA='RC'
		WHERE RAMO_RESERVA IN ('MC_RC_UBER','MC_RC_CORNER')

		UPDATE MI_A3_COMPLETO_FINAL
		SET COBERTURA='DP'
		WHERE RAMO_RESERVA IN ('MC_DP','MP_DP','MC_DAÑOS_UBER','MC_DP_SALFA','MC_DP_SCANIA')

		UPDATE MI_A3_COMPLETO_FINAL
		SET COBERTURA='PT'
		WHERE RAMO_RESERVA IN ('MP_DT','MC_DT','MC_DT_SALFA','MC_DT_SCANIA')



		DECLARE @MES_CORRIENTE AS INT;						
		SET @MES_CORRIENTE=201012;		

		SELECT A1.NNUMSINI, A1.NNUCOSIN, REPLACE(A1.RAMO_RESERVA,' ','') AS RAMO_RESERVA,					
		REPLACE((CASE 
		WHEN RAMO_RESERVA='ASISTENCIA                    '							THEN 'ASISTENCIA'				
		WHEN A1.NFECSINI<200900														THEN RAMO_RESERVA					
		WHEN RAMO_RESERVA LIKE '%TPL%'												THEN (LEFT(RAMO_RESERVA,27))			
		WHEN B.CDESELEM LIKE'ROBO%'													THEN (LEFT(RAMO_RESERVA,26)+'ROBO')				
		WHEN (B.CDESELEM LIKE'PERDIDA TOTAL%' OR B.CDESELEM LIKE'%PERIDA TOTAL%')	THEN (LEFT(RAMO_RESERVA,28)+'PT')
		WHEN A1.NFECSINI>200900														THEN (LEFT(RAMO_RESERVA,27)+'DP')				
		ELSE 'VER'END),' ','') COBERTURA_IBNR,'    'COBERTURA
		INTO #RAMO_RESERVA_HERTZ
		FROM (SELECT SINIESTRO NNUMSINI,EXPEDIENTE NNUCOSIN,RAMO_RESERVA,FECHA_APER  NFECSINI FROM MI_PAGOS_RESERVAS_2 WHERE CIERRE>=@MES_CORRIENTE 
		AND RAMO_KEIRA='MOTOR' AND RAMO_IBNR_IFRS LIKE ('%HERTZ%')
		GROUP BY SINIESTRO,EXPEDIENTE,RAMO_RESERVA,FECHA_APER) A1											
		LEFT JOIN (SELECT * FROM OPENQUERY(SOL,'SELECT SN.NNUMSINI,TB.CCODUNIC,TB.CDESELEM FROM 		
			RSASOLDB2.TBACSTGE TB, RSASOLDB2.SNACSCSI SN WHERE TB.CCODUNIC=SN.CCODCSIN ') ) B ON  A1.NNUMSINI=B.NNUMSINI	
		GROUP BY A1.NNUMSINI, A1.NNUCOSIN, A1.RAMO_RESERVA,					
		(CASE WHEN RAMO_RESERVA='ASISTENCIA                    ' THEN 'ASISTENCIA'				
		WHEN A1.NFECSINI<200900 THEN RAMO_RESERVA					
		WHEN RAMO_RESERVA LIKE '%TPL%' THEN (LEFT(RAMO_RESERVA,27))			
		WHEN B.CDESELEM LIKE'ROBO%' THEN (LEFT(RAMO_RESERVA,26)+'ROBO')				
		WHEN (B.CDESELEM LIKE'PERDIDA TOTAL%' OR B.CDESELEM LIKE'%PERIDA TOTAL%') THEN (LEFT(RAMO_RESERVA,28)+'PT')
		WHEN A1.NFECSINI>200900  THEN (LEFT(RAMO_RESERVA,27)+'DP')				
		ELSE 'VER'END)

		
		UPDATE #RAMO_RESERVA_HERTZ
		SET COBERTURA='DP'
		WHERE COBERTURA_IBNR LIKE ('%DP%')

		UPDATE #RAMO_RESERVA_HERTZ
		SET COBERTURA='ROBO'
		WHERE COBERTURA_IBNR LIKE ('%ROBO%')

		UPDATE #RAMO_RESERVA_HERTZ
		SET COBERTURA='PT'
		WHERE COBERTURA_IBNR LIKE ('%PT%')

		UPDATE MI_A3_COMPLETO_FINAL
		SET COBERTURA=B.COBERTURA
		FROM MI_A3_COMPLETO_FINAL A, #RAMO_RESERVA_HERTZ B
		WHERE A.NNUMSINI=B.NNUMSINI AND A.NNUCOSIN=B.NNUCOSIN
		AND A.COBERTURA IS NULL

		SELECT SINIESTRO,EXPEDIENTE INTO #RECUPOERO FROM MI_PAGOS_RESERVAS_2 WHERE RAMO_KEIRA='MOTOR' and RAMO_IBNR_IFRS like ('%ROBO%') AND DESC_CAUSA='ROBO HABIDO'


		UPDATE MI_A3_COMPLETO_FINAL
		SET RECUPERO=1
		FROM MI_A3_COMPLETO_FINAL A, #RECUPOERO B
		WHERE A.NNUMSINI=B.SINIESTRO AND A.NNUCOSIN=B.EXPEDIENTE

		
		TRUNCATE TABLE REPORTES.DBO.MI_A3_COMPLETO_FINAL 
		INSERT INTO REPORTES.DBO.MI_A3_COMPLETO_FINAL
		SELECT *  FROM MI_A3_COMPLETO_FINAL

		END

END






/*---------CONTROL_MONTO_INCURRIDO-------------

SELECT year(PER)*100+month(PER),SUM(INC_GROSS) AS INC_GROSS,  SUM(ULT_GROSS) AS ULT_GROSS
from [SGF1025].REPORTES.DBO.MI_A3_COMPLETO_FINAL 
where year(PER)*100+month(PER) between 201901 and 202207 and linea_negocio like 'PER%'

GROUP BY year(PER)*100+month(PER)
ORDER BY year(PER)*100+month(PER)


---------CONTROL_DIFERENCIAS_INCURRIDO_ULTIMATE-------------

SELECT NNUMDOCU, COBERTURA, SUM(INC_GROSS_p), SUM(ULT_GROSS_p)
from [SGF1025].REPORTES.DBO.MI_A3_COMPLETO_FINAL 
where year(PER)*100+month(PER) between 201901 and 202207 and linea_negocio like 'PER%'
AND  INC_GROSS> 0 AND ULT_GROSS = 0
GROUP BY NNUMDOCU, COBERTURA
*/






