USE [Transaccional]
GO
/****** Object:  StoredProcedure [dbo].[SP_MI_TRIANGULOS_SINIESTRALIDAD]    Script Date: 14-10-2025 10:28:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


--SP EN DESARROLLO
ALTER  PROCEDURE [dbo].[SP_MI_TRIANGULOS_SINIESTRALIDAD] (
	@CIERRE AS INT
)
AS
   
--exec [dbo].[SP_MI_TRIANGULOS_SINIESTRALIDAD] 202505

BEGIN

-------------------------------------------------------
--TRUNCATE TABLE AUX_MOTOR_06_CHECKPOINTS
--SELECT * FROM AUX_MOTOR_06_CHECKPOINTS
-------------------------------------------------------

/****** Checkpoint Inicio ********************************************************/
INSERT INTO AUX_MOTOR_06_CHECKPOINTS VALUES('TRIANGULOS SINIESTRALIDAD - INICIADO', SYSDATETIME())
/*********************************************************************************/
drop table if exists Transaccional.DBO.AUX1_PRIMA_GANADA_PYG
drop table if exists Transaccional.DBO.AUX3_PRIMA_GANADA_PYG
drop table if exists Transaccional.DBO.AUX4_PRIMA_GANADA_PYG
drop table if exists Transaccional.DBO.AUX5_ATRIBUTOS1
drop table if exists Transaccional.DBO.AUX5_ATRIBUTOS2
drop table if exists Transaccional.dbo.Prima_Siniestros_Balance_Motor
drop table if exists Transaccional.DBO.COBERTURA_STRO

---- inicio
--IMPORTANTE!!!
--RECORDATORIO: VALIDAR QUE LA TABLA sgf1034.GESTIONPORTAFOLIO.DBO.BASE_PYG_MOTOR TENGA DATOS DEL ULTIMO CIERRE!!! DE LO CONTRARIO NO SEGUIR CON LA QUERY
--SELECT MAX(CIERRE) FROM sgf1034.GESTIONPORTAFOLIO.DBO.BASE_PYG_MOTOR

--6 min
DECLARE @CONSULTA AS NVARCHAR(4000)	
SET @CONSULTA = 'SELECT * into Transaccional.DBO.AUX1_PRIMA_GANADA_PYG FROM OPENQUERY(SGF1034,'' 
SELECT 
	CIERRE,[LINEANEGOCIO_KEIRA],NNUMDOCU,NNUMENDO,RAMOCONTABLE,CANAL,CANAL_FINAL,PARTNER_ESTUDIOS,PARTNER_FINAL,
	SUM(CASE WHEN RTRIM(CODSUBCONC) IN (''''10'''') THEN MONTO_MM ELSE 0 END) GWP,
	SUM(CASE WHEN RTRIM(CODSUBCONC) IN (''''20'''',''''21'''') THEN MONTO_MM ELSE 0 END) CWP,
	SUM(CASE WHEN RTRIM(CODSUBCONC) BETWEEN 50 AND 57 THEN MONTO_MM ELSE 0 END) UPR,

	SUM(CASE WHEN RTRIM(CODSUBCONC) IN (''''10'''') THEN MONTO_MM ELSE 0 END) +
	SUM(CASE WHEN RTRIM(CODSUBCONC) IN (''''20'''',''''21'''') THEN MONTO_MM ELSE 0 END) +
	SUM(CASE WHEN RTRIM(CODSUBCONC) BETWEEN 50 AND 57 THEN MONTO_MM ELSE 0 END) NEP,

	SUM(CASE WHEN RTRIM([codsubconc]) IN (''''60'''',''''61'''',''''62'''',''''63'''',''''64'''',''''66'''',''''67'''',''''68'''',''''69'''',''''70'''',''''71'''',''''72'''',''''73'''',''''74'''',''''75'''',''''76'''',''''77'''',''''78'''',''''86'''',''''87'''') THEN MONTO_MM ELSE 0 END) NIC,
	SUM(CASE WHEN RTRIM([codsubconc]) IN (''''60'''',''''61'''',''''62'''',''''63'''',''''64'''',''''66'''',''''67'''',''''68'''',''''69'''',''''70'''',''''71'''',''''72'''',''''73'''',''''74'''',''''75'''',''''76'''',''''77'''',''''78'''',''''86'''',''''87'''') AND [TESDOCGLOSA] LIKE ''''%IBNR%'''' THEN MONTO_MM ELSE 0 END) VAR_IBNR
FROM GESTIONPORTAFOLIO.DBO.BASE_PYG_MOTOR
WHERE RTRIM(RAMOCONTABLE) in (''''8102'''',''''8121'''',''''8202'''',''''8221'''') and CIERRE >= 202201
GROUP BY 
	CIERRE,[LINEANEGOCIO_KEIRA],NNUMDOCU,NNUMENDO,RAMOCONTABLE,CANAL,CANAL_FINAL,PARTNER_ESTUDIOS,PARTNER_FINAL
'')'
EXEC SP_EXECUTESQL @CONSULTA
--32.208.088 registros



/****** Checkpoint 1 ********************************************************/
INSERT INTO AUX_MOTOR_06_CHECKPOINTS VALUES('TRIANGULOS SINIESTRALIDAD - CHECKPOINT 1', SYSDATETIME())
/****************************************************************************/
--segs
drop table if exists aux
SELECT DISTINCT 
	a.NNUMDOCU,a.nnumendo
INTO aux
FROM Transaccional.DBO.AUX1_PRIMA_GANADA_PYG a

--ESTA ES LA PARTE QUE MAS TARDA DEL PROCESO
--1 hora 23 min
drop table if exists AUX2_PRIMA_GANADA_PYG
DECLARE @CONSULTA2 NVARCHAR(4000)
SET @CONSULTA2 = 'SELECT a.nnumdocu, a.nnumendo, a.nnumitem 
into AUX2_PRIMA_GANADA_PYG 
FROM OPENQUERY(SOL,'' 
	SELECT distinct 
		nnumdocu, nnumendo, nnumitem 
	from S1031EBB.RSASOLDB2.SUACSITE
	where NFEINVIG >= 20200101
'') a
left join sgf1025.transaccional.dbo.aux b on 
	a.nnumdocu=b.nnumdocu and 
	a.nnumendo=B.nnumendo'
EXEC SP_EXECUTESQL @CONSULTA2
--32.208.088 registros

--segs
drop table if exists Transaccional.DBO.AUX3_PRIMA_GANADA_PYG
select NNUMDOCU,NNUMENDO,MAX(NNUMITEM) NNUMITEM
into Transaccional.DBO.AUX3_PRIMA_GANADA_PYG
from AUX2_PRIMA_GANADA_PYG
group by NNUMDOCU,NNUMENDO

drop table if exists aux
drop table if exists AUX2_PRIMA_GANADA_PYG
--PRIMER CHECKPOINT, EN CASO QUE EL PROCESO SE CAIGA SI HASTA ACA YA SE EJECUTÓ SE PUEDE RETOMAR DESDE AQUI



/****** Checkpoint 2 ********************************************************/
INSERT INTO AUX_MOTOR_06_CHECKPOINTS VALUES('TRIANGULOS SINIESTRALIDAD - CHECKPOINT 2', SYSDATETIME())
/****************************************************************************/
--1 min
drop table if exists Transaccional.DBO.AUX4_PRIMA_GANADA_PYG
SELECT  
	CIERRE,[LINEANEGOCIO_KEIRA],A.NNUMDOCU,A.NNUMENDO,NNUMITEM,CANAL,CANAL_FINAL,PARTNER_ESTUDIOS,PARTNER_FINAL,
	sum(gwp) GWP,sum(CWP) CWP,SUM(UPR) UPR,SUM(NEP) NEP,SUM(NIC) NIC,SUM(VAR_IBNR) VAR_IBNR
INTO Transaccional.DBO.AUX4_PRIMA_GANADA_PYG
FROM Transaccional.DBO.AUX1_PRIMA_GANADA_PYG A
LEFT JOIN Transaccional.DBO.AUX3_PRIMA_GANADA_PYG B
ON A.NNUMDOCU=B.NNUMDOCU AND A.NNUMENDO=B.NNUMENDO
WHERE RAMOCONTABLE IN ('8102','8121','8202','8221')
GROUP BY 
	CIERRE,[LINEANEGOCIO_KEIRA],A.NNUMDOCU,A.NNUMENDO,NNUMITEM,CANAL,CANAL_FINAL,PARTNER_ESTUDIOS,PARTNER_FINAL 

--segs
DELETE from Transaccional.DBO.AUX4_PRIMA_GANADA_PYG
WHERE GWP=0 AND NEP=0 AND UPR=0 and NIC=0 AND VAR_IBNR=0

--segs
drop table if exists Transaccional.DBO.AUX5_ATRIBUTOS1
SELECT NNUMDOCU,MAX([LINEANEGOCIO_KEIRA]) [LINEANEGOCIO_KEIRA],MAX(CANAL) CANAL,MAX(CANAL_FINAL) CANAL_FINAL,MAX(PARTNER_ESTUDIOS) PARTNER_ESTUDIOS,MAX(PARTNER_FINAL) PARTNER_FINAL,MIN(CIERRE) MES_EMISION
INTO Transaccional.DBO.AUX5_ATRIBUTOS1
FROM Transaccional.DBO.AUX4_PRIMA_GANADA_PYG
GROUP BY NNUMDOCU

--segs
drop table if exists Transaccional.DBO.AUX5_ATRIBUTOS2
SELECT NNUMDOCU,NNUMITEM,MAX([LINEANEGOCIO_KEIRA]) [LINEANEGOCIO_KEIRA], MAX(CANAL) CANAL,MAX(CANAL_FINAL) CANAL_FINAL,MAX(PARTNER_ESTUDIOS) PARTNER_ESTUDIOS,MAX(PARTNER_FINAL) PARTNER_FINAL,MIN(CIERRE) MES_EMISION
INTO Transaccional.DBO.AUX5_ATRIBUTOS2
FROM Transaccional.DBO.AUX4_PRIMA_GANADA_PYG
GROUP BY NNUMDOCU,NNUMITEM

--segs
drop table if exists Transaccional.DBO.COBERTURA_STRO
SELECT NNUMSINI,NNUCOSIN,MIN(COBERTURA) COBERTURA 
INTO Transaccional.DBO.COBERTURA_STRO
FROM SGF1025.REPORTES.DBO.MI_A3_COMPLETO_FINAL
GROUP BY NNUMSINI,NNUCOSIN

--segs
drop table if exists #INCURRIDO	
select 
	A.[LINEA_NEGOCIO],NUM_POLIZA,NUM_ITEM,ROUND(FECHA_OCU/100,0) FECHA_OCU,RAMO_IBNR_IFRS,
	sum(CASE WHEN RTRIM(RAMO_IBNR_IFRS) IN ('MP_DP','MC_DP','MC_DAÑOS_UBER') OR (RTRIM(B.COBERTURA)='DP' and RTRIM(LINEA_NEGOCIO)='PERSONAL') THEN CASE WHEN CONCEPTO LIKE 'RV%' AND CIERRE < @CIERRE THEN 0 ELSE MONTO_NET_CLP END ELSE 0 END) AS INC_DP,
	sum(CASE WHEN RTRIM(RAMO_IBNR_IFRS) IN ('MP_DT','MC_DT') OR (RTRIM(B.COBERTURA)='PT' and RTRIM(LINEA_NEGOCIO)='PERSONAL') THEN CASE WHEN CONCEPTO LIKE 'RV%' AND CIERRE < @CIERRE THEN 0 ELSE MONTO_NET_CLP END ELSE 0 END) AS INC_PT,
	sum(CASE WHEN RTRIM(RAMO_IBNR_IFRS) IN ('MP_DMA','MP_DPE','MC_DMA','MC_DPE','MC_RC_UBER') OR (RTRIM(B.COBERTURA)='RC' and RTRIM(LINEA_NEGOCIO)='PERSONAL') THEN CASE WHEN CONCEPTO LIKE 'RV%' AND CIERRE < @CIERRE THEN 0 ELSE MONTO_NET_CLP END ELSE 0 END) AS INC_RC,
	sum(CASE WHEN RTRIM(RAMO_IBNR_IFRS) IN ('MP_ROBO','MC_ROBO') OR (RTRIM(B.COBERTURA)='ROBO' and RTRIM(LINEA_NEGOCIO)='PERSONAL') THEN CASE WHEN CONCEPTO LIKE 'RV%' AND CIERRE < @CIERRE THEN 0 ELSE MONTO_NET_CLP END ELSE 0 END) AS INC_ROBO,
	
	sum(CASE WHEN RTRIM(RAMO_IBNR_IFRS) IN ('MC_BUSES_DMA','MC_BUSES_DPE') THEN CASE WHEN CONCEPTO LIKE 'RV%' AND CIERRE < @CIERRE THEN 0 ELSE MONTO_NET_CLP END ELSE 0 END) AS INC_RC_BUSES,
	sum(CASE WHEN RTRIM(RAMO_IBNR_IFRS) IN ('MC_DMA_SALFA','MC_DPE_SALFA','MC_DP_SALFA','MC_DT_SALFA','MC_ROBO_SALFA') THEN CASE WHEN CONCEPTO LIKE 'RV%' AND CIERRE < @CIERRE THEN 0 ELSE MONTO_NET_CLP END ELSE 0 END) AS INC_SALFA,
	sum(CASE WHEN RTRIM(RAMO_IBNR_IFRS) IN ('MC_DMA_SCANIA','MC_DPE_SCANIA','MC_DP_SCANIA','MC_DT_SCANIA','MC_ROBO_SCANIA') THEN CASE WHEN CONCEPTO LIKE 'RV%' AND CIERRE < @CIERRE THEN 0 ELSE MONTO_NET_CLP END ELSE 0 END) AS INC_SCANIA,
	
	sum(CASE WHEN CONCEPTO LIKE 'RV%' AND CIERRE < @CIERRE THEN 0 ELSE MONTO_NET_CLP END) AS INC_TOTAL,
	sum(CASE WHEN CONCEPTO NOT LIKE 'RV%' AND CIERRE <= @CIERRE THEN MONTO_NET_CLP ELSE 0 END) AS PAGOS_TOTAL,
	sum(CASE WHEN CONCEPTO LIKE 'RV%' AND CIERRE = @CIERRE THEN MONTO_NET_CLP ELSE 0 END) AS RVA_TOTAL
INTO #INCURRIDO		
--from SGF1034."Actuarial"."dbo"."Pagos_Rvas" a	
from openquery(sgf1034, 'select * from Actuarial.dbo.Pagos_Rvas') a
LEFT JOIN Transaccional.DBO.COBERTURA_STRO B ON A.SINIESTRO=B.NNUMSINI AND A.EXPEDIENTE=B.NNUCOSIN
where CIERRE <= @CIERRE			
and (RAMO_IBNR_IFRS like 'MC_%' or RAMO_IBNR_IFRS like 'MP_%') AND FECHA_OCU>=20180101
group by A.[LINEA_NEGOCIO],A.NUM_POLIZA,NUM_ITEM,ROUND(FECHA_OCU/100,0),RAMO_IBNR_IFRS

--segs
drop table if exists #INCURRIDO2
SELECT A.*,[LINEANEGOCIO_KEIRA],CANAL,CANAL_FINAL,PARTNER_ESTUDIOS,PARTNER_FINAL,MES_EMISION
INTO #INCURRIDO2
FROM #INCURRIDO	A	
LEFT JOIN Transaccional.DBO.AUX5_ATRIBUTOS2 B
ON B.NNUMDOCU=A.NUM_POLIZA AND B.NNUMITEM=A.NUM_ITEM

--segs
UPDATE #INCURRIDO2
SET CANAL=B.CANAL,CANAL_FINAL=B.CANAL_FINAL,PARTNER_ESTUDIOS=B.PARTNER_ESTUDIOS,PARTNER_FINAL=B.PARTNER_FINAL,MES_EMISION=B.MES_EMISION,[LINEANEGOCIO_KEIRA]=B.[LINEANEGOCIO_KEIRA]
FROM #INCURRIDO2 A
LEFT JOIN Transaccional.DBO.AUX5_ATRIBUTOS1 B
ON B.NNUMDOCU=A.NUM_POLIZA
WHERE A.CANAL IS NULL

---- SE GENERA EXPOSICIÓN TECNICA DE NUESTROS CUBOS DE INFORMACIÓN TECNICA.
DROP TABLE IF EXISTS #EXPOSICION
SELECT 
	B.MES_EMISION,YEAR(PER)*100+MONTH(PER) CIERRE,A.NNUMDOCU,A.NNUMITEM,[LINEANEGOCIO_KEIRA],
	B.CANAL,B.CANAL_FINAL,B.PARTNER_ESTUDIOS,B.PARTNER_FINAL,
	SUM(PRIMA_DEV) PRIMA_DEV_UF,SUM(EXPOS) EXPOS,
	SUM(CANT_ULT_DP) CANT_ULT_DP,SUM(CANT_ULT_PT) CANT_ULT_PT,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO,SUM(CANT_ULT_RC) CANT_ULT_RC
INTO #EXPOSICION
FROM TRANSACCIONAL.DBO.TABLERO_MOTOR A
LEFT JOIN Transaccional.DBO.AUX5_ATRIBUTOS2 B
ON B.NNUMDOCU=A.NNUMDOCU AND B.NNUMITEM=A.NNUMITEM
WHERE YEAR(PER)*100+MONTH(PER)>=202101 AND B.NNUMITEM IS NOT NULL
GROUP BY 
	B.MES_EMISION,A.NNUMDOCU,A.NNUMITEM,YEAR(PER)*100+MONTH(PER),B.CANAL,B.CANAL_FINAL,B.PARTNER_ESTUDIOS,B.PARTNER_FINAL,[LINEANEGOCIO_KEIRA]



/****** Checkpoint 3 ********************************************************/
INSERT INTO AUX_MOTOR_06_CHECKPOINTS VALUES('TRIANGULOS SINIESTRALIDAD - CHECKPOINT 3', SYSDATETIME())
/****************************************************************************/
--segs
DROP TABLE IF EXISTS #UNION
---------- UNION ---------- Query hasta linea 238
select 
	B.MES_EMISION,A.CIERRE,A.NNUMDOCU,A.NNUMITEM,A.[LINEANEGOCIO_KEIRA],A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,
	sum(gwp) GWP,sum(CWP) CWP,SUM(UPR) UPR,SUM(NEP) NEP,SUM(NIC) NIC,SUM(VAR_IBNR) VAR_IBNR,
	0 INC_DP,0 INC_PT,0 INC_RC,0 INC_ROBO,0 INC_RC_BUSES,0 INC_SALFA,0 INC_SCANIA,0 INC_TOTAL,
	0 PRIMA_DEV_UF,0 EXPOS,0 CANT_ULT_DP,0 CANT_ULT_PT,0 CANT_ULT_ROBO,0 CANT_ULT_RC
INTO #UNION
from Transaccional.DBO.AUX4_PRIMA_GANADA_PYG A
LEFT JOIN Transaccional.DBO.AUX5_ATRIBUTOS2 B
ON B.NNUMDOCU=A.NNUMDOCU AND B.NNUMITEM=A.NNUMITEM
GROUP BY A.CIERRE,A.[LINEANEGOCIO_KEIRA],B.MES_EMISION,A.NNUMDOCU,A.NNUMITEM,A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL

UNION ALL

SELECT  
	A.MES_EMISION,A.FECHA_OCU,A.NUM_POLIZA,A.NUM_ITEM,
	CASE WHEN [LINEA_NEGOCIO]='PERSONAL' THEN 'PERSONAL' ELSE 'COMMERCIAL' END,A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,0 GWP,0 CWP,0 UPR,0 NEP,0 NIC,0 VAR_IBNR,
	SUM(INC_DP)/1000000,SUM(INC_PT)/1000000,SUM(INC_RC)/1000000,SUM(INC_ROBO)/1000000,SUM(INC_RC_BUSES)/1000000 INC_RC_BUSES,SUM(INC_SALFA)/1000000 INC_SALFA,SUM(INC_SCANIA)/1000000 INC_SACNIA,SUM(INC_TOTAL)/1000000,
	0 PRIMA_DEV_UF,0 EXPOS,0 CANT_ULT_DP,0 CANT_ULT_PT,0 CANT_ULT_ROBO,0 CANT_ULT_RC
FROM #INCURRIDO2 A
GROUP BY A.FECHA_OCU,CASE WHEN [LINEA_NEGOCIO]='PERSONAL' THEN 'PERSONAL' ELSE 'COMMERCIAL' END,A.MES_EMISION,A.NUM_POLIZA,A.NUM_ITEM,A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL

UNION ALL

SELECT 
	MES_EMISION,CIERRE,NNUMDOCU,NNUMITEM,[LINEANEGOCIO_KEIRA],CANAL,CANAL_FINAL,PARTNER_ESTUDIOS,PARTNER_FINAL,
	0 GWP,0 CWP,0 UPR,0 NEP,0 NIC,0 VAR_IBNR,
	0 INC_DP,0 INC_PT,0 INC_RC,0 INC_ROBO,0 INC_RC_BUSES,0 INC_SALFA,0 INC_SCANIA,0 INC_TOTAL,
	SUM(PRIMA_DEV_UF) PRIMA_DEV_UF,SUM(EXPOS) EXPOS,SUM(CANT_ULT_DP) CANT_ULT_DP,SUM(CANT_ULT_PT) CANT_ULT_PT,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO,SUM(CANT_ULT_RC) CANT_ULT_RC
FROM  #EXPOSICION
GROUP BY MES_EMISION,[LINEANEGOCIO_KEIRA],CIERRE,NNUMDOCU,NNUMITEM,CANAL,CANAL_FINAL,PARTNER_ESTUDIOS,PARTNER_FINAL
---------- UNION ----------


--segs
DROP TABLE IF EXISTS #ATRIBUTOS
SELECT POLIZA NNUMDOCU, ITEM NNUMITEM, GRUPO_FLOTA, CODRAMO ,TAMAÑO_FLOTA, MAX(CHANNEL) CANAL2,MAX(NUEVA_RENOV) NUEVA_RENOV,MAX(TIPO_PLAN) TIPO_PLAN,MAX(NUEVA_RENOV2) NUEVA_RENOV2,MIN(MES_INI) MES_INI, 
MAX(CASE WHEN FLOTA LIKE 'SEG%' THEN CASE WHEN DATEDIFF(DAY,FECINVIG,FECTEVIG)>180 THEN 'SEGXKM ANUAL' ELSE 'SEGXKM MENSUAL' END ELSE 'RESTO' END) SEGMENTO,
MAX(EXISTE_INSPECCION) AS EXISTE_INSPECCION,MAX(INSP_MODALIDAD) INSP_MODALIDAD,
MAX(CASE WHEN RTRIM(GAMA_VEH) IN ('AGRAVADOS','BLOQUEADOS') THEN GAMA_VEH ELSE 'RESTO' END) SEGMENTO_ROBO,
MIN(FECINVIG) FECINVIG
INTO #ATRIBUTOS
--FROM sgf1034.GestionPortafolio.dbo.atributos2
FROM Transaccional.dbo.atributos2
GROUP BY POLIZA,ITEM, GRUPO_FLOTA, CODRAMO ,TAMAÑO_FLOTA


----- salida guardado poliza item
DROP TABLE IF EXISTS #SALIDA
DROP TABLE IF EXISTS #AJUSTES1
DROP TABLE IF EXISTS #AJUSTES2
DROP TABLE IF EXISTS #AJUSTES3
DROP TABLE IF EXISTS #AJUSTES_NIC


--3 min
SELECT 
	LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3 Q_EMI,
	LEFT(A.CIERRE,4)*100+(ROUND((RIGHT(A.CIERRE,2)-1)/3,0)+1)*3 Q_DEV,
	A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,
	CASE 
		WHEN YEAR(FECINVIG)<2023 THEN 202303 
		WHEN YEAR(FECINVIG) IS NULL THEN LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3 
		ELSE YEAR(FECINVIG)*100+(ROUND((MONTH(FECINVIG)-1)/3,0)+1)*3 
	END Q_VIG,
	A.LINEANEGOCIO_KEIRA,CANAL2,NUEVA_RENOV,EXISTE_INSPECCION,INSP_MODALIDAD,TIPO_PLAN,SEGMENTO,SEGMENTO_ROBO,A.NNUMDOCU,A.NNUMITEM,MES_EMISION,CIERRE MES_DEV,NUEVA_RENOV2,MES_INI,GRUPO_FLOTA,CODRAMO,TAMAÑO_FLOTA,
	SUM(GWP) GWP,SUM(CWP) CWP,SUM(UPR) UPR,SUM(GWP)+SUM(CWP) NWP,
	SUM(NEP) NEP, SUM(NEP) NEP_AJUST,
	SUM(NIC) NIC, SUM(NIC) NIC_AJUST,
	SUM(VAR_IBNR) VAR_IBNR, SUM(VAR_IBNR) VAR_IBNR_AJUST,
	SUM(INC_DP) INC_DP,SUM(INC_PT) INC_PT,SUM(INC_RC) INC_RC,SUM(INC_ROBO) INC_ROBO,SUM(INC_RC_BUSES) INC_RC_BUSES,SUM(INC_SALFA) INC_SALFA,SUM(INC_SCANIA) INC_SCANIA,SUM(INC_TOTAL) INC_TOTAL,
	SUM(INC_DP) INC_DP_AJUST,SUM(INC_PT) INC_PT_AJUST,SUM(INC_RC) INC_RC_AJUST,SUM(INC_ROBO) INC_ROBO_AJUST,SUM(INC_RC_BUSES) INC_RC_BUSES_AJUST,SUM(INC_SALFA) INC_SALFA_AJUST,SUM(INC_SCANIA) INC_SCANIA_AJUST,SUM(INC_TOTAL) INC_TOTAL_AJUST,
	SUM(PRIMA_DEV_UF) PRIMA_DEV_UF, SUM(PRIMA_DEV_UF) PRIMA_DEV_UF_AJUST,
	SUM(EXPOS) EXPOS, SUM(EXPOS) EXPOS_AJUST,
	SUM(CANT_ULT_DP) CANT_ULT_DP,SUM(CANT_ULT_PT) CANT_ULT_PT,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO,SUM(CANT_ULT_RC) CANT_ULT_RC,
	SUM(CANT_ULT_DP) CANT_ULT_DP_AJUST,SUM(CANT_ULT_PT) CANT_ULT_PT_AJUST,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO_AJUST,SUM(CANT_ULT_RC) CANT_ULT_RC_AJUST            
INTO #SALIDA
FROM #UNION A
LEFT JOIN #ATRIBUTOS B ON A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM
WHERE CIERRE<=@CIERRE ---cambiar fecha --202403
GROUP BY 
	LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3,
	LEFT(A.CIERRE,4)*100+(ROUND((RIGHT(A.CIERRE,2)-1)/3,0)+1)*3,
	A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,
	CASE 
		WHEN YEAR(FECINVIG)<2023 THEN 202303 
		WHEN YEAR(FECINVIG) IS NULL THEN LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3 
		ELSE YEAR(FECINVIG)*100+(ROUND((MONTH(FECINVIG)-1)/3,0)+1)*3 
	END,
	A.LINEANEGOCIO_KEIRA,CANAL2,NUEVA_RENOV,EXISTE_INSPECCION,INSP_MODALIDAD,TIPO_PLAN,SEGMENTO,SEGMENTO_ROBO,A.NNUMDOCU,A.NNUMITEM,MES_EMISION,CIERRE,NUEVA_RENOV2,MES_INI, GRUPO_FLOTA, CODRAMO ,TAMAÑO_FLOTA

-- Validacion
--select distinct q_emi from #SALIDA
--select distinct q_dev from #SALIDA



/****** Checkpoint 4 ********************************************************/
INSERT INTO AUX_MOTOR_06_CHECKPOINTS VALUES('TRIANGULOS SINIESTRALIDAD - CHECKPOINT 4', SYSDATETIME())
/****************************************************************************/
--segs
SELECT 
	MES_DEV,MES_EMISION,CANAL_FINAL,PARTNER_ESTUDIOS,LINEANEGOCIO_KEIRA,
	SUM(NEP) NEP,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE NEP END) NEP_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN NEP ELSE 0 END) NEP_NULL
INTO #AJUSTES1
FROM #SALIDA
WHERE MES_EMISION >= 202210 --fecha se deja igual
GROUP BY MES_DEV,MES_EMISION,CANAL_FINAL,PARTNER_ESTUDIOS,LINEANEGOCIO_KEIRA
HAVING SUM(CASE WHEN NUEVA_RENOV IS NULL THEN NEP ELSE 0 END)<>0


--segs
UPDATE #SALIDA 
SET 
NEP_AJUST=CASE WHEN A.NUEVA_RENOV IS NULL THEN 0 WHEN NEP_SIN_NULL=0 THEN A.NEP ELSE A.NEP*B.NEP/NEP_SIN_NULL END
FROM #SALIDA A
LEFT JOIN #AJUSTES1 B ON 
	A.MES_DEV=B.MES_DEV AND 
	A.CANAL_FINAL=B.CANAL_FINAL AND 
	A.PARTNER_ESTUDIOS=B.Partner_ESTUDIOS AND 
	A.LINEANEGOCIO_KEIRA=B.LINEANEGOCIO_KEIRA AND 
	A.MES_EMISION=B.MES_EMISION
WHERE B.CANAL_FINAL IS NOT NULL AND NEP_SIN_NULL<>0

--segs
SELECT 
	MES_DEV,CANAL_FINAL,PARTNER_ESTUDIOS,LINEANEGOCIO_KEIRA,
	SUM(NEP) NEP,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE NEP END) NEP_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN NEP ELSE 0 END) NEP_NULL
INTO #AJUSTES2
FROM #SALIDA
WHERE MES_EMISION<202210
GROUP BY MES_DEV,CANAL_FINAL,PARTNER_ESTUDIOS,LINEANEGOCIO_KEIRA
HAVING SUM(CASE WHEN NUEVA_RENOV IS NULL THEN NEP ELSE 0 END)<>0

--segs
UPDATE #SALIDA 
SET 
NEP_AJUST=CASE WHEN A.NUEVA_RENOV IS NULL THEN 0 WHEN NEP_SIN_NULL=0 THEN A.NEP ELSE A.NEP*B.NEP/NEP_SIN_NULL END
FROM #SALIDA A
LEFT JOIN #AJUSTES2 B ON A.MES_DEV=B.MES_DEV AND A.CANAL_FINAL=B.CANAL_FINAL AND A.PARTNER_ESTUDIOS=B.Partner_ESTUDIOS
AND A.LINEANEGOCIO_KEIRA=B.LINEANEGOCIO_KEIRA
WHERE MES_EMISION<202210 AND B.CANAL_FINAL IS NOT NULL AND NEP_SIN_NULL<>0

--segs
SELECT 
	MES_DEV,CANAL_FINAL,PARTNER_ESTUDIOS,LINEANEGOCIO_KEIRA,
	SUM(NIC) NIC,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE NIC END) NIC_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN NIC ELSE 0 END) NIC_NULL,
	SUM(VAR_IBNR) VAR_IBNR,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE VAR_IBNR END) VAR_IBNR_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN VAR_IBNR ELSE 0 END) VAR_IBNR_NULL
INTO #AJUSTES_NIC
FROM #SALIDA
GROUP BY MES_DEV,CANAL_FINAL,PARTNER_ESTUDIOS,LINEANEGOCIO_KEIRA
HAVING SUM(CASE WHEN NUEVA_RENOV IS NULL THEN NIC ELSE 0 END)<>0

--segs
UPDATE #SALIDA 
SET 
NIC_AJUST=CASE WHEN A.NUEVA_RENOV IS NULL THEN 0 WHEN NIC_SIN_NULL=0 THEN A.NIC ELSE A.NIC*B.NIC/NIC_SIN_NULL END
FROM #SALIDA A
LEFT JOIN #AJUSTES_NIC B ON 
	A.MES_DEV=B.MES_DEV AND 
	A.CANAL_FINAL=B.CANAL_FINAL AND 
	A.PARTNER_ESTUDIOS=B.Partner_ESTUDIOS AND 
	A.LINEANEGOCIO_KEIRA=B.LINEANEGOCIO_KEIRA
WHERE B.CANAL_FINAL IS NOT NULL AND NIC_SIN_NULL<>0

--segs
UPDATE #SALIDA 
SET 
VAR_IBNR_AJUST=CASE WHEN A.NUEVA_RENOV IS NULL THEN 0 WHEN VAR_IBNR_SIN_NULL=0 THEN A.NIC ELSE A.VAR_IBNR*B.VAR_IBNR/VAR_IBNR_SIN_NULL END
FROM #SALIDA A
LEFT JOIN #AJUSTES_NIC B ON 
	A.MES_DEV=B.MES_DEV AND 
	A.CANAL_FINAL=B.CANAL_FINAL AND 
	A.PARTNER_ESTUDIOS=B.Partner_ESTUDIOS AND 
	A.LINEANEGOCIO_KEIRA=B.LINEANEGOCIO_KEIRA
WHERE B.CANAL_FINAL IS NOT NULL AND VAR_IBNR_SIN_NULL<>0

--segs
SELECT 
	MES_EMISION,MES_DEV,CANAL_FINAL,PARTNER_ESTUDIOS,LINEANEGOCIO_KEIRA,

	SUM(INC_DP) INC_DP,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE INC_DP END) INC_DP_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN INC_DP ELSE 0 END) INC_DP_NULL,
	SUM(INC_PT) INC_PT,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE INC_PT END) INC_PT_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN INC_PT ELSE 0 END) INC_PT_NULL,
	SUM(INC_ROBO) INC_ROBO,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE INC_ROBO END) INC_ROBO_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN INC_ROBO ELSE 0 END) INC_ROBO_NULL,
	SUM(INC_RC) INC_RC,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE INC_RC END) INC_RC_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN INC_RC ELSE 0 END) INC_RC_NULL,

	SUM(CANT_ULT_DP) CANT_ULT_DP,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE CANT_ULT_DP END) CANT_ULT_DP_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN CANT_ULT_DP ELSE 0 END) CANT_ULT_DP_NULL,
	SUM(CANT_ULT_PT) CANT_ULT_PT,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE CANT_ULT_PT END) CANT_ULT_PT_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN CANT_ULT_PT ELSE 0 END) CANT_ULT_PT_NULL,
	SUM(CANT_ULT_ROBO) CANT_ULT_ROBO,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE CANT_ULT_ROBO END) CANT_ULT_ROBO_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN CANT_ULT_ROBO ELSE 0 END) CANT_ULT_ROBO_NULL,
	SUM(CANT_ULT_RC) CANT_ULT_RC,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE CANT_ULT_RC END) CANT_ULT_RC_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN CANT_ULT_RC ELSE 0 END) CANT_ULT_RC_NULL,

	SUM(PRIMA_DEV_UF) PRIMA_DEV_UF,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE PRIMA_DEV_UF END) PRIMA_DEV_UF_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN PRIMA_DEV_UF ELSE 0 END) PRIMA_DEV_UF_NULL,

	SUM(EXPOS) EXPOS,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN 0 ELSE EXPOS END) EXPOS_SIN_NULL,
	SUM(CASE WHEN NUEVA_RENOV IS NULL THEN EXPOS ELSE 0 END) EXPOS_NULL
INTO #AJUSTES3
FROM #SALIDA
WHERE MES_DEV<=@CIERRE
GROUP BY MES_EMISION,MES_DEV,CANAL_FINAL,PARTNER_ESTUDIOS,LINEANEGOCIO_KEIRA
HAVING SUM(CASE WHEN NUEVA_RENOV IS NULL THEN INC_DP+INC_PT+INC_ROBO+INC_RC ELSE 0 END)<>0

--segs
UPDATE #SALIDA 
SET 
	INC_DP_AJUST		=	CASE WHEN A.NUEVA_RENOV IS NULL THEN 0 WHEN INC_DP_SIN_NULL			= 0 THEN A.INC_DP		ELSE A.INC_DP*B.INC_DP/INC_DP_SIN_NULL END,
	INC_PT_AJUST		=	CASE WHEN A.NUEVA_RENOV IS NULL THEN 0 WHEN INC_PT_SIN_NULL			= 0 THEN A.INC_PT		ELSE A.INC_PT*B.INC_PT/INC_PT_SIN_NULL END,
	INC_ROBO_AJUST		=	CASE WHEN A.NUEVA_RENOV IS NULL THEN 0 WHEN INC_ROBO_SIN_NULL		= 0 THEN A.INC_ROBO		ELSE A.INC_ROBO*B.INC_ROBO/INC_ROBO_SIN_NULL END,
	INC_RC_AJUST		=	CASE WHEN A.NUEVA_RENOV IS NULL THEN 0 WHEN INC_RC_SIN_NULL			= 0 THEN A.INC_RC		ELSE A.INC_RC*B.INC_RC/INC_RC_SIN_NULL END,
	PRIMA_DEV_UF_AJUST	=	CASE WHEN A.NUEVA_RENOV IS NULL THEN 0 WHEN PRIMA_DEV_UF_SIN_NULL	= 0 THEN A.PRIMA_DEV_UF ELSE A.PRIMA_DEV_UF*B.PRIMA_DEV_UF/PRIMA_DEV_UF_SIN_NULL END,
	EXPOS_AJUST			=	CASE WHEN A.NUEVA_RENOV IS NULL THEN 0 WHEN EXPOS_SIN_NULL			= 0 THEN A.EXPOS		ELSE A.EXPOS*B.EXPOS/EXPOS_SIN_NULL END
FROM #SALIDA A
LEFT JOIN #AJUSTES3 B ON 
	A.MES_DEV=B.MES_DEV AND 
	A.MES_EMISION=B.MES_EMISION AND 
	A.CANAL_FINAL=B.CANAL_FINAL AND 
	A.PARTNER_ESTUDIOS=B.Partner_ESTUDIOS AND 
	A.LINEANEGOCIO_KEIRA=B.LINEANEGOCIO_KEIRA
WHERE 
	A.MES_DEV<=@CIERRE AND B.CANAL_FINAL IS NOT NULL AND 
	(INC_DP_SIN_NULL<>0 OR INC_PT_SIN_NULL<>0 OR INC_ROBO_SIN_NULL<>0 OR INC_RC_SIN_NULL<>0 OR PRIMA_DEV_UF_SIN_NULL<>0 OR EXPOS_SIN_NULL<>0)

--segs
UPDATE #SALIDA
SET 
INC_TOTAL=INC_DP+INC_PT+INC_ROBO+INC_RC,
INC_TOTAL_AJUST=INC_DP_AJUST+INC_PT_AJUST+INC_ROBO_AJUST+INC_RC_AJUST

--SEGS
ALTER TABLE #SALIDA
ADD SUCURSAL VARCHAR(255)

--NUEVAS VARIABLES
ALTER TABLE #SALIDA
ADD MARCA VARCHAR(200)

ALTER TABLE #SALIDA
ADD MODELO VARCHAR(200)

ALTER TABLE #SALIDA
ADD MARCA_MODELO VARCHAR(250)

ALTER TABLE #SALIDA
ADD VIGENCIA VARCHAR(50)

ALTER TABLE #SALIDA
ADD DEDUCIBLE VARCHAR(5)
--

--segs
drop table if exists Transaccional.dbo.Prima_Siniestros_Balance_Motor
SELECT * 
into Transaccional.dbo.Prima_Siniestros_Balance_Motor
FROM #SALIDA
--CHECKPOINT

--segs
UPDATE Transaccional.dbo.Prima_Siniestros_Balance_Motor
SET [CANAL_FINAL] = CASE 
	WHEN [CANAL] LIKE '%CANAL%ASESOR%' THEN 'CAS' 
	WHEN [CANAL] LIKE '%NEGOCIOS%CORPORATIVOS%' THEN 'LBR' 
	WHEN [CANAL] LIKE '%CANAL%DIRECTO%' THEN 'DIR' 
	WHEN [CANAL] LIKE '%AFFINITY%' THEN 'AFF' 
	WHEN [CANAL] LIKE '%UNDEFINED%' THEN 'UND' 
	ELSE 'EYP' END
--FROM Transaccional.dbo.Prima_Siniestros_Balance_Motor
WHERE MES_DEV = @CIERRE --202404

select * into #SALIDA_BKP from Transaccional.dbo.Prima_Siniestros_Balance_Motor
-----------------------------------------------------------------------------------------------------------------------------------------
--CORRECCION DE CANAL Y PARTNER
update Transaccional.dbo.Prima_Siniestros_Balance_Motor
set
	CANAL_FINAL = CASE WHEN B.CANAL_ACTUAL IS NULL OR B.CANAL_ACTUAL = '' THEN A.CANAL_FINAL ELSE B.CANAL_ACTUAL END,
	PARTNER_ESTUDIOS = CASE WHEN B.[PARTNER] IS NULL OR B.[PARTNER] = '' THEN A.PARTNER_ESTUDIOS ELSE B.[PARTNER] END
from Transaccional.dbo.Prima_Siniestros_Balance_Motor A
left join (
	select
		NNUMDOCU,
		CASE
			WHEN CANAL_ACTUAL LIKE '%CANAL%ASESOR%' THEN 'CAS' 
			WHEN CANAL_ACTUAL LIKE '%CORPORATIVO%' THEN 'LBR' 
			WHEN CANAL_ACTUAL LIKE '%CANAL%DIRECTO%' THEN 'DIR' 
			WHEN CANAL_ACTUAL LIKE '%AFFINITY%' THEN 'AFF' 
			WHEN CANAL_ACTUAL LIKE '%UNDEFINED%' THEN 'UND'
			WHEN CANAL_ACTUAL LIKE '%PYME%' THEN 'EYP'
			ELSE CANAL_ACTUAL
		END AS CANAL_ACTUAL,
		[PARTNER]
	from reportes.dbo.POLIZAS_MOVILIDAD_NUEVO
) B ON
A.NNUMDOCU = B.NNUMDOCU

--CORRECCION DE NOMBRES A CANAL Y PARTNER
update Transaccional.dbo.Prima_Siniestros_Balance_Motor
set
	CANAL_FINAL = CASE 
		WHEN CANAL_FINAL = '' THEN NULL
		ELSE CANAL_FINAL
	END,
	PARTNER_ESTUDIOS = CASE
		WHEN PARTNER_ESTUDIOS = '' THEN NULL
		ELSE PARTNER_ESTUDIOS
	END

update Transaccional.dbo.Prima_Siniestros_Balance_Motor
set
	PARTNER_ESTUDIOS = 'NO APLICA'
where
	CANAL_FINAL <> 'AFF'

update Transaccional.dbo.Prima_Siniestros_Balance_Motor
set
	PARTNER_ESTUDIOS = CASE
		WHEN PARTNER_ESTUDIOS = 'ABCDIN' THEN 'ABC DIN'
		WHEN PARTNER_ESTUDIOS IN ('DEALER DIRECTO', 'Dealers Directos') THEN 'DEALERS DIRECTOS'
		ELSE UPPER(PARTNER_ESTUDIOS)
	END
where
	CANAL_FINAL = 'AFF'
-----------------------------------------------------------------------------------------------------------------------------------------

--1 min
--DECLARE @CIERRE integer = '202404'
begin
	if RIGHT(@CIERRE,2) in (03, 06, 09, 12)
	begin 
		--USAR PARA TRIMESTRES CERRADOS (03, 06, 09, 12)
		update Transaccional.dbo.Prima_Siniestros_Balance_Motor
		set Q_emi = LEFT(mes_emision,4)*100 + case when RIGHT(mes_emision,2) IN ('12') THEN 0 ELSE 0 END + case when RIGHT(mes_emision,2) IN ('01','02','03') then 3 when  RIGHT(mes_emision,2) IN ('04','05','06') then 6 when RIGHT(mes_emision,2) IN ('07','08', '09') then 9 else 12 end,  
		Q_DEV = LEFT(mes_dev,4)*100 + case when RIGHT(mes_DEV,2) IN ('12') THEN 0 ELSE 0 END + case when RIGHT(mes_dev,2) IN ('01','02','03') then 3 when  RIGHT(mes_dev,2) IN ('04','05','06') then 6 when RIGHT(mes_dev,2) IN ('07','08', '09') then 9 else 12 end  
	end
	if RIGHT(@CIERRE,2) in (04, 07, 10, 01)
	begin
		--USAR PARA TRIMESTRES 1er MES (04, 07, 10, 01)
		update Transaccional.dbo.Prima_Siniestros_Balance_Motor
		set Q_emi = LEFT(mes_emision,4)*100 + case when RIGHT(mes_emision,2) IN ('11', '12') THEN 100 ELSE 0 END + case when RIGHT(mes_emision,2) IN ('11','12','01') then 1 when  RIGHT(mes_emision,2) IN ('02','03','04') then 4 when RIGHT(mes_emision,2) IN ('05','06','07') then 7 else 10 end,  
		Q_DEV = LEFT(mes_dev,4)*100 + case when RIGHT(mes_DEV,2) IN ('11', '12') THEN 100 ELSE 0 END + case when RIGHT(mes_dev,2) IN ('11','12','01') then 1 when  RIGHT(mes_dev,2) IN ('02','03','04') then 4 when RIGHT(mes_dev,2) IN ('05','06','07') then 7 else 10 end
	end
	if RIGHT(@CIERRE,2) in (05, 08, 11, 02)
	begin
		--USAR PARA TRIMESTRES 2do MES (05, 08, 11, 02)
		update Transaccional.dbo.Prima_Siniestros_Balance_Motor
		set Q_emi = LEFT(mes_emision,4)*100 + case when RIGHT(mes_emision,2) IN ('12') THEN 100 ELSE 0 END + case when RIGHT(mes_emision,2) IN ('12','01','02') then 2 when  RIGHT(mes_emision,2) IN ('03','04','05') then 5 when RIGHT(mes_emision,2) IN ('06','07','08') then 8 else 11 end,  
		Q_DEV = LEFT(mes_dev,4)*100 + case when RIGHT(mes_DEV,2) IN ('12') THEN 100 ELSE 0 END + case when RIGHT(mes_dev,2) IN ('12','01','02') then 2 when  RIGHT(mes_dev,2) IN ('03','04','05') then 5 when RIGHT(mes_dev,2) IN ('06','07','08') then 8 else 11 end  
	end
end



/****** Checkpoint 5 ********************************************************/
INSERT INTO AUX_MOTOR_06_CHECKPOINTS VALUES('TRIANGULOS SINIESTRALIDAD - CHECKPOINT 5', SYSDATETIME())
/****************************************************************************/
--segs
update Transaccional.dbo.Prima_Siniestros_Balance_Motor
set Q_emi = @CIERRE-100
where Q_EMI<=@CIERRE-100--202303

--segs
/*SELECT NNUMDOCU,MAX(SUCURSAL) SUCURSAL
INTO #SUCURSAL
FROM sgf1034.GESTIONPORTAFOLIO.DBO.BASE_PYG_MOTOR
GROUP BY NNUMDOCU*/

--segs
drop table if exists #SUCURSAL
SELECT *
INTO #SUCURSAL
--FROM sgf1034.GESTIONPORTAFOLIO.DBO.BASE_PYG_MOTOR
FROM OPENQUERY (SGF1034, 'SELECT NNUMDOCU,MAX(SUCURSAL) SUCURSAL FROM GESTIONPORTAFOLIO.DBO.BASE_PYG_MOTOR GROUP BY NNUMDOCU')

--5 min
UPDATE Transaccional.dbo.Prima_Siniestros_Balance_Motor
SET SUCURSAL=RTRIM(B.SUCURSAL)
FROM Transaccional.dbo.Prima_Siniestros_Balance_Motor A
LEFT JOIN #SUCURSAL B ON A.NNUMDOCU=B.NNUMDOCU
WHERE B.NNUMDOCU IS NOT NULL


--segs
drop table if exists ATRIBUTOS
select * into ATRIBUTOS from #ATRIBUTOS --respaldo por si se cae la conexion, luego borrar la tabla


update Prima_Siniestros_Balance_Motor
set
NUEVA_RENOV = b.NUEVA_RENOVADA
from Prima_Siniestros_Balance_Motor a
left join (select nnumdocu, nnumitem, max(nueva_renovada) nueva_renovada from Reportes.dbo.MI_PRIMA_SINIESTRO_MOTOR group by nnumdocu, nnumitem) b on
a.nnumdocu = b.NNUMDOCU and
a.NNUMITEM = b.NNUMITEM
where a.NUEVA_RENOV is null


update Prima_Siniestros_Balance_Motor
set
TIPO_PLAN = b.TIPPLAN
from Prima_Siniestros_Balance_Motor a
left join (select nnumdocu, nnumitem, max(TIPPLAN) TIPPLAN from Reportes.dbo.MI_PRIMA_SINIESTRO_MOTOR group by nnumdocu, nnumitem) b on
a.nnumdocu = b.NNUMDOCU and
a.NNUMITEM = b.NNUMITEM
where a.TIPO_PLAN is null



-----------------------------------------------------------------------------------------------------------------------------------------
--AGREGAR FLOTAS TSTGO
update Prima_Siniestros_Balance_Motor
set
grupo_flota = b.flota
from Prima_Siniestros_Balance_Motor a
left join (
	select nnumdocu, nnumitem, contratante, max(flota) flota 
	from Reportes.dbo.MI_PRIMA_SINIESTRO_MOTOR 
	where CONTRATANTE IN (77532011, 77532114, 77532117, 77532096, 99557440, 76071048, 99577050)
	group by nnumdocu, nnumitem, contratante
) b on
a.nnumdocu = b.NNUMDOCU and
a.NNUMITEM = b.NNUMITEM
where b.CONTRATANTE IN (77532011, 77532114, 77532117, 77532096, 99557440, 76071048, 99577050)
-----------------------------------------------------------------------------------------------------------------------------------------
--AGREGAR VARIABLES
drop table if exists #sura_movilidad_transaccional

select nnumdocu, nnumitem, max(marca) marca, max(modelo) modelo, max(marca_modelo) marca_modelo, max(vigencia) vigencia, max(deducible) deducible
into #sura_movilidad_transaccional
from Reportes.dbo.SURA_MOVILIDAD_TRANSACCIONAL
group by nnumdocu, nnumitem


--7 min
update Prima_Siniestros_Balance_Motor
set
	marca = b.marca, 
	modelo = b.modelo, 
	marca_modelo = b.marca_modelo, 
	vigencia = b.vigencia,
	deducible = b.deducible
from Prima_Siniestros_Balance_Motor a
left join #sura_movilidad_transaccional b on
a.nnumdocu = b.NNUMDOCU and
a.NNUMITEM = b.NNUMITEM

--

drop table if exists #mi_prima_siniestro_motor

--2 min
select 
	nnumdocu, nnumitem, max(CCOMAVEH) CCOMAVEH, max(CDESCORT) CDESCORT, max(ltrim(rtrim(CCOMAVEH))+' - '+ltrim(rtrim(CDESCORT))) marca_modelo,
	MIN(case when NPLANTEC IN (5709,
	5710, 5711,5712,5951,5952,5953,5954,5955,5956,5957,5958,5959,5960,5961,5962,5963,5964,5965,5966,5967,5968,5969,5970,5971,5972,5973,5974,5975,5976,
	5977, 5978,5979,5980,5981,5982,5983,5984,5985,5986,6002,6091,6092,6093,6094,6095,6096,6097,6098,6099,6100,6101,6102,6103,6104,6105,6106,6107,6108,
	6109, 6110,6111,6112,6113,6114,6145,6146,6147,6148,6149,6150,6151,6152,6153,6154,6155,6156,6465,6479,6480,6481,6677,6678,6679,6680,6681,6682,6957,
	6958, 6959,6960,6991,6992,6993,6994,7009,7010,7011,7012,7013,7014,7015,7016,7017,7018,7019,7020,7080,7081,7082,7083,7181,7183,7184,7185,7186,7187,
	7188, 7189,7190,7191,7192,7193,7294,7295,7296,7297,7349,7350,7351,7352,7353,7354,7355,7356,7357,7358,7359,7360,7361,7362,7363,7364,7365,7366,7367,
	7368, 7369,7370,7371,7372,7373,7374,7375,7376,7377,7378,7379,7380,7381,7382,7383,7384,7385,7468,7469,7470,7471,7472,7473,7474,7475,7476,7477,7478,
	7479, 7486,7487,7488,7489,7502,7503,7504,7505,7506,7507,7508,7509,7518,7519,7520,7521,7522,7523,7524,7525,7526,7527,7528,7529,7598,7599,7600,7601,
	8170, 8171,8172,8173,8174,8175,8176,8177,8178,8179,8180,8181,8182,8183,8184,8185,8186,8187,8188,8189,8190,8191,8192,8193,8194,8195,8196,8197,8198,
	8199, 8200,8201,8202,8203,8204,8205,8206,8440,8442,8443,8445,8446,8447,8448,8449,8450,8451,8452,8453,8454,8455,8456,8457,8458,8459,8460,8461,8462,
	8529, 8623,8624,8625, 8626
	) then 'SEGURO X KM' ELSE 'OTRO' END) producto
into #mi_prima_siniestro_motor
from Reportes.dbo.MI_PRIMA_SINIESTRO_MOTOR
group by nnumdocu, nnumitem


update Prima_Siniestros_Balance_Motor
set
	marca = b.CCOMAVEH,  
	modelo = b.CDESCORT, 
	marca_modelo = b.marca_modelo
from Prima_Siniestros_Balance_Motor a
left join #mi_prima_siniestro_motor b on
a.nnumdocu = b.NNUMDOCU and
a.NNUMITEM = b.NNUMITEM
where 
	(a.marca = '' or a.marca is null) and
	b.CCOMAVEH is not null and
	b.CCOMAVEH <> ''

update Prima_Siniestros_Balance_Motor
set
	marca = null,
	modelo = null,
	marca_modelo = null
where marca = ''
-----------------------------------------------------------------------------------------------------------------------------------------
--CORREGIR VARIABLE SEGMENTO
update Prima_Siniestros_Balance_Motor
set
	segmento = producto
from Prima_Siniestros_Balance_Motor a
left join #mi_prima_siniestro_motor b on
a.nnumdocu = b.NNUMDOCU and
a.NNUMITEM = b.NNUMITEM
-----------------------------------------------------------------------------------------------------------------------------------------
--AGREGAR POLIZAS INSPECCION DIFERENCIADA
update Prima_Siniestros_Balance_Motor
set
	EXISTE_INSPECCION = 'SIN INSPECCION'
from Prima_Siniestros_Balance_Motor a
INNER join data_inspecciones_diferenciadas_V2 b on
a.nnumdocu = b.NNUMDOCU and
a.NNUMITEM = b.NNUMITEM
-----------------------------------------------------------------------------------------------------------------------------------------
--APROBADO POR CIA
DROP TABLE IF EXISTS #APROBADO_CIA
select CCODELEM, CDESELEM into #APROBADO_CIA from SOL.S1031EBB.RSASOLDB2.TBACSTGE where DCODTABL = 1761 and CDESELEM = 'APROBADO POR CIA'

DROP TABLE IF EXISTS #SUACSPOL
select NNUMDOCU, NNUMITEM, CCODCRIE into #SUACSSOL from SOL.S1031EBB.RSASOLDB2.SUACSSOL WHERE NFECUACT >= 20230101

select distinct
	a.NNUMDOCU, a.NNUMITEM, a.CCODCRIE, b.CDESELEM
into #SUACSSOL_2
from #SUACSSOL a
inner join #APROBADO_CIA b on
a.CCODCRIE = b.CCODELEM
--order by nnumdocu, nnumitem, ccodcrie

update Prima_Siniestros_Balance_Motor
set
	EXISTE_INSPECCION = b.CDESELEM
from Prima_Siniestros_Balance_Motor a
INNER join #SUACSSOL_2 b on
a.nnumdocu = b.NNUMDOCU and
a.NNUMITEM = b.NNUMITEM
-----------------------------------------------------------------------------------------------------------------------------------------

drop table if exists Triangulos_Motor_P_EXCEL
drop table if exists Triangulos_Motor_C_EXCEL


/****** Checkpoint 6 ********************************************************/
INSERT INTO AUX_MOTOR_06_CHECKPOINTS VALUES('TRIANGULOS SINIESTRALIDAD - CHECKPOINT 6', SYSDATETIME())
/****************************************************************************/

-------------------------------------------SALIDA TABLERO EXCEL PERSONAL---------------------------------------------------------
--declare @cierre int = 202507
SELECT  
	case when Q_EMI<=202401 then 202401 else Q_EMI END Q_EMI, Q_DEV,
	A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,A.SUCURSAL,SUM(GWP) GWP,SUM(CWP) CWP,SUM(UPR) UPR,SUM(GWP)+SUM(CWP) NWP,
	SUM(NEP) NEP,SUM(NEP) NEP_AJUST/*,SUM(NIC) NIC,SUM(VAR_IBNR) VAR_IBNR*/,SUM(INC_DP) INC_DP,SUM(INC_PT) INC_PT,SUM(INC_RC) INC_RC,SUM(INC_ROBO) INC_ROBO,SUM(INC_TOTAL) INC_TOTAL,
	SUM(INC_DP) INC_DP_AJUST,SUM(INC_PT) INC_PT_AJUST,SUM(INC_RC) INC_RC_AJUST,SUM(INC_ROBO) INC_ROBO_AJUST,SUM(INC_TOTAL) INC_TOTAL_AJUST,
	SUM(PRIMA_DEV_UF) PRIMA_DEV_UF,CAST(CAST(SUM(EXPOS) AS NUMERIC(10,4)) AS FLOAT) EXPOS,SUM(PRIMA_DEV_UF) PRIMA_DEV_UF_AJUST,CAST(CAST(SUM(EXPOS) AS NUMERIC(10,6)) AS FLOAT) EXPOS_AJUST,
	SUM(CANT_ULT_DP) CANT_ULT_DP,SUM(CANT_ULT_PT) CANT_ULT_PT,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO,SUM(CANT_ULT_RC) CANT_ULT_RC,
	SUM(CANT_ULT_DP) CANT_ULT_DP_AJUST,SUM(CANT_ULT_PT) CANT_ULT_PT_AJUST,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO_AJUST,SUM(CANT_ULT_RC) CANT_ULT_RC_AJUST,
	CASE 
		WHEN YEAR(FECINVIG)*100+MONTH(FECINVIG)<=202401 THEN 202401 
		WHEN YEAR(FECINVIG) IS NULL THEN LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3 
		ELSE YEAR(FECINVIG)*100+(ROUND((MONTH(FECINVIG)-1)/3,0)+1)*3 
	END Q_VIG,
	a.CANAL2,a.NUEVA_RENOV,a.TIPO_PLAN,a.SEGMENTO,
	a.EXISTE_INSPECCION,a.INSP_MODALIDAD,a.SEGMENTO_ROBO ,CAST(cast(SUM(EXPOS) as numeric(10,5)) AS FLOAT) EXPOS2,0 PRIMA_DEV_ORIG
INTO Triangulos_Motor_P_EXCEL
FROM Transaccional.dbo.Prima_Siniestros_Balance_Motor A
LEFT JOIN ATRIBUTOS B ON A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM
WHERE MES_DEV between 202401 and @cierre AND LINEANEGOCIO_KEIRA LIKE 'PER%' and Q_EMI IS NOT NULL
	and Q_EMI >= @cierre-100
	and Q_DEV >= @cierre-100
GROUP BY case when Q_EMI<=202401 then 202401 else Q_EMI END, Q_DEV,
A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,
CASE WHEN YEAR(FECINVIG)*100+MONTH(FECINVIG)<=202401 THEN 202401 WHEN YEAR(FECINVIG) IS NULL THEN LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3 ELSE YEAR(FECINVIG)*100+(ROUND((MONTH(FECINVIG)-1)/3,0)+1)*3 END,
a.CANAL2,a.NUEVA_RENOV,a.EXISTE_INSPECCION,a.INSP_MODALIDAD,a.TIPO_PLAN,a.SEGMENTO,a.SEGMENTO_ROBO,A.SUCURSAL	

-------------------------------------------SALIDA TABLERO EXCEL COMMERCIAL---------------------------------------------------------
--declare @cierre int = 202507
SELECT  
	case when Q_EMI<=202401 then 202401 else Q_EMI END Q_EMI, Q_DEV,
	A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,/*A.SUCURSAL,*/SUM(GWP) GWP,SUM(CWP) CWP,SUM(UPR) UPR,SUM(GWP)+SUM(CWP) NWP,
	SUM(NEP) NEP,SUM(NEP) NEP_AJUST/*,SUM(NIC) NIC,SUM(VAR_IBNR) VAR_IBNR*/,SUM(INC_DP) INC_DP,SUM(INC_PT) INC_PT,SUM(INC_RC) INC_RC,SUM(INC_ROBO) INC_ROBO,
	SUM(INC_RC_BUSES) INC_RC_BUSES,SUM(INC_SALFA) INC_SALFA,SUM(INC_SCANIA) INC_SCANIA,SUM(INC_TOTAL) INC_TOTAL,
	SUM(INC_DP) INC_DP_AJUST,SUM(INC_PT) INC_PT_AJUST,SUM(INC_RC) INC_RC_AJUST,SUM(INC_ROBO) INC_ROBO_AJUST,
	SUM(INC_RC_BUSES_AJUST) INC_RC_BUSES_AJUST,SUM(INC_SALFA_AJUST) INC_SALFA_AJUST,SUM(INC_SCANIA_AJUST) INC_SCANIA_AJUST,SUM(INC_TOTAL) INC_TOTAL_AJUST,
	SUM(PRIMA_DEV_UF) PRIMA_DEV_UF,CAST(SUM(EXPOS) AS FLOAT) EXPOS,SUM(PRIMA_DEV_UF) PRIMA_DEV_UF_AJUST,CAST(SUM(EXPOS) AS FLOAT) EXPOS_AJUST,
	SUM(CANT_ULT_DP) CANT_ULT_DP,SUM(CANT_ULT_PT) CANT_ULT_PT,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO,SUM(CANT_ULT_RC) CANT_ULT_RC,
	SUM(CANT_ULT_DP) CANT_ULT_DP_AJUST,SUM(CANT_ULT_PT) CANT_ULT_PT_AJUST,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO_AJUST,SUM(CANT_ULT_RC) CANT_ULT_RC_AJUST,
	CASE 
		WHEN YEAR(FECINVIG)*100+MONTH(FECINVIG)<=202401 THEN 202401 
		WHEN YEAR(FECINVIG) IS NULL THEN LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3 
		ELSE YEAR(FECINVIG)*100+(ROUND((MONTH(FECINVIG)-1)/3,0)+1)*3 
	END  Q_VIG,
	a.CANAL2,a.NUEVA_RENOV,a.TIPO_PLAN,a.SEGMENTO,a.EXISTE_INSPECCION,a.INSP_MODALIDAD,a.SEGMENTO_ROBO, a.GRUPO_FLOTA,a.CODRAMO,a.TAMAÑO_FLOTA,
	CAST(SUM(EXPOS) AS FLOAT) EXPOS2, 0 PRIMA_DEV_ORIG
INTO Triangulos_Motor_C_EXCEL
FROM Transaccional.dbo.Prima_Siniestros_Balance_Motor A
LEFT JOIN ATRIBUTOS B ON A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM
WHERE MES_DEV between 202401 and @CIERRE AND LINEANEGOCIO_KEIRA LIKE 'COM%' and Q_EMI IS NOT NULL
	and Q_EMI >= @cierre-100
	and Q_DEV >= @cierre-100
GROUP BY case when Q_EMI<=202401 then 202401 else Q_EMI END, Q_DEV,
A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,
CASE WHEN YEAR(FECINVIG)*100+MONTH(FECINVIG)<=202401 THEN 202401 WHEN YEAR(FECINVIG) IS NULL THEN LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3 ELSE YEAR(FECINVIG)*100+(ROUND((MONTH(FECINVIG)-1)/3,0)+1)*3 END,
a.CANAL2,a.NUEVA_RENOV,a.EXISTE_INSPECCION,a.INSP_MODALIDAD,a.TIPO_PLAN,a.SEGMENTO,a.SEGMENTO_ROBO,A.SUCURSAL,a.GRUPO_FLOTA,a.CODRAMO,a.TAMAÑO_FLOTA	




drop table if exists Triangulos_Motor_P
drop table if exists Triangulos_Motor_C

--segs
-------------------------------------------SALIDA INTERMEDIA POWER BI PERSONAL (LUEGO SE ELIMINA)---------------------------------------------------------
--declare @cierre int = 202507
SELECT  
	case when Q_EMI<=202401 then 202401 else Q_EMI END Q_EMI, Q_DEV,
	A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,A.SUCURSAL,a.MARCA,a.MODELO,a.MARCA_MODELO,a.VIGENCIA,a.DEDUCIBLE,SUM(GWP) GWP,SUM(CWP) CWP,SUM(UPR) UPR,SUM(GWP)+SUM(CWP) NWP,
	SUM(NEP) NEP,SUM(NEP) NEP_AJUST/*,SUM(NIC) NIC,SUM(VAR_IBNR) VAR_IBNR*/,SUM(INC_DP) INC_DP,SUM(INC_PT) INC_PT,SUM(INC_RC) INC_RC,SUM(INC_ROBO) INC_ROBO,SUM(INC_TOTAL) INC_TOTAL,
	SUM(INC_DP) INC_DP_AJUST,SUM(INC_PT) INC_PT_AJUST,SUM(INC_RC) INC_RC_AJUST,SUM(INC_ROBO) INC_ROBO_AJUST,SUM(INC_TOTAL) INC_TOTAL_AJUST,
	SUM(PRIMA_DEV_UF) PRIMA_DEV_UF,CAST(CAST(SUM(EXPOS) AS NUMERIC(10,4)) AS FLOAT) EXPOS,SUM(PRIMA_DEV_UF) PRIMA_DEV_UF_AJUST,CAST(CAST(SUM(EXPOS) AS NUMERIC(10,6)) AS FLOAT) EXPOS_AJUST,
	SUM(CANT_ULT_DP) CANT_ULT_DP,SUM(CANT_ULT_PT) CANT_ULT_PT,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO,SUM(CANT_ULT_RC) CANT_ULT_RC,
	SUM(CANT_ULT_DP) CANT_ULT_DP_AJUST,SUM(CANT_ULT_PT) CANT_ULT_PT_AJUST,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO_AJUST,SUM(CANT_ULT_RC) CANT_ULT_RC_AJUST,
	CASE 
		WHEN YEAR(FECINVIG)*100+MONTH(FECINVIG)<=202401 THEN 202401 
		WHEN YEAR(FECINVIG) IS NULL THEN LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3 
		ELSE YEAR(FECINVIG)*100+(ROUND((MONTH(FECINVIG)-1)/3,0)+1)*3 
	END Q_VIG,
	a.CANAL2,a.NUEVA_RENOV,a.TIPO_PLAN,a.SEGMENTO,
	a.EXISTE_INSPECCION,a.INSP_MODALIDAD,a.SEGMENTO_ROBO ,CAST(cast(SUM(EXPOS) as numeric(10,5)) AS FLOAT) EXPOS2,0 PRIMA_DEV_ORIG
INTO Triangulos_Motor_P
FROM Transaccional.dbo.Prima_Siniestros_Balance_Motor A
LEFT JOIN ATRIBUTOS B ON A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM
WHERE MES_DEV between 202401 and @CIERRE AND LINEANEGOCIO_KEIRA LIKE 'PER%' and Q_EMI IS NOT NULL
	and Q_EMI >= @cierre-100
	and Q_DEV >= @cierre-100
GROUP BY case when Q_EMI<=202401 then 202401 else Q_EMI END, Q_DEV,
A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,
CASE WHEN YEAR(FECINVIG)*100+MONTH(FECINVIG)<=202401 THEN 202401 WHEN YEAR(FECINVIG) IS NULL THEN LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3 ELSE YEAR(FECINVIG)*100+(ROUND((MONTH(FECINVIG)-1)/3,0)+1)*3 END,
a.CANAL2,a.NUEVA_RENOV,a.EXISTE_INSPECCION,a.INSP_MODALIDAD,a.TIPO_PLAN,a.SEGMENTO,a.SEGMENTO_ROBO,A.SUCURSAL,a.MARCA,a.MODELO,a.MARCA_MODELO,a.VIGENCIA,a.DEDUCIBLE


--segs
-------------------------------------------SALIDA INTERMEDIA POWER BI COMMERCIAL (LUEGO SE ELIMINA)---------------------------------------------------------
--declare @cierre int = 202507
SELECT  
	case when Q_EMI<=202401 then 202401 else Q_EMI END Q_EMI, Q_DEV,
	A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,/*A.SUCURSAL,*/a.MARCA,a.MODELO,a.MARCA_MODELO,a.VIGENCIA,a.DEDUCIBLE,SUM(GWP) GWP,SUM(CWP) CWP,SUM(UPR) UPR,SUM(GWP)+SUM(CWP) NWP,
	SUM(NEP) NEP,SUM(NEP) NEP_AJUST/*,SUM(NIC) NIC,SUM(VAR_IBNR) VAR_IBNR*/,SUM(INC_DP) INC_DP,SUM(INC_PT) INC_PT,SUM(INC_RC) INC_RC,SUM(INC_ROBO) INC_ROBO,
	SUM(INC_RC_BUSES) INC_RC_BUSES,SUM(INC_SALFA) INC_SALFA,SUM(INC_SCANIA) INC_SCANIA,SUM(INC_TOTAL) INC_TOTAL,
	SUM(INC_DP) INC_DP_AJUST,SUM(INC_PT) INC_PT_AJUST,SUM(INC_RC) INC_RC_AJUST,SUM(INC_ROBO) INC_ROBO_AJUST,
	SUM(INC_RC_BUSES_AJUST) INC_RC_BUSES_AJUST,SUM(INC_SALFA_AJUST) INC_SALFA_AJUST,SUM(INC_SCANIA_AJUST) INC_SCANIA_AJUST,SUM(INC_TOTAL) INC_TOTAL_AJUST,
	SUM(PRIMA_DEV_UF) PRIMA_DEV_UF,CAST(SUM(EXPOS) AS FLOAT) EXPOS,SUM(PRIMA_DEV_UF) PRIMA_DEV_UF_AJUST,CAST(SUM(EXPOS) AS FLOAT) EXPOS_AJUST,
	SUM(CANT_ULT_DP) CANT_ULT_DP,SUM(CANT_ULT_PT) CANT_ULT_PT,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO,SUM(CANT_ULT_RC) CANT_ULT_RC,
	SUM(CANT_ULT_DP) CANT_ULT_DP_AJUST,SUM(CANT_ULT_PT) CANT_ULT_PT_AJUST,SUM(CANT_ULT_ROBO) CANT_ULT_ROBO_AJUST,SUM(CANT_ULT_RC) CANT_ULT_RC_AJUST,
	CASE 
		WHEN YEAR(FECINVIG)*100+MONTH(FECINVIG)<=202401 THEN 202401 
		WHEN YEAR(FECINVIG) IS NULL THEN LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3 
		ELSE YEAR(FECINVIG)*100+(ROUND((MONTH(FECINVIG)-1)/3,0)+1)*3 
	END  Q_VIG,
	a.CANAL2,a.NUEVA_RENOV,a.TIPO_PLAN,a.SEGMENTO,a.EXISTE_INSPECCION,a.INSP_MODALIDAD,a.SEGMENTO_ROBO, a.GRUPO_FLOTA,a.CODRAMO,a.TAMAÑO_FLOTA,
	CAST(SUM(EXPOS) AS FLOAT) EXPOS2, 0 PRIMA_DEV_ORIG
INTO Triangulos_Motor_C
FROM Transaccional.dbo.Prima_Siniestros_Balance_Motor A
LEFT JOIN ATRIBUTOS B ON A.NNUMDOCU=B.NNUMDOCU AND A.NNUMITEM=B.NNUMITEM
WHERE MES_DEV between 202401 and @CIERRE AND LINEANEGOCIO_KEIRA LIKE 'COM%' and Q_EMI IS NOT NULL
	and Q_EMI >= @cierre-100
	and Q_DEV >= @cierre-100
GROUP BY case when Q_EMI<=202401 then 202401 else Q_EMI END, Q_DEV,
A.CANAL,A.CANAL_FINAL,A.PARTNER_ESTUDIOS,A.PARTNER_FINAL,a.MARCA,a.MODELO,a.MARCA_MODELO,a.VIGENCIA,a.DEDUCIBLE,
CASE WHEN YEAR(FECINVIG)*100+MONTH(FECINVIG)<=202401 THEN 202401 WHEN YEAR(FECINVIG) IS NULL THEN LEFT(A.MES_EMISION,4)*100+(ROUND((RIGHT(A.MES_EMISION,2)-1)/3,0)+1)*3 ELSE YEAR(FECINVIG)*100+(ROUND((MONTH(FECINVIG)-1)/3,0)+1)*3 END,
a.CANAL2,a.NUEVA_RENOV,a.EXISTE_INSPECCION,a.INSP_MODALIDAD,a.TIPO_PLAN,a.SEGMENTO,a.SEGMENTO_ROBO,/*A.SUCURSAL,*/a.GRUPO_FLOTA,a.CODRAMO,a.TAMAÑO_FLOTA		



/****** Checkpoint 7 ********************************************************/
INSERT INTO AUX_MOTOR_06_CHECKPOINTS VALUES('TRIANGULOS SINIESTRALIDAD - CHECKPOINT 7', SYSDATETIME())
/****************************************************************************/
----------TABLA FACTORES LDF----------
drop table if exists #LDF_PIVOT
select 
	MES
	,[MP_DMA]  as [ULT_MP_DMA]
	,[MP_DP]   as [ULT_MP_DP]
	,[MP_DT]   as [ULT_MP_DT]
	,[MP_RC]   as [ULT_MP_RC]
	,[MP_ROBO] as [ULT_MP_ROBO]
	,[MC_DMA]  as [ULT_MC_DMA]
	,[MC_DP]   as [ULT_MC_DP]
	,[MC_DT]   as [ULT_MC_DT]
	,[MC_RC]   as [ULT_MC_RC]
	,[MC_ROBO] as [ULT_MC_ROBO]
	,[MC_BUSES] as [ULT_MC_BUSES]
into #LDF_PIVOT
from (
	SELECT 
		RAMO_RESERVA, MES, 
		case 
			when RAMO_RESERVA like 'MP_%' then sum((ATT_ULTIMATE_$ + WE_ULTIMATE_$) / 1000) 
			when RAMO_RESERVA like 'MC_%' then sum((ATT_ULTIMATE_$ + LL_ULTIMATE_$ + WE_ULTIMATE_$) / 1000)
		end	AS ULTIMATE 
	FROM procesos.dbo.BASE_LDF_COMPLETO_V2
	where MES between dateadd(year, -3, GETDATE()) and dateadd(year, 1, GETDATE())
	group by RAMO_RESERVA,MES
	--order by RAMO_RESERVA, MES
) as TableToPivot
pivot (
	SUM(ULTIMATE)
	FOR RAMO_RESERVA IN (
		[MP_DMA],[MP_DP],[MP_DT],[MP_RC],[MP_ROBO]
		,[MC_DMA],[MC_DP],[MC_DT],[MC_RC],[MC_ROBO],[MC_BUSES]
	)
) as PivotTable

----------------------------- TRIANGULO PERSONAL PBI -----------------------------
--declare @cierre int = 202507
drop table if exists Triangulos_Motor_P_Completa
select 
	Q_EMI,Q_DEV,CANAL,CANAL_FINAL,PARTNER_ESTUDIOS,PARTNER_FINAL,SUCURSAL,a.MARCA,a.MODELO,a.MARCA_MODELO,a.VIGENCIA,a.DEDUCIBLE,GWP,CWP,UPR,NWP,NEP,NEP_AJUST,INC_DP,INC_PT,INC_RC,INC_ROBO,INC_TOTAL,INC_DP_AJUST,INC_PT_AJUST,INC_RC_AJUST,INC_ROBO_AJUST,INC_TOTAL_AJUST,PRIMA_DEV_UF,EXPOS,PRIMA_DEV_UF_AJUST,EXPOS_AJUST,CANT_ULT_DP,CANT_ULT_PT,CANT_ULT_ROBO,CANT_ULT_RC,CANT_ULT_DP_AJUST,CANT_ULT_PT_AJUST,CANT_ULT_ROBO_AJUST,CANT_ULT_RC_AJUST,Q_VIG,CANAL2,NUEVA_RENOV,TIPO_PLAN,SEGMENTO,EXISTE_INSPECCION,/*INSP_MODALIDAD,*/SEGMENTO_ROBO,EXPOS2,PRIMA_DEV_ORIG,
	MAX([ULT_MP_DP]) AS ULT_MP_DP,
	SUM(SUM(INC_DP_AJUST)) over(PARTITION BY Q_DEV) AS TOTAL_DP,
	MAX([ULT_MP_DP]) / SUM(SUM(INC_DP_AJUST)) over(PARTITION BY Q_DEV) FDA_DP,

	MAX([ULT_MP_DT]) AS ULT_MP_DT,
	SUM(SUM(INC_PT_AJUST)) over(PARTITION BY Q_DEV) AS TOTAL_DT,
	MAX([ULT_MP_DT]) / SUM(SUM(INC_PT_AJUST)) over(PARTITION BY Q_DEV) FDA_DT,

	MAX([ULT_MP_ROBO]) AS ULT_MP_ROBO,
	SUM(SUM(INC_ROBO_AJUST)) over(PARTITION BY Q_DEV) AS TOTAL_ROBO,
	MAX([ULT_MP_ROBO]) / SUM(SUM(INC_ROBO_AJUST)) over(PARTITION BY Q_DEV) FDA_ROBO,

	MAX([ULT_MP_RC]) AS ULT_MP_RC,
	SUM(SUM(INC_RC_AJUST)) over(PARTITION BY Q_DEV) AS TOTAL_RC,
	MAX([ULT_MP_RC]) / SUM(SUM(INC_RC_AJUST)) over(PARTITION BY Q_DEV) FDA_RC
into Triangulos_Motor_P_Completa
from Triangulos_Motor_P a
left join #LDF_PIVOT b on
	a.Q_DEV = YEAR( DATEADD(month,case ((right(@cierre,2)-1) % 3) + 1 when 1 then 1 when 2 then 2 when 3 then 0 end, b.MES) ) * 100 +
			  MONTH( DATEADD(month,case ((right(@cierre,2)-1) % 3) + 1 when 1 then 1 when 2 then 2 when 3 then 0 end, b.MES) )
--= YEAR(b.MES)*100+MONTH(b.MES)
where b.ULT_MP_DMA <> 0 
group by --Q_EMI, Q_DEV
	Q_EMI,Q_DEV,CANAL,CANAL_FINAL,PARTNER_ESTUDIOS,PARTNER_FINAL,SUCURSAL,a.MARCA,a.MODELO,a.MARCA_MODELO,a.VIGENCIA,a.DEDUCIBLE,GWP,CWP,UPR,NWP,NEP,NEP_AJUST,INC_DP,INC_PT,INC_RC,INC_ROBO,INC_TOTAL,INC_DP_AJUST,INC_PT_AJUST,INC_RC_AJUST,INC_ROBO_AJUST,INC_TOTAL_AJUST,PRIMA_DEV_UF,EXPOS,PRIMA_DEV_UF_AJUST,EXPOS_AJUST,CANT_ULT_DP,CANT_ULT_PT,CANT_ULT_ROBO,CANT_ULT_RC,CANT_ULT_DP_AJUST,CANT_ULT_PT_AJUST,CANT_ULT_ROBO_AJUST,CANT_ULT_RC_AJUST,Q_VIG,CANAL2,NUEVA_RENOV,TIPO_PLAN,SEGMENTO,EXISTE_INSPECCION,/*INSP_MODALIDAD,*/SEGMENTO_ROBO,EXPOS2,PRIMA_DEV_ORIG

--BORRAR LA DATA CORRESPONDIENTE A LA PARTE INFERIOR DEL TRIANGULO (BAJO LA RECTA)
delete from Transaccional.dbo.Triangulos_Motor_P_Completa where Q_EMI > Q_DEV
------------------------------------------------------------------------------------

----------------------------- TRIANGULO COMMERCIAL PBI -----------------------------
--declare @cierre int = 202507
drop table if exists Triangulos_Motor_C_Completa
select 
	Q_EMI,Q_DEV,CANAL,CANAL_FINAL,PARTNER_ESTUDIOS,PARTNER_FINAL,MARCA,MODELO,MARCA_MODELO,VIGENCIA,DEDUCIBLE,GWP,CWP,UPR,NWP,NEP,NEP_AJUST,INC_DP,INC_PT,INC_RC,INC_ROBO,INC_RC_BUSES,INC_SALFA,INC_SCANIA,INC_TOTAL,INC_DP_AJUST,INC_PT_AJUST,INC_RC_AJUST,INC_ROBO_AJUST,INC_RC_BUSES_AJUST,INC_SALFA_AJUST,INC_SCANIA_AJUST,INC_TOTAL_AJUST,PRIMA_DEV_UF,EXPOS,PRIMA_DEV_UF_AJUST,EXPOS_AJUST,CANT_ULT_DP,CANT_ULT_PT,CANT_ULT_ROBO,CANT_ULT_RC,CANT_ULT_DP_AJUST,CANT_ULT_PT_AJUST,CANT_ULT_ROBO_AJUST,CANT_ULT_RC_AJUST,Q_VIG,CANAL2,NUEVA_RENOV,TIPO_PLAN,SEGMENTO,EXISTE_INSPECCION,INSP_MODALIDAD,SEGMENTO_ROBO,GRUPO_FLOTA,CODRAMO,TAMAÑO_FLOTA,EXPOS2,PRIMA_DEV_ORIG,
	MAX([ULT_MC_DP]) AS ULT_MC_DP,
	SUM(SUM(INC_DP_AJUST)) over(PARTITION BY Q_DEV) AS TOTAL_DP,
	MAX([ULT_MC_DP]) / SUM(SUM(INC_DP_AJUST)) over(PARTITION BY Q_DEV) FDA_DP,

	MAX([ULT_MC_DT]) AS ULT_MC_DT,
	SUM(SUM(INC_PT_AJUST)) over(PARTITION BY Q_DEV) AS TOTAL_DT,
	MAX([ULT_MC_DT]) / SUM(SUM(INC_PT_AJUST)) over(PARTITION BY Q_DEV) FDA_DT,

	MAX([ULT_MC_ROBO]) AS ULT_MC_ROBO,
	SUM(SUM(INC_ROBO_AJUST)) over(PARTITION BY Q_DEV) AS TOTAL_ROBO,
	MAX([ULT_MC_ROBO]) / SUM(SUM(INC_ROBO_AJUST)) over(PARTITION BY Q_DEV) FDA_ROBO,

	MAX([ULT_MC_RC]) AS ULT_MC_RC,
	SUM(SUM(INC_RC_AJUST)) over(PARTITION BY Q_DEV) AS TOTAL_RC,
	MAX([ULT_MC_RC]) / SUM(SUM(INC_RC_AJUST)) over(PARTITION BY Q_DEV) FDA_RC,

	MAX([ULT_MC_BUSES]) AS ULT_MC_BUSES,
	SUM(SUM(INC_RC_BUSES_AJUST)) over(PARTITION BY Q_DEV) AS TOTAL_RC_BUSES,
	MAX([ULT_MC_BUSES]) / SUM(SUM(INC_RC_BUSES_AJUST)) over(PARTITION BY Q_DEV) FDA_RC_BUSES
into Triangulos_Motor_C_Completa
from Triangulos_Motor_C a
left join #LDF_PIVOT b on
	a.Q_DEV = YEAR( DATEADD(month,case ((right(@cierre,2)-1) % 3) + 1 when 1 then 1 when 2 then 2 when 3 then 0 end, b.MES) ) * 100 +
			  MONTH( DATEADD(month,case ((right(@cierre,2)-1) % 3) + 1 when 1 then 1 when 2 then 2 when 3 then 0 end, b.MES) )
--= YEAR(b.MES)*100+MONTH(b.MES)
where 
	b.ULT_MC_DMA <> 0 and 
	Q_EMI <= Q_DEV
group by
	Q_EMI,Q_DEV,CANAL,CANAL_FINAL,PARTNER_ESTUDIOS,PARTNER_FINAL,MARCA,MODELO,MARCA_MODELO,VIGENCIA,DEDUCIBLE,GWP,CWP,UPR,NWP,NEP,NEP_AJUST,INC_DP,INC_PT,INC_RC,INC_ROBO,INC_RC_BUSES,INC_SALFA,INC_SCANIA,INC_TOTAL,INC_DP_AJUST,INC_PT_AJUST,INC_RC_AJUST,INC_ROBO_AJUST,INC_RC_BUSES_AJUST,INC_SALFA_AJUST,INC_SCANIA_AJUST,INC_TOTAL_AJUST,PRIMA_DEV_UF,EXPOS,PRIMA_DEV_UF_AJUST,EXPOS_AJUST,CANT_ULT_DP,CANT_ULT_PT,CANT_ULT_ROBO,CANT_ULT_RC,CANT_ULT_DP_AJUST,CANT_ULT_PT_AJUST,CANT_ULT_ROBO_AJUST,CANT_ULT_RC_AJUST,Q_VIG,CANAL2,NUEVA_RENOV,TIPO_PLAN,SEGMENTO,EXISTE_INSPECCION,INSP_MODALIDAD,SEGMENTO_ROBO,GRUPO_FLOTA,CODRAMO,TAMAÑO_FLOTA,EXPOS2,PRIMA_DEV_ORIG

--BORRAR LA DATA CORRESPONDIENTE A LA PARTE INFERIOR DEL TRIANGULO (BAJO LA RECTA)
delete from Transaccional.dbo.Triangulos_Motor_C_Completa where Q_EMI > Q_DEV
------------------------------------------------------------------------------------


/****** Checkpoint PROCESO TERMINADO ********************************************************/
INSERT INTO AUX_MOTOR_06_CHECKPOINTS VALUES('TRIANGULOS SINIESTRALIDAD - TERMINADO', SYSDATETIME())
/****************************************************************************/
drop table if exists #INCURRIDO
drop table if exists #INCURRIDO2
drop table if exists #EXPOSICION
drop table if exists #UNION
drop table if exists #ATRIBUTOS
drop table if exists #SALIDA
drop table if exists #AJUSTES1
drop table if exists #AJUSTES2
drop table if exists #AJUSTES3
drop table if exists #AJUSTES_NIC
drop table if exists #SUCURSAL

drop table if exists Triangulos_Motor_P
drop table if exists Triangulos_Motor_C


----------SALIDA TABLERO EXCEL PERSONAL
select * from Transaccional.dbo.Triangulos_Motor_P_EXCEL
----------SALIDA TABLERO EXCEL COMERCIAL
select * from Transaccional.dbo.Triangulos_Motor_C_EXCEL

----------PBI
--select * from Transaccional.dbo.Triangulos_Motor_P_Completa
----------PBI
--select * from Transaccional.dbo.Triangulos_Motor_C_Completa


--drop table if exists Transaccional.DBO.AUX1_PRIMA_GANADA_PYG
--drop table if exists Transaccional.DBO.AUX3_PRIMA_GANADA_PYG
--drop table if exists Transaccional.DBO.AUX4_PRIMA_GANADA_PYG
--drop table if exists Transaccional.DBO.AUX5_ATRIBUTOS1
--drop table if exists Transaccional.DBO.AUX5_ATRIBUTOS2
--drop table if exists Transaccional.DBO.COBERTURA_STRO
--drop table if exists ATRIBUTOS


END