SELECT TOP (1000) [LINEA_NEGOCIO]
      ,[CHANNEL]
      ,[GRUPO_CHANNEL]
      ,[BU]
      ,[CORREDOR]
      ,[NPLANTEC]
      ,[TIPPLAN]
      ,[PLAN_TECNICO]
      ,[PLAN_TECNICO2]
      ,[PRODUCTOS_NUEVOS]
      ,[DEDUCIBLE]
      ,[TIPO_VEH]
      ,[GAMA_VEH]
      ,[MARCA]
      ,[MODELO]
      ,[MARCA_MODELO]
      ,[TOP100]
      ,[ZONA_SUCURSAL]
      ,[SUCURSAL]
      ,[REGION]
      ,[REGION_URBE]
      ,[PROVINCIA]
      ,[NUEVA_RENOV]
      ,[nueva_renov2]
      ,[FLOTA]
      ,[GRUPO_FLOTA]
      ,[PERIODO]
      ,[ANT_VEH]
      ,[EDAD]
      ,[EXTRANJERO]
      ,[PERFIL_UBER]
      ,[VIGENCIA]
      ,[CONTRATANTE]
      ,[REGION_REAL]
      ,[CODRAMO]
      ,[TAMAÑO_FLOTA]
      ,[INCLUSIÓN]
      ,[PRIMA_EMI]
      ,[COMIS_EMI]
      ,[PRIMA_EMI_ENT]
      ,[c_emisiones]
      ,[EXPOS]
      ,[PRIMA_DEV]
      ,[COMIS_DEV]
      ,[Gtos_Adq]
      ,[PRDP_EMI]
      ,[PRPT_EMI]
      ,[PRRC_EMI]
      ,[PRROBO_EMI]
      ,[PRRIESGO_EMI]
      ,[PRDP_DEV]
      ,[PRPT_DEV]
      ,[PRRC_DEV]
      ,[PRROBO_DEV]
      ,[PRRIESGO_DEV]
      ,[FRECDP_DEV]
      ,[FRECPT_DEV]
      ,[FRECRC_DEV]
      ,[FRECROBO_DEV]
      ,[FRECTOT_DEV]
      ,[CANT_ULT_DP]
      ,[CANT_ULT_PT]
      ,[CANT_ULT_RC]
      ,[CANT_ULT_ROBO]
      ,[CANT_ULT_ASIST]
      ,[CANT_ULT_TOTAL]
      ,[ULT_DP]
      ,[ULT_PT]
      ,[ULT_RC]
      ,[ULT_ROBO]
      ,[ULT_ASIST]
      ,[ULT_TOTAL]
      ,[CANT_DP]
      ,[CANT_PT]
      ,[CANT_RC]
      ,[CANT_ROBO]
      ,[CANT_ASIST]
      ,[CANT_ULT]
      ,[PAGO_DP]
      ,[PAGO_PT]
      ,[PAGO_RC]
      ,[PAGO_ROBO]
      ,[PAGO_ASIST]
      ,[PAGO_TOTAL]
      ,[RESERVA_DP]
      ,[RESERVA_PT]
      ,[RESERVA_RC]
      ,[RESERVA_ROBO]
      ,[RESERVA_ASIST]
      ,[RESERVA_TOTAL]
      ,[ant_empresa]
      ,[MAS_ROBADOS]
 FROM [Transaccional].[dbo].[Tablero_Motor_final];


 -- Hay NULL y 'Unknown'
 SELECT DISTINCT TIPO_VEH
 FROM Transaccional.dbo.Tablero_Motor_final;

  -- Hay NULL
 SELECT DISTINCT GAMA_VEH
 FROM Transaccional.dbo.Tablero_Motor_final;

 -- TIPO_VEH ANALISIS
 SELECT
    CHANNEL,
    COUNT(*) AS TOTAL_COUNT,
    COUNT(TIPO_VEH) AS NO_NULL_COUNT,
    COUNT(CASE WHEN TIPO_VEH IS NULL OR TIPO_VEH = 'Unknown' THEN 1 END) AS NULL_UNKNOWN_COUNT
 FROM Transaccional.dbo.Tablero_Motor_final
 GROUP BY CHANNEL
 ORDER BY NULL_UNKNOWN_COUNT DESC;

-- GAMA_VEH ANALISIS
SELECT
    CHANNEL,
    COUNT(*) AS TOTAL_COUNT,
    COUNT(GAMA_VEH) AS NO_NULL_COUNT,
    CAST(CAST(COUNT(CASE WHEN GAMA_VEH IS NULL THEN 1 END) AS NUMERIC)/CAST(COUNT(*) AS NUMERIC) AS NUMERIC(17,2)) AS NULL_COUNT_PERCENTAGE,
    COUNT(CASE WHEN GAMA_VEH IS NULL THEN 1 END) AS NULL_COUNT
FROM Transaccional.dbo.Tablero_Motor_final
GROUP BY CHANNEL
HAVING 
    CAST(CAST(COUNT(CASE WHEN GAMA_VEH IS NULL THEN 1 END) AS NUMERIC)/CAST(COUNT(*) AS NUMERIC) AS NUMERIC(17,2)) > 0.05
    AND COUNT(GAMA_VEH) > 1000
ORDER BY NULL_COUNT_PERCENTAGE DESC, NULL_COUNT DESC;

-- Agrupando por MARCA, MARCA-MODELO
SELECT
    LTRIM(RTRIM(MARCA)) AS MARCA_VIEJO,
    LTRIM(RTRIM(MARCA_MODELO)) AS MODELO_VIEJO,
    LTRIM(RTRIM(GAMA_VEH)) AS SEGMENTACION_VIEJO,
    COUNT(*) AS TOTAL_COUNT_VIEJO,
    COUNT(GAMA_VEH) AS NO_NULL_COUNT_VIEJO,
    CAST(CAST(COUNT(CASE WHEN GAMA_VEH IS NULL THEN 1 END) AS NUMERIC)/CAST(COUNT(*) AS NUMERIC) AS NUMERIC(17,2)) AS NULL_COUNT_PERCENTAGE_VIEJO,
    COUNT(CASE WHEN GAMA_VEH IS NULL THEN 1 END) AS NULL_COUNT_VIEJO
FROM Transaccional.dbo.Tablero_Motor_final
WHERE 
    LINEA_NEGOCIO = 'Personal'
GROUP BY MARCA, MARCA_MODELO, GAMA_VEH
ORDER BY MARCA_VIEJO ASC, MODELO_VIEJO ASC, NULL_COUNT_PERCENTAGE_VIEJO DESC, NULL_COUNT_VIEJO DESC;

-- TIPO_VEH Y GAMA_VEH ANALISIS
SELECT
    CHANNEL,
    COUNT(*) AS TOTAL_COUNT,
    COUNT(GAMA_VEH) AS GAMA_VEH_NO_NULL_COUNT,
    COUNT(TIPO_VEH) AS TIPO_VEH_NO_NULL_COUNT,
    COUNT(CASE WHEN GAMA_VEH IS NULL AND TIPO_VEH IS NULL THEN 1 END) AS NULL_COUNT
FROM Transaccional.dbo.Tablero_Motor_final
GROUP BY CHANNEL
ORDER BY NULL_COUNT DESC;