-- SURA_MOVILIDAD_TRANSACCIONAL con tasación y menos dimensiones
-- Traer fechas y nueva renovada
--SELECT * 
--FROM almacen_de_datos.dbo.New_variables_modelo_personal_2024

-- DIFERENCIA PORCENTUAL DE LAS TASACIONES DESVIADAS CON RESPECTO A LAS TASACIONES "CORRECTAS" (DISMINUYEN O SE MANTIENEN)
SELECT 
    SUM(CASE WHEN SUB_JOIN.PREV_DIFF_TASACION > 0 THEN SUB_JOIN.TASACION_NUEVO END) AS SUMA_TASACIONES_POSITIVAS,
    SUM(CASE WHEN SUB_JOIN.PREV_DIFF_TASACION <= 0 THEN SUB_JOIN.TASACION_NUEVO END) AS SUMA_TASACIONES_TOTAL,
    CAST(CAST(SUM(CASE WHEN SUB_JOIN.PREV_DIFF_TASACION > 0 THEN SUB_JOIN.TASACION_NUEVO END) AS NUMERIC)/CAST(SUM(CASE WHEN SUB_JOIN.PREV_DIFF_TASACION <= 0 THEN SUB_JOIN.TASACION_NUEVO END) AS NUMERIC) AS NUMERIC(17,2)) AS RELACION_PORCENTUAL
FROM 
(
SELECT
    LTRIM(RTRIM(SMT.MARCA)) AS MARCA_NUEVO,
    LTRIM(RTRIM(SMT.MODELO)) AS MODELO_NUEVO,
    SMT.AÑO AS YEAR_NUEVO,
    LTRIM(RTRIM(SMT.SEGMENTACION)) AS SEGMENTACION_NUEVO,
    SMT.FECHA_FIRMA_POLIZA,
    SMT.IND_RENOVACION_LLAVE_2,
    MAX(NVP.TASACION) AS TASACION_NUEVO,
    SMT.IND_RENOVACION_LLAVE_2 - LAG(SMT.IND_RENOVACION_LLAVE_2, 1, 0) OVER (PARTITION BY SMT.MARCA, SMT.MODELO, SMT.AÑO ORDER BY SMT.MARCA ASC, SMT.MODELO ASC, SMT.AÑO ASC, SMT.FECHA_FIRMA_POLIZA ASC, SMT.IND_RENOVACION_LLAVE_2 ASC) AS PREV_DIFF_IND_RENOVACION_LLAVE_2,
    MAX(NVP.TASACION) - LAG(MAX(NVP.TASACION), 1, MAX(NVP.TASACION)) OVER (PARTITION BY SMT.MARCA, SMT.MODELO, SMT.AÑO ORDER BY SMT.MARCA ASC, SMT.MODELO ASC, SMT.AÑO ASC, SMT.FECHA_FIRMA_POLIZA ASC, SMT.IND_RENOVACION_LLAVE_2 ASC) AS PREV_DIFF_TASACION
FROM REPORTES.DBO.SURA_MOVILIDAD_TRANSACCIONAL AS SMT
INNER JOIN ALMACEN_DE_DATOS.DBO.NEW_VARIABLES_MODELO_PERSONAL_2024 AS NVP
    ON SMT.NNUMDOCU = NVP.NNUMDOCU AND SMT.NNUMITEM = NVP.NNUMITEM AND SMT.FECHA_FIRMA_POLIZA = NVP.FECHA_FIRMA_POLIZA
WHERE 
    SMT.LINEA_NEGOCIO = 'PERSONAL'
    --AND VIGENTE = 1
    AND YEAR(SMT.INICIO_VIGENCIA) >= 2024
    AND (NVP.TASACION > 0)
GROUP BY SMT.MARCA, SMT.MODELO, SMT.SEGMENTACION, SMT.AÑO, SMT.FECHA_FIRMA_POLIZA, SMT.IND_RENOVACION_LLAVE_2
) AS SUB_JOIN
WHERE
    SUB_JOIN.PREV_DIFF_IND_RENOVACION_LLAVE_2 IN (0, 1)
--ORDER BY SUB_JOIN.MARCA_NUEVO ASC, SUB_JOIN.MODELO_NUEVO ASC, SUB_JOIN.YEAR_NUEVO ASC, SUB_JOIN.FECHA_FIRMA_POLIZA ASC, SUB_JOIN.IND_RENOVACION_LLAVE_2 ASC



SELECT 
    *
FROM 
(
SELECT
    LTRIM(RTRIM(SMT.MARCA)) AS MARCA_NUEVO,
    LTRIM(RTRIM(SMT.MODELO)) AS MODELO_NUEVO,
    SMT.AÑO AS YEAR_NUEVO,
    LTRIM(RTRIM(SMT.SEGMENTACION)) AS SEGMENTACION_NUEVO,
    SMT.FECHA_FIRMA_POLIZA,
    SMT.IND_RENOVACION_LLAVE_2,
    MAX(NVP.TASACION) AS TASACION_NUEVO
FROM REPORTES.DBO.SURA_MOVILIDAD_TRANSACCIONAL AS SMT
INNER JOIN ALMACEN_DE_DATOS.DBO.NEW_VARIABLES_MODELO_PERSONAL_2024 AS NVP
    ON SMT.NNUMDOCU = NVP.NNUMDOCU AND SMT.NNUMITEM = NVP.NNUMITEM AND SMT.FECHA_FIRMA_POLIZA = NVP.FECHA_FIRMA_POLIZA
WHERE 
    SMT.LINEA_NEGOCIO = 'PERSONAL'
    AND YEAR(SMT.INICIO_VIGENCIA) >= 2024
    AND (NVP.TASACION > 0)
GROUP BY SMT.MARCA, SMT.MODELO, SMT.SEGMENTACION, SMT.AÑO, SMT.FECHA_FIRMA_POLIZA, SMT.IND_RENOVACION_LLAVE_2
) AS SUB_JOIN
ORDER BY SUB_JOIN.MARCA_NUEVO ASC, SUB_JOIN.MODELO_NUEVO ASC, SUB_JOIN.YEAR_NUEVO ASC, SUB_JOIN.FECHA_FIRMA_POLIZA ASC, SUB_JOIN.IND_RENOVACION_LLAVE_2 ASC