SELECT TOP 100 * FROM REPORTES.dbo.SURA_MOVILIDAD_TRANSACCIONAL;


SELECT
    LTRIM(RTRIM(MARCA)) AS MARCA_NUEVO,
    LTRIM(RTRIM(MODELO)) AS MODELO_NUEVO,
    LTRIM(RTRIM(SEGMENTACION)) AS SEGMENTACION_NUEVO,
    COUNT(*) AS TOTAL_COUNT_NUEVO,
    COUNT(SEGMENTACION) AS NO_NULL_COUNT_NUEVO,
    CAST(CAST(COUNT(CASE WHEN SEGMENTACION IS NULL THEN 1 END) AS NUMERIC)/CAST(COUNT(*) AS NUMERIC) AS NUMERIC(17,2)) AS NULL_COUNT_PERCENTAGE_NUEVO,
    COUNT(CASE WHEN SEGMENTACION IS NULL THEN 1 END) AS NULL_COUNT_NUEVO
FROM REPORTES.DBO.SURA_MOVILIDAD_TRANSACCIONAL
WHERE 
    LINEA_NEGOCIO = 'PERSONAL'
    --AND VIGENTE = 1
    AND YEAR(INICIO_VIGENCIA) > 2024
GROUP BY MARCA, MODELO, SEGMENTACION
ORDER BY MARCA_NUEVO ASC, MODELO_NUEVO ASC, NULL_COUNT_PERCENTAGE_NUEVO DESC, NULL_COUNT_NUEVO DESC;

SELECT DISTINCT SEGMENTACION
FROM REPORTES.DBO.SURA_MOVILIDAD_TRANSACCIONAL;

SELECT *
FROM REPORTES.DBO.SURA_MOVILIDAD_TRANSACCIONAL
WHERE
    NNUMDOCU = 3282889
	AND NNUMITEM = 3915
ORDER BY NNUMDOCU, NNUMITEM